### ISSUE TITLE
karpenter instances in nlb target group

### ISSUE THREAD

**Issue by Izvi-digibank** [aws/karpenter-provider-aws#1562]
Do instances that Karpenter create should automatically appear in the nlb target group? 
If not - in order to see those machines in the nlb target group do I have to take any action ? if so, which?

Thanks in advance

**Comment by dewjam** [comment]
Hello @Izvi-digibank .  
Karpenter does not automatically handle adding nodes to an NLB target group.  But you could deploy the [AWS Load Balancer controller](https://docs.aws.amazon.com/eks/latest/userguide/aws-load-balancer-controller.html) and configure a Service of Type `LoadBalancer`.  This will provision an NLB and handle targets for you automatically.

However, please read through the docs to understand if this is the right approach for you.
