### ISSUE TITLE
Question: very simple one - at least 1 running worker in provider or have a minimum free CPU always available

### ISSUE THREAD

**Issue by funes79** [aws/karpenter-provider-aws#1874]
Hi!
The question is simple: **How to achieve at least one running worker (of any size, or of a preferrable size)?**

According to the docs  if I dont set `ttlSecondsAfterEmpty: 30`  the node(s) will never expire. I would like to have that but only for the last node, so for example if I have 10 busy nodes, and suddenly all the pods exits, I would like to keep the last one running forever. 
I know it is kind of against the concept of elastic autoscaling, as Karpenter calculates the optimal node size.

I also realize that it could happen if I throw 50 pods to the cluster, it will spin up a massive EC2 with many cores and large memory, and in that case I would like to get the node deleted (after `ttlSecondsAfterEmpty`) and instead of it spin up a smaller size.

The reason behind this is that I want to get quick response time for workers provided by "notebook" provisioner. These nodes are dedicated to jupyter notebooks and they are tainted with "notebook" taint. The pods of jupyter notebooks selects these labels using nodeSelector and tolerate the taint. In this way we have a pool of nodes for notebooks. But the first start of a kernel takes too much time and sometimes times out. Therefore I started to investigate if it is possible to have something like minimum worker count or event better minimum CPU always on running.

**Is an existing page relevant?**

**What karpenter features are relevant?**

**How should the docs be improved?**

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by njtran** [comment]
Hey @funes79, we recommend that you keep one node running so that Karpenter can run. In the [eksctl getting-started guide](https://karpenter.sh/v0.10.1/getting-started/getting-started-with-eksctl/#create-a-cluster), we do this with Managed Node Groups. If you wanted, you could set this instance type and desired capacity to 2, so that you always have at least that much CPU up and running.

**Comment by njtran** [comment]
Does this work for you? Let me know if you have any other requirements to see if maybe this is a feature you want.

**Comment by funes79** [comment]
Hi, the example from the getting started guide does not really helps as it creates an always-on set on nodes (1 or 2) with for service pods. In my case I wanted to have a specific node type (maybe w gpu) dedicated for notebooks. 
But anyway the problem can be solved by setting up a simple deployment and keep it with scale factor 1 with pods tolerating the taint of "notebook" nodes. In this way the provisioner will keep at least 1 node running.

**Comment by grosser** [comment]
I wanted this feature too, since it would make testing an empty karpenter config simple (can confirm nodes scale up/down etc without having to put workload on it)
