### ISSUE TITLE
Failed to retrieve credentials due to OIDC thumbprint misconfiguration (private cluster)

### ISSUE THREAD

**Issue by Wykiki** [aws/karpenter-provider-aws#1893]
## Version

**Karpenter**: v0.10.1

**Kubernetes**: v1.22.9-eks-a64ea69

## Expected Behavior

Once installed and Provisioner resource configured, Karpenter should schedule new nodes when pods are waiting for scheduling.

## Actual Behavior

Karpenter is unable to add nodes to the cluster, looping over OIDC certificate misconfiguration (see logs).

## Steps to Reproduce the Problem

- Follow the [Getting started with Terraform documentation](https://karpenter.sh/v0.10.1/getting-started/getting-started-with-terraform/)
- Use existing private Subnets instead of the given VPC configuration
- Add Karpenter tag on subnets
- Apply the `inflate` Deployment resource and scale it to 5

## Resource Specs and Logs

```yaml
# Provisioner
apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: default
spec:
  limits:
    resources:
      cpu: 1k
  provider:
    securityGroupSelector:
      karpenter.sh/discovery: tooling-test
    subnetSelector:
      karpenter.sh/discovery: enabled
    tags:
      karpenter.sh/discovery: tooling-test
  requirements:
  - key: karpenter.sh/capacity-type
    operator: In
    values:
    - spot
  - key: kubernetes.io/arch
    operator: In
    values:
    - amd64
  ttlSecondsAfterEmpty: 30
---
# Inflate deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inflate
spec:
  replicas: 0
  selector:
    matchLabels:
      app: inflate
  template:
    metadata:
      labels:
        app: inflate
    spec:
      terminationGracePeriodSeconds: 0
      containers:
        - name: inflate
          image: public.ecr.aws/eks-distro/kubernetes/pause:3.2
          resources:
            requests:
              cpu: 1
```

```
2022-06-03T13:46:58.949Z        INFO    controller      Waiting for unschedulable pods  {"commit": "10fc37b"}
2022-06-03T13:47:03.538Z        INFO    controller      Batched 4 pod(s) in 1.000580071s        {"commit": "10fc37b"}
2022-06-03T13:47:03.901Z        ERROR   controller      Provisioning failed, getting instance types, fetching instance types using ec2.DescribeInstanceTypes, WebIdentityErr: failed to retrieve credentials
caused by: InvalidIdentityToken: OpenIDConnect provider's HTTPS certificate doesn't match configured thumbprint
        status code: 400, request id: cdb39909-8607-4616-a3ea-1c95b78d0b1f      {"commit": "10fc37b"}
```

**Comment by njtran** [comment]
The provisioner and deployment look normal and good to me. This looks like an IRSA problem. Are you using all the latest versions of the terraform docs?

Can you check your karpenter-controller role and see if the oidc provider looks right here?
```
module "karpenter_irsa" {
  source  = "terraform-aws-modules/iam/aws//modules/iam-role-for-service-accounts-eks"
  version = "4.17.1"

  role_name                          = "karpenter-controller-${local.cluster_name}"
  attach_karpenter_controller_policy = true

  karpenter_controller_cluster_id = module.eks.cluster_id
  karpenter_controller_node_iam_role_arns = [
    module.eks.eks_managed_node_groups["initial"].iam_role_arn
  ]

  oidc_providers = {
    ex = {
      provider_arn               = module.eks.oidc_provider_arn
      namespace_service_accounts = ["karpenter:karpenter"]
    }
  }
}
```

**Comment by Wykiki** [comment]
Well, I encountered other issues regarding EKS and custom CNI (other than VPC CNI), that blocks webhook requests, so I'm not able to validate Karpenter installation.

I was using the Terraform setup of Karpenter, and used everything provided but the VPC / Subnet config (used existing ones).

I'm closing this issue as I'm pretty sure it is finally unrelated to Karpenter, but more to how EKS manages things on its side when it comes to cluster that aren't able to reach internet and needs to use VPC Endpoints instead.
