### ISSUE TITLE
Strange logging in new cluster state controller

### ISSUE THREAD

**Issue by ellistarn** [aws/karpenter-provider-aws#1907]
## Version

**Karpenter**: HEAD

**Kubernetes**: v1.22.x

## Expected Behavior

Useful logs

## Actual Behavior

```
karpenter-5b6958b8f-2n8rt controller 2022-06-08T19:04:46.060Z	INFO	controller	pod kube-system/kube-proxy-4g2m4 has moved from node  to ip-192-168-153-103.us-west-2.compute.internal	{"commit": "7d2414b"}
karpenter-5b6958b8f-2n8rt controller 2022-06-08T19:04:46.080Z	INFO	controller	pod kube-system/kube-proxy-4klgb has moved from node  to ip-192-168-83-101.us-west-2.compute.internal	{"commit": "7d2414b"}
karpenter-5b6958b8f-2n8rt controller 2022-06-08T19:04:46.080Z	ERROR	controller	getting node, Node "ip-192-168-83-101.us-west-2.compute.internal" not found	{"commit": "7d2414b"}
karpenter-5b6958b8f-2n8rt controller 2022-06-08T19:04:46.096Z	INFO	controller	pod kube-system/kube-proxy-8ptsq has moved from node  to ip-192-168-153-154.us-west-2.compute.internal	{"commit": "7d2414b"}
karpenter-5b6958b8f-2n8rt controller 2022-06-08T19:04:46.130Z	INFO	controller	pod kube-system/aws-node-rdc7l has moved from node  to ip-192-168-132-198.us-west-2.compute.internal	{"commit": "7d2414b"}
karpenter-5b6958b8f-2n8rt controller 2022-06-08T19:04:46.130Z	ERROR	controller	getting node, Node "ip-192-168-132-198.us-west-2.compute.internal" not found	{"commit": "7d2414b"}
karpenter-5b6958b8f-2n8rt controller 2022-06-08T19:04:46.145Z	INFO	controller	pod kube-system/kube-proxy-7h5zm has moved from node  to ip-192-168-145-190.us-west-2.compute.internal	{"commit": "7d2414b"}
karpenter-5b6958b8f-2n8rt controller 2022-06-08T19:04:46.209Z	ERROR	controller	getting node, Node "ip-192-168-152-202.us-west-2.compute.internal" not found	{"commit": "7d2414b"}
karpenter-5b6958b8f-2n8rt controller 2022-06-08T19:04:46.242Z	ERROR	controller	getting node, Node "ip-192-168-139-135.us-west-2.compute.internal" not found	{"commit": "7d2414b"}
karpenter-5b6958b8f-2n8rt controller 2022-06-08T19:04:46.258Z	INFO	controller	pod kube-system/aws-node-tpftf has moved from node  to ip-192-168-139-135.us-west-2.compute.internal	{"commit": "7d2414b"}
karpenter-5b6958b8f-2n8rt controller 2022-06-08T19:04:46.276Z	INFO	controller	pod kube-system/aws-node-rlxtr has moved from node  to ip-192-168-152-202.us-west-2.compute.internal	{"commit": "7d2414b"}
```

**Comment by ishworg** [comment]
I am definitely keen to see more informative logs as well. We rolled out Karpenter `v0.12.0` to production yesterday. So far, all the bits and bobs have been phenomenal 💯  The only thing from our perspective that could be made better is the nature of the logs.

I turned on the JSON structured log and INFO level via Helm set - those are really good. Thank you. 
But, making the logs contextual and informative is equally useful for our operational readiness. If this could be prioritized, I'll be ever so grateful.

**Comment by ellistarn** [comment]
> I turned on the JSON structured log and INFO level via Helm set - those are really good. Thank you.
But, making the logs contextual and informative is equally useful for our operational readiness. If this could be prioritized, I'll be ever so grateful.

Can you be specific about the gaps you see?

**Comment by ishworg** [comment]
> Can you be specific about the gaps you see?

Sure. The specific nature of the gap is Log verbosity at INFO level. 

Do operators need to care if leader election is taking place?
```
attempting to acquire leader
```
I am not certain if trying to _acquire_ a leader is a significant log event. However, I _do_ care if it _fails_ to acquire a leader during an election. That's just one instance of this *gap*.

Another one -
```
Webhook ServeHTTP request=&http.Request{Method:"POST", URL:(*url.URL)(0xc000a053b0), Proto:"HTTP/1.1", ProtoMajor:1, ProtoMinor:1, Header:http.Header{"Accept":[]string{"application/json, */*"}, "Accept-Encoding":[]string{"gzip"}, "Content-Length":[]string{"3064"}, "Content-Type":[]string{"application/json"}, "User-Agent":[]string{"kube-apiserver-admission"}}, Body:(*http.body)(0xc000859900), GetBody:(func() (io.ReadCloser, error))(nil), ContentLength:3064, TransferEncoding:[]string(nil), Close:false, Host:"karpenter-karpenter-controller.karpenter.svc:443", Form:url.Values(nil), PostForm:url.Values(nil), MultipartForm:(*multipart.Form)(nil), Trailer:http.Header(nil), RemoteAddr:"10.249.201.187:34890", RequestURI:"/validate-resource?timeout=10s", TLS:(*tls.ConnectionState)(0xc000182580), Cancel:(<-chan struct {})(nil), Response:(*http.Response)(nil), ctx:(*context.cancelCtx)(0xc000859940)}
```
How can ⬆️  be improved? Is this relevant at the INFO level?

The number one question, Karpenter devs should be asking is - what do the log entries mean to someone who is _operating_ the pod? If there is confusion in the log level perhaps there needs to be a consensus in the zap logger's log level that Karpenter uses (if I am not mistaken) and what _absolute_ message *must* be emitted at that level. 

Thanks for asking for clarification. So yep, those are the generic questions I'd ask myself If I was iterating on Karpenter today.

**Comment by tzneal** [comment]
The leader lease log is from [Kubernetes](https://github.com/kubernetes/kubernetes/blob/9918aa1e035a00bc7c0f16a05e1b222650b3eabc/staging/src/k8s.io/client-go/tools/leaderelection/leaderelection.go#L248).

The Webhook serve log is from [knative](https://github.com/knative/pkg/blob/f5db22566a80b3d44861a543219ba9ab8cbf8ecf/webhook/admission.go#L90) . 

We didn't add these logs explicitly, they're from dependencies.

**Comment by tzneal** [comment]
Closing, can re-open or re-create if this becomes an issue.
