### ISSUE TITLE
Does karpenter support overriding user data when provisioning via an existing launch template?

### ISSUE THREAD

**Issue by maxsargentdev** [aws/karpenter-provider-aws#2065]
I am trying to use karpenter to spin up a few powerful bare metal instances for a HPC workload.

For this I would like to override some of bottlerockets settings via the user data toml file.

Does karpenter support overriding the via spec.userData in the AWSNodeTemplate CRD, if we are using an existing launch template via  spec.launchTemplate?

~~~yaml
apiVersion: karpenter.k8s.aws/v1alpha1
kind: AWSNodeTemplate
metadata:
  name: example-node-template
spec:
  launchTemplate: 'example-launch-template'
  subnetSelector:
    kubernetes.io/cluster: example-cluster
  userData: |
    [settings.kubernetes]
    cpu-manager-policy = "static"
~~~

The above config will provision a node, however the cpu-manager-policy is not being set correctly on inspection of bottlerockets config via apiclient get.

I would also like to use settings.boot.kernel-parameters, I have mentioned this missing section of bottlerocket toml on another thread.

**Is an existing page relevant?**

https://karpenter.sh/v0.13.1/aws/launch-templates/#define-launchtemplate-for-provisioner

**What karpenter features are relevant?**

User data for launch templates.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by bwagner5** [comment]
Karpenter will not overwrite userdata from an existing launch template. We will never modify a launch template that you provide us. The example AWSNodeTemplate supplied should actually fail validation to notify you that we won't use user-data.

**Comment by maxsargentdev** [comment]
Okay thanks for the clarity here, I will have to figure out the best way to create a separate launch template with modified user data.

Can I suggest this gets added to the documentation? 

It isn't clear what the behaviour is right now when using launchTemplate in conjunction with userData.

Thanks again.
