### ISSUE TITLE
Expose Cloud Provider Offering Availability as Metrics

### ISSUE THREAD

**Issue by jonathan-innis** [aws/karpenter-provider-aws#2596]
### Tell us about your request

This idea was originally proposed by @bwagner5.

The idea here would be to expose a gauge metric like `karpenter_cloudprovider_offering_available` with labels `instance_type`, `capacity_type`, and `zone`. 

This metric would be set to 1 for all offerings that Karpenter is aware are available from the cloud provider. If the cloudprovider changed its mind about the availability of the offering (i.e. for AWS, there is an ICE [Insufficient Capacity Error] when launching an instance) then the gauge would be exposed as 0

### Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?

N/A

### Are you currently working around this issue?

N/A

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by chu-yik** [comment]
interested to take this one up :)

**Comment by njtran** [comment]
@chu-yik any progress here?
