### ISSUE TITLE
Add a label for CPU Manufacturer/Name

### ISSUE THREAD

**Issue by zbintliff** [aws/karpenter-provider-aws#3529]
### Tell us about your request

Similar to how you provide `karpenter.k8s.aws/instance-gpu-manufacturer` it would be great to have one for CPU manufacterer. We have a use case where workloads are using intel specific features and want to target `i` nodes vs `a` nodes. Right now the labels show they are just arch amd64 for both, which means we need to define specific instance types and update them as new generations come out.

### Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?

We have come workloads that only want to go on intel based instances. Right now we have our own metadata to add this type of information but would be great if it was "free".

### Are you currently working around this issue?

During startup we parse the output of `lscpu` to determine `amd` vs `intel`

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by sftim** [comment]
Although Karpenter could do the labelling, you could also have a Provisioner with an allow list of instance types (which is already supported) and then use [node feature discovery](https://kubernetes-sigs.github.io/node-feature-discovery/) to add the labels you want.
