### ISSUE TITLE
Documentation issue: Default weight?

### ISSUE THREAD

**Issue by Almenon** [aws/karpenter-provider-aws#3627]
I'm wondering what the default weight is. Also, if there are just two provisioners and neither have a weight, in what order do you go through them?

**Comment by njtran** [comment]
Hi! If you don't specify a weight, it's the same as a 0 weight provisioner. In addition, weight is only considered if there is an overlap in provisioning requirements in the two provisioners. In the case of two equal weights, the order is random.

**Comment by Almenon** [comment]
Thanks! Lower weights are chosen first, right, so 0 would be highest priority?
