### ISSUE TITLE
Define NodePool Weight/Pod Preference Interactions

### ISSUE THREAD

**Issue by jonathan-innis** [aws/karpenter-provider-aws#3714]
### Tell us about your request

Currently, the interactions and lines drawn between provisioner `.spec.weight` and pod preference mechanisms is ambigious. Some example of pod "preference" mechanisms are:
- `topologySpreadConstraint` ScheduleAnyway
- `podAffinity` preferredDuringSchedulingIgnoredDuringExecution
- `nodeAffinity` preferredDuringSchedulingIgnoredDuringExecution

It would be good if Karpenter had an opinionated stance that was well-defined and well-documented on the order of priority each of these preference mechanisms is given by Karpenter's bin-packing.

Linked Issues:
- aws/karpenter#3569
- aws/karpenter-core#721

Linked Discussions:
- https://kubernetes.slack.com/archives/C02SFFZSA2K/p1680627021710789

### Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?

The interactions between various preference mechanisms is an inherently computationally complex problem. It's computationally infeasible to be "perfect" here but it should be possible to give users an ordering mechanism or a scoring calculation that is easily understood.

### Are you currently working around this issue?

N/A

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by njtran** [comment]
closing as covered by https://github.com/kubernetes-sigs/karpenter/issues/666
