### ISSUE TITLE
Add az-id label to nodes

### ISSUE THREAD

**Issue by sidewinder12s** [aws/karpenter-provider-aws#3878]
### Tell us about your request

Can Karpenter Add an az-id label to nodes?

This currently cannot be done as users need to set the labels using a startup script and/or modify the bootstrap flag for node labels. 

I am not sure if the inability to modify bootstrap command flags is changing with the new machine ownership changes in 0.28

### Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?

Our cost team needs the az-id label for pricing. I could see a lot of other uses too.

### Are you currently working around this issue?

We're not with Karpenter. An alternative is to add some kind of daemonset or controller which adds this label to nodes after join. This exposes some limitations in Prometheus metrics which can cause issues with multiple time series when you modify the labels on that series after creation.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by njtran** [comment]
We have an AZ Label on the node already, but as I understand it you want it in the form of `use1-az1` for consistency, right?

**Comment by sidewinder12s** [comment]
Yup, there are a lot of use cases where you might need to get the real physical location for pricing/network/etc.

**Comment by ellistarn** [comment]
Related: https://github.com/kubernetes/cloud-provider-aws/issues/300

**Comment by njtran** [comment]
Would be great if we can just rely on the linked issue above to do this for us. I'm sure we could do this in Karpenter, but if it's going to be implemented in the future, it just means that the label will be redundant in the future.

**Comment by sftim** [comment]
Outside Kubernetes itself, it'd be handy to have AWS define what the label key is going to be. We can get that defined and agreed even before the code to set it is written.

**Comment by timchenko-a** [comment]
Does anybody know any "easy" workaround for this? E.g. getting AZ ID in UserData and passing it to kubelet somehow?

**Comment by sidewinder12s** [comment]
> Does anybody know any "easy" workaround for this? E.g. getting AZ ID in UserData and passing it to kubelet somehow?

I think you'd have to do it in a post node join controller or daemon set. Karpenter doesn't expose the bootstrap.sh config which is why you can't set the labels during that step, which was the long standing way you'd set runtime labels on startup as far as I know.
