### ISSUE TITLE
Ubuntu compatability testing

### ISSUE THREAD

**Issue by jonathan-innis** [aws/karpenter-provider-aws#4134]
### Description

We should be testing compatibility with the Ubuntu AMIs across all K8s versions that we say that Karpenter supports. We should ensure that we are testing all SSM aliases that we resolve within Karpenter.

__Good Places to Start__
1. Adding SSM resolution tests to the [AMI Test Suite](https://github.com/aws/karpenter/blob/main/test/suites/integration/ami_test.go)
2. Adding basic configuration Smoke Tests to the [KubeletConfiguraiton Test Suite](https://github.com/aws/karpenter/blob/main/test/suites/integration/kubelet_config_test.go)

**Comment by jmdeal** [comment]
Closing due to Ubuntu support being dropped at v1.
