### ISSUE TITLE
Stop passing --container-runtime in the bootstrap for K8s >= 1.27

### ISSUE THREAD

**Issue by tzneal** [aws/karpenter-provider-aws#4241]
### Description

**Observed Behavior**:

We pass the container runtime flag to the bootstrap script.

**Expected Behavior**:

We shouldn't pass it at all.  It currently works as the bootstrap ignores it, but we should remove it now to prevent problems in the future.

**Reproduction Steps** (Please include YAML):

**Versions**:
- Chart Version: 
- Kubernetes Version (`kubectl version`): 

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by jmdeal** [comment]
Closed by https://github.com/aws/karpenter-provider-aws/pull/5335
