### ISSUE TITLE
Add Integration Tests for Ephemeral Volumes

### ISSUE THREAD

**Issue by jonathan-innis** [aws/karpenter-provider-aws#4381]
### Description

**What problem are you trying to solve?**

We currently don't have E2E integration tests that test that ephemeral volumes work with Karpenter and that Karpenter respects the CSI volume limits for ephemeral volumes when scheduling. We should add tests to validate this.

### Code Pointers

1. https://github.com/aws/karpenter/blob/main/test/suites/integration/storage_test.go
2. https://github.com/aws/karpenter-core/blob/main/pkg/controllers/provisioning/scheduling/suite_test.go#L2591

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by jmdeal** [comment]
Closed by #5229
