### ISSUE TITLE
E2E Tests should use a Docker Image as opposed to installing tooling at runtime

### ISSUE THREAD

**Issue by jonathan-innis** [aws/karpenter-provider-aws#4545]
### Description

Currently, our E2E tests run local actions to install tooling at runtime (like `helm`, `helm diff`, `prometheus`, `eksctl`, etc.). We should create an image that we can use to run our testing so that we don't have to install these things at runtime, reduce our test time, and have more reliability in our tests which sometimes fail due to these installation failures.

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by aman0408** [comment]
Can I work on this issue?

**Comment by jonathan-innis** [comment]
@aman0408 Yep! Assigned! Reach out to me over Slack DM if you have any questions or want to know any more info on how to get started.

**Comment by jonathan-innis** [comment]
Closing this out since we agreed that we don't want to add this right now. We can re-open this issue if we think that this is necessary down-the-line.
