### ISSUE TITLE
Update the Grafana default example to v1beta1

### ISSUE THREAD

**Issue by jonathan-innis** [aws/karpenter-provider-aws#4838]
### Description

**How can the docs be improved?**

The [Grafana configuration](https://karpenter.sh/preview/getting-started/getting-started-with-karpenter/#add-optional-monitoring-with-grafana) that is shipped with the [Getting Started Guide](https://karpenter.sh/preview/getting-started/getting-started-with-karpenter) should be updated to consider v1beta1 APIs and metric names.

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by Hronom** [comment]
@jonathan-innis created https://github.com/aws/karpenter-provider-aws/pull/5546 please help to push
