### ISSUE TITLE
v1 Laundry List for AWS

### ISSUE THREAD

**Issue by njtran** [aws/karpenter-provider-aws#5006]
### Description

**What problem are you trying to solve?**
This issue contains a list of breaking API changes that we want to make for v1 for AWS APIs.

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by jonathan-innis** [comment]
We should look at the `karpenter.k8s.aws/instance-memory` and `karpenter.k8s.aws/instance-cpu` metrics to see if they are still reasonable to use. I can see these labels being a little clunky since they don't necessarily always map to the allocatable and different DS scheduling may give you different available resources for workloads.

**Comment by garvinp-stripe** [comment]
We have also noticed that EC2's hypervisor takes some random amount of memory (7-5% depending on instance type), so we usually don't rely on any pre-determined labels for node level resources at run time.

**Comment by jonathan-innis** [comment]
We should investigate dropping the `karpenter.sh/managed-by` tag for instance resources. This tag was added as a migration mechanism when Machines were introduced, but `kubernetes.io/cluster/<cluster-name>` basically gives us the same information as the `karpenter.sh/managed-by` tag does today.

**Comment by jmdeal** [comment]
We should drop this bit of [ENI configuration magic](https://github.com/aws/karpenter-provider-aws/blob/8fb62bf3983e8f9fa0ff83a8ec2bb131e9fb5a3b/pkg/providers/launchtemplate/launchtemplate.go#L291-L304), given that #5437 merges before v1 (I have no reason to believe it wouldn't). This was originally introduced to solve #3815 but #5437 introduces the long term solution discussed there.

**Comment by jmdeal** [comment]
We should decouple the release process for the AWS provider and the upstream library: https://github.com/aws/karpenter-provider-aws/issues/5765

**Comment by jonathan-innis** [comment]
Closing out since #6604 was closed.
