### ISSUE TITLE
Allow disabling Drift on a NodePool level

### ISSUE THREAD

**Issue by nadavbuc** [aws/karpenter-provider-aws#5052]
### Description

**What problem are you trying to solve?**
Ability to disable Drift on a specific node pool by either label/annotation or setting
**How important is this feature to you?**
Without it - i can't enable drift feature gate in production
The Drift Feature is really amazing but can become self-harming on specific use-cases 
**For example** 
i have nodegroups on which i want the nodes to remain active until i manually recycle them.
These nodegroups are configured as follows:
_Capacity type: `on-demand`_
_expireAfter: `"Never"`_

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by engedaam** [comment]
Have you considered using PDBs or `karpenter.sh/do-not-disrupt` annotation on pods? Are you finding that not be sufficient for your use case?

**Comment by nadavbuc** [comment]
It would require lot more work rather then just specifying it on the nodepool level - but for now i will proceed with PDB

**Comment by njtran** [comment]
Hey @nadavbuc  👋 

Was hoping to understand more of the use-case here. In what ways are you triggering drift? And in what ways is it drifting that you're not expecting it to?

**Comment by nadavbuc** [comment]
Hey @njtran 
Basically its just planning, on dev i let it drift freely, and its fine.
On production, i have specific node pools which consists of pretty hardcoded values like instance type, and capacity type set to on-demand.

On these node groups i would like to be the only one responsible for recycling nodes manually, unless there is an hardware issue in which case it will be auto-healed

My concern is whenever a new k8s-patch ami will be released, or when we are upgrading kubernetes, for other node groups the drift mechanism should be wonderful, but for these specific node groups it might be a concern.

I'm focusing solely on AMI drifts, unless i am misinterpreting its activity and goals.

**Comment by njtran** [comment]
> My concern is whenever a new k8s-patch ami will be released, or when we are upgrading kubernetes, for other node groups the drift mechanism should be wonderful, but for these specific node groups it might be a concern.
I'm focusing solely on AMI drifts, unless i am misinterpreting its activity and goals.

Is it possible to pin the AMI ID you want to use for each EKS Optimized AMI? This is a pain point we've heard from others that if you want to use the latest EKS Optimized AMI, you need to be flexible to the disruptions that a new release would incur. For these NodePools, if you can pin the AMI in the EC2NodeClass that would probably be the best workaround for now.

In the long run, we're working on a disruption budget that would be in-line with the NodePool that you can use to drive when you think disruptions should be allowed or not. More to come on that soon. 

Design: https://github.com/kubernetes-sigs/karpenter/blob/main/designs/disruption-controls.md and larger issue with many related issues: https://github.com/aws/karpenter-provider-aws/issues/1738

**Comment by nadavbuc** [comment]
This [new feature](https://karpenter.sh/docs/concepts/disruption/#nodes)s is exactly what i need 🙏
