### ISSUE TITLE
Drift Detection always leave one instance with older version after a Kubernetes version upgrade.

### ISSUE THREAD

**Issue by jetersen** [aws/karpenter-provider-aws#5108]
### Description

**Observed Behavior**:
After upgrading Kubernetes version I have observed that a single Karpenter instance is left running with the older Kubernetes version running. Even after a whole day the node has not been upgraded yet.

I have observed this is 3 clusters after upgrading to EKS 1.27 and 1.28
Looks like an off by one kind of thing 😓

(screenshot shows taint cause I ended up deleting the node)
![image](https://github.com/aws/karpenter/assets/1661688/fb941eeb-767c-45d9-8b5c-1e6f71346e7b)

**Expected Behavior**:
All instances should be marked as drifted and upgraded

**Reproduction Steps** (Please include YAML):
```
settings:
  featureGates:
    drift: true
```

**Versions**:
- Chart Version: `v0.32.1`
- Kubernetes Version (`kubectl version`): 
```
Client Version: v1.28.2
Server Version: v1.28.3-eks-4f4795d
```

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by tzneal** [comment]
Can you show the output of `kubectl describe node the-node-name` on the node? In particular I want to see the events.
