### ISSUE TITLE
Clarify that do-not-disrupt annotation applies to expiration

### ISSUE THREAD

**Issue by billrayburn** [aws/karpenter-provider-aws#5125]
### Description

**How can the docs be improved?**

Update https://karpenter.sh/docs/concepts/disruption/#node-level-controls to clarify that `do-not-disrupt` annotation applies to both expiration as well as consolidation. Currently only mentions consolidation.

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by theothermike** [comment]
This just cost us over a grand in EC2 costs, YES PLEASE UPDATE THE DOCS
