### ISSUE TITLE
Back AWS Global Tags in Helm Chart and defaultInstanceProfile

### ISSUE THREAD

**Issue by fonteslucas** [aws/karpenter-provider-aws#5131]
### Description

**What problem are you trying to solve?**
In the Alpha version, we could pass tags in the global configuration that allow us to simplify the management of tags when deploying karpenter nodes with ArgoCD, exposing only few fields to developer to pass in AWSNodeTemplate.

In the ArgoCD, the manifests were something like this:

> apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: karpenter-provisioner
spec:
  consolidation:
    enabled: true
  labels:
    type: karpenter
  requirements:
    - key: karpenter.sh/capacity-type
      operator: In
      values: ["spot"]
    - key: "node.kubernetes.io/instance-type"
      operator: In
      values: ["t3a.medium", "t3.medium"]
  limits:
    resources:
      cpu: 1000
      memory: 1000Gi
  providerRef:
    name: karpenter-node

> apiVersion: karpenter.k8s.aws/v1alpha1
kind: AWSNodeTemplate
metadata:
  name: karpenter-node
spec:
  subnetSelector:
    karpenter.sh/discovery: ""
  securityGroupSelector:
    karpenter.sh/discovery: ""
  tags:
    app.kubernetes.io/created-by: karpenter

And the controller was deployed with the EKS Cluster with terraform, configuring the helm values that allows the previous NodeTemplate and Provisioner beeing "simpler" for the dev, and fixing some values that governance ask, for example:

> helm_config = merge(
    {
      name       = local.name
      chart      = local.name
      repository = "oci://public.ecr.aws/karpenter"
      version    = "v0.30.0"
      namespace  = local.name
      values = [
        <<-EOT
          settings:
            aws:
              clusterName: ${var.addon_context.eks_cluster_id}
              clusterEndpoint: ${var.addon_context.aws_eks_cluster_endpoint}
              defaultInstanceProfile: ${var.node_iam_instance_profile}
              interruptionQueueName: ${try(aws_sqs_queue.this[0].name, "")}
              tags: ${local.tags}
        EOT
      ]

**How important is this feature to you?**

Governance and GitOps "simpler" with ArgoCD

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by jonathan-innis** [comment]
> exposing only few fields to developer to pass in AWSNodeTemplate

We're trying to get out of the business of doing global configuration since it makes it difficult to orchestrate things like drift detection where we basically can't drift on the global mechanism. Is there a way that you could auto-populate these tags/enforce that these tags are present on every EC2NodeClass through an admission policy/admission webhook

**Comment by fonteslucas** [comment]
Sorry, I do not understand.
Can you please provide an example of this?

> Is there a way that you could auto-populate these tags/enforce that these tags are present on every EC2NodeClass through an admission policy/admission webhook

**Comment by jonathan-innis** [comment]
You could use something like [Kyverno](https://kyverno.io/) to automatically see any new EC2NodeClass and auto-populate fields into it. You can do this so that this happens when certain names are used, annotations are added, or labels are added.
