### ISSUE TITLE
Disruption policy WhenUnderUtilized not working accordingly.

### ISSUE THREAD

**Issue by marcofranssen** [aws/karpenter-provider-aws#5154]
### Description

**Observed Behavior**:

Unable to configure consolidateAfter with WhenUnderUtilized.

**Expected Behavior**:

Be able to define the consolidateAfter when using policy WhenUnderUtilized.

**Reproduction Steps** (Please include YAML):

**Versions**:
- Chart Version: 0.32.1
- Kubernetes Version (`kubectl version`): 1.26

I think these validation rules are mixed up and therefore not allow to configure the consolidation that should happen with WhenUnderUtilized.

See https://github.com/aws/karpenter/blob/main/pkg/apis/crds/karpenter.sh_nodepools.yaml#L66-L70

1. Am I correct?
2. Can we enhance [the documentation](https://karpenter.sh/docs/concepts/disruption/#consolidation) to make these settings and combinations more understandable?

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by jonathan-innis** [comment]
> Unable to configure consolidateAfter with WhenUnderUtilized

This is the correct behavior for `consolidateAfter` today. You can see this in the [NodePool conceptual docs here](https://karpenter.sh/docs/concepts/nodepools/#:~:text=This%20value%20can%20currently%20only%20be%20set%20when%20the%20consolidationPolicy%20is%20%27WhenEmpty%27).

There are some technical limitations to us being able to support `consolidateAfter` with `consolidationPolicy=WhenUnderutilized` today. The details of this are captured in https://github.com/kubernetes-sigs/karpenter/issues/735
