### ISSUE TITLE
Karpenter consolidation after 15 minutes if pod is not spun up

### ISSUE THREAD

**Issue by badaldavda8** [aws/karpenter-provider-aws#5184]
### Description

**Observed Behavior**:

Version - karpenter-v0.29.1

Using Karpenter with EKS v1.28

I have a setup where my node needs to download a docker image and import the image using ctr. This operation goes beyond 15mins. 

When I check my pod, it initializes and starts running but during that period the node starts terminating.

**Expected Behavior**:

The 15min time should be configurable in case of node startup.  Will this be resolved if I upgrade to the latest karpenter version with new terminologies and new properties?

**Reproduction Steps** (Please include YAML):
pod should not start until 15mins and then after 15mins when it starts, node has already been marked for consolidation. This race condition does not let my pod complete.

**Versions**:
- Chart Version: v0.29.1
- Kubernetes Version (`kubectl version`): 1.28

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

Screenshots and Logs For reference - 
![MicrosoftTeams-image (2)](https://github.com/aws/karpenter/assets/45222001/a678ea4d-fd12-4a96-8114-2263d7081956)
![MicrosoftTeams-image (1)](https://github.com/aws/karpenter/assets/45222001/7e85e5ce-61dc-4435-ae4c-cc8a6ae58250)
![MicrosoftTeams-image](https://github.com/aws/karpenter/assets/45222001/76eea26f-8961-4b16-a89c-910da62ee9d6)
[karp.log](https://github.com/aws/karpenter/files/13498235/karp.log)

**Comment by jmdeal** [comment]
Can you provider your `Provisioner`, `AWSNodeTemplate`, and pod specs? Also it doesn't seem like the provided logs capture the node in the screenshot, do you have logs that capture the event shown in the screenshot so we can determine what triggered it to be deleted?

**Comment by jmdeal** [comment]
Also to clarify, is the pod able to schedule to the node while the node is pulling this image or is the Node not ready until after this 15 minute period?
