### ISSUE TITLE
unexpected status from HEAD request to https://public.ecr.aws/v2/karpenter/karpenter-crd/manifests/v0.29.0: 400 Bad Request

### ISSUE THREAD

**Issue by gkaskonas** [aws/karpenter-provider-aws#5186]
### Description

**Observed Behavior**:
unexpected status from HEAD request to https://public.ecr.aws/v2/karpenter/karpenter-crd/manifests/v0.29.0: 400 Bad Request when installing any version of the chart

**Expected Behavior**:
Install ok
**Reproduction Steps** (Please include YAML):
I am using AWS CDK Helm installation
**Versions**:
- Chart Version: any
- Kubernetes Version 1.28

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by Infra-Red** [comment]
It seems to be a wider issue with `public.ecr.aws`, I'm getting the same error when trying to install `aws-controllers-k8s/ecr-chart`:

```sh
Error: unexpected status from HEAD request to https://public.ecr.aws/v2/aws-controllers-k8s/ecr-chart/manifests/1.0.9: 400 Bad Request
```

**Comment by gkaskonas** [comment]
Latest CDK uses Helm Version: 3.13.1

**Comment by corkupine** [comment]
Running CDKTF 0.19.2 with Helm v3.13.2 and ran into this same issue. Tried `docker logout public.ecr.aws` as well as omitting repo username and password, and still get the same error.

**Comment by AnilPothula** [comment]
https://docs.aws.amazon.com/AmazonECR/latest/public/public-troubleshooting.html

below worked for me
```sh
docker logout public.ecr.aws
helm registry logout public.ecr.aws
```
