### ISSUE TITLE
Karpenter memory utilisation balloons after upgrade to 0.32.2

### ISSUE THREAD

**Issue by paddy-bedraggled** [aws/karpenter-provider-aws#5196]
### Description

**Observed Behavior**:
After upgrading Karpenter Helm Chart from v0.31.1 to v0.32.2 the memory usage more than doubles in some cases. In all clusters a dramatic change in memory utilisation can be seen.

This cluster with 33 nodes + 7 Fargate nodes running approximately 1000 pods
![Screenshot 2023-11-30 at 17 17 36](https://github.com/aws/karpenter/assets/65182762/df61e9fc-eb65-4fc2-b830-5222b0372696)

This cluster with 12 nodes + 7 Fargate nodes running approximately 250 pods
![Screenshot 2023-11-30 at 17 19 37](https://github.com/aws/karpenter/assets/65182762/a4afc91b-aad4-4e19-980c-eb2d46d9cb6a)

**Expected Behavior**:
Memory utilisation should remain the same where
* No changes occurred with the work load on the cluster
* No new Karpenter features were activated during/prior to this upgrade

If this is expected, a note about this in the Changelog would be good to apprise users

**Reproduction Steps** (Please include YAML):
Upgrade to Karpenter 0.32.2 from 0.31.1
Monitor resource utilisation of the pods/deployment

**Versions**:
- Chart Version:
0.32.2

**Update:** 
The issue starts in version 0.32.0 and is present in later versions as above.

Reverting back to 0.31.2 from 0.32.2 seems to restore original memory usage

![image](https://github.com/aws/karpenter/assets/65182762/64ab4c25-5705-4ec5-b3da-7c8dc23c1aa3)

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by jonathan-innis** [comment]
Can you share the number of pods and nodes that you are running on your cluster?

**Comment by jonathan-innis** [comment]
Looks like there is a critical detail that's missed in the documentation here which is that you need to enable the `ENABLE_PROFILING` environment variable on the Karpenter container to enable the profiling server.

**Comment by jonathan-innis** [comment]
It's surprising to me that your memory utilization would be that high. I'm working to replicate your environment and I'm not seeing anywhere near the same utilization (getting around 500Mi of memory usage with 40 nodes and around 30 pods/node)

**Comment by jonathan-innis** [comment]
I'm still digging into it, but just doing a cursory look, it looks like something changed with the way that we are storing our InstanceTypes so that the size of our InstanceTypes stored in memory increased on the new version.

**Comment by jonathan-innis** [comment]
I'm particularly suspicious of this change: https://github.com/aws/karpenter/pull/4857 which changed the way that we do instance type caching to be based on subnets instead of AZs. My initial suspicion is that something in this new hash key value is changing constantly such that we are getting cache misses and may be storing more in memory than we should here.

**Comment by jonathan-innis** [comment]
Do these spikes correlate with the spikes in the graph? It looks like if you overlay them, they might occur during the same periods of time. Also, can you share if each Provisioner that you have is pointing to a different AWSNodeTemplate or if they are all pointing to the same one?

**Comment by jonathan-innis** [comment]
> All our provisioners reference their own dedicated AWSNodeTemplate

How different are they? Do they reference different security groups? Different subnets? Different AMIs? etc?

**Comment by jonathan-innis** [comment]
I overlayed an `instance_type_cache_size` metric over the memory utilization for a test container of Karpenter that I had spinning up nodes with 60 Provisioners and 60 AWSNodeTemplates and this was the result of doing that

<img width="718" alt="Screenshot 2023-12-01 at 8 14 19 PM" src="https://github.com/aws/karpenter/assets/26334334/bb6b7e9d-779f-464e-9958-654cb4d319b9">

It definitely looks like they are strongly correlated. When looking at the difference between the cache sizes on v0.31.2 vs. the cache sizes on v0.32.3, I can see that there's a big jump in cache size. I had to deploy a number of different AWSNodeTemplates to properly see the memory and instance type cache jump up

<img width="718" alt="Screenshot 2023-12-01 at 8 15 36 PM" src="https://github.com/aws/karpenter/assets/26334334/1b604723-6452-4dbb-bd75-2426d13ff92d">

**Comment by engedaam** [comment]
The memory increases seems to becoming from the key the is used to store our instancetype in cache. We have a cache key that is being created every minute and possible duplicating data. Several values are used in the creation of the cache key:

1. instanceTypeSeqNum 
2. instanceTypeOfferingSeqNum 
3. unavailableOfferingsSeqNum
4. ec2nodeclass UID
5. subnetHash 
6. kubeletConfigurationHash 

There are two components that are contributing to the memory increases: 
1. instancetype and instanceTypeOffering data expiries every minute, but the data is not being cleaned up after 10 minutes
2. Storing new cache key for every EC2Nodeclass even if the relevant EC2Nodeclass details are the same for multiple EC2Nodeclass.  

Going forward, the plan will be to clear out the cache when the instanceType and instanceTypeOffering has changed or updated. Also, the cache key should hold the relevant unique configuration values from the Nodepool and EC2Nodeclass, and not a key for each kubeletConfiguration and EC2Nodeclass combination, as that can result in duplicate data if the relevant values are the same.
