### ISSUE TITLE
Removal of default Instance Profile breaks old AWSNodeTemplates

### ISSUE THREAD

**Issue by j-vizcaino** [aws/karpenter-provider-aws#5205]
### Description

**Observed Behavior**:

0.32.x introduced new CRDs and, in the process removed the default instance profile option from the chart options.

This means upgrading to 0.32 silently breaks all previously existing AWSNodeTemplates that relied on that feature: no new nodes for those nodes can be provisioned anymore, and the controller logs informs about default-instance-profile.
 
**Expected Behavior**:

* Maintain support for default instance profile and push it to 0.33 to ease migration between 0.31 and 0.32.
* Document this edge case

**Reproduction Steps** (Please include YAML):

* Deploy Karpenter latest 0.31 with `defaultInstanceProfile` set
* Create a AWSNodeTemplate without `instanceProfile`
* Verify that new nodes of that type can be created
* Upgrade to 0.32.3, loose the ability to define `defaultInstanceProfile` in chart
* Controller starts, finds existing v1alpha[15] CRDs
* Creation of nodes supported by the previous AWSNodeTemplates does not work anymore.

**Versions**:
- Chart Version: 0.32.3
- Kubernetes Version (`kubectl version`): 1.27.7

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by jonathan-innis** [comment]
You can still enable the `defaultInstanceProfile` in the `karpenter-global-settings` and you _should_ still enable it in there if you are running AWSNodeTemplates that do not contain an instance profile in v0.32.3. The setting is under `settings.aws.defaultInstanceProfile` still, we just don't document the value as part of the chart in an effort to migrate users over to the newer values.

**Comment by jonathan-innis** [comment]
I was able to successfully deploy nodes using a Provisioner and AWSNodeTemplate that didn't have an `instanceProfile` value set when I had the `defaultInstanceProfile` value set on `v0.32.3`.

**Comment by j-vizcaino** [comment]
Hi @jonathan-innis, thank you for your reply, I'll give this a try next week (got pulled into another topic).

Should this trick be documented to prevent other users stepping into the same trap?

**Comment by j-vizcaino** [comment]
I was able to successfully (and smoothly) upgrade to Karpenter 0.32.3 today, thanks to your comment 🎉 

I see that the docs still reference the `defaultInstanceProfile` option in the `helm upgrade` command.
This issue can be closed. Thank you for your help 🙇🏻
