### ISSUE TITLE
How to avoid frequent changes in the number of nodes due to frequent ci?

### ISSUE THREAD

**Issue by txjjjjj** [aws/karpenter-provider-aws#5211]
### Description

env:
```
karpenter v0.31.2 
```

Q1. Is it possible to wait a few minutes before terminating a node? 
I have a lot of apps, which are likely to be released intensively (perhaps with short time intervals between releases), and at each rolling update, a node will register and terminating, in order to avoid this.

Q2. At present, we found that there is only an event (DeprovisioningTerminating/RemovingNode) generated when decoupling nodes(BTW, some of the labels of the new node can be carried for datadog event alert msg).

There is no event when a new node is registered. This makes it impossible to prepare for monitoring new node registration.
Any plans to add this k8s event, or any other workarounds?

**Comment by txjjjjj** [comment]
@jmdeal 

1.We currently use the consolidation feature for cost save, And we want to avoid the problem of frequent changes in the number of nodes. What's the workaround?


2. We are actually pointing to an event registered by the node of interest. This type of event can be emitted by the karpenter.

Currently karpenter only fires the event when terminating a machine.
<img width="740" alt="image" src="https://github.com/aws/karpenter-provider-aws/assets/60080355/0a6395fa-88a5-4610-90f5-2a6e8996d344">

**Comment by jmdeal** [comment]
Configuring `ttlSecondsAfterEmpty` is the workaround, are you running into issues with this? As for the events, which stage of node creation are you looking for an event for? Many of those events are already covered by the Node itself (e.g. node registration, node ready, etc).
