### ISSUE TITLE
Evict pods like rolling-update

### ISSUE THREAD

**Issue by Vormillion** [aws/karpenter-provider-aws#5232]
### Description

Hi,

We have cluster with development environments and each pod is a single replica. During the consolidation, Karpenter is deleting this single pod so it transforms to Terminating status and new pod is in Init status. Of course it cause downtime as new connections cannot be routed to Terminating pod.

We'd like to have some option to control how pods are rescheduled during consolidation. I think that maybe after node cordon, Karpenter can do rollout restart of pod so it will respect maxUnavailable parameter and we can avoid downtime. At the end node can be deleted.

Is it something on roadmap or maybe there is already an existing solution? For sure I don't want to disable consolidation, it should just be aware of single replicas and avoid downtime.

**Comment by ellistarn** [comment]
Check out the conversation here: https://github.com/kubernetes-sigs/karpenter/issues/740

**Comment by vainkop** [comment]
How is it completed? The linked issues is closed due to inactivity but is pretty important

**Comment by nikoul** [comment]
This issue also affects our single-replica deployments that are accessed through a service. Initially, I considered using a preStop hook, but this solution proved ineffective since it still transitions the pod to a terminating state and immediately removes it from the service endpoints.
