### ISSUE TITLE
Chart repo: charts.karpenter.sh -> 404

### ISSUE THREAD

**Issue by netanel-haber** [aws/karpenter-provider-aws#5251]
### Description

**Observed Behavior**:
Deprecated  `charts.karpenter.sh` but ostensibly preserved chart repo is returning a 404.
```bash
curl -I 'https://charts.karpenter.sh/' | head -1
...
HTTP/2 404
```

**Expected Behavior**:
https://karpenter.sh/docs/upgrading/upgrade-guide/#upgrading-to-v0170 - states that the old site will be maintained, and there is no further communication that I've seen that changes this status:

> With this change [charts.karpenter.sh](https://charts.karpenter.sh/) is no longer updated but preserved to allow using older Karpenter versions. For examples on working with the Karpenter helm charts look at [Install Karpenter Helm Chart](https://karpenter.sh/docs/getting-started/getting-started-with-karpenter/#install-karpenter-helm-chart).

This has broken a production argocd setup, and affects anything that relies on this url to be alive, including scripting and CI/CD environments.

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by ellistarn** [comment]
https://charts.karpenter.sh/index.yaml is now resolving.
