### ISSUE TITLE
Karpenter nodes are not coming up

### ISSUE THREAD

**Issue by amitmantha** [aws/karpenter-provider-aws#5267]
Karpenter nodes are not coming up, instead of having unscheduled pods.
karpenter version : v0.33

pod:
dcpui               serviceaccount-59cb5b648d-8vpw2                 0/1     Pending   0          23s

Events:
  Type     Reason            Age   From               Message
  ----     ------            ----  ----               -------
  Warning  FailedScheduling  54s   default-scheduler  0/1 nodes are available: 1 Insufficient cpu. preemption: 0/1 nodes are available: 1 No preemption victims found for incoming pod..
  Normal   Nominated         53s   karpenter          Pod should schedule on: nodeclaim/default-zjrnm
  
  sh-4.2$ kubectl get nodes
NAME                                         STATUS   ROLES    AGE   VERSION
ip-172-25-18-28.us-west-2.compute.internal   Ready    <none>   55m   v1.26.6-eks-a5565ad

**Comment by jonathan-innis** [comment]
Are the nodes ever joining the cluster? Have you looked at the instances after they are launched by the NodeClaim to see if the instance is getting terminated as soon as it's launched?

**Comment by limanalhassann** [comment]
@jonathan-innis I am having same issue here: https://github.com/aws/karpenter-provider-aws/issues/6323. Can you kindly add your advice here
