### ISSUE TITLE
Spot Instances Not scaling

### ISSUE THREAD

**Issue by jls-appfire** [aws/karpenter-provider-aws#5270]
### Description

**Observed Behavior**: 
Upgraded to v0.33.0 and spot instances do not launch. I received the error 
```
UnauthorizedOperation: You are not authorized to perform this operation. User: arn:aws:sts::1234567890123:assumed-role/my-cluster-karpenter-controller/1234567890 is not authorized to perform: ec2:CreateTags on resource: arn:aws:ec2:us-east-1:1234567890123:spot-instances-request/* because no identity-based policy allows the ec2:CreateTags action.
```

**Expected Behavior**:
Spot instances launch correctly when required.

**Reproduction Steps** (Please include YAML):
- Created the IAM role from https://raw.githubusercontent.com/aws/karpenter-provider-aws/v0.33.0/website/content/en/preview/upgrading/v1beta1-controller-policy.json (I got to this URL by following the the v0.32.3 upgrade guide and then changing the URL for v0.33.0).
- Deployed version 0.33.0
- Created a node pool with only spot instance type
- Created an EC2 Node Class

I don't use CloudFormation, I use Terraform. The documentation makes it very easy to use CF, but I have to interpret many different things for Terraform. So it's possible I did something wrong along the way. I could not readily find links to standalone IAM policy files and had to fumble my way through the process.

Node Pool setting used:
```
      - key: karpenter.sh/capacity-type
        operator: In
        values:
        - spot
```

**OTHER INFORMATION**:
Last time something similar happened to me, the issue turned out to be that I had grabbed the wrong version of the IAM policy. Please confirm that the IAM policy URL is correct and that there is not a newer version. Or if there is a version at an alternate location.

The issue was resolved for me when I changed these sections:
```
		{
			"Action": "ec2:CreateTags",
			"Condition": {
				"StringEquals": {
					"aws:RequestTag/kubernetes.io/cluster/my-cluster": "owned",
					"ec2:CreateAction": [
						"RunInstances",
						"CreateFleet",
						"CreateLaunchTemplate"
					]
				},
				"StringLike": {
					"aws:RequestTag/karpenter.sh/nodepool": "*"
				}
			},
			"Effect": "Allow",
			"Resource": [
				"arn:aws:ec2:us-east-1:*:fleet/*",
				"arn:aws:ec2:us-east-1:*:instance/*",
				"arn:aws:ec2:us-east-1:*:volume/*",
				"arn:aws:ec2:us-east-1:*:network-interface/*",
				"arn:aws:ec2:us-east-1:*:launch-template/*"
			],
			"Sid": "AllowScopedResourceCreationTagging"
		},
		{
			"Action": "ec2:CreateTags",
			"Condition": {
				"ForAllValues:StringEquals": {
					"aws:TagKeys": [
						"karpenter.sh/nodeclaim",
						"Name"
					]
				},
				"StringEquals": {
					"aws:ResourceTag/kubernetes.io/cluster/my-cluster": "owned"
				},
				"StringLike": {
					"aws:ResourceTag/karpenter.sh/nodepool": "*"
				}
			},
			"Effect": "Allow",
			"Resource": [
				"arn:aws:ec2:us-east-1:*:instance/*"
			],
			"Sid": "AllowScopedResourceTagging"
		},
```
to this value (I added `"arn:aws:ec2:us-east-1:*:spot-instances-request/*"` to both sections):
```
		{
			"Action": "ec2:CreateTags",
			"Condition": {
				"StringEquals": {
					"aws:RequestTag/kubernetes.io/cluster/my-cluster": "owned",
					"ec2:CreateAction": [
						"RunInstances",
						"CreateFleet",
						"CreateLaunchTemplate"
					]
				},
				"StringLike": {
					"aws:RequestTag/karpenter.sh/nodepool": "*"
				}
			},
			"Effect": "Allow",
			"Resource": [
				"arn:aws:ec2:us-east-1:*:fleet/*",
				"arn:aws:ec2:us-east-1:*:instance/*",
				"arn:aws:ec2:us-east-1:*:volume/*",
				"arn:aws:ec2:us-east-1:*:network-interface/*",
				"arn:aws:ec2:us-east-1:*:launch-template/*",
				"arn:aws:ec2:us-east-1:*:spot-instances-request/*"
			],
			"Sid": "AllowScopedResourceCreationTagging"
		},
		{
			"Action": "ec2:CreateTags",
			"Condition": {
				"ForAllValues:StringEquals": {
					"aws:TagKeys": [
						"karpenter.sh/nodeclaim",
						"Name"
					]
				},
				"StringEquals": {
					"aws:ResourceTag/kubernetes.io/cluster/my-cluster": "owned"
				},
				"StringLike": {
					"aws:ResourceTag/karpenter.sh/nodepool": "*"
				}
			},
			"Effect": "Allow",
			"Resource": [
				"arn:aws:ec2:us-east-1:*:instance/*",
				"arn:aws:ec2:us-east-1:*:spot-instances-request/*"
			],
			"Sid": "AllowScopedResourceTagging"
		},
```

**Versions**:
- Chart Version: 0.33.0
```
❯ helm ls -n kube-system | grep karpenter
karpenter                       kube-system     10              2023-12-07 11:02:39.074263 -0500 EST    deployed        karpenter-v0.33.0                               0.33.0     
karpenter-crd                   kube-system     9               2023-12-07 11:02:36.084741 -0500 EST    deployed        karpenter-crd-v0.33.0                           0.33.0     
```

- Kubernetes Version (`kubectl version`):
```
❯ kubectl version
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.2", GitCommit:"7f6f68fdabc4df88cfea2dcf9a19b2b830f1e647", GitTreeState:"clean", BuildDate:"2023-05-17T14:20:07Z", GoVersion:"go1.20.4", Compiler:"gc", Platform:"darwin/arm64"}
Kustomize Version: v5.0.1
Server Version: version.Info{Major:"1", Minor:"28+", GitVersion:"v1.28.3-eks-4f4795d", GitCommit:"e77944ea667aee90c84c48a74a2a0da7a23e0508", GitTreeState:"clean", BuildDate:"2023-10-20T23:21:39Z", GoVersion:"go1.20.10", Compiler:"gc", Platform:"linux/amd64"}
```

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by ellistarn** [comment]
Your policy looks right to me. This may be something that AWS support is better equipped to help with.

**Comment by jls-appfire** [comment]
I do have the service linked role. I think that the file I grabbed is not the correct one. Meaning there are two copies out there of the IAM policy file and the one I grabbed is not correct. I checked the CloudFormation code for v0.33.0 and it already includes that missing `"arn:aws:ec2:us-east-1:*:spot-instances-request/*"` item in the resource list.

**Comment by jls-appfire** [comment]
@ellistarn - I'm not sure this should be closed. I had to manually fix the policy file I downloaded from  https://raw.githubusercontent.com/aws/karpenter-provider-aws/v0.33.0/website/content/en/preview/upgrading/v1beta1-controller-policy.json

That policy file doesn't match what is available in v0.33.0 of the CloudFormation script. So I'm assuming that the CloudFormation script is accurate but the JSON file is not. Perhaps the controller policy file should be deleted or updated?

As a non CloudFormation user, I go to the non CloudFormation files first, and I'm sure there are many others out there in the same boat. Are there plans to get documentation that isn't CloudFormation focused so us non-CloudFormation users don't have to sort through JSON files and CloudFormation scripts to find correct information?

**Comment by ellistarn** [comment]
Sorry I misinterpreted your last message.

**Comment by jonathan-innis** [comment]
> That policy file doesn't match what is available in v0.33.0 of the CloudFormation script. So I'm assuming that the CloudFormation script is accurate but the JSON file is not.

**Comment by jls-appfire** [comment]
@jonathan-innis the issue for me was that I *thought* that if the file  at https://raw.githubusercontent.com/aws/karpenter-provider-aws/v0.33.0/website/content/en/preview/upgrading/v1beta1-controller-policy.json _has v0.33.0 in the path_, then it would be the exact same policy as the v0.33.0 CloudFormation policy file. How can you have a v1beta1 policy version v0.33.0 that is different then the published CloudFormation file? I can understand why v0.32.3 would have a different policy, it is an entirely different version.

**Comment by jls-appfire** [comment]
Also, thank you @ellistarn and @jonathan-innis for the help with everything, appreciate the responsiveness / support, and appreciate you're having created / contributed to this package.

One last question for you - is there another place to look for the policy file outside of CloudFormation? Is that path documented and I just missed it?

Thank you again!

**Comment by jonathan-innis** [comment]
> is there another place to look for the policy file outside of CloudFormation

**Comment by kasvith** [comment]
Hi, i had the same issue when i did `v1beta` migration with https://raw.githubusercontent.com/aws/karpenter-provider-aws/v0.32.10/website/content/en/preview/upgrading/v1beta1-controller-policy.json according to the [guide](https://karpenter.sh/v0.32/upgrading/v1beta1-migration/#upgrade-procedure)

Faced the same issue and had to manually update the policy as @jls-appfire did to resolve it

I also wasn't using Cloudformation or Terraform

It would be good to add this to the policy document or at least putting a note in the guide about potential issue

Note: i already had the linked role
