### ISSUE TITLE
Unclear upgrade instructions for Log Encoding

### ISSUE THREAD

**Issue by rifelpet** [aws/karpenter-provider-aws#5288]
### Description

**Observed Behavior**:

The [0.32.0 upgrade guide](https://karpenter.sh/docs/upgrading/upgrade-guide/) mentions changes to log encoding:

> The default log encoding changed from console to json. If you were previously not setting the type of log encoding, this default will change with the helm chart. If you were setting the value through logEncoding, this value will continue to work until v0.33.x but it is deprecated in favor of logConfig.logEncoding

However in 0.33.0 the `logConfig.logEncoding` helm value has no effect. [Searching the repo](https://github.com/search?q=repo%3Aaws%2Fkarpenter-provider-aws%20logEncoding&type=code) doesn't show any usage of this value in chart templates

If support for changing the log encoding is intentionally removed, the guide should state as such.  Otherwise the templates arent using the value. I see the [env var for LOG_LEVEL](https://github.com/kubernetes-sigs/karpenter/blob/cc54b340f630b46a26d19a3cbd49d90c8b3a6d45/pkg/operator/options/options.go#L94) but nothing for log encoding so I'm not sure how it the chart would use the value.

**Expected Behavior**:

`logConfig.logEncoding` helm value affects the pod's log encoding

**Reproduction Steps** (Please include YAML):

`helm template karpenter oci://public.ecr.aws/karpenter/karpenter --version v0.33.0 --set logConfig.logEncoding=foobar | grep foobar`
 
**Versions**:
- Chart Version: v0.33.0
- Kubernetes Version (`kubectl version`): 1.28.0

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by jonathan-innis** [comment]
Anything in the `logConfig` section is deployed or not deployed through `--set logConfig.enabled`. There's mention that this value changed in `v0.33.x` here: https://karpenter.sh/docs/upgrading/upgrade-guide/#:~:text=v0.33.x%20drops%20looking,Guide%20for%20more%20details.

**Comment by calvinbui** [comment]
@jonathan-innis  Can I also get clarification?

- 0.31 -> 0.32: change to [logConfig](https://karpenter.sh/docs/upgrading/v1beta1-migration/#helm-values)
- 0.32 -> 0.33: logConfig is now deprecated, use [logLevel instead](https://github.com/aws/karpenter-provider-aws/blob/571e0fb471f04f873c290287e2ff03a6210410f6/charts/karpenter/values.yaml#L145)

What's the right way to configure outpath paths as `logLevel` only controls the severity of the messages outputted? I am using the helm chart to install Karpenter and its CRDs.

**Comment by jonathan-innis** [comment]
> What's the right way to configure outpath paths as logLevel only controls the severity of the messages outputted? I am using the helm chart to install Karpenter and its CRDs

We're dropped the majority of the log configuration directly supported by Karpenter since the general stance that we have is that we surfaced too much logging configuration through the Zap config originally and are pulling back to take a more opinionated stance on how logs should be output.

You can still configure the output paths and error output paths through the `logConfig.outputPaths` and `logConfig.errorOutputPaths` repspectively.

How do you have this configured on your side that's different than the default?

**Comment by calvinbui** [comment]
> You can still configure the output paths and error output paths through the `logConfig.outputPaths` and `logConfig.errorOutputPaths` repspectively.

but isn't using `logConfig` deprecated as I've linked above? is there a replacement for it yet?

**Comment by jonathan-innis** [comment]
> is there a replacement for it yet

No, there's no replacement for it. In general, we looked across the project landscape and didn't see a ton of utility to supporting all of the API surface that Zap logger was directly supporting. Much of the logging config that they were supporting could likewise be supported in the log scraper or log aggregator. 

We'd be open to considering additional API surface moving forward on a one-off basis, but (at least for tracking) it would be best if you opened a separate feature ask to return one of these fields. It'd be good to layout the reasons why you want the field back and the limitations that you are running into with the lack of proposed support around it.

**Comment by calvinbui** [comment]
No, I only wanted clarification on how to configure logging on 0.33.0 properly given the changes I mentioned earlier. 

I'm still using `logConfig.outputPaths` and `logConfig.errorOutputPaths` since the 0.32.0 upgrade.

**Comment by jonathan-innis** [comment]
> No, I only wanted clarification on how to configure logging on 0.33.0 properly given the changes I mentioned earlier

Unless you have explicit need, I would move away from using the `logConfig` and only set the `--log-level` on the karpenter controller, let karpenter handle the rest. If there are particular features that you need that are _only_ supported in the `logConfig`, that's where I'd recommend that you open an issue. 

Hope that helps 👍🏼

**Comment by calvinbui** [comment]
Understood 👍🏼

Yeah, we need still `logConfig` to forward logs. Fargate Fluent Bit doesn't support Loki yet (https://github.com/aws/containers-roadmap/issues/1242)

**Comment by jonathan-innis** [comment]
Got it, yeah. This is the type of feedback we are looking for to understand which configuration parameters need to be supported long-term and are actually critical to everyone else trying to run Karpenter.

It would be _enormously_ helpful if you could open an issue for this as a feature request, ref-ing out the issue that you just referenced here so that we can track and consider this as we go to v1.
