### ISSUE TITLE
The Helm chart version isn't a valid SemVer

### ISSUE THREAD

**Issue by stevehipwell** [aws/karpenter-provider-aws#5305]
### Description

**Observed Behavior**:
The Karpenter Helm chart is currently using the release tag instead of the release version for the chart version; so `v0.33.0` instead of `0.33.0`. This causes unexpected behaviour in various tools including Helm itself (see below).

This must be happening as part of the release process as the _Chart.yaml_ is structured correctly.

I'm happy to open a PR to fix this.

**Expected Behavior**:
I'd expect the Karpenter Helm chart to use a SemVer version.

**Reproduction Steps** (Please include YAML):

Run the following command and observe the error; it should pull the latest chart version.

```shell
helm pull oci://public.ecr.aws/karpenter/karpenter
```

**Versions**:
- Chart Version: n/a
- Kubernetes Version (`kubectl version`): n/a

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by stevehipwell** [comment]
CC @jonathan-innis

**Comment by jonathan-innis** [comment]
Looks like a duplicate of #4248. We'd definitely support an update where we push both tags. I'm not sure that we can completely drop the old version. Does helm not work if we support both tags in our ECR?

**Comment by stevehipwell** [comment]
@jonathan-innis either GitHub or I had an issue yesterday as I specifically searched for existing issues, I'll take my reply into #4248.
