### ISSUE TITLE
IAM Policy

### ISSUE THREAD

**Issue by bluegumcity** [aws/karpenter-provider-aws#5309]
### Description

Please publish the needed IAM roles/policies needed. See https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.6/deploy/installation/#configure-iam as an example.

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by jonathan-innis** [comment]
The IAM policy needed to run Karpenter is included as part of the Getting Started Guide here: https://github.com/aws/karpenter-provider-aws/blob/main/website/content/en/docs/getting-started/getting-started-with-karpenter/cloudformation.yaml.

**Comment by bluegumcity** [comment]
@jonathan-innis It would be good if they were pure json documents that you could pretty much copy/paste. In the example given, you can just download the json documents and then run `aws iam create-policy` with them.

**Comment by jonathan-innis** [comment]
@bluegumcity There's a trade-off here for us of having to maintain and keep two different types of documents consistent here. Are you able to convert from the current Getting Started CloudFormation guide to the JSON document that you need? There was a similar discussion here on this topic #2649, so if this issue boils down to needing a JSON representation of the IAM policy, I'd point you to the other issue to add additional input. 

We're definitely not strictly opposed to it. I'd like us to support better ways to automate this for users but the problem right now is that we don't have automation that allows us to maintain both the JSON policy and the CloudFormation documents that we need. If we had that in place and had a single source-of-truth for maintaining the JSON document, then I'd be all on-board.

We'd happily accept a contribution that supported some way to achieve this; most of the maintainers don't currently have the bandwidth to support this right now.

**Comment by bluegumcity** [comment]
@jonathan-innis Thanks, closing this as a dupe of #2649
