### ISSUE TITLE
Create pod on a node with no more IP

### ISSUE THREAD

**Issue by DanielCastronovo** [aws/karpenter-provider-aws#5317]
### Description

**Observed Behavior**:
When a pod is created, they are an issue because the instance size has no more IP. Like M instance size (8 IP address limits)

**Expected Behavior**:
Assign a node type related to the limits on nodes IP address.

**Reproduction Steps** (Please include YAML):

**Versions**:
- Chart Version: v0.32.1
- Kubernetes Version (`kubectl version`): 1.27

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by FernandoMiguel** [comment]
@DanielCastronovo you should be using Prefix Delegation which will expand the number of IPs available on a node by quite a lot
https://docs.aws.amazon.com/eks/latest/userguide/cni-increase-ip-addresses.html
and you should monitor for running out of IPs in the subnets.

**Comment by njtran** [comment]
Potentially related https://github.com/aws/karpenter-provider-aws/issues/5234

**Comment by FernandoMiguel** [comment]
@njtran i don't think it is related to subnets, but to ec2 ENI capacity.

**Comment by njtran** [comment]
Agreed, was pointing to your comment about running out of IPs in the subnets.

**Comment by FernandoMiguel** [comment]
I was just trying to provide extra general guidance
