### ISSUE TITLE
Respect do-not-disrupt annotation for static pods

### ISSUE THREAD

**Issue by Devern** [aws/karpenter-provider-aws#5325]
### Description

**What problem are you trying to solve?**

Presently, the `karpenter.sh/do-not-disrupt: "true"` annotation will prevent consolidation when present on K8s resources, with the exception of terminating pods, terminal pods, DaemonSet pods and static pods.

For the use case of Airflow on Kubernetes, jobs are spawned as static pods and consolidation causes them to receive sigterm from being evicted. In this use case, it is desirable to exempt these pods from consolidation-initiated eviction.

To that end, this feature request is to implement support for the annotation `karpenter.sh/do-not-disrupt: "true"` on static pods.

**How important is this feature to you?**

Workarounds exist (disabling consolidation, scheduling to a nodegroup without consolidation), however given the transient nature of Airflow workloads, it is desirable to have it execute alongside other workloads, and making full use of consolidation is an enormous boon to efficiency.

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by njtran** [comment]
Thank you for cutting this. Since this is applicable for all cloud providers, could you cut the same issue in github.com/kubernetes-sigs/karpenter?

**Comment by Devern** [comment]
> Thank you for cutting this. Since this is applicable for all cloud providers, could you cut the same issue in github.com/kubernetes-sigs/karpenter?

I've opened the following issue in kubernetes-sigs/karpenter: https://github.com/kubernetes-sigs/karpenter/issues/863

**Comment by njtran** [comment]
Appreciate it! Will close this in favor of that one.
