### ISSUE TITLE
how to disable settings.aws.enablePodENI in v0.33.0

### ISSUE THREAD

**Issue by txjjjjj** [aws/karpenter-provider-aws#5341]
### Description

```
eks 1.28
karpenter v0.33.0
cilium cni   overlay network.  not use awscni.  the pod id is managed by cilium
```
How to disable this option, as it is not found in the new version(v0.33.0) of helm charts?
settings.aws.enablePodENI

<img width="1549" alt="image" src="https://github.com/aws/karpenter-provider-aws/assets/60080355/a3317918-80d0-409a-bb3c-f5c48e2ba2de">

What does this `vpc.amazonaws.com/pod-eni ` do? since i saw some cni log.
```
{"level":"INFO","time":"2023-12-15T16:00:26.899Z","logger":"controller.nodeclaim.lifecycle","message":"launched nodeclaim","commit":"2dd7fdc","nodeclaim":"general-64rkm","provider-id":"aws:///ap-southeast-1a/i-xxxxxxx","instance-type":"m6a.2xlarge","zone":"ap-southeast-1a","capacity-type":"spot","allocatable":{"cpu":"7910m","ephemeral-storage":"71Gi","memory":"29317Mi","pods":"123","vpc.amazonaws.com/pod-eni":"38"}}
```

Does it affect anything?  I set maxpod to 120.  but there are  "vpc.amazonaws.com/pod-eni":"38".

**Comment by jonathan-innis** [comment]
> Does it affect anything
