### ISSUE TITLE
Does the limit for nodepool indicate the entire cluster or that nodepool?

### ISSUE THREAD

**Issue by txjjjjj** [aws/karpenter-provider-aws#5342]
There are multiple nodepools configured in a cluster, and each nodepool has a limit cpu 1000, this limit is meant for this nodepool and not the whole cluster, right?

**Comment by jonathan-innis** [comment]
It indicates the limit for the NodePool itself. There's a separate issue that's opened right now over global limits for the cluster: https://github.com/kubernetes-sigs/karpenter/issues/745

**Comment by njtran** [comment]
Closing as it looks like a duplicate and is answered.
