### ISSUE TITLE
How karpenter considers Daemonset's resource requests when spawn new node?

### ISSUE THREAD

**Issue by txjjjjj** [aws/karpenter-provider-aws#5351]
### Description

```
eks: 1.28
karpenter: v0.33.0

```

My environment:

A cluster set up with two nodepools.
```
nodepoola:    my-app-a    via nodeSelector  app=a
nodepoolb:    my-app-b    via nodeSelector app=b

log-ds and datadog-ds has no any nodeSelector. 
just set default is to have them run on all nodes in the cluster.
```

When nodepool needs to expand its nodes
Q1: Is that how karpenter calculates it? All ds's requests + my-app-b's request => pick the correct instance type?

![image](https://github.com/aws/karpenter-provider-aws/assets/60080355/868b964f-6c59-4ae4-b0d9-1bc35c3dc292)

**Comment by njtran** [comment]
Hey @txjjjjj, if I understand your question right, Karpenter will consider all Daemonsets and your app resource requests when choosing which instance types can fit your pods. You can check the generated instance types information we have [here](https://karpenter.sh/docs/reference/instance-types/) for more information. Let me know if this helps.

Additionally, feel free to ask questions in the [kubernetes/karpenter slack channel](https://kubernetes.slack.com/archives/C02SFFZSA2K).
