### ISSUE TITLE
Karpenter is provisioning new nodes but they are not including them in the cluster

### ISSUE THREAD

**Issue by ricardocunha** [aws/karpenter-provider-aws#5399]
### Description

** READ BEFORE CONTINUING: If your issue is not specific to AWS, please cut a ticket in [kubernetes-sigs/karpenter](https://github.com/kubernetes-sigs/karpenter/issues/new/choose).

**Observed Behavior**:
Karpenter is provisioning new nodes and then shutting down following the requirements, however, the new nodes were not appearing on node-group. I can see up and running on EC2 instances and then those instances shutdown properly but those new nodes are not attached to the cluster properly. There are no errors on Karpenter logs. A similar configuration was working before on 0.16 with Provisioner and AWSNodeTemplate in an old cluster now I'm creating a new one with 1.28 and don't get success on it.

**Expected Behavior**:
New nodes appear on EKS

**Reproduction Steps** (Please include YAML):

Helm v0.33.1 parameters provided:

aws:
  defaultInstanceProfile: <<ommited>>
serviceAccount:
  annotations:
    eks.amazonaws.com/role-arn: <<ommited>>
settings:
  clusterEndpoint: <<ommited>>
  clusterName: engineering-pipelines
  interruptionQueue: engineering-pipelines

apiVersion: karpenter.k8s.aws/v1beta1
kind: EC2NodeClass
metadata:
  name: default
spec:
  amiFamily: AL2
  role: "${data.aws_iam_role.karpenter_controller.name}"
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: "${data.aws_eks_cluster.cluster.id}"
  securityGroupSelectorTerms:
    - id: "${data.aws_eks_cluster.cluster.vpc_config[0].cluster_security_group_id}"
  tags:
    karpenter.sh/discovery: ${data.aws_eks_cluster.cluster.id}  

apiVersion: karpenter.sh/v1beta1
kind: NodePool
metadata:
  name: default
spec:
  template:
    spec:
      requirements:
        - key: karpenter.sh/capacity-type
          operator: In
          values:
            - spot
        - key: node.kubernetes.io/instance-type
          operator: In
          values:
            - r5n.2xlarge
      nodeClassRef:
        name: default

**Versions**:
- Chart Version: v0.33.1 
- Kubernetes Version (`kubectl version`): v1.28.4

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by engedaam** [comment]
Did you upgrade using [v1beta1 migration guide](https://karpenter.sh/docs/upgrading/v1beta1-migration/)? Did upgrade to v0.32 before upgrading to v0.33 and install the v1beta1 CRDs?

**Comment by ricardocunha** [comment]
@engedaam it is a new and fresh 1.28 cluster created using Terraform

**Comment by jmdeal** [comment]
Are you able to connect to the EC2 instances and check the kubelet logs? Also, have you rolled your own terraform config or are you using a community one? Have the IAM policies been updated for v0.33.x?

**Comment by jmdeal** [comment]
Also can you provide the status from your `EC2NodeClass`?

**Comment by ricardocunha** [comment]
@jmdeal My terraform code was created by myself.
EC2NodeClass status:
`status:
  amis:
    - id: ami-02c6131deef1686f2
      name: amazon-eks-arm64-node-1.28-v20231201
      requirements:
        - key: kubernetes.io/arch
          operator: In
          values:
            - arm64
        - key: karpenter.k8s.aws/instance-gpu-count
          operator: DoesNotExist
        - key: karpenter.k8s.aws/instance-accelerator-count
          operator: DoesNotExist
    - id: ami-03cb3ad5d60227842
      name: amazon-eks-gpu-node-1.28-v20231201
      requirements:
        - key: kubernetes.io/arch
          operator: In
          values:
            - amd64
        - key: karpenter.k8s.aws/instance-gpu-count
          operator: Exists
    - id: ami-03cb3ad5d60227842
      name: amazon-eks-gpu-node-1.28-v20231201
      requirements:
        - key: kubernetes.io/arch
          operator: In
          values:
            - amd64
        - key: karpenter.k8s.aws/instance-accelerator-count
          operator: Exists
    - id: ami-0a728a56442124f5c
      name: amazon-eks-node-1.28-v20231201
      requirements:
        - key: kubernetes.io/arch
          operator: In
          values:
            - amd64
        - key: karpenter.k8s.aws/instance-gpu-count
          operator: DoesNotExist
        - key: karpenter.k8s.aws/instance-accelerator-count
          operator: DoesNotExist
  instanceProfile: engineering-pipelines_6795124765534763251
  securityGroups:
    - id: sg-032d30b0583f76b3f
      name: eks-cluster-sg-engineering-pipelines-626597929
  subnets:
    - id: subnet-0c9b23bc4fc532fdb
      zone: us-east-2b
    - id: subnet-0ef19196e7ece3ccb
      zone: us-east-2a`

My terraform code to create the iam policy:

`    "Statement": [
        {
            "Action": [
                "ssm:GetParameter",
                "iam:PassRole",
                "iam:GetInstanceProfile",
                "iam:CreateInstanceProfile",
                "iam:TagInstanceProfile",
                "iam:AddRoleToInstanceProfile",
                "iam:DeleteInstanceProfile",
                "ec2:RunInstances",
                "ec2:DescribeSubnets",
                "ec2:DescribeSecurityGroups",
                "ec2:DescribeLaunchTemplates",
                "ec2:DescribeInstances",
                "ec2:DescribeInstanceTypes",
                "ec2:DescribeInstanceTypeOfferings",
                "ec2:DescribeAvailabilityZones",
                "ec2:DeleteLaunchTemplate",
                "ec2:CreateTags",
                "ec2:CreateLaunchTemplate",
                "ec2:CreateFleet",
                "ec2:DescribeSpotPriceHistory",
                "ec2:DescribeImages",
                "pricing:GetProducts",
                "sqs:DeleteMessage",
                "sqs:ReceiveMessage",
                "sqs:GetQueueAttributes",
                "sqs:GetQueueUrl",
                "eks:DescribeCluster",
                "autoscaling:CompleteLifecycleAction",
                "autoscaling:DescribeAutoScalingInstances",
                "autoscaling:DescribeTags",
                "iam:RemoveRoleFromInstanceProfile"
            ],
            "Effect": "Allow",
            "Resource": "*",
            "Sid": "Karpenter"
        },
        {
            "Action": "ec2:TerminateInstances",
            "Condition": {
                "StringLike": {
                    "ec2:ResourceTag/karpenter.sh/nodepool": "*"
                }
            },
            "Effect": "Allow",
            "Resource": "*",
            "Sid": "ConditionalEC2Termination"
        }
    ],
    "Version": "2012-10-17"`

**Comment by jmdeal** [comment]
I think the EC2NodeClass status looks good, mostly just checking to make sure it was able to resolve the security groups. It looks like the IAM policy you added is for the Karpenter controller, can you provide the worker node role? This should be the role you specified in your EC2NodeClass (or the role linked to the instance profile if you specified that).

**Comment by ricardocunha** [comment]
@jmdeal that was my mistake I was attaching the IAM role for Karpenter and not the one for EKS nodes. After changing that it is working properly. Thank you for help me.
