### ISSUE TITLE
Interruption handling: handle 'SpotInterrupted' message immediately rather than a queue. 

### ISSUE THREAD

**Issue by pranaytripathi** [aws/karpenter-provider-aws#5400]
### Description

** READ BEFORE CONTINUING: If your issue is not specific to AWS, please cut a ticket in [kubernetes-sigs/karpenter](https://github.com/kubernetes-sigs/karpenter/issues/new/choose).

**What problem are you trying to solve?**

Currently how spot interruptions are handled is that the SpotInterrupted messages are pushed to the queue to handle different interruption messages. This can cause a delay in the message being processed and nodes to cordon and drain rather than immediately executing the cordon and drain on node when the message is received. This can cause a node to be terminated before the workloads are ported to a new node. This is a major issue when multiple nodes are spot terminated simultaneously.

**How important is this feature to you?**

We would expect spot termination events to cause an immediate cordon and drain of a node regardless of the status of any other nodes.  The drain should still object eviction rules. Rebalance recommendations (while not implemented yet) can be slower so would ideally cordon immediately and drain as port of the queue. 

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by pranaytripathi** [comment]
I am interested to work on this.

**Comment by jonathan-innis** [comment]
> This is a major issue when multiple nodes are spot terminated simultaneously

Can you clarify a bit on what the exact issue is here since I'm seeing you mention a couple things? IIUC, you are saying that the latency from the queue is causing a problem here since the message isn't seen before the EC2 instance is reclaimed by the EC2 service? What kind of latency are you observing? How many spot interruptions are you receiving at one time?

**Comment by pranaytripathi** [comment]
We currently in the analysis phase for karpenter a so this is not yet implemented so don't have a exact latency yet. The spot interruptions behaviour has been were we have multiple same types of instance terminating at the same time for example we have instances in past where 12xlarge and 24xlarge instances receive spot terminations at the same time in one of our regions.

As per my understanding, the queue is implement each message sequentially to cordon an drain the nodes, this can cause workloads to terminate before being ported to new node. Let me know I am understanding something incorrect here.

**Comment by jonathan-innis** [comment]
> this can cause workloads to terminate before being ported to new node

Karpenter will still respect PDBs during the drain, though. So as long as you are using PDBs, you should still be able to maintain application availability while Karpenter is launching the new node for the pods to move over to.

**Comment by jonathan-innis** [comment]
Realizing now that if this issue is just covering the case that we are terminating the instances that's causing a hit in application availability that this is captured in this issue here: #2917. Closing this issue as a duplicate for now. Let me know if I misunderstood and that's not correct.
