### ISSUE TITLE
karpenter service account cannot list nodeclaims

### ISSUE THREAD

**Issue by samispurs** [aws/karpenter-provider-aws#5424]
### Description

**Observed Behavior**:

v1beta1.NodeClaim: nodeclaims.karpenter.sh is forbidden: User \"system:serviceaccount:kube-system:karpenter\" cannot list resource \"nodeclaims\

**Expected Behavior**:
List nodeclaims

**Reproduction Steps** (Please include YAML):

**Versions**: 0.33.0
- Chart Version: 0.16.3
- Kubernetes Version (`kubectl version`): v1.29.0

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by jonathan-innis** [comment]
Can you check the ClusterRoleBindings and ClusterRoles to see if there is a mapping between the service account that you've listed there in the `kube-system` namespace and those ClusterRoleBindings and ClusterRoles that give permission to list NodeClaims.

**Comment by samispurs** [comment]
@jonathan-innis 

After unzipping the karpenter-0.16.3.tgz, under templates/clusterrole.yaml this is what I have.  I don't see anything related to nodeclaims

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "karpenter.fullname" . }}
  labels:
    {{- include "karpenter.labels" . | nindent 4 }}
  {{- with .Values.additionalAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
rules:
  # Read
  - apiGroups: ["karpenter.sh"]
    resources: ["provisioners", "provisioners/status"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["karpenter.k8s.aws"]
    resources: ["awsnodetemplates"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["pods", "nodes", "persistentvolumes", "persistentvolumeclaims", "replicationcontrollers"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["storageclasses", "csinodes"]
    verbs: ["get", "watch", "list"]
  - apiGroups: ["apps"]
    resources: ["daemonsets", "deployments", "replicasets", "statefulsets"]
    verbs: ["list", "watch"]
  - apiGroups: ["admissionregistration.k8s.io"]
    resources: ["validatingwebhookconfigurations", "mutatingwebhookconfigurations"]
    verbs: ["get", "watch", "list"]
  - apiGroups: [ "policy" ]
    resources: [ "poddisruptionbudgets" ]
    verbs: [ "get", "list", "watch" ]
  # Write
  - apiGroups: ["karpenter.sh"]
    resources: ["provisioners/status"]
    verbs: ["create", "delete", "patch"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create", "patch"]
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["create", "patch", "delete"]
  - apiGroups: [""]
    resources: ["pods/eviction"]
    verbs: ["create"]
  - apiGroups: ["admissionregistration.k8s.io"]
    resources: ["validatingwebhookconfigurations"]
    verbs: ["update"]
    resourceNames: ["validation.webhook.provisioners.karpenter.sh", "validation.webhook.config.karpenter.sh"]
  - apiGroups: ["admissionregistration.k8s.io"]
    resources: ["mutatingwebhookconfigurations"]
    verbs: ["update"]
    resourceNames: ["defaulting.webhook.provisioners.karpenter.sh"]

**Comment by samispurs** [comment]
ps The tar file does not include the crds required for v0.33.0, I had to add them manual into our unzipped chart.

karpenter.sh_nodepools.yaml
karpenter.sh_nodeclaims.yaml
karpenter.k8s.aws_ec2nodeclasses.yaml

**Comment by jonathan-innis** [comment]
Can you share what's actually applied to the cluster? Also, you need to share the ClusterRoleBinding too; with just the ClusterRole, there's not enough info to know if that role is properly mapped to the service account.

**Comment by samispurs** [comment]
Apologies!

clusterrolebinding in the tar:

```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "karpenter.fullname" . }}
  labels:
    {{- include "karpenter.labels" . | nindent 4 }}
  {{- with .Values.additionalAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "karpenter.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ template "karpenter.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
```

on the cluster:
```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    meta.helm.sh/release-name: karpenter
    meta.helm.sh/release-namespace: kube-system
  creationTimestamp: "2024-01-04T19:33:31Z"
  labels:
    app.kubernetes.io/instance: karpenter
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: karpenter
    app.kubernetes.io/version: 0.16.3
    helm.sh/chart: karpenter-0.16.3
  name: karpenter
  resourceVersion: "72872"
  uid: 777119d2-637b-44e3-8ec2-8d2396ff9fef
rules:
- apiGroups:
  - karpenter.sh
  resources:
  - provisioners
  - provisioners/status
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - karpenter.k8s.aws
  resources:
  - awsnodetemplates
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  - nodes
  - persistentvolumes
  - persistentvolumeclaims
  - replicationcontrollers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - storage.k8s.io
  resources:
  - storageclasses
  - csinodes
  verbs:
  - get
  - watch
  - list
- apiGroups:
  - apps
  resources:
  - daemonsets
  - deployments
  - replicasets
  - statefulsets
  verbs:
  - list
  - watch
- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - validatingwebhookconfigurations
  - mutatingwebhookconfigurations
  verbs:
  - get
  - watch
  - list
- apiGroups:
  - policy
  resources:
  - poddisruptionbudgets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - karpenter.sh
  resources:
  - provisioners/status
  verbs:
  - create
  - delete
  - patch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - create
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - pods/eviction
  verbs:
  - create
- apiGroups:
  - admissionregistration.k8s.io
  resourceNames:
  - validation.webhook.provisioners.karpenter.sh
  - validation.webhook.config.karpenter.sh
  resources:
  - validatingwebhookconfigurations
  verbs:
  - update
- apiGroups:
  - admissionregistration.k8s.io
  resourceNames:
  - defaulting.webhook.provisioners.karpenter.sh
  resources:
  - mutatingwebhookconfigurations
  verbs:
  - update
 ```

clusterrolebinding:
```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
    meta.helm.sh/release-name: karpenter
    meta.helm.sh/release-namespace: kube-system
  creationTimestamp: "2024-01-04T15:21:29Z"
  labels:
    app.kubernetes.io/instance: karpenter
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: karpenter
    app.kubernetes.io/version: 0.16.3
    helm.sh/chart: karpenter-0.16.3
  name: karpenter
  resourceVersion: "2105"
  uid: 33fe7298-04ec-4465-9980-dafc502c5b34
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: karpenter
subjects:
- kind: ServiceAccount
  name: karpenter
  namespace: kube-system
```
clusterrole karpenter-admin:

```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    meta.helm.sh/release-name: karpenter
    meta.helm.sh/release-namespace: kube-system
  creationTimestamp: "2024-01-04T19:33:31Z"
  labels:
    app.kubernetes.io/instance: karpenter
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: karpenter
    app.kubernetes.io/version: 0.16.3
    helm.sh/chart: karpenter-0.16.3
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
  name: karpenter-admin
  resourceVersion: "72870"
  uid: 05e0d940-98f6-4ae7-8de8-da4790a75cff
rules:
- apiGroups:
  - karpenter.sh
  resources:
  - provisioners
  - provisioners/status
  verbs:
  - get
  - list
  - watch
  - create
  - delete
  - patch
- apiGroups:
  - karpenter.k8s.aws
  resources:
  - awsnodetemplates
  verbs:
  - get
  - list
  - watch
  - create
  - delete
  - patch
  ```

**Comment by samispurs** [comment]
Looks like the NoePool permission is also missing. Thanks!
{"level":"ERROR","time":"2024-01-04T19:53:19.127Z","logger":"controller","message":"k8s.io/client-go@v0.28.4/tools/cache/reflector.go:229: Failed to watch *v1beta1.NodePool: failed to list *v1beta1.NodePool: nodepools.karpenter.sh is forbidden: User \"system:serviceaccount:kube-system:karpenter\" cannot list resource \"nodepools\" in API group \"karpenter.sh\" at the cluster scope","commit":"2dd7fdc"}

**Comment by samispurs** [comment]
The following fixes the permissions issues when added in templates/clusterrole.yaml

```
rules:
  # Read
  - apiGroups: ["karpenter.sh"]
    resources: ["provisioners", "provisioners/status", "nodeclaims", "nodepools"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["karpenter.k8s.aws"]
    resources: ["awsnodetemplates", "ec2nodeclasses"]
    verbs: ["get", "list", "watch"]
```

**Comment by jonathan-innis** [comment]
Both of these mention that they are coming from v0.16.3, have you updated these roles and bindings since that version?

**Comment by samispurs** [comment]
We install karpenter from a local installed chart.

helm repo add karpenter https://charts.karpenter.sh/
helm pull karpenter/karpenter --version 0.16.3 --untar

From here we use terraform to install using the blueprints-addon (https://registry.terraform.io/modules/aws-ia/eks-blueprints-addons/aws/latest)
0.16.3 does not match what's in release 0.33.0.  I see in 0.33.0 there's a clusterrole-core.yaml which is not included in the helm chart version.

The helm chart versioning and versioning that is in this repo is really confusing for me.  Is charts.karpenter.sh still the correct place to be pulling helm charts from? Thanks!

**Comment by samispurs** [comment]
I guess charts.karpenter.sh is not maintained anymore for the newer versions after 0.16.3 :(
