### ISSUE TITLE
Unable to pass a context to API_CreateFleet due to hardcoded allocation strategy

### ISSUE THREAD

**Issue by yagonobre** [aws/karpenter-provider-aws#5426]
### Description

**Observed Behavior**:
I'm trying to use a context id to create the instances using this EC2NodeClass:

```yaml
apiVersion: karpenter.k8s.aws/v1beta1
kind: EC2NodeClass
metadata:
  name: test
spec:
  context: XXXXXXXXXXXX
```

But it is failing with
```json
{"level":"ERROR","time":"2024-01-04T19:44:28.317Z","logger":"controller","message":"Reconciler error","commit":"a70b39e","controller":"nodeclaim.lifecycle","controllerGroup":"karpenter.sh","controllerKind":"NodeClaim","NodeClaim":{"name":"test-tkfr4"},"namespace":"","name":"test-tkfr4","reconcileID":"XXXXXXXX","error":"launching nodeclaim, creating instance, creating fleet InvalidParameterCombination: The \"price-capacity-optimized\" SpotAllocationStrategy is not valid for the Context \"XXXXXXXX\". Configure SpotAllocationStrategy to [\"capacity-optimized\",\"capacity-optimized-prioritized\"].\n\tstatus code: 400, request id: XXXXXXXXX"}
```

**Expected Behavior**:

Be able to define the `SpotAllocationStrategy` or Karpenter use the right strategy based on the context provided. 

**Reproduction Steps** (Please include YAML):

**Versions**:
- Chart Version: Last version
- Kubernetes Version (`kubectl version`): 
```
kubectl version --short
Flag --short has been deprecated, and will be removed in the future. The --short output will become the default.
Client Version: v1.27.3
Kustomize Version: v5.0.1
Server Version: v1.27.8-eks-8cb36c9
```

I have a draft pr to allow the user to choose the Allocation Strategy but it required futter consideration on the api changes added, I'll submit this for discussion in a bit.

Related issue https://github.com/aws/karpenter-provider-aws/issues/1240

**Comment by jonathan-innis** [comment]
I'm assuming that the context id that you are passing through requires that the launch use a different allocation strategy? I don't think that this is true for all context ids.

**Comment by yagonobre** [comment]
Yes, the context id that I'm using require it, I don't know if it is required for all context ids

**Comment by jonathan-innis** [comment]
>  I don't know if it is required for all context ids

Yeah, definitely not all context ids require that you have to specify a different allocation strategy than PCO. I think at this point (since this is basically just asking to be able to manually specify the context id), I'd recommend adding additional context over to #1240 and we can close this one as a duplicate. Let me know if that doesn't make sense to you.

**Comment by yagonobre** [comment]
Make senses!

**Comment by jonathan-innis** [comment]
I think given that we have #1240, I'm going to go ahead and close this one out.
