### ISSUE TITLE
Nodes created by Karpenter are not recognized by Terraform state

### ISSUE THREAD

**Issue by sunitanair30** [aws/karpenter-provider-aws#5428]
I'm currently using Karpenter to provision nodes in my Amazon EKS cluster. However, I've run into an issue where the nodes created by Karpenter aren't recognized by Terraform.

You see, I rely on Terraform to manage my infrastructure and keep track of the resources and their states. Unfortunately, the nodes created by Karpenter don't show up in the Terraform state. This makes it challenging for me to effectively manage and keep track of these nodes using Terraform.

We rely on the resources listed in the Terraform state to track our cloud expenses, and the absence of Karpenter resources in the state leads to inaccurate cost calculations and forecasting.

I'm reaching out for guidance and assistance on how I can dynamically add the new Karpenter resources to the relevant Terraform state. This way, I'll be able to manage and track these nodes effectively and accurately calculate our cloud expenses.

Any help or advice you can provide would be greatly appreciated.

Thank you so much.

**Comment by FernandoMiguel** [comment]
karpenter is an autoscaller . it will spin up and down based on needs.
same with AWS ASG... it will replace nodes when it needs.
you can never track that with a static state file, like the one produced by terraform.

you should instead look at something like kubecost that dynamically looks at resources.
or at tools that look at actual aws billing based on tags

**Comment by jonathan-innis** [comment]
This feels out-of-scope for the Karpenter project to be able to handle due to how dynamic the infrastructure is with Karpenter. I'm going to close this one as not planned.

**Comment by sunitanair30** [comment]
> karpenter is an autoscaller . it will spin up and down based on needs. same with AWS ASG... it will replace nodes when it needs. you can never track that with a static state file, like the one produced by terraform.
> 
> you should instead look at something like kubecost that dynamically looks at resources. or at tools that look at actual aws billing based on tags

Thank you, that makes sense.

**Comment by sunitanair30** [comment]
> This feels out-of-scope for the Karpenter project to be able to handle due to how dynamic the infrastructure is with Karpenter. I'm going to close this one as not planned.

Sure, thanks
