### ISSUE TITLE
Karpenter fails to recognize AWSServiceRoleForEC2Spot

### ISSUE THREAD

**Issue by altosys** [aws/karpenter-provider-aws#5436]
### Description

**Observed Behavior**:
When Karpenter starts up (on Fargate) in our EKS clusters it fails to provision EC2 spot instances with the below error message even though the AWSServiceRoleForEC2Spot already exists.

```
{"level":"ERROR","time":"2024-01-05T15:34:02.997Z","logger":"controller","message":"Reconciler error","commit":"a70b39e","controller":"nodeclaim.lifecycle","controllerGroup":"karpenter.sh","controllerKind":"NodeClaim","NodeClaim":
{"name":"default-wdftd"},"namespace":"","name":"default-wdftd","reconcileID":"f6943ed0-d66c-4be5-991b-ba01b0bd3704","error":"launching nodeclaim, creating instance, with fleet error(s), AuthFailure.ServiceLinkedRoleCreationNotPerm
itted: The provided credentials do not have permission to create the service-linked role for EC2 Spot Instances."}
```

**Expected Behavior**:
Karpenter should provision spot instances without issue.

**Context**:
We are using [terraform-aws-eks-blueprints-addons](https://github.com/aws-ia/terraform-aws-eks-blueprints-addons) to provision the Karpenter instance profile and role.

The problem we're having is similar to the Karpenter troubleshooting example for a [missing service linked role](https://karpenter.sh/docs/troubleshooting/#missing-service-linked-role), which is also found to have been the issue for [others](https://github.com/eksctl-io/eksctl/issues/6064). We however already have the service linked role for spot instances provisioned and are still getting this error message when Karpenter starts up. What's even stranger is that after about 30 minutes Karpenter stops throwing the error and then proceeds to successfully provision the requested spot instances.

We have verified that the service linked role exists both by checking in the web ui as well as with the AWS CLI:
```
❯ aws iam create-service-linked-role --aws-service-name spot.amazonaws.com

An error occurred (InvalidInput) when calling the CreateServiceLinkedRole operation: Service role name AWSServiceRoleForEC2Spot has been taken in this account, please try a different suffix.
```

**Reproduction Steps** (Please include YAML):
Run Karpenter on Fargate (probably not relevant).

We have a very barebones nodeClass configuration:
```
apiVersion: karpenter.k8s.aws/v1beta1
kind: EC2NodeClass
metadata:
  name: default
spec:
  amiFamily: AL2

  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: ${cluster_name}

  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: ${cluster_name}

  instanceProfile: ${node_instance_profile_name}
```

The workload we're trying to deploy is ArgoCD, which has only `capacity-type` configured for all nodeSelectors (below showing only one example):
```
controller:
  nodeSelector:
    karpenter.sh/capacity-type: spot
```

**Versions**:
- Chart Version: 0.33.1
- Kubernetes Version (`kubectl version`): 
```
❯ kubectl version
Client Version: v1.29.0
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.28.4-eks-8cb36c9
```

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by njtran** [comment]
Could you share a larger subset of your logs? Are you using IRSA? Are you able to spin up any other nodes? 

You should be able to check if your karpenter service account has an eks role arn annotation to see if your pod is getting the right IAM permissions.

**Comment by franklouwers** [comment]
You'd need this:

```hcl
resource "aws_iam_service_linked_role" "spot" {
  aws_service_name = "spot.amazonaws.com"
}
```

**Comment by amalic** [comment]
> You'd need this:
> 
> ```terraform
> resource "aws_iam_service_linked_role" "spot" {
>   aws_service_name = "spot.amazonaws.com"
> }
> ```

is this still required?

**Comment by palmithor** [comment]
> You'd need this:
> 
> ```terraform
> resource "aws_iam_service_linked_role" "spot" {
>   aws_service_name = "spot.amazonaws.com"
> }
> ```

Why is this needed exactly and since it is, shouldn't it be part of the example?

**Comment by AmineBenAmor98** [comment]
I think it should be part of documentation to be honest
this needs to be appended to the controller policy 

```
{
            "Sid": "AllowSpotServiceLinkedRole",
            "Effect": "Allow",
            "Resource": f"arn:aws:iam::{aws_account_id}:role/aws-service-role/spot.amazonaws.com/*",
            "Action": "iam:CreateServiceLinkedRole",
            "Condition": {"StringEquals": {"iam:AWSServiceName": "spot.amazonaws.com"}},
        }
```
