### ISSUE TITLE
Modify Node Role Naming

### ISSUE THREAD

**Issue by satellite-no** [aws/karpenter-provider-aws#5444]
### Description

This is a general question and opportunity to improve documentation.  

My node role is `{cluster_name}-KarpenterNodeRole` vs the default `KarpenterNodeRole-{cluster_name}`.  Everything seems to be working except in the karpenter controller im seening the below error. 

```text
AccessDenied: User: arn:aws:sts::ACCOUNT_ID:assumed-role/CLUSTER_NAME-KarpenterControllerRole/1704838296921190277 is not authorized to perform: iam:PassRole on resource: arn:aws:iam::ACCOUNT_ID:role/KarpenterNodeRole-CLUSTER_NAME because no identity-based policy allows the iam:PassRole action\n\tstatus code: 403, request id: 8cf2c336-d3c4-4a9b-9b9a-640487705252"}
```
Which is due to the naming addressed above.  Is there currently a way to change the set the `KarpenterNodeRole` that the Karpenter Controller is trying to assign to new instances if so I have not been able to find that in documentation anywhere.

**Comment by jonathan-innis** [comment]
> Karpenter Controller is trying to assign to new instances if so I have not been able to find that in documentation anywhere

If you have assigned a different role to your instances through the `EC2NodeClass`, you need to make sure the Karpenter controller policy has `iam:PassRole` permission on that role. This is documented (though it is in the CloudFormation permission reference here: https://karpenter.sh/docs/reference/cloudformation/#:~:text=Additionally%2C%20you%20would%20ensure%20that%20the%20Controller%20Policy%20has%20iam%3APassRole%20permission%20to%20the%20role%20attached%20to%20the%20generated%20instance%20profiles)

**Comment by satellite-no** [comment]
@jonathan-innis thanks for the response and the link to the docs!  

The AWS IAM was all correct, I just could not find the missing piece of where that role was defined and assigned.  But I see now its in the `EC2NodeClass` under spec.role which as you said is in the CloudFormation section but also under the EC2NodeClass specifications!  With that i just cant search and appears docs are just fine :D. 

Appreciate the assist.
