### ISSUE TITLE
Add support for specifiying time windows for voluntary lifecycle events

### ISSUE THREAD

**Issue by erhudy** [aws/karpenter-provider-aws#5452]
### Description

**What problem are you trying to solve?**

I would like to add a feature to Karpenter to be able to specify time windows for when Karpenter will execute non-compulsory lifecycle events on nodes (e.g., TTL expiration, consolidation). The use case for this is that I strongly favor deploying my EKS cluster nodes with Karpenter and TTLs in order to take advantage of autoscaling and node recycling to keep the AL2 AMIs up to date, but I would also like to be able to avoid disruption to nodes on certain clusters during business hours (or, if relevant to the environment in question, avoiding disruption outside a specific change window). In principle, the feature would work similarly to Argo CD sync windows, where pending changes are recognized but not applied until a sync window is reached.

As far as an implementation goes, I think that could also potentially be borrowed from Argo CD; add a field to the CRDs which contains various sync window parameters, e.g.:

```
spec:
  syncWindowConfiguration:
    defaultPolicy: deny
    windows:
      - policy: allow
        schedule: "0 15 * * *"
        duration: 2h
      - policy: allow
        schedule: "0 8 * * 6"
        duration: 9h
```

When performing voluntary events such as consolidation or TTL decommissioning, Karpenter would first check the sync window configuration and determine whether it can make the change now or not. The default configuration would be a defaultPolicy of allow with no windows specified, resulting in no changes from Karpenter's current behavior.

**How important is this feature to you?**

It is not critical but would be nice to have. I would be happy to implement the feature myself if it is deemed worthy of admission.

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by Bryce-Soghigian** [comment]
this is coming via disruption budgets https://github.com/kubernetes-sigs/karpenter/blob/main/designs/disruption-controls.md#proposed-spec

**Comment by njtran** [comment]
closing as this is solved through https://github.com/kubernetes-sigs/karpenter/pull/849
