### ISSUE TITLE
Default Drift behaviour - Karpenter (v0.33) doc needs correction

### ISSUE THREAD

**Issue by badrish-s** [aws/karpenter-provider-aws#5466]
### Description

**How can the docs be improved?**

The [How do I upgrade an EKS Cluster with Karpenter? ](https://karpenter.sh/v0.33/faq/#how-do-i-upgrade-an-eks-cluster-with-karpenter) section under FAQs of Karpenter v0.33 document states that "Karpenter Drift currently needs to be enabled using a [feature gate](https://karpenter.sh/v0.33/reference/settings/#feature-gates)". 

I dont believe above is true, the Karpenter drift is enabled by default as per [Upgrading to v0.33.0+](https://karpenter.sh/v0.33/upgrading/upgrade-guide/#upgrading-to-v0330).

Based on above, the FAQ section may need correction to avoid contradictions and confusion.

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by jonathan-innis** [comment]
Yep, good catch. @badrish-s Any chance you would be willing to fix the docs across the versions where it's incorrect, including the `preview` version?

**Comment by badrish-s** [comment]
@jonathan-innis I have submitted a PR https://github.com/aws/karpenter-provider-aws/pull/5481 with corrections. Please review and approve. Thanks!

**Comment by jonathan-innis** [comment]
Closing this one since #5481 merged
