### ISSUE TITLE
Kubernetes 1.29 Compatibility

### ISSUE THREAD

**Issue by maxemann96** [aws/karpenter-provider-aws#5528]
I didn't find any hint, whether Karpenter is compatible with Kubernetes 1.29. Any hints?

**Comment by cococowboy** [comment]
Latest release as of this writing is not - I have tried deploying it on new test clusters. But I'm also very interested in any sense of when the next release will be cut to support this. We're hoping to go live with these clusters next week, so if we can get a release that supports 1.29 it would save us having to do an upgrade later. 😄

**Comment by jonathan-innis** [comment]
> so if we can get a release that supports 1.29 it would save us having to do an upgrade later

Which version of Karpenter are you on? We're working on releasing 1.29 support in the latest version of Karpenter that should be coming out soon and has a host of new features (v0.34.0)

**Comment by gyoza** [comment]
I anxiously await this release lol.

**Comment by robmarlow** [comment]
0.34 is released with 1.29 support.

**Comment by jmdeal** [comment]
Closing since it's now supported in v0.34.
