### ISSUE TITLE
Eventbridge with spot interrupt from SQS 

### ISSUE THREAD

**Issue by haimgeo** [aws/karpenter-provider-aws#5536]
### Description

**Versions**:
-karpenter image Version:
v0.29.2
- Kubernetes Version (`kubectl version`):
eks-1.24
* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

It is not clear to me what happens when using Eventbridge with rule e.g (**EC2 spot interrupt message**) and **rule target** is **SQS** , interrupt event filtering rule is on the **account - region level** , `meaning that all spot interruption in the aws account in that region will be sent to the SQS `that karpenter is pulling from .
so the question is if i have 2 clusters , "cluster a" and "cluster b" in the same region,  what will karpenter in "cluster a" do with an SQS message he pulled from the Queue about interruption node that belongs to "cluster b", will he delete the message from the queue or rather see it doesnt "concern" his nodes and leave on Queue  it and thus "cluster b" karpenter can receive it and handle graceful termination, can you elaborate what is the flow here ?
do you suggest each karpenter controller to have a dedicated event bus and queue or all karpenter controllers can share the same bus, queue ??

**Comment by haimgeo** [comment]
This is a question not a bug ...

**Comment by ellistarn** [comment]
Each installation should have it's own queue, but you can share an event bus. We'll drop messages for instances that an individual karpenter doesn't handle: https://github.com/aws/karpenter-provider-aws/blob/235cb9a8fe6378450b4a604e34528ef72a293476/pkg/controllers/interruption/controller.go#L158

**Comment by haimgeo** [comment]
Thank you for clarifying this ...

**Comment by hitsub2** [comment]
> Each installation should have it's own queue, but you can share an event bus. We'll drop messages for instances that an individual karpenter doesn't handle:
> 
> https://github.com/aws/karpenter-provider-aws/blob/235cb9a8fe6378450b4a604e34528ef72a293476/pkg/controllers/interruption/controller.go#L158

@ellistarn May I know which version does this issue has be fixed?
