### ISSUE TITLE
Target group is not registering any targets for NLB (NGINX Ingress Controller)

### ISSUE THREAD

**Issue by bittracer** [aws/karpenter-provider-aws#5554]
### Description

**Observed Behavior**:

While deploying the NGINX Ingress Controller (https://kubernetes.github.io/ingress-nginx), the pods are successfully running. However, there's an issue with the NLB creation, as the associated target group is not registering any targets.

**Expected Behavior**:
 
The associated target group must register the target. 

**NOTE**: The karpenter is installed successfully on fargate & it provisions the node for NGINX Ingress Controller pod.

**Comment by tzneal** [comment]
Can you provide some more information? If Karpenter is launching the correct capacity and pods are scheduling/going running, the issue may be somewhere else.
