### ISSUE TITLE
Pod remains Unscheduled indefinitely

### ISSUE THREAD

**Issue by ashutoshsingh85** [aws/karpenter-provider-aws#5570]
### Description

**Observed Behavior**:
- Create a pod `pod-1` asking for resources which is not available in the cluster. Lets say available cpu on existing node is 4. Then let `pod-1` ask for 6 cpus.
- Provisioner will add a node `node-2` (having > 6 cpus) so that `pod-1` can be scheduled. 
- `node-2` transitions from Unknown -> NotReady -> Ready state.
- When `node-2` is in Unknown state, cordon it and delete it using `kubectl cordon node-2; kubectl delete node node-2 --force`
- Now `pod-1` will remain Unscheduled indefinitely.

**Expected Behavior**:
Expecting that Karpenter would add another node to the cluster.

**Reproduction Steps** (Please include YAML):

- Create a pod `pod-1` asking for resources which is not available in the cluster. Lets say available cpu on existing node is 4. Then let `pod-1` ask for 6 cpus.
- Provisioner will add a node `node-2` (having > 6 cpus) so that `pod-1` can be scheduled. 
- `node-2` transitions from Unknown -> NotReady -> Ready state.
- When `node-2` is in Unknown state, cordon it and delete it using `kubectl cordon node-2; kubectl delete node node-2 --force`
- Now `pod-1` will remain Unscheduled indefinitely.

**Versions**:
- Chart Version: 0.20
- Kubernetes Version (`kubectl version`): 1.23

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by tzneal** [comment]
What version of Karpenter is this?

**Comment by ashutoshsingh85** [comment]
0.20

**Comment by tzneal** [comment]
That's a very old version, can you upgrade to a newer version and test? v0.32.6 is the latest version that still support Provisioners and won't require you to switch to NodePools.

**Comment by tzneal** [comment]
If the node is NotReady, its failing for some reason. Can you show the output of `kubectl describe node the-node-name`?

**Comment by vstthomas** [comment]
That may be part of the issue; it's been difficult to gain access to the node in a few ways.

I can only seem to see it because of `eks-node-viewer` (output above)

`% eks-node-viewer --node-selector="karpenter.sh/nodepool" --resources memory,cpu`

Attempting the same thing with `kubectl` doesn't display anything

`% kubectl get node -l karpenter.sh/nodepool`

**Comment by vstthomas** [comment]
I was able to get something from EKS > Clusters > $CLUSER_NAME > Observability > Authenticator:

```log
time="2024-01-31T17:29:56Z" level=warning msg="access denied" arn="arn:aws-us-gov:iam::367652197469:role/reproduction-20240130191606502300000001" client="127.0.0.1:38012" error="Identity is not mapped" method=POST path=/authenticate
```

This message is repeated every 1 second.

**Comment by todd-dsm** [comment]
I've just granted Karpenter some pretty far-reaching access

```
mapRoles:
----
- groups:
  - system:masters <- Added this line
  - system:bootstrappers
  - system:nodes
  rolearn: arn:aws-us-gov:iam::367652197469:role/reproduction-20240130191606502300000001
  username: system:node:{{EC2PrivateDNSName}}
```

No effect. At this point I'm out of ideas; please advise.

**Comment by tzneal** [comment]
>  can only seem to see it because of eks-node-viewer (output above)

The node viewer shows node claims (the object Karpenter creates that exists prior to the node being created). If you are never seeing the node object, then the node is not able to join the cluster correctly.  You'll need to login to the node to look at logs to see why its failing to join. There are instructions on how to do this at https://karpenter.sh/docs/troubleshooting/#node-notready

**Comment by vstthomas** [comment]
That was yesterday for me. Since the node never fully finishes inclusion it's inaccessible, by any means. I tried a number of things:
* everything above
* logging in through the EC2 console
* aws ssm start-session --target $INSTANCE_ID

Nothing worked. 

Today, I'm going to 
1. create a custom AMI: 
   * `amazon/amazon-eks-node` + my `ssh-key`. Then 
2. configure Karpenter to [use the custom AMI](https://karpenter.sh/v0.31/concepts/node-templates/#specamiselector) and 
3. login to see what's up. 

If you have something that descri

**Comment by tzneal** [comment]
SSM should work, what happens when you try to SSM?  Karpenter will terminate the instances if they don't join the cluster which is part of the behavior you are seeing.

**Comment by vstthomas** [comment]
K8S means you shouldn't need to worry about nodes - so my SSM is weak/non-existent. This is what I see after setting the instance id

```sh
% aws ssm start-session --target $INSTANCE_ID
...TargetNotConnected when calling the StartSession operation.

I've attached the `arn:${local.part}:iam::aws:policy/service-role/AmazonEC2RoleforSSM` to the node, verified the agent is running, opened up ports; seems like I'm missing some minute detail. Given up on it for now.

---

However, I've gained access the old fashioned way and have full control of the shell. 

_**What are we looking for in the logs?**_

**Comment by tzneal** [comment]
You'll want to look at the kubelet logs (`sudo journalctl -u kubelet`) and see if it is reporting any errors.

**Comment by tzneal** [comment]
Glad you have it working!
