### ISSUE TITLE
Refresh instance types for every release

### ISSUE THREAD

**Issue by chlunde** [aws/karpenter-provider-aws#5580]
### Description

**What problem are you trying to solve?**

Use new instance types after release by the EC2 team

**How important is this feature to you?**

I think it's a time drain for users and support to debug issues when new instance types are available, but not working, so I think this is important.

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by chlunde** [comment]
I ran hack/codegen.sh on the 0.33.x branch with the following result: https://github.com/aws/karpenter-provider-aws/compare/release-v0.33.x...chlunde:karpenter-provider-aws:codegen-0.33.x

The instance type I'm currently looking for is r7i and I see it's included. I can create a PR if you would like and intend to do another 0.33-release before 0.34, but I'm also hoping you can do this as a normal activity whenever making a new release or monthly.

**Comment by jonathan-innis** [comment]
> but I'm also hoping you can do this as a normal activity whenever making a new release or monthly

This should have been part of our automation but there was a break in it that was missed. We should have the v0.34.0 version here pretty shortly. If that version was out soon and had support for this instance type, would you still have a need for a back-port?

**Comment by chlunde** [comment]
For us, we try to run the latest version whenever possible, so we don't need a backport. Nice improvement on 0.33.2 with CPU reduced by 50% btw :)
