### ISSUE TITLE
support eks access entry

### ISSUE THREAD

**Issue by pdeva** [aws/karpenter-provider-aws#5581]
### Description

All our new clusters use the new [EKS access entry](https://aws.amazon.com/blogs/containers/a-deep-dive-into-simplified-amazon-eks-access-management-controls/) auth method instead of the old (and cumbersome)  aws-auth configmap stuff.  However it seems Karpenter doesnt support access entry yet, or atleast i cant find any documentation for it.

**Comment by jonathan-innis** [comment]
This looks like a duplicate of https://github.com/aws/karpenter-provider-aws/issues/5369
