### ISSUE TITLE
Downgrade from v0.32.6 to v0.31.2 is stuck

### ISSUE THREAD

**Issue by apeduru-patreon** [aws/karpenter-provider-aws#5613]
### Description

**Observed Behavior**:
This issue is related to https://github.com/aws/karpenter-provider-aws/issues/5578 where I'm finding it difficult to reproduce the upgrade bug because the downgrade to v0.31.2 gets stuck when trying to terminate the NodeClaims with this error in the logs. 
```
karpenter-7d6fdd79c8-w5j65 controller {"level":"INFO","time":"2024-02-06T19:18:50.231Z","logger":"controller","message":"k8s.io/client-go@v0.26.6/tools/cache/reflector.go:169: failed to list *v1beta1.NodePool: nodepools.karpenter.sh is forbidden: User \"system:serviceaccount:karpenter:karpenter\" cannot list resource \"nodepools\" in API group \"karpenter.sh\" at the cluster scope\n","commit":"709030d"}
karpenter-7d6fdd79c8-w5j65 controller {"level":"ERROR","time":"2024-02-06T19:18:50.231Z","logger":"controller","message":"k8s.io/client-go@v0.26.6/tools/cache/reflector.go:169: Failed to watch *v1beta1.NodePool: failed to list *v1beta1.NodePool: nodepools.karpenter.sh is forbidden: User \"system:serviceaccount:karpenter:karpenter\" cannot list resource \"nodepools\" in API group \"karpenter.sh\" at the cluster scope\n","commit":"709030d"}
```

This suggests that the permissions are insufficient. We're using ArgoCD to sync changes so likely what is happening is that the ClusterRoles are changing to the previous version before the nodes are done draining. 

Output of `kubectl get nodes` 
```
ip-10-16-17-64.us-west-2.compute.internal    Ready,SchedulingDisabled   <none>   27m    v1.24.17-eks-5e0fdde
```

Here are the Events for that node 
```
Events:
  Type     Reason                   Age                From                     Message
  ----     ------                   ----               ----                     -------
  Normal   Starting                 28m                kube-proxy
  Warning  InvalidDiskCapacity      28m                kubelet                  invalid capacity 0 on image filesystem
  Normal   NodeHasSufficientMemory  28m (x2 over 28m)  kubelet                  Node ip-10-16-17-64.us-west-2.compute.internal status is now: NodeHasSufficientMemory
  Normal   NodeHasNoDiskPressure    28m (x2 over 28m)  kubelet                  Node ip-10-16-17-64.us-west-2.compute.internal status is now: NodeHasNoDiskPressure
  Normal   NodeHasSufficientPID     28m (x2 over 28m)  kubelet                  Node ip-10-16-17-64.us-west-2.compute.internal status is now: NodeHasSufficientPID
  Normal   NodeAllocatableEnforced  28m                kubelet                  Updated Node Allocatable limit across pods
  Normal   Starting                 28m                kubelet                  Starting kubelet.
  Normal   ControllerVersionNotice  28m                vpc-resource-controller  The node is managed by VPC resource controller version v1.4.4
  Normal   NodeReady                28m                kubelet                  Node ip-10-16-17-64.us-west-2.compute.internal status is now: NodeReady
  Normal   NodeTrunkInitiated       28m                vpc-resource-controller  The node has trunk interface initialized successfully
  Normal   NodeNotSchedulable       23m                kubelet                  Node ip-10-16-17-64.us-west-2.compute.internal status is now: NodeNotSchedulable
```

**Expected Behavior**:

The upgrade docs state that only v0.31.2 or v0.31.3 are the only versions that can be rolled back from v0.32.0
https://karpenter.sh/preview/upgrading/upgrade-guide/#upgrading-to-v0320

**Reproduction Steps** (Please include YAML):

Downgrade the helm chart from v0.32.6 to v0.31.2. 

Please find the YAML for both versions here: https://gist.github.com/apeduru-patreon/bdc4f399cdabdffa59f7322bc9c4d790

**Versions**:
- Chart Version: v0.32.6 -> v0.31.2
- Kubernetes Version (`kubectl version`):
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.6", GitCommit:"ad3338546da947756e8a88aa6822e9c11e7eac22", GitTreeState:"clean", BuildDate:"2022-04-14T08:49:13Z", GoVersion:"go1.17.9", Compiler:"gc", Platform:"darwin/arm64"}
Server Version: version.Info{Major:"1", Minor:"24+", GitVersion:"v1.24.17-eks-5e0fdde", GitCommit:"221f136737816ce068aa975f082cd0bf81c7ad5f", GitTreeState:"clean", BuildDate:"2024-01-02T20:35:57Z", GoVersion:"go1.20.10", Compiler:"gc", Platform:"linux/amd64"}
```

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by apeduru-patreon** [comment]
I've again tested this on v0.32.0 and I'm seeing the same error message regarding permission errors show up in the logs

**Comment by jonathan-innis** [comment]
> I've again tested this on v0.32.0 and I'm seeing the same error message regarding permission errors show up in the logs

Is this the full log output from downgrading the nodes (you get that log message at startup) or you get that message after Karpenter runs for a bit on v0.31.x?

**Comment by apeduru-patreon** [comment]
I see that log message after nodes have initiated a drain whilst syncing a Chart. Presumably Karpenter is running on v0.31.2 at this point.

**Comment by jonathan-innis** [comment]
It definitely looks like there may be a bug with Karpenter attempting to grab a NodePool in v0.31.2 when there was a previously-provisioned NodeClaim under a NodePool. As a workaround for now, if you add permission to the ClusterRole for Karpenter to be able to get NodePools, the rollback should succeed.

**Comment by jonathan-innis** [comment]
> I'll note also that I'm seeing this for the EC2NodeClass API as well. I think this might be error logging for all v1beta1 APIs

Looking at where you are seeing this error with the informers, it looks like this may be occurring with the newer version of Karpenter (v0.32.0). Are you sure that your permissions were maintained when going between these two versions? From the looks of it, it seems like you may have upgraded back to v0.32.0 and the permission for the ClusterRole on NodePool and EC2NodeClass were dropped.

**Comment by jonathan-innis** [comment]
Hey @apeduru-patreon, we have an updated version of the chart that fixes the issue with the rollback. Are you willing to try `KARPENTER_VERSION=v0-bea8ff219b209db8f9a9344533dd00bb72771bbf` and confirm that it fixes your issue during rollback?

You can find the instructions for installing this version here: https://karpenter.sh/docs/upgrading/compatibility/#snapshot-releases

**Comment by engedaam** [comment]
Closing as v0.31.4 is released with the fix.
