### ISSUE TITLE
NodeClasses amiFamily

### ISSUE THREAD

**Issue by elitistphoenix** [aws/karpenter-provider-aws#5630]
I know this will seem fairly brief, but is the AL2 instance type just the general AL2 ami or the EKS Optimized one?

https://karpenter.sh/v0.34/concepts/nodeclasses/#specamifamily
https://docs.aws.amazon.com/eks/latest/userguide/eks-optimized-ami.html

**Comment by engedaam** [comment]
It is the EKS Optimized AMI

**Comment by elitistphoenix** [comment]
Thanks. Might be worth saying it explicitly in the doco though.
