### ISSUE TITLE
Karpenter can not connect to EKS v1.29

### ISSUE THREAD

**Issue by GaborVarga** [aws/karpenter-provider-aws#5652]
We migrated from Cluster Autoscaler to Karpenter, followed the migration guide (https://karpenter.sh/docs/getting-started/migrating-from-cas/), however, we can see this in the Karpenter log: 

"logger":"controller","message":"unable to detect the cluster endpoint, failed to resolve cluster endpoint, RequestError: send request failed\ncaused by: Get \"https://eks.us-east-1.amazonaws.com/clusters/EKS-name\": dial tcp: lookup eks.us-east-1.amazonaws.com on 10.100.0.10:53: no such host"

Any idea what could be wrong? When Karpenter was deployed, we used private endpoint, since then we switched to public, still no resolution.

**Comment by jonathan-innis** [comment]
Does this error occur consistently? What exact setup are you using (what capacity is Karpenter running on, is this a private cluster vs. a public cluster, etc.)?

**Comment by GaborVarga** [comment]
karpenter version: 0.33.2
EKS version: 1.29
AMI version: 1.29.0-20240117
EKS has public server endpoint now.
We are using Fargate for all the workload in the default namespace.  

I am before this step in the migration guide: Remove CAS
So cluster autoscaler is still there but at this point Karpenter should run as well, right? 

The error is there continuously, Karpenter pods are in CrashLoopBackOff, logs are above.

**Comment by GaborVarga** [comment]
After some digging here are more details: it turned out that this is some network problem for Karpenter, described here: https://serverfault.com/questions/1153247/eks-coredns-resolve-eks-us-east-1-amazonaws-com

Any hint what is misconfigured?

**Comment by jonathan-innis** [comment]
Do you know the DNS policy that you are using with the Karpenter pod?

**Comment by GaborVarga** [comment]
Where can I check the DNS policy per pod? I guess it should be the same as for any other pods running in the cluster. Other pods are running smoothly, only Karpenter is failing with this. Very strange.

**Comment by GaborVarga** [comment]
spec:
      serviceAccountName: karpenter
      priorityClassName: "system-cluster-critical"
      dnsPolicy: Default

**Comment by jonathan-innis** [comment]
I'm asking a member of the Fargate team to take a look at this since this seems like a networking issue with Fargate and I'm less familiar with how the details of that work.

**Comment by jonathan-innis** [comment]
Can you post the entire deployment for Karpenter that is applied to your cluster? I'm also surprised that `dnsPolicy: Default` is being used here. The only reason I'm calling that out is that the original log that you shared shows the Karpenter pod trying to do DNS resolution over at `10.100.0.10:53` which is the entry for core-dns resolution on an EKS kubernetes cluster

**Comment by jonathan-innis** [comment]
It might also be useful to see if you can get the output of running this step in your Karpenter pod to see how the DNS resolution is configured: https://repost.aws/knowledge-center/eks-dns-failure#:~:text=Verify%20that%20the%20cluster%20IP%20address%20of%20the%20kube%2Ddns%20service%20is%20in%20your%20pod%27s%20/etc/resolv.conf%20file.%20Run%20the%20following%20command%20in%20the%20shell%20that%27s%20inside%20the%20pod

**Comment by jonathan-innis** [comment]
Also also, it would be useful to see the log output from the `core-dns` pods from their startup, throughout the time that Karpenter is running.

**Comment by GaborVarga** [comment]
Thanks a lot for the ideas and time you spent on this, but we decided to deploy a new cluster and remove this old one. It worked, Karpenter now runs smoothly on the new EKS, the interesting thing is that we did not change our deployment process. You can close / delete this issue.

**Comment by jonathan-innis** [comment]
Sounds good. Thanks. Still unclear to me what happened here. Closing it out. One last question: Is the new cluster that y'all spun-up also 1.29?

**Comment by GaborVarga** [comment]
Yes, 1.29.
