### ISSUE TITLE
Nodepool should have a minimum-size of nodes for applications requiring HA.

### ISSUE THREAD

**Issue by jmbravo** [aws/karpenter-provider-aws#5663]
### Description

**What problem are you trying to solve?**

We want our nginx controller to always be on two different nodes. We can't afford packet loss if the current node goes down while the provisioner is setting up another node.

**How important is this feature to you?**

Critical

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by tzneal** [comment]
If you put an inter-pod anti-affinity constraint by hostname on the pod spec, Karpenter will launch one node per pod and the scheduler will only ever schedule one pod per node. See https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#scheduling-a-group-of-pods-with-inter-pod-affinity-to-themselves for details.

**Comment by jonathan-innis** [comment]
Going to close this out since this is a known way to spread pods across nodes using kube-scheduler.

**Comment by jonathan-innis** [comment]
Going to close this out since this is a known way to spread pods across nodes using kube-scheduler.
