### ISSUE TITLE
Need to check on how tags will be updated on existent node spun up by Karpenter 

### ISSUE THREAD

**Issue by akunduru9** [aws/karpenter-provider-aws#5668]
Hi Team,

We already have some instances running that were created by the Karpenter node pool, but they are missing some tags that we need. How does it work when we add tags? Will it also update existing instances or will it only apply to newly created ones after adding the tag? Below are some of the tags I'm adding to the node pool:

    tags:
    app.kubernetes.io/created-by: cloud
    customer-id: test
    division: test

**Comment by akunduru9** [comment]
we are  trying to set it on k8s nodes.and yes I am adding it to EC2Nodeclass how do we enable drift.

**Comment by jmdeal** [comment]
Again to clarify, there is a difference between tags and labels. Labels, which you would set on the NodePool, are applied to k8s nodes. Tags, which are set on the EC2NodeClass, are applied to the underlying instances and other EC2 resources (i.e. tags you could view in the AWS console). Updating either would trigger drift but they are two completely concepts.

**Comment by akunduru9** [comment]
got it thanks .

**Comment by akunduru9** [comment]
@jmdeal  Thanks !
