### ISSUE TITLE
QUESTION: Does Karpenter need pods to define limits on cpu and memory

### ISSUE THREAD

**Issue by travis-jorge** [aws/karpenter-provider-aws#5669]
I have a cluster where many workloads do not have limits set i'm working on having them set by the engineering teams but until them i'm curious how not having them set affects karpenters ability to do its job.

**Comment by jmdeal** [comment]
Karpenter schedules based on requests, not limits, so no they don't need to be set. There are some caveats here, I think the EKS best practice guidelines give a good example of why you might want to set requests == limits, in particular when using consolidation: https://aws.github.io/aws-eks-best-practices/karpenter/#configure-requestslimits-for-all-non-cpu-resources-when-using-consolidation. Basically you should just be aware of the risks of burstable pods in a tightly packed cluster.

**Comment by travis-jorge** [comment]
Thank you! @jmdeal
