### ISSUE TITLE
Getting Started with Karpenter

### ISSUE THREAD

**Issue by santosh-at-github** [aws/karpenter-provider-aws#5677]
# Description
The Karpenter pods fails to come up when the helm command provided in the documentation used for deploying Karpenter pods on Fargate.

**Command used**
```
helm upgrade --install karpenter oci://public.ecr.aws/karpenter/karpenter --version "${KARPENTER_VERSION}" --namespace "${KARPENTER_NAMESPACE}" --create-namespace \
  --set "settings.clusterName=${CLUSTER_NAME}" \
  --set "settings.interruptionQueue=${CLUSTER_NAME}" \
  --set controller.resources.requests.cpu=1 \
  --set controller.resources.requests.memory=1Gi \
  --set controller.resources.limits.cpu=1 \
  --set controller.resources.limits.memory=1Gi \
  --wait
```

**The error**
```
$ k logs -n kube-system karpenter-7b57c88954-k6fzn
panic: failed to get region from metadata server: EC2MetadataRequestError: failed to get EC2 instance identity document
caused by: RequestError: send request failed
caused by: Get "http://169.254.169.254/latest/dynamic/instance-identity/document": context deadline exceeded (Client.Timeout exceeded while awaiting headers)

goroutine 1 [running]:
github.com/samber/lo.must({0x27c69c0, 0xc000615680}, {0xc00099fc48, 0x1, 0x1})
	github.com/samber/lo@v1.39.0/errors.go:51 +0x1c5
github.com/samber/lo.Must[...](...)
	github.com/samber/lo@v1.39.0/errors.go:65
github.com/aws/karpenter-provider-aws/pkg/operator.NewOperator({0x3156b18, 0xc0009f6a20}, 0xc0001014a0)
	github.com/aws/karpenter-provider-aws/pkg/operator/operator.go:112 +0x314
main.main()
	github.com/aws/karpenter-provider-aws/cmd/controller/main.go:33 +0x2a
```

**Expected Behavior**
Karpenter pod should come up on Fargate and pass it's readiness as well as liveness probe.

**Fix**
Use following helm command for installing karpenter Fargate profile:
```
helm upgrade --install karpenter oci://public.ecr.aws/karpenter/karpenter --version "${KARPENTER_VERSION}" --namespace "${KARPENTER_NAMESPACE}"   --create-namespace \
  --set "settings.clusterName=${CLUSTER_NAME}" \
  --set "settings.interruptionQueue=${CLUSTER_NAME}" \
  --set controller.resources.requests.cpu=1 \
  --set controller.resources.requests.memory=1Gi \
  --set controller.resources.limits.cpu=1 \
  --set controller.resources.limits.memory=1Gi \
  --set serviceAccount.annotations."eks\.amazonaws\.com/role-arn"="arn:${AWS_PARTITION}:iam::${AWS_ACCOUNT_ID}:role/${CLUSTER_NAME}-karpenter" \
  --wait
```

**Comment by alekseikurepin** [comment]
@SantoshK07bec kudos to you, my upgrade fix it:
`helm upgrade --install karpenter \
  oci://public.ecr.aws/karpenter/karpenter \
  --version v0.33.6 \
  --namespace karpenter \
  --set settings.clusterName=${CLUSTER_NAME} \
  --set settings.interruptionQueue=${my-karpenter-name}-queue \
  --set aws.defaultRegion=eu-north-1 --set "serviceAccount.annotations.eks\.amazonaws\.com/role-arn=arn:aws:iam::${AWS_ACCOUNT_ID}:role/${my-karpenter-name}-karpenter-controller"
Pulled: public.ecr.aws/karpenter/karpenter:v0.33.6
Digest: sha256:e8013beca0076b0a5804cb00cfc8feed273929f81f5cc5de90b56f8131d41d3b
Release "karpenter" has been upgraded. Happy Helming!
NAME: karpenter
LAST DEPLOYED: Fri Jan 16 11:48:30 2026
NAMESPACE: karpenter
STATUS: deployed
REVISION: 26
DESCRIPTION: Upgrade complete
TEST SUITE: None`
