### ISSUE TITLE
[Cross Account AMI] Instances launched by Karpenter immediately terminate, while using AMI shared from cross account and with encrypted KMS key

### ISSUE THREAD

**Issue by paramanandd** [aws/karpenter-provider-aws#5690]
### Description

**Observed Behaviour**:
- AMI created (Account B) Karpenter and EKS Cluster in (Account A)
      Instance terminates immediately after creation before initialisation steps.
- AMI created (Account A) Karpenter and EKS Cluster in (Account A)
     Instance registers with cluster and karpenter works as expected.

here 
**Account A** is consumer account where eks cluster and karpenter is running 
**Account B** is central account where AMI is build and encrypted using KMS and later shared to Account A
 

- Also have referred the docs for troubleshooting, added the suggested permissions but does not help for cross account AMI specific feature.
-  Below are the references followed and implemented but did not helped

1. https://karpenter.sh/docs/troubleshooting/#node-terminates-before-ready-on-failed-encrypted-ebs-volume
2. https://github.com/aws/karpenter-provider-aws/issues/1407

**Expected Behavior**:
EC2 Instances launched by Karpenter successfully start

**Reproduction Steps** (Please include YAML):
- AMI created in account B, encrypted using the KMS key from account B
- AMI is shared with Account A.
- The karpenter is installed in Account A, in EKS cluster.
- While using the AMI from Account B, instance never comes to ready state and terminates before initialisation.

**Versions**:
- Chart Version: v0.34.0
- Kubernetes Version (`kubectl version`): 1.27

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

@bwagner5 any leads will be helpful

**Comment by jonathan-innis** [comment]
Have you taken a look at https://karpenter.sh/docs/troubleshooting/#node-terminates-before-ready-on-failed-encrypted-ebs-volume to see if that's what you might be running into here?

**Comment by paramanandd** [comment]
It is resolved now, seems like issue with the permissions provided to the karpenter Controller Role (from Account A). It needs explicit permissions to KMS key from Account B.
Even though the KMS resource policy has the permissions to Account A, we need to provide the permissions in Role assigned to the karpenter pod as well.
