### ISSUE TITLE
ec2 CreateFleet call fails in some regions.

### ISSUE THREAD

**Issue by amdonov** [aws/karpenter-provider-aws#5700]
### Description

**What problem are you trying to solve?**

I'd like the option to not set metadataOptions in launch templates created by Karpenter. Currently, all options are set to default values if they're deleted from the EC2NodeClass. In my case, the launch templates are successfully created, but calls to create fleet fail with an error that HTTPProtocol settings are not supported in region.

I'd like the ability to not set/remove metadata options from Karpenter created launch templates.

**How important is this feature to you?**

This is blocking creation of nodes in some regions.

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by amdonov** [comment]
I was able to work around the problem by removing the httpProtocolIPv6 field from metadataOptions within the EC2NodeClass CRD.

**Comment by jmdeal** [comment]
What regions were you running into this in? Also, to clarify, you got around this by editing the CRD (removing the field) and reapplying the CRD?
