### ISSUE TITLE
Use an outgoing proxy

### ISSUE THREAD

**Issue by gmembre-zenika** [aws/karpenter-provider-aws#5710]
### Description

**What problem are you trying to solve?**

My current VPC is located in eu-west-3 and it doesn't have a direct internet access, it uses `--isolated-vpc`. All applications in this cluster must use a proxy for outgoing connections.

The pricing API is located in eu-central-1 and thus, we cannot create a VPC endpoint to this API in the eu-west-3. Moreover, we don't want to setup a new region for a new VPC just for adding this VPC Endpoint.

I don't think that #5704 will solve the problem when the cluster is located in another region, Karpenter won't be able to get the price.
To solve this problem, Karpenter should be able to use the public access to this API through an internet connection. For us, it must go through a proxy. 
Being able to set some env variable like `https_proxy` would be super !

**How important is this feature to you?**

Currently, we cannot use spot instances as the price cannot be fetched.

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by jonathan-innis** [comment]
> I don't think that https://github.com/aws/karpenter-provider-aws/pull/5704 will solve the problem when the cluster is located in another region, Karpenter won't be able to get the price

To be fair, I don't think that #5704 is trying to solve this problem for the on-demand pricing endpoint, it's only trying to solve this for the spot pricing. Spot pricing is from EC2, which has a VPC endpoint in every region.

> Being able to set some env variable like https_proxy would be super

You should be able to set this value through the deployment environment variables on a helm install with `controller.env`. Have you tried setting these and the container is still not proxying traffic appropriately?

**Comment by gmembre-zenika** [comment]
> You should be able to set this value through the deployment environment variables on a helm install with `controller.env`. Have you tried setting these and the container is still not proxying traffic appropriately?

I didn't not try as I didn't no see it in the documentation.
But, I tried this morning by setting `controller.env` and removing `isolatedVPC`: it works great, Karpenter requests go through the proxy.

This is perfect, thanks !
