### ISSUE TITLE
 Carpenter's installation method is too complicated and not explained properly.

### ISSUE THREAD

**Issue by ssunghwan** [aws/karpenter-provider-aws#5726]
https://shadow-isthmus-7e2.notion.site/Karpenter-aws-cli-20f5edca36284723bb3cd085d5de19cc?pvs=4

제가 karpenter에 대해 배포하는 과정을 정리한 내용입니다. 한번 읽어봐주시고 어떤게 문제가 있는지, 추가할 내용이라던가 수정사항이 있으시면 답변주세요.

현재 파드상태는 아래와 같습니다.
root@ip-10-100-254-142:~/karpenter-cli# kubectl get pods -n karpenter
NAMESPACE     NAME                         READY   STATUS             RESTARTS        AGE
karpenter     karpenter-8546b4689b-pblkh   0/1     CrashLoopBackOff   7 (4m30s ago)   15m
karpenter     karpenter-8546b4689b-sqt8w   0/1     CrashLoopBackOff   7 (4m9s ago)    15m

현재 파드에 대한 에러 로그는 아래와 같습니다.
root@ip-10-100-254-142:~/karpenter-cli# kubectl logs -n karpenter karpenter-8546b4689b-pblkh 
{"level":"FATAL","time":"2024-02-24T06:47:45.483Z","logger":"controller","message":"Checking EC2 API connectivity, WebIdentityErr: failed to retrieve credentials\ncaused by: InvalidIdentityToken: No OpenIDConnect provider found in your account for https://oidc.eks.ap-northeast-2.amazonaws.com/id/4F92A25FA10F98F239811FC0A7386160\n\tstatus code: 400, request id: e47bad4f-ad62-4687-9421-e880fb080465","commit":"596ea97"}

**Comment by jmdeal** [comment]
It looks like you never create an IAM OIDC provider for your cluster, Karpenter's official documentation includes it as part of the [cluster creation](https://karpenter.sh/docs/getting-started/getting-started-with-karpenter/#3-create-a-cluster) or you can create it manually via this command:
```
eksctl utils associate-iam-oidc-provider --cluster $cluster_name --approve
```

**Comment by ssunghwan** [comment]
문제는 해결했지만 여전히 고민이 있다.
karpenter.yaml을 배포할 때 serviceaccount에 대한 내용을 빼고 배포하니까 karpenter의 pods들이
running 상태였다.

AS-IS
  helm template karpenter oci://public.ecr.aws/karpenter/karpenter
--version ${KARPENTER_VERSION} --namespace karpenter \ --set
aws.defaultInstanceProfile=KarpenterInstanceProfile \ --set
"settings.clusterName=${CLUSTER_NAME}" \ --set
"settings.interruptionQueue=${CLUSTER_NAME}" \ --set
clusterEndpoint="${CLUSTER_ENDPOINT}" \ --set clusterName=${CLUSTER_NAME} \
--set
serviceAccount.annotations."eks\.amazonaws\.com/role-arn"="arn:aws:iam::${AWS_ACCOUNT_ID}:role/KarpenterControllerRole"
\ --version ${KARPENTER_VERSION} > karpenter.yaml

TO-BE
  helm template --namespace karpenter --create-namespace \
  karpenter oci://public.ecr.aws/karpenter/karpenter \
  --version ${KARPENTER_VERSION} \
  --set settings.aws.clusterName=${CLUSTER_NAME} \
  --set settings.aws.clusterEndpoint=${CLUSTER_ENDPOINT} \
  --set defaultProvisioner.create=false \
  --set
settings.aws.defaultInstanceProfile=KarpenterNodeInstanceProfile-${CLUSTER_NAME}
\
  --set settings.aws.interruptionQueueName=${CLUSTER_NAME} \
  > karpenter-setup.yaml

왜 serviceaccount에 대한 내용을 빼면 파드상태가 정상적인지, 이유를 찾지 못하고 있습니다.
빠른 회신 부탁드리겠습니다

2024년 2월 26일 (월) 오전 10:38, 허성환 ***@***.***>님이 작성:

**Comment by ssunghwan** [comment]
빠른 회신 부탁드립니다.

**Comment by jmdeal** [comment]
Closing in favor of https://github.com/aws/karpenter-provider-aws/issues/5732. Could you please keep this in a single issue from here on out, it's harder to track if you continue to open new issues.
