### ISSUE TITLE
Getting Started Guide is missing script includes

### ISSUE THREAD

**Issue by jgarcia-nops** [aws/karpenter-provider-aws#5734]
### Description

**Observed Behavior**:
Script includes in Getting Started documentation don't load 
**Expected Behavior**:
All elements would load
**Reproduction Steps** (Please include YAML):
Visit the [Getting Started Guide](https://karpenter.sh/docs/getting-started/getting-started-with-karpenter/)
**Versions**:
- Chart Version: n/a
- Kubernetes Version (`kubectl version`): n/a

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by ftwabhi** [comment]
Same for me.

**Comment by ftwabhi** [comment]
<img width="1087" alt="image" src="https://github.com/aws/karpenter-provider-aws/assets/140103918/c737de49-7d6e-4da4-8bda-c16aa4ac1965">

It looks like this.

**Comment by jonathan-innis** [comment]
Something broke on a package bump to `hugo-extended`. I'm reverting the change in the PR that I linked so that we get back to rendering the content. We still need to track-down what exactly broke so that we are free to upgrade to the newer version.
