### ISSUE TITLE
karpenter 0.34.0 failed with AccessDeniedException message

### ISSUE THREAD

**Issue by fortressll87** [aws/karpenter-provider-aws#5737]
### Description

**Observed Behavior**:
I have questions. 

after deploy karpenter. pod got this error message. 

{"level":"FATAL","time":"2024-02-27T07:38:13.023Z","logger":"controller","message":"unable to detect the cluster endpoint, failed to resolve cluster endpoint, AccessDeniedException: User: arn:aws:sts::xxx:assumed-role/KarpenterControllerRole-dev-eks/1709019492890466777 is not authorized to perform: eks:DescribeCluster on resource: arn:aws:eks:ap-northeast-2:xxx:cluster/dev-eks","commit":"17d6c05"}

**Expected Behavior**:

**Reproduction Steps** (Please include YAML):

**Versions**:
- Chart Version:
- Kubernetes Version (`kubectl version`):
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.9", GitCommit:"a1a87a0a2bcd605820920c6b0e618a8ab7d117d4", GitTreeState:"clean", BuildDate:"2023-04-12T12:16:51Z", GoVersion:"go1.19.8", Compiler:"gc", Platform:"darwin/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"27+", GitVersion:"v1.27.9-eks-5e0fdde", GitCommit:"3f8ed3d5017d988600f597734a4851930eda35a6", GitTreeState:"clean", BuildDate:"2024-01-02T20:34:38Z", GoVersion:"go1.20.12", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.25) and server (1.27) exceeds the supported minor version skew of +/-1
* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by jigisha620** [comment]
Can you provide more details about the Karpenter chart version that you are using? As per the error that you have received, clearly the `KarpenterControllerRole` that was created does not have the `eks:DescribeCluster` permission. More details can be found in the [documentation](https://karpenter.sh/v0.34/reference/cloudformation/#allowapiserverendpointdiscovery).
