### ISSUE TITLE
Clarification on consolidation limits prior to v.0.34.x

### ISSUE THREAD

**Issue by andrewhibbert** [aws/karpenter-provider-aws#5744]
### Description

**How can the docs be improved?**

https://karpenter.sh/docs/upgrading/upgrade-guide/#upgrading-to-v0341. Looking at the notes here I'm a bit confused:

> Empty Expiration / Empty Drift / Empty Consolidation: infinite parallelism

Is this just when a node is completely empty or underutilized?

> Non-Empty Expiration / Non-Empty Drift / Single-Node Consolidation: one node at a time

Not sure what/when single-node consolidation happens?

> Multi-Node Consolidation: max 100 nodes

Not sure when multi-node consolidation happens?

**Comment by njtran** [comment]
A node is empty if it has no [reschedulable pods](https://github.com/kubernetes-sigs/karpenter/blob/main/pkg/utils/pod/scheduling.go#L43)

Consolidation is evaluated in three stages as part of the [disruption controller](https://karpenter.sh/docs/concepts/disruption/#disruption-controller). 

More on Consolidation [here](https://karpenter.sh/docs/concepts/disruption/#consolidation) 
 
More on all automated methods [here](https://karpenter.sh/docs/concepts/disruption/#automated-methods)

**Comment by andrewhibbert** [comment]
Shouldn't the docs be in line with https://karpenter.sh/docs/concepts/disruption/#consolidation then? To me this makes more sense:

Empty Node Consolidation - infinite parallelism
Multi Node Consolidation (non empty node consolidation) - max 100 nodes
Single Node Consolidation (non empty node consolidation)- One node at a time

**Comment by andrewhibbert** [comment]
The misleading bit really is that you don't have "non-empty consolidation" which I think is the most common one

**Comment by jonathan-innis** [comment]
> The misleading bit really is that you don't have "non-empty consolidation" which I think is the most common one

I see, so you're thinking that we should have consistency between the different lines in our upgrade documentation? If you think there are ways that we should improve our upgrade docs, we'd definitely accept a PR that makes things clearer here.

**Comment by njtran** [comment]
Agreed^ feel free to cut a PR to logically separate it as you see fit. I'll close this in favor of your PR
