### ISSUE TITLE
Hello, version v0.33 and v0.34 and v0.35 is compatible with eks 1.29.

### ISSUE THREAD

**Issue by pv-brunoalves** [aws/karpenter-provider-aws#5784]
### Description

Hello, version 0.33 and 0.34 and 0.35 is compatible with eks 1.29. I wonder why in the AWS documentation it states that support for EKS Pod Identity is up to 1.28 ?
 
 https://docs.aws.amazon.com/pt_br/eks/latest/userguide/pod-identities.html
 
 
 
* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by pv-brunoalves** [comment]
Firstly, thank you very much for the answer.

I asked this question because I ran the step-by-step documentation v0.34 and v0.35 of karpenter on eks um 1.29 with Amazon EKS Pod Identity Agent v1.2.0-eksbuild.1 because from version v0.34 and v0.35 the IAM access method changed to podIdentityAssociations


during the installation of helm it gives the error

Checking ec2 api connectivity " NoProviders no valid according to print know what is the cause of the error I am using eks 1.29 and karpenter v0.34 or v0.35 and Amazon EKS Pod Identity Agent v1.2.0-eksbuild.1
![Captura de tela 2024-03-05 151845](https://github.com/aws/karpenter-provider-aws/assets/109089424/ddb68046-e716-4505-a494-c9c2a4c40a54)
![Captura de tela 2024-03-05 151831](https://github.com/aws/karpenter-provider-aws/assets/109089424/26fc5d06-85e4-44f3-8eca-11256fdbf451)

**Comment by jmdeal** [comment]
What does the trust relationship look like for your Karpenter controller IAM role? It should look something like this:
```json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Principal": {
                "Service": "pods.eks.amazonaws.com"
            },
            "Action": [
                "sts:AssumeRole",
                "sts:TagSession"
            ]
        }
    ]
}
```
It's unclear to me from the logs why pod identity is unable to fetch the credentials, this seems like a reasonable first thing to check.

**Comment by pv-brunoalves** [comment]
Yes, I'm using the policy/KarpenterControllerPolicy-${CLUSTER_NAME} with Trust Relationships, using EKS 1.29 with Karpenter v0.35. I'll send a screenshot and the cluster creation file via eksctl.

Basically, I created the variables and executed aws cloudformation deploy with version v0.35.

And when installing Karpenter v0.35 on EKS 1.29 with eks-pod-identity-agent, the error occurs:

{"level":"FATAL","time":"2024-03-06T01:02:25.073Z","logger":"controller","message":"Checking EC2 API connectivity, NoCredentialProviders: no valid providers in chain. Deprecated.\n\tFor verbose messaging see aws.Config.CredentialsChainVerboseErrors","commit":"2c8f2a5"} ││ stream closed
![Captura de tela 2024-03-05 215827](https://github.com/aws/karpenter-provider-aws/assets/109089424/6639a899-0f5b-44ac-aeea-350e706d65e6)
![Captura de tela 2024-03-05 215900](https://github.com/aws/karpenter-provider-aws/assets/109089424/c502f1ff-d4ef-46a5-8852-295a0ff5b92c)
![Captura de tela 2024-03-05 215739](https://github.com/aws/karpenter-provider-aws/assets/109089424/ab8ecfa3-f835-40b2-9795-adf48e099d58)
![Captura de tela 2024-03-05 211207](https://github.com/aws/karpenter-provider-aws/assets/109089424/1b0f98ba-a353-4ec2-b2df-17f5ce40e1f2)
![7](https://github.com/aws/karpenter-provider-aws/assets/109089424/4a9a9c98-fa37-4a9d-ace8-a8c006b27da6)

**Comment by pv-brunoalves** [comment]
Note: Don't worry, it's a sandbox account.

**Comment by jmdeal** [comment]
Can you post the output from `kubectl describe pod -n kube-system <karpenter-pod>`? I'm looking to verify that the `eks-pod-identity-token` volume exists. Could you also verify that the `karpenter` service account exists in your cluster?

**Comment by realexcel2021** [comment]
Had this same issue on a sand box account.... was anyone able to fix?

**Comment by pv-brunoalves** [comment]
I was able to install the version, but I changed the authentication method, I didn't use the Pod Identities eks 1.29 method, I used IRSA  with OIDC: from the other versions and it worked, the error occurred both in the sandbox and with my normal AWS account.

**Comment by ahoehma** [comment]
@pv-brunoalves is there somewhere a "complete" example how to setup latest karpenter with irsa in eks etc. I can't really find something new. Only old youtube videos (1 year old) with manual setup of almost everything. I try to setup eks with karpenter from the https://github.com/aws-ia/terraform-aws-eks-blueprints-addons project and I see only errors in my karpenter controller about "missing" stuff ... mostly roles etc.

**Comment by abnormalend** [comment]
Experiencing the same error when I tried to move to pod identity, and worked around by reverting to IRSA like @pv-brunoalves did.

EKS Version: 1.29
Karpenter Version: 0.36.0
Karpenter Terraform module: 20.8.5

**Comment by jonathan-innis** [comment]
If you're looking for a way to setup with IRSA and OIDC, our [Fargate method with EKSCTL in the Getting Started doc](https://karpenter.sh/docs/getting-started/getting-started-with-karpenter/#3-create-a-cluster) pretty much covers this case.

**Comment by jonathan-innis** [comment]
If you're running into an issue with pod identities not finding any credentials in the chain, it may be because you don't have any associations with the pod, you should try to run `aws eks list-pod-identity-associations` and validate that you have an association for the specific Karpenter pod you're targeting.

**Comment by sungmincs** [comment]
had the same issue with pod identity. all the pod associations and IAM permissions were set correctly but realized that it was failing due to the missing `eks-pod-identity-agent` add-on.

**Comment by ClementV78** [comment]
> had the same issue with pod identity. all the pod associations and IAM permissions were set correctly but realized that it was failing due to the missing `eks-pod-identity-agent` add-on.

THANK YOU !

**Comment by filipponova** [comment]
In my case, I had aduno installed, but I didn't have any nodes running, just fargates and as the addon has a matchExpression so that it doesn't provision fargates, the addon ended up not being able to provision the pods. To solve this, I added a node group and the pods from the pod identity and the nodes were provisioned and the Karpenter problem was solved.
