### ISSUE TITLE
[Question] Should WhenEmpy consolidation consolidate when only one workloadpod is present in terminating status

### ISSUE THREAD

**Issue by travis-jorge** [aws/karpenter-provider-aws#5787]
### Description

According to these docs https://karpenter.sh/v0.33/concepts/nodepools/
# If using `WhenEmpty`, Karpenter will only consider nodes for consolidation that contain no workload pods
    consolidationPolicy: WhenUnderutilized | WhenEmpty

Does this apply to workload pods that are terminating status. I have observed that a pod that might be stuck or taking a long time to terminate is holding the node. Is this expected? below are the Daemonsets that are also present:

<img width="509" alt="image" src="https://github.com/aws/karpenter-provider-aws/assets/80355769/72d5033a-c903-4581-bc1b-e93e2fda13ff">

**Comment by engedaam** [comment]
Is this pod created from a [StatefulSet](https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/)?

**Comment by travis-jorge** [comment]
@engedaam  no its just a deployment

**Comment by engedaam** [comment]
For deployments pods that are in a terminating state, Karpenter will not consider those pods and will terminate those nodes for being empty. Can you provide Karpenter logs and pod spec where you see nodes being stuck on terminating?

**Comment by cqwense** [comment]
I am experiencing similar behavior, but with a different desired outcome:

Any pod with a termination grace period greater than disruption.consolidateAfter , will have the draining process initiated at consolidateAfter even though the pod may stay terminating for long after that.  Our use case includes pods that require hostNetwork so its a 1:1 ratio between workloadPods:Node.

I was going to create an issue asking if the combination of whenEmpty and consolidateAfter could respect a workload pod in a terminating state, and only take affect when the only pods on the node were actually daemonsets.

I'll hope to have some time to make some simple manifests this week and if I do will provide them.

**Comment by qxmips** [comment]
> workload



> For deployments pods that are in a terminating state, Karpenter will not consider those pods and will terminate those nodes for being empty. Can you provide Karpenter logs and pod spec where you see nodes being stuck on terminating?

why such behavior  was choosen? if a pod has terminationGracePeriod  configured   shouldn't  karpenter respect it?
