### ISSUE TITLE
Adding karpenter dashboards to helm chart

### ISSUE THREAD

**Issue by tvonhacht-apple** [aws/karpenter-provider-aws#5791]
### Description

**What problem are you trying to solve?**

There are a few karpenter dashboards under getting-started (https://github.com/aws/karpenter-provider-aws/tree/main/website/content/en/docs/getting-started/getting-started-with-karpenter), it would be great if these would be bundled into the helm-chart, so deploying these to your cluster is as easy as setting values.yaml (f.e.: `grafana.dashboards.enabled: true`) to get latest updated charts with the last helm-chart being deployed.

Currently you have to copy the json file, add it to a ConfigMap and then either apply it, or use postRenderer in helm to add into the same release.

**How important is this feature to you?**

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by tvonhacht-apple** [comment]
I am interested in adding these files myself, if this is something accepted by Karpenter dev team

**Comment by njtran** [comment]
I can understand the use-case, but we’ve always treated these dashboards as a first step, where users likely want to make many different types of edits, and don't know if that's up to Karpenter to maintain. I think you'll only need to copy the json file once. Is it not possible to couple this with your Prometheus/Grafana installations?

**Comment by tvonhacht-apple** [comment]
> I can understand the use-case, but we’ve always treated these dashboards as a first step, where users likely want to make many different types of edits, and don't know if that's up to Karpenter to maintain. I think you'll only need to copy the json file once. Is it not possible to couple this with your Prometheus/Grafana installations?

Flux does this, it has dashboards:
- https://github.com/fluxcd/flux/blob/master/chart/flux/templates/configmap-dashboards.yaml
