### ISSUE TITLE
Make controller's container.securityContext configurable

### ISSUE THREAD

**Issue by GyunCho** [aws/karpenter-provider-aws#5794]
### Description

**What problem are you trying to solve?**
Context:
I used to use Karpenter v0.28.1, and with that version I was able to configure Karpenter pod's container securityContext.
However, after starting to use v0.34.1, this field is not configurable, and values are fixed like
runAsUser and runAsGroup's values are fixed to `65536`, and I can't change it
[deployment.yaml](https://github.com/aws/karpenter-provider-aws/blob/v0.35.0/charts/karpenter/templates/deployment.yaml#L61-L71)

I see that with https://github.com/aws/karpenter-provider-aws/issues/4278
and https://github.com/aws/karpenter-provider-aws/pull/4320, 
someone wanted to set default securityContext to enforce security by default, that I agree completely, and is a good change, but it should've been still left configurable.

**How important is this feature to you?**
This is security related feature.

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by jonathan-innis** [comment]
> and is a good change, but it should've been still left configurable

What do you need to configure it to such that you need the value to be configurable? The reason we didn't make it configurable was that we couldn't reason about a case why someone would even want to configure it away from the default.

**Comment by GyunCho** [comment]
@jonathan-innis 
I'd like to use different UIDs for `runAsUser`, `runAsGroup`, and `fsGroup`.
or at least, can we use a different number value other than 65536 by default?
Like any number between 10001-65535.

Is there a specific reason why 65536 was picked?

**Comment by jonathan-innis** [comment]
> Is there a specific reason why 65536 was picked

The main reason is that we want to pick a `runAsUser`, `runAsGroup`, and `fsGroup` that do not have any permissions assigned on the host. There is no delineation between the users that exist within the context of the CRI and the context of the host so we want to make sure that the container users and groups that we are using don't have permissions by default since the Karpenter container process doesn't have any need to make kernel calls, do anything on the host, or access any filesystems that would be owned by a user or group on the host.

**Comment by jonathan-innis** [comment]
This also allows us to adhere to the [Restricted](https://kubernetes.io/docs/concepts/security/pod-security-standards/#:~:text=specified)%20Pod%20configuration.-,Restricted,-Heavily%20restricted%20policy) security standard out of the box.

**Comment by jonathan-innis** [comment]
There's also a bit of back-and-forth that happened over in the Kubernetes slack if you want to get some insight into why we decided to go this direction: https://kubernetes.slack.com/archives/C019LFTGNQ3/p1692634797271299

**Comment by jonathan-innis** [comment]
I actually see a use-case for this now (see https://cookbook.openshift.org/users-and-role-based-access-control/why-do-my-applications-run-as-a-random-user-id.html). @GyunCho I'm not sure if this is what you are going for, but I could imagine that if you were trying to run each of these containers as different UUIDs to mitigate impact on a container break-out, you would want to be able to configure this manually.

**Comment by nicolas-docto** [comment]
Hello, I have sort of equivalent needs. I have enforced Gatekeeper constraints where I need to add under the securityContext : `privileged: false`. Is it possible to do it in any way ? Thanks a lot
