### ISSUE TITLE
Configure buffer space for consolidation

### ISSUE THREAD

**Issue by RandellP** [aws/karpenter-provider-aws#5802]
### Description

**What problem are you trying to solve?**
We get loads that spike rather suddenly.  And waiting for new nodes to be spun up is time we can't afford.  Consolidation seems to run too tight of a ship, leaving us very little room for fast expansion.  I would like to be able to tune a bit of a buffer so that we have a little extra capacity standing by to use to spin up new pods while we wait for the new node to fire up...

**How important is this feature to you?**
Not being able to do something like this will likely prevent us from using consolidation at all in the not to distant future.  

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by edas-smith** [comment]
Not sure if you have already seen this before, but this is a very good way of doing it currently : https://aws.amazon.com/blogs/containers/eliminate-kubernetes-node-scaling-lag-with-pod-priority-and-over-provisioning/ but you of course do pay a little $ extra as there are "overprovisioned" resources but its worth it in such cases :)

**Comment by engedaam** [comment]
There is currently a mega-issue on over-provisioning or manual node provisioning here: https://github.com/kubernetes-sigs/karpenter/issues/749. I would recommended closing this issue and provide your use-case there

**Comment by njtran** [comment]
closing in favor of above issue
