### ISSUE TITLE
Using Tags with Node Pools

### ISSUE THREAD

**Issue by abebars** [aws/karpenter-provider-aws#5804]
### Description

**What problem are you trying to solve?**
While the NodeClass can apply the specified tags to the underlying EC2 resources. NodePool can't and since there is a connection between NodePool and NodeClass, It would be useful that NodePool can also specify the tags on that level and both tags can be merged together.

**How important is this feature to you?**
Since the NodePool is the logic behind deciding which NodeClass to use, it's important to know on the underlying resources which provisioner decided that.

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by abebars** [comment]
I am also happy to help with the implementation if there is no blocker on adding this.

**Comment by engedaam** [comment]
What do you mean the NodePool by the applying tags to EC2 resources? Are you thinking that karpenter should propagate labels and annotation from the NodePool on to  EC2 resources?

**Comment by jonathan-innis** [comment]
> It would be useful that NodePool can also specify the tags on that level and both tags can be merged together

There is a many to one mapping from NodePools to EC2NodeClass. If you wanted different tags for each of your NodePools, you could create different EC2NodeClasses to manage the different tags. If you were looking to set tags dynamically, I think there's some feature requests to cover this [here](https://github.com/aws/karpenter-provider-aws/issues/2783) and [here](https://github.com/aws/karpenter-provider-aws/issues/4228)

**Comment by abebars** [comment]
Any updates on that?

**Comment by abebars** [comment]
@jonathan-innis I looked at the code and I don't think Provisioner or NodePool supports tagging right now as AWSNodeTeamplate or NodeClass, Let me know if I am missing it but I need the tags to be defined in the provisioner as the node template
so the goal would be something like this

- Provisioner Tags`spec.tags: X`
- AWSNodeTemplate Tags `spec.tags: Y`

That should result to a node create with a tag X & Y
