### ISSUE TITLE
Allow to pass the cluster service cidr

### ISSUE THREAD

**Issue by stijndehaes** [aws/karpenter-provider-aws#5825]
### Description

**What problem are you trying to solve?**

With the support of AL2023 suddenly the `eks:DescribeCluster` IAM action has to be allowed, before it wasn't needed since we could pass all the information statically that would be fetched with this call.

**How important is this feature to you?**

It is annoying since we need to update rights, and the error received are not very clear.

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by jonathan-innis** [comment]
> before it wasn't needed since we could pass all the information statically that would be fetched with this call

@stijndehaes I'm curious. What's the reason that you don't or can't add `eks:DescribeCluster` permission to the Karpenter pod role?
