### ISSUE TITLE
failure-domain.beta.kubernetes.io Removed after 1.26 upgrade

### ISSUE THREAD

**Issue by ramcloud199** [aws/karpenter-provider-aws#5840]
### Description

**Observed Behavior**:
failure-domain.beta.kubernetes.io Node label is being removed after eks version upgraded from 1.25 to 1.26
**Expected Behavior**:
failure-domain.beta.kubernetes.io should be present
**Reproduction Steps** (Please include YAML):

**Versions**:
- Chart Version:
- Kubernetes Version (`kubectl version`): 1.26
- Karpenter Version: v0.25.0

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Is there way to get those failue-domain.beta labels ?**

**Comment by jonathan-innis** [comment]
This seems like an issue that might be related to EKS's change to use `--cloudprovider=external` when starting up nodes starting on 1.26. I suspect that this change is causing a different set of labels to be added than before. Checking to see if this is intentional behavior.

**Comment by jonathan-innis** [comment]
This is odd. The [upstream code](https://github.com/kubernetes/cloud-provider/blob/master/controllers/node/node_controller.go#L541) indicates that we should be adding this label. I'm going to try a repro and see what I get.

**Comment by jonathan-innis** [comment]
Potential duplicate, but we weren't able to repro it: https://github.com/aws/karpenter-provider-aws/issues/3996. Are you able to go through AWS support so that we could get more details into the cluster, including apiserver audit logs?

**Comment by mmerkes** [comment]
Have you confirmed that `topology.kubernetes.io/zone` is set correctly?

**Comment by ramcloud199** [comment]
![image](https://github.com/aws/karpenter-provider-aws/assets/160160069/d47835aa-4fbd-4283-ab60-1c6132f118c5)
As per the document it will be deprecated and successor to the stable version.
https://karpenter.sh/docs/concepts/scheduling/#well-known-labels

```
failure-domain.beta.kubernetes.io/zone
failure-domain.beta.kubernetes.io/region
beta.kubernetes.io/arch
beta.kubernetes.io/os
beta.kubernetes.io/instance-type
```
From Our existing node i can below labels which are even deprecated as per the document.

Labels:             beta.kubernetes.io/arch=arm64
                    beta.kubernetes.io/os=linux

Also from EKS logs there is no logs which is related label adding.

**Comment by jonathan-innis** [comment]
> From Our existing node i can see below labels which are even deprecated as per the document

So, to confirm, can you share all the labels from your node with `kubectl get node <node-name> -o yaml`. We could at least confirm that everything is propagating down correctly.

Better would be if you could open a ticket with AWS support and then it could get routed to our service team where we would look at the actual ordering of apiserver calls that were made here.

**Comment by ramcloud199** [comment]
Issue is fixed after upgraded the karpenter version from v0.25.0  to v0.29.2.

**Comment by engedaam** [comment]
Closing the issue as it fix in the newer versions of Karpenter.
