### ISSUE TITLE
Documentation Compatibility Matrix

### ISSUE THREAD

**Issue by erezzarum** [aws/karpenter-provider-aws#5841]
### Description

**How can the docs be improved?**
Improve the compatibility matrix, by changing the Semantic Version of Karpenter in the matrix.
Instead of using Major.Minor.Patch+, replace with >= Major.Minor.Patch

Example:
Karpenter 0.28.x+ is matched with Kubernetes 1.26 and 1.27 in the current matrix, users confuse that they are unable to use Karpenter 0.33 with Kubernetes 1.26 and 1.27 and they can only run patch releases of 0.28 on Kubernetes 1.26 and 1.27
Changing the Karpenter semantic version comparison to ">= 0.28" is more clear.

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by OverStruck** [comment]
Please Karpenter team, make this change. That doc is extremely confusing.

**Comment by sftim** [comment]
Pull requests are welcome!

**Comment by erezzarum** [comment]
I did, pull request #5842
