### ISSUE TITLE
enhance decommission of expired node using budget

### ISSUE THREAD

**Issue by bhavasarpritesh** [aws/karpenter-provider-aws#5898]
### Description

**What problem are you trying to solve?**
 I've set up Karpenter to handle node scaling and configured a budget to prevent expired node disruptions during daytime. However, a problem has arisen: when new nodes are commissioned due to high traffic, they are not decommissioned after traffic subsides.
    budgets:
    - nodes: "0"
      schedule: "0 3 * * *"
      duration: 18h
**How important is this feature to you?**
  it is very important and useful to control the recycling of expired node

**Comment by engedaam** [comment]
Have you tried using a separate NodePool with different disruption budgets rules during scaling events?

**Comment by bhavasarpritesh** [comment]
I have 2 NodePools but for both, I want the same behavior for both that is it shouldn't commission expired nodes in daytime

**Comment by engedaam** [comment]
So If I understand correctly, you would like nodes to be disrupted for consolidation but not for expiration during daytime?

**Comment by bhavasarpritesh** [comment]
yes, correct

**Comment by engedaam** [comment]
Closing this as a duplicate, we have a similar issue open to track this feature request https://github.com/kubernetes-sigs/karpenter/issues/924
