### ISSUE TITLE
Consolidation to a larger node if price is the same

### ISSUE THREAD

**Issue by oleksiytsyban** [aws/karpenter-provider-aws#5903]
Should Karpenter consolidate two c6a.2xlarge nodes into one c6a.4xlarge node if the price is exactly the same?
```
karpenter_cloudprovider_instance_type_price_estimate{capacity_type="on-demand",instance_type=~"c6a.2xlarge"} *2 = 0.6984

karpenter_cloudprovider_instance_type_price_estimate{capacity_type="on-demand",instance_type=~"c6a.4xlarge"}  = 0.6984

```

**Comment by engedaam** [comment]
No, Karpenter should not consolidate nodes if we see that the price is the same. With each consolidation action Karpenter expect to lower the cost of the cluster. https://karpenter.sh/v0.32/concepts/disruption/#consolidation

**Comment by oleksiytsyban** [comment]
Even if price is exactly the same, one node can save some costs, comparing to two smaller nodes. It would have one set of daemons and one physical volume.

**Comment by a7i** [comment]
@engedaam can this be re-opened and discussed further? in a setup where DaemonSets (and kubeResrved/systemReserved) take up a chunk of allocatable resources, it makes sense to consolidate to a single larger node.

**Comment by grosser** [comment]
FYI when running with node-overlay that adds minimal per-host cost this issue goes away
