### ISSUE TITLE
Filter instances based on EBS baseline bandwidth

### ISSUE THREAD

**Issue by mohanvarupula** [aws/karpenter-provider-aws#5905]
### Description

**What problem are you trying to solve?**
Currently, I can't see a way to provision [EC2 EBS optimised instances](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ebs-optimized.html) by filtering based on the EBS baseline bandwidth. This can help in provisioning the instances where the workload requires higher EBS bandwidth. 

**Example:** We have cypress tests which are failing when using m5a instances (large,xlarge,2xlarge) as they don't have enough EBS baseline bandwidth and can only extend upto 2880Mbps. But, cypress tests require at least 3000Mbps. This is preventing us to allocate wide range of instance categories to the nodepool and defeating the purpose of Karpenter as have restricted our workload to only few instance families. 

Need something like `karpenter.k8s.aws/instance-ebs-bandwidth`.

**How important is this feature to you?**
It will be helpful to filter EBS optimised instances and also use wide range of instance categories.

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by njtran** [comment]
Looking at the describe-instance-types API I see this bit:

```
            "EbsInfo": {
                "EbsOptimizedSupport": "default",
                "EncryptionSupport": "supported",
                "EbsOptimizedInfo": {
                    "BaselineBandwidthInMbps": 90,
                    "BaselineThroughputInMBps": 11.25,
                    "BaselineIops": 500,
                    "MaximumBandwidthInMbps": 2085,
                    "MaximumThroughputInMBps": 260.625,
                    "MaximumIops": 11800
                },
                "NvmeSupport": "required"
            },
```
And I see other instance types with this value. 
```
            "EbsInfo": {
                "EbsOptimizedSupport": "unsupported",
                "EncryptionSupport": "supported",
                "NvmeSupport": "unsupported"
            },
```

I'm assuming you'd want it to be match of `EbsInfo.EbsOptimizedSupport != "unsupported"`. Are you more concerned with the baseline bandwidth or the maximum?

**Comment by mohanvarupula** [comment]
@njtran Yes. I want to pick up the EBS optimized instances which matches `EbsInfo.EbsOptimizedSupport != "unsupported"` and would like to filter the instances based on their baseline and maximum ebs bandwidth.

**Comment by njtran** [comment]
At the surface I don't have any complaints with this. Are you willing to make the contribution?

**Comment by NetanelK** [comment]
I can help 
/assign
