### ISSUE TITLE
What formula is used to calculate the value of memory in Resource table?

### ISSUE THREAD

**Issue by micxyj** [aws/karpenter-provider-aws#5906]
### Description

I check the [document](https://karpenter.sh/docs/reference/instance-types/), for example: The instance memory of a1.medium is 2048M, but memory in [resource](https://karpenter.sh/docs/reference/instance-types/#resources) is 1392M, how to calculate reserve memory can get the value of 1392M?

**Comment by njtran** [comment]
These are estimated allocatable resources for the instance type given some overhead. https://karpenter.sh/docs/reference/instance-types/#resources:~:text=AWS%20instance%20types,default%20of%20AL2
