### ISSUE TITLE
NodePool Resource limits not constrain the total size of the cluster.

### ISSUE THREAD

**Issue by maisam94** [aws/karpenter-provider-aws#5909]
## Issue
NodePool Resource limits  not prevent Karpenter from creating new instances once the limit is exceeded.
## Description
I configure nodepool with resource limit of cpu "1000", but karpenter add node with 4core(4000m) of cpu..
Also when reduce the CPU limit, karpenter not scale down running nodes (not delete running nodes), it's just disables the creation of new nodes.
## Expected Behavior 
To  prevent Karpenter from creating new instances once the limit is exceeded
And to scale down nodes when reduce cpu limits

**Comment by maisam94** [comment]
> Do you have multiple NodePools in your cluster? Can you share the NodePool and Karpenter logs of this event? Also lowering the CPU limit will not trigger disruption on your nodes, It will only disable node creation, which is outlined in our [docs](https://karpenter.sh/docs/concepts/nodepools/#speclimits).

we have two nodepool on our cluster. and as i described the limits on below nodepool not disable node creation, I scale up replicas pods and karpenter still create new node for the new pods so now we have 2 nodes from below nodepool, each node with instance type c5a.xlarge and 4core cpu . 

Logs from karpenter controller:

{"level":"INFO","time":"2024-03-21T07:14:07.874Z","logger":"controller.provisioner","message":"found provisionable pod(s)","commit":"2dd7fdc","pods":"sqdl/frontend-6f566ccdf8-zjxxn, sqdl/frontend-6f566ccdf8-nzgqc, sqdl/frontend-6f566ccdf8-htq6r","duration":"7.517335ms"}
{"level":"INFO","time":"2024-03-21T07:14:07.874Z","logger":"controller.provisioner","message":"computed new nodeclaim(s) to fit pod(s)","commit":"2dd7fdc","nodeclaims":1,"pods":3}
{"level":"INFO","time":"2024-03-21T07:14:07.897Z","logger":"controller.provisioner","message":"created nodeclaim","commit":"2dd7fdc","nodepool":"spot-stg","nodeclaim":"spot-stg-jdz7c","requests":{"cpu":"480m","memory":"504Mi","pods":"8"},"instance-types":"c3.xlarge, c4.xlarge, c5.xlarge, c5a.xlarge, c5ad.xlarge and 45 other(s)"}
{"level":"INFO","time":"2024-03-21T07:14:10.940Z","logger":"controller.nodeclaim.lifecycle","message":"launched nodeclaim","commit":"2dd7fdc","nodeclaim":"spot-stg-jdz7c","provider-id":"aws:///us-east-1c/i-0b2cdcad40cc2e08f","instance-type":"c5a.xlarge","zone":"us-east-1c","capacity-type":"spot","allocatable":{"cpu":"3920m","ephemeral-storage":"44Gi","memory":"6584Mi","pods":"58","vpc.amazonaws.com/pod-eni":"18"}}
{"level":"INFO","time":"2024-03-21T07:14:52.518Z","logger":"controller.nodeclaim.lifecycle","message":"initialized nodeclaim","commit":"2dd7fdc","nodeclaim":"spot-stg-jdz7c","provider-id":"aws:///us-east-1c/i-0b2cdcad40cc2e08f","node":"ip-10-1-108-193.ec2.internal"}


Node Pool yaml:

apiVersion: karpenter.sh/v1beta1
kind: NodePool
metadata:
  annotations:
    karpenter.sh/nodepool-hash: "8487896078615553801"
  creationTimestamp: "2023-12-14T11:03:47Z"
  generation: 19
  name: spot-stg
  resourceVersion: "111919385"
  uid: 7faf7d33-ea76-4be8-b409-d8785936cc1f
spec:
  disruption:
    consolidateAfter: 100s
    consolidationPolicy: WhenEmpty
    expireAfter: 720h
  limits:
    cpu: "1000"
    memory: 1000Gi
  template:
    spec:
      nodeClassRef:
        name: stg-ec2-node-class
      requirements:
      - key: kubernetes.io/arch
        operator: In
        values:
        - amd64
      - key: kubernetes.io/os
        operator: In
        values:
        - linux
      - key: karpenter.sh/capacity-type
        operator: In
        values:
        - spot
      - key: karpenter.k8s.aws/instance-category
        operator: In
        values:
        - c
        - m
        - r
      - key: karpenter.k8s.aws/instance-size
        operator: In
        values:
        - xlarge
        - 2xlarge
        - 4xlarge
status:
  resources:
    cpu: "8"
    ephemeral-storage: 104832984Ki
    memory: 16044960Ki
    pods: "116"

**Comment by maisam94** [comment]
ok so as i understand lowering the CPU limit is a feature and not a bug.

**Comment by engedaam** [comment]
> Do you have multiple NodePools in your cluster? Can you share the NodePool and Karpenter logs of this event? 

@maisam94 I haven't been able to reproduce this issue, can you provide more details on your environment?
