### ISSUE TITLE
We are trying to add a configuration for our NodePool to consolidate when under utilized 

### ISSUE THREAD

**Issue by akunduru9** [aws/karpenter-provider-aws#5912]
### Description

**Observed Behavior**:
  We are expecting to see with below setting node should stay active for 15 min after all cron jobs completed .
   
    limits:
    cpu: "1000"
    memory: 1000Gi
  disruption:
    consolidationPolicy: WhenUnderutilized
    minAge: 15m
    expireAfter: 1h
 
**Expected Behavior**:
  But the node was being removed immediately after the jobs finished. I just wanted to confirm if the settings I had are correct for my use case, or if there is any other way to make it work
**Reproduction Steps** (Please include YAML):

**Versions**:
- Chart Version:
- Kubernetes Version (`kubectl version`):

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by engedaam** [comment]
Karpenter currently does not support a minAge for NodeClaims. We have an open issue for it. https://github.com/kubernetes-sigs/karpenter/issues/1030

**Comment by akunduru9** [comment]
@engedaam We're facing an issue where, whenever Karpenter spins up a new node for our NodePools, the Datadog agent pod on those nodes takes nearly 4 minutes to start. This delay means that by the time the pod starts, the jobs running on the node may have already finished and vanished, causing us to miss logs. Can you suggest any alternative solutions to resolve this situation?

**Comment by engedaam** [comment]
Can you use a startupTaints? This sounds very similar to the cilium use-case, where you need Datadog agent to be configured before the job starts running. https://karpenter.sh/docs/concepts/nodepools/#cilium-startup-taint

**Comment by akunduru9** [comment]
I did give it a try but seeing toleration issue for pod : "0/5 nodes are available: 1 node(s) had untolerated taint {node.datadoghq.com/agent-not-ready: true}, 1 node(s) had untolerated taint {nodepool: applications}, 1 node(s) had untolerated taint {nodepool: reserved}, 2 node(s) had untolerated taint {dedicated: admin}. preemption: 0/5 nodes are available: 5 Preemption is not helpful for scheduling."

my current setup 

    spec:
      taints:
        - key: "nodepool"
          value: "db-jobs"
          effect: "NoSchedule"
      startupTaints:
        - key:  node.datadoghq.com/agent-not-ready
          value: "true"
          effect: NoExecute

**Comment by engedaam** [comment]
Do you have a controller or deamonset removing the taint? 

>  Provisioned nodes will have these taints, but pods do not need to tolerate these taints to be provisioned by this
    NodePool. These taints are expected to be temporary and some other entity (e.g. a DaemonSet) is responsible for
     removing the taint after it has finished initializing the node.

**Comment by akunduru9** [comment]
We do have DaemonSets for many applications, but we do not have any logic to remove taints from NodePools. Do you have any examples or references on how it should be defined to fit my use case?

**Comment by assaftir** [comment]
You should add a toleration for that startup taint in your datadog node agent configuration, and have some periodic task to run and monitor when the dd node agent is ready, then remove that taint to allow your jobs to be scheduled.

**Comment by akunduru9** [comment]
Ok, cool. I will take a look. Do you have any examples on how to set it up?
