### ISSUE TITLE
Karpenter On AWS Gov Cloud :  retreiving on-demand pricing data, UnrecognizedClientException: The security token included in the request is invalid

### ISSUE THREAD

**Issue by Nadavmak** [aws/karpenter-provider-aws#5922]
### Description

**Observed Behavior**:
 After installing Karpenter with eks_blueprints_kubernetes_addons on our EKS Cluster (
github.com/aws-ia/terraform-aws-eks-blueprints//modules/kubernetes-addons | v4.32.1 )

We see this error with in our Karpenter pods : 
{"level":"ERROR","time":"2024-03-24T11:43:46.157Z","logger":"controller.pricing","message":"retreiving on-demand pricing data, UnrecognizedClientException: The security token included in the request is invalid\n\tstatus code: 400, request id: bf96dc7e-2bf6-478b-a3fa-00e577c87aa2; UnrecognizedClientException: The security token included in the request is invalid\n\tstatus code: 400, request id: 703284ba-8a9f-492f-8074-0b4ecb50b463","commit":"cac2034"}

**Expected Behavior**:
Karpenter pods should run without this error.

**Reproduction Steps** (Please include YAML):
Install Karpenter with eks_blueprints_kubernetes_addons on EKS Cluster

**Versions**:
- Chart Version: karpenter-v0.34.3
- Kubernetes Version (`kubectl version`): Server Version: v1.27.11-eks-b9c9ed7

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by engedaam** [comment]
I would suggest opening an issues with https://github.com/aws-ia/terraform-aws-eks-blueprints. They would have the most context on the configuration set-up using terraform

**Comment by govinda-attal** [comment]
Hey team, we are also facing the same issue
