### ISSUE TITLE
"Could not schedule pods, all available instance types exceed limits" during EC2 API outage

### ISSUE THREAD

**Issue by joshuabaird** [aws/karpenter-provider-aws#5937]
### Description

**Observed Behavior**:
During a recent EC2 API outage (on 3/26/24), we observed the following errors:

```
Could not schedule pod, all available instance types exceed limits for nodepool: "use1-production-01"
```

Our NodePools do have available resources.  I believe this may be the case of a bad/incorrect error due to the EC2 API being unavailable.

We also see expected errors such as:

```
listing instance types for use1-production-01, fetching instance types using ec2.DescribeInstanceTypes, InternalError: An internal error has occurred
	status code: 500
```

**Expected Behavior**:
A better error message should be displayed.

**Versions**:
- Chart Version: 0.35.2
- Kubernetes Version (`kubectl version`): 1.29/EKS

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by gvillafanetapia** [comment]
same here 😞 

it would also be great to have some contingency for this? maybe karpenter could cache the instance types and work around 
an outage? 🤔

**Comment by joshuabaird** [comment]
> same here 😞
> 
> it would also be great to have some contingency for this? maybe karpenter could cache the instance types and work around an outage? 🤔

Yeah - in the case of this outage which seems to be affecting only `Describe` calls, I think some sort of caching mechanism on `DescribeInstanceTypes` could be helpful.

**Comment by bala151187** [comment]
Any insight on this issues would be helpful!! . thanks

**Comment by GnatorX** [comment]
This was related to an AWS outage in us-east-1 for DescribeInstanceTypes and DescribeInstanceTypeOffering. I haven't look into what and why Karpenter need to make this call. Is this information necessary to be updated continuously.

**Comment by engedaam** [comment]
https://github.com/kubernetes-sigs/karpenter/pull/1165 should fix this erroneous log message

**Comment by jonathan-innis** [comment]
It seems like this issue is larger than just fixing the error message. It might be worth fixing this error message and then opening a larger issue for improvements in caching the instance types if one isn't open already.

**Comment by GnatorX** [comment]
i was going to mention this doesn't feel like an wrong error message. It seems like cache isn't working or we are listing periodically for instance type

**Comment by GnatorX** [comment]
I think its because of this https://github.com/kubernetes-sigs/karpenter/blob/main/pkg/controllers/provisioning/provisioner.go#L221 the scheduler performs this GetInstanceTypes each time we create a new scheduler which we do every time we evaluate scheduling

**Comment by njtran** [comment]
Our instance type cache does more than keep track of the names of the instance types, it keeps track of the allocatable of each of the offerings for a given setting of inputs, and caches the outputs for each given set. This is because of how bits and piece of other API modifies how Karpenter thinks of instance types. 

Realistically, we can probably increase this timeout, but how long did this issue impact you? Would something like 15 minutes be enough? 30 minutes? 2 hours?

**Comment by GnatorX** [comment]
The problem here isn't about how long a cache should be rather some parts of the cache doesn't need be refreshed to prevent issues like zonal outages from AWS. In this case after 5 minutes Karpenter will start failing to perform any actions(?) even though the data it relies on to calculate is already there and won't change (instance type and instance type offering). 

Its true that the whole instanceTypeProvider cache does more than just cache instance types and it actually contains multiple "sub"-caches however not every part of the cache needs refreshing. 

Breaking out the caches where somethings are static is more of an availability improvement to Karpenter and not necessarily a performance thing.

**Comment by JacobHenner** [comment]
> Realistically, we can probably increase this timeout, but how long did this issue impact you? Would something like 15 minutes be enough? 30 minutes? 2 hours?

When we observed this issue on 2024-03-26 it lasted for approximately 2h. See graphs below (time in EDT).

![image(1)](https://github.com/aws/karpenter-provider-aws/assets/144119/9592bd2d-5c3f-46f0-a74f-b7644d3417dc)
![image](https://github.com/aws/karpenter-provider-aws/assets/144119/096cdd3e-cafc-4160-8ede-8e436d6c1a7b)

**Comment by engedaam** [comment]
> The problem here isn't about how long a cache should be rather some parts of the cache doesn't need be refreshed to prevent issues like zonal outages from AWS. In this case after 5 minutes Karpenter will start failing to perform any actions(?) even though the data it relies on to calculate is already there and won't change (instance type and instance type offering).

Karpenter now maintains a controller to hydrate and instance type APIs asynchronously. The instance type controller will be responsible for querying DescribeInstanceTypes ,and DescribeInstanceTypesOfferings caching the data. The controller will attempt to refresh the data every 12 hours. The instance type data will only update the instance type data upon a successful response. This will allow Karpenter to be more genrally resilient. https://github.com/aws/karpenter-provider-aws/pull/6045

**Comment by GnatorX** [comment]
Nice I think that address this issue

**Comment by yaroslav-nakonechnikov** [comment]
5 cents to others, who may face that issue, but with another rootcause:
on 0.32.9 (at least), if there is a limit defined like `cpu: 0` - it really means 0, and nothing will work with error "Could not schedule pods, all available instance types exceed limits"

for me it was a bit surprise, as in most other places that would mean unlimited.

**Comment by engedaam** [comment]
Just an FYI, here are list of PRs that hope to address this issue

- [ ] https://github.com/aws/karpenter-provider-aws/pull/6057
- [ ] https://github.com/aws/karpenter-provider-aws/pull/6069
- [ ] https://github.com/aws/karpenter-provider-aws/pull/6089

**Comment by engedaam** [comment]
Closing as all the tracked PRs are merged.

**Comment by booleanbetrayal** [comment]
I wanted to chime in on this issue, as we experienced something similar, causing a full NodePool rebuild (!) after a batch of Karpenter error logs like the following:

```
{"level":"ERROR","time":"2025-09-11T10:09:59.065Z","logger":"controller","message":"Reconciler error","commit":"13242ea","controller":"nodeclass","controllerGroup":"karpenter.k8s.aws","controllerKind":"EC2NodeClass","EC2NodeClass":{"name":"default"},"namespace":"","name":"default","reconcileID":"468a48aa-25a9-4798-89f4-5b1d336bcde4","aws-error-code":"InternalError","aws-operation-name":"CreateFleet","aws-request-id":"7289535f-9cfa-458d-96d4-6ec354382e48","aws-service-name":"EC2","aws-status-code":500,"error":"validating ec2:CreateFleet authorization, operation error EC2: CreateFleet, https response error StatusCode: 500, RequestID: 7289535f-9cfa-458d-96d4-6ec354382e48, api error InternalError: An internal error has occurred (aws-error-code=InternalError, aws-operation-name=CreateFleet, aws-request-id=7289535f-9cfa-458d-96d4-6ec354382e48, aws-service-name=EC2, aws-status-code=500)"}
```

I can open a separate issue as needed, but this issue was easily surfaced when searching on AWS internal errors causing Karpenter problems.
