### ISSUE TITLE
HELM Missed config 

### ISSUE THREAD

**Issue by noamgreen** [aws/karpenter-provider-aws#5939]
### Description

HI 
in the helm files 
https://github.com/aws/karpenter-provider-aws/blob/v0.35.2/charts/karpenter/values.yaml

the ver is static config to v0.34.0 i think its need to be "0.35.2"

can you pls change it 

many thanks :-)

**Comment by engedaam** [comment]
Closing as a duplicate https://github.com/aws/karpenter-provider-aws/issues/5415
