### ISSUE TITLE
Inconsistency between amiFamily and amiSelectorTerms leading to bad userdata.

### ISSUE THREAD

**Issue by omerap12** [aws/karpenter-provider-aws#5940]
### Description

**Observed Behavior**:
Create ec2.nodeclass with  amiFamily: Bottlerocket  amiSelectorTerms of a amazon linux 2 (default aws image), new nodes will have user data in bottlerocket format and won't register to the cluster.

**Expected Behavior**:
Some validation between amiFamily and the actual ami should fail/warn.

**Reproduction Steps** (Please include YAML):
use the following  ec2.nodeclass yaml snippet:
apiVersion: karpenter.k8s.aws/v1beta1
kind: EC2NodeClass
metadata:
  annotations:
    helm.sh/hook: post-install
    helm.sh/hook-weight: "10"
    meta.helm.sh/release-name: karpenter
spec:
  amiFamily: Bottlerocket
  amiSelectorTerms:
  - id: ami-0677b4f5ab8236601

According to the documentation:
```When you specify amiSelectorTerms, you fully override the default AMIs that are selected on by your EC2NodeClass amiFamily.```
https://karpenter.sh/docs/concepts/nodeclasses/#specamiselectorterms

**Versions**:
- Chart Version: karpenter-0.35.1
- Kubernetes Version (`kubectl version`): Server Version: v1.27.10-eks-508b6b3

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by njtran** [comment]
How are you expecting Karpenter to infer the underlying operating system of the AMI that you're trying to provision? If it's tough to do this generally, also including validation to check this will be tough as well. It seems like also the turnaround on realizing that you've made an error here is pretty quick.

As a general user-experience, before setting my AMI to a specific AMI ID, I'd want to make sure that my AMI is running the same AMI Family as what I've prescribed in my EC2NodeClass. The fact that we also have the amiFamily apply to all discovered AMIs also means that we're implicitly not allowing OS-flexible NodeClasses, in case that's what you were trying to achieve.

**Comment by omerap12** [comment]
Hi @njtran,

Thank you for getting back to me. I understand. But after reading the following line in the documentation:
```
When you specify amiSelectorTerms, you fully override the default AMIs that are selected on by your EC2NodeClass amiFamily.
```

I had assumed that Karpenter might have all the details about certain AMIs (I used AL2, which seemed plausible), including the amiFamily (maybe in memory db on the controller itself). Adding a remark like this in the docs would be helpful I think :)

**Comment by njtran** [comment]
The controls should be understood as amiFamily prescribing the bootstrapping mode, and the amiSelectorTerms prescribing the AMI that should be used. I can understand your confusion. Would you be willing to make a documentation change here to make this clearer?

**Comment by omerap12** [comment]
Hey @njtran ,
Yes, of course

**Comment by omerap12** [comment]
Hello @njtran,
I have created the PR. Thanks
