### ISSUE TITLE
prometheus KubeMemoryOvercommit warnings

### ISSUE THREAD

**Issue by brianmay** [aws/karpenter-provider-aws#5980]
### Description

**Observed Behavior**:

Prometheus generates KubeMemoryOvercommit on relatively new cluster.

I have no idea if this is something I should be concerned about, but it looks wrong. And I can't find any information on how to deal with it.

**Expected Behavior**:

Karpenter should add a new node, to stop these warnings from appearing. But I think Karpenter isn't making any allowances to increase tolerance for nodes going done, which the prometheus check is looking for.

**Reproduction Steps** (Please include YAML):

Sorry, not really sure here.

**Versions**:
- Chart Version: 0.35.4
- Kubernetes Version (`kubectl version`): 1.28.6-eks-508b6b3

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by njtran** [comment]
Karpenter bin-packs based off your app requests, and if your limits sum to higher than the node allocatable, it's possible you'll see this overcommitted message. If you find that Prometheus isn't consuming as much memory as you're thinking, you should reduce the memory limits. The same goes for any of your other pods on that node. 

Going to close, feel free to reopen if you want.

**Comment by brianmay** [comment]
Sorry, not finding this easy to comprehend. Not even sure what the KubeMemoryOvercommit promethus warning means, I have seen what looks like very different definitions here.

* https://runbooks.prometheus-operator.dev/runbooks/kubernetes/kubememoryovercommit/ "Cluster has overcommitted Memory resource requests for Pods and cannot tolerate node failure."

* https://medium.com/pareture/kubernetes-node-overcommitted-57ec7c3dfe9e - seems to indicate if requests > limits, then this warning will occur. But not 100% convinced I understood this.

If the limits sum to higher then allowed by the node, doesn't this mean the pods should get moved to new nodes?
