### ISSUE TITLE
"Migrating from Cluster Autoscaler" IAM missed config if AWS Load Balancer Controller version v2.1.1 or earlier

### ISSUE THREAD

**Issue by noamgreen** [aws/karpenter-provider-aws#5993]
### Description

**How can the docs be improved?**

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

in the doc you have policy  e.g. 
``` yaml 

id": "AllowScopedInstanceProfileTagActions",
            "Effect": "Allow",
            "Resource": "*",
            "Action": [
            "iam:TagInstanceProfile"
            ],
            "Condition": {
            "StringEquals": {
                "aws:ResourceTag/kubernetes.io/cluster/${CLUSTER_NAME}": "owned",
                "aws:ResourceTag/topology.kubernetes.io/region": "${AWS_REGION}",
                "aws:RequestTag/kubernetes.io/cluster/${CLUSTER_NAME}": "owned",
                "aws:RequestTag/topology.kubernetes.io/region": "${AWS_REGION}"
            },
            "StringLike": {
                "aws:ResourceTag/karpenter.k8s.aws/ec2nodeclass": "*",
                "aws:RequestTag/karpenter.k8s.aws/ec2nodeclass": "*"
            }

```
aws:ResourceTag/kubernetes.io/cluster/${CLUSTER_NAME}": "owned",

this was use in old EKS versions and AWS Load Balancer Controller  as far as i can understand its not needed any more and not in use ( only need if AWS Load Balancer Controller old ves < 2.1 and eks 1.8 ) 
https://repost.aws/knowledge-center/eks-vpc-subnet-discovery
https://docs.aws.amazon.com/eks/latest/userguide/network_reqs.html

i think you need to change the policy  example is it will not work in the "StringEquals" 

Thansk

**Comment by jonathan-innis** [comment]
Can you explain what you mean? This policy is correct generally for the TagInstanceProfile actions. Did you mean to link a separate part of the policy that was specifically in relation to the subnet discovery -- since that's the doc that you linked?
