### ISSUE TITLE
IAM Policy in v1beta1 migration guide AWS_PARTITION template error

### ISSUE THREAD

**Issue by donovanrost** [aws/karpenter-provider-aws#5994]
### Description

When following the migration guide for v1beta1, users will use `envsubst` to populate values for `AWS_REGION`, `AWS_PARTITION`, etc. in the IAM policy
There exists a statement in that policy which doesn't have the correct substitution

```json
    {
      "Sid": "AllowInterruptionQueueActions",
      "Effect": "Allow",
      "Resource": "arn:aws:sqs:${AWS_REGION}:${AWS_ACCOUNT_ID}:${CLUSTER_NAME}",
      "Action": [
        "sqs:DeleteMessage",
        "sqs:GetQueueAttributes",
        "sqs:GetQueueUrl",
        "sqs:ReceiveMessage"
      ]
    },
``` 

should be

```json
    {
      "Sid": "AllowInterruptionQueueActions",
      "Effect": "Allow",
      "Resource": "arn:${AWS_PARTITION}:sqs:${AWS_REGION}:${AWS_ACCOUNT_ID}:${CLUSTER_NAME}",
      "Action": [
        "sqs:DeleteMessage",
        "sqs:GetQueueAttributes",
        "sqs:GetQueueUrl",
        "sqs:ReceiveMessage"
      ]
    },
``` 

To be in line with the rest of the document

**Comment by jigisha620** [comment]
@donovanrost Can you please link the doc that you are looking at where you see this?

**Comment by donovanrost** [comment]
Absolutely
https://karpenter.sh/v0.32/upgrading/v1beta1-migration/#iam-controller-permissions
Step 4.
 https://raw.githubusercontent.com/aws/karpenter-provider-aws/v0.32.9/website/content/en/preview/upgrading/v1beta1-controller-policy.json

**Comment by jigisha620** [comment]
Thanks for linking the doc. I see there's a problem. Do you mind opening PR for the fix?

**Comment by jonathan-innis** [comment]
This change was merged, so closing this issue since the fix is in now.
