### ISSUE TITLE
Would this repo accept Pulumi program for deploying Karpenter and/or EKS?

### ISSUE THREAD

**Issue by AaronFriel** [aws/karpenter-provider-aws#6000]
Hey folks, for one of our hackathon projects at Pulumi I've authored a "from zero to fully functioning" Kubernetes cluster blueprint, using EKS and Karpenter to host large language models.

I'd like to contribute some or all of this this back, and Karpenter seems like a reasonable place for it - if this is misplaced, please redirect me or reach out to me via email.

The Karpenter-specific portion of this code could be published as its own Pulumi component, or we could look at a larger collaboration to open source the entire project. The major parts are Pulumi projects, each individual programs written in TypeScript using Pulumi, that handle each of these aspects of deployment with optional or configurable sub-components. These are:

* `aws-vps`: root VPC with appropriate private and public subnets with routing, NAT gateways
* `eks-cluster`: a barebones EKS cluster deployed to the private subnet with sensible defaults including AWS Access Entries, KMS credentials, and updates the default storage class updated to `gp3`. No nodes or node group is provisioned.
* `eks-karpenter`: deploys Karpenter onto Fargate nodes to bootstrap the cluster
* `eks-l2`: updates and installs add-ons including CoreDNS, AWS Pod Identity, VPC CNI, EBS CSI, EFS CSI, CloudWatch observability, configures a wildcard certificate for applications on the cluster, and charts for the AWS Load Balancer controller, External DNS, and Cert-Manager

These are loosely coupled, so a user could bring their own VPC, or VPC + Cluster, or... and so on.

Additionally, this cluster:
* "Scales to zero" via Karpenter on Fargate
* Uses secure defaults, including:
  * AWS Access Entries by default
  * Bottlerocket as default AMI
  * Blocks instance/node metadata for pods, all controllers use IRSA or Pod Identity

I consider a cluster after `eks-l2` is deployed to be ready to serve production applications, as it provides all of the baseline user experience I'd expect from a platform team.

There are additional Pulumi projects I've authored to deploy Istio, MLOps frameworks like Kubeflow, and generative AI inference serving using the [vLLM project](https://github.com/vllm-project/vllm), but I suspect those are best contributed back to their respective projects.

**Comment by casey-robertson-paypal** [comment]
Upvote because as of now, the Getting Started doc does not work - fails on cluster creation - CNI/aws-node issues.

**Comment by jonathan-innis** [comment]
> I'd like to contribute some or all of this this back, and Karpenter seems like a reasonable place for it

We've generally been a little cautious of adding additional getting started mechanisms directly into the repo -- only because they can quickly get out of date. For example, we had onboarding Terraform as s getting started mechanism, but then we quickly diverged between the eksctl getting started guide and the Terraform one. There were constant bugs in that getting started guide -- to the point that it was almost useless as a getting started guide.

IMO, there are two paths that make sense so that we have a scalable approach to maintaining these other mechanisms of installing karpenter but also allow users to easily discover them: 1) Store them in another repo and have the karpenter README or docs link out to them or 2) Have a blogpost that is tightly scoped to running Karpenter with Pulumi so that it doesn't have to be actively maintained.

@AaronFriel Happy to hear any other thoughts if you have any around where the best place to store this can be that helps users but that also gets actively maintained.

**Comment by AaronFriel** [comment]
The current deployment guide requires a mixture of `eksctl`, CloudFormation, and Helm. The path dependency to that approach makes sense, but it does leave the user with a variety of different tools managing state - and some resources like the cluster itself unmanaged by IaC.

The Pulumi deployment uses the existing Helm chart (as a [`kubernetes.helm.sh/v3.Chart` resource](https://www.pulumi.com/registry/packages/kubernetes/api-docs/helm/v3/chart/)), which mainly leaves the CloudFormation resources - mostly IAM roles - as a source of drift. Given that, would it be more palatable to include Pulumi here?

**Comment by askulkarni2** [comment]
Hi @AaronFriel, have you seen https://github.com/aws-samples/karpenter-blueprints? Would it make sense for Pulumi to create a similar project?

**Comment by jonathan-innis** [comment]
> have you seen https://github.com/aws-samples/karpenter-blueprints? Would it make sense for Pulumi to create a similar project

I'm not seeing this as something that we should take up in this repo or in our public documentation specific to Karpenter (it's going to create too much sprawl). If this is something that we want to see in https://github.com/aws-samples/karpenter-blueprints, I think we should open an issue there. Closing this for now.

**Comment by chainlink** [comment]
@AaronFriel Would love to have a look at your blueprints! Are they pushed anywhere?
