### ISSUE TITLE
Problem upgrading 0.32 to 0.33.4

### ISSUE THREAD

**Issue by mk2134226** [aws/karpenter-provider-aws#6011]
### Description

I upgraded from 0.32 to 0.33.4 . one replica is running fine but other karpneter pod crashloops with
One replica always runs fine , problem with other replica, rollback to 0.32 also works fine . not sure whats the issue

panic: failed to setup manager: failed to determine if *v1.Lease is namespaced: failed to get restmapping: failed to get server groups: Get "https://172.20.0.1:443/api": dial tcp 172.20.0.1:443: i/o timeout

goroutine 1 [running]:
github.com/samber/lo.must({0x25cd020, 0xc0009f8120}, {0xc00089f760, 0x1, 0x1})
	github.com/samber/lo@v1.39.0/errors.go:51 +0x1c5
github.com/samber/lo.Must[...](...)
	github.com/samber/lo@v1.39.0/errors.go:65
sigs.k8s.io/karpenter/pkg/operator.NewOperator()
	sigs.k8s.io/karpenter@v0.33.4/pkg/operator/operator.go:160 +0x13b8
main.main()
	github.com/aws/karpenter/cmd/controller/main.go:33 +0x25

**Comment by jigisha620** [comment]
What is the namespace under which Karpenter is operating?

**Comment by mk2134226** [comment]
karpenter is in **karpenter** namespace and i want to keep in there not move in kube-system

**Comment by engedaam** [comment]
@mk2134226 Can you share the helm upgrade command that was used?

**Comment by jigisha620** [comment]
Would you also mind verifying if there was any modification to the roles and policies that are needed for Karpenter to work? Probably Karpenter Controller Policy?

**Comment by kaykhan** [comment]
@mk2134226 what was your solution?
