### ISSUE TITLE
Daemonset scheduling

### ISSUE THREAD

**Issue by RonPortnoy** [aws/karpenter-provider-aws#6015]
### Description

****What problem are you trying to solve?****
Have enough capacity for a pod that is scheduled on a new node with other daemon-sets. 
in case I have a pod that is requiring a 15vCPU, I will get a 16vCPU node, the problem is that my daemon set's in total could require 1.5 vCPU. 

This scenario creates a really bad behavior which I call a _"scheduling loop"_:
- scheduler will get a request of 15vCPU allocation
- karpenter will allocate me a 16vCPU node
- all daemon set's will be scheduled 
- the 15vCPU required workload could not be scheduled on that node. setting pod priority and evicting other pods is not an option.
- the new node will be terminated, the pod will continue to be in pending state, and karpenter will allocate me the same instance size.

the only way I can resolve this behavior is to ask in advance more cores on the dedicated workload to get a bigger instance size.

I would like to add a new annotation on the node-pool scheduling, which could be called "daemon-set-overhead". 
so that any new node's that are being scheduled from that node-pool will take into consideration the DS requests. 
for example:
- workload of 15 vCPU
- DS overhead of 1.5 vCPU
scheduler will be asked to get a node with at least 16.5 vCPU. 

**How important is this feature to you?**
This feature can help me avoid scenarios where specific workload is not scheduled due to this behavior, daemon-sets are taking a critical part in my infrastructure, by taking daemons into the scheduler calculations I can avoid having unnecessary request allocation and be at peace of mind that my workload will be scheduled properly 

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by jonathan-innis** [comment]
Karpenter should already calculate the DaemonSets that should be assigned to the node when the node spins up and add that to the pod requests for your applications. If you aren't seeing that behavior, it means there's potentially a bug with how Karpenter is doing the calculation. Could you provide a little more detail into the behavior that you are seeing with Karpenter and how that's different from what you are expecting?

**Comment by RonPortnoy** [comment]
Hi @jonathan-innis 
I am running karpenter 0.35 on EKS
I have an application that is requiring 15vCPU, so karpenter will schedule me a 16 vCPU machine, once the machine is scheduled an running, my daemon-sets will start to schedule before the application will be scheduled. the problem is that after the daemon-sets are ready it appears there in not enough room for my application to be scheduled because of the daemon-sets workload, after this is happening, the node is being terminated and new scheduling is happening with exactly the same node capacity.

**Comment by RonPortnoy** [comment]
The main workload is using this EC2NC and node pool

Ec2NodeClass:
```
Name:         arm64-specific-al2
Namespace:    
Labels:       <none>
Annotations:  karpenter.k8s.aws/ec2nodeclass-hash: XXXXXXXX
API Version:  karpenter.k8s.aws/v1beta1
Kind:         EC2NodeClass
Metadata:
  Creation Timestamp:  2024-03-13T11:01:13Z
  Finalizers:
    karpenter.k8s.aws/termination
  Generation:  1
  Managed Fields:
    API Version:  karpenter.k8s.aws/v1beta1
    Fields Type:  FieldsV1
    fieldsV1:
      f:spec:
        f:amiFamily:
        f:blockDeviceMappings:
        f:role:
        f:securityGroupSelectorTerms:
        f:subnetSelectorTerms:
    Manager:      XXXXXXXX
    Operation:    Apply
    Time:         2024-03-13T11:01:13Z
    API Version:  karpenter.k8s.aws/v1beta1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .:
          f:karpenter.k8s.aws/ec2nodeclass-hash:
        f:finalizers:
          .:
          v:"karpenter.k8s.aws/termination":
    Manager:      karpenter
    Operation:    Update
    Time:         2024-03-13T11:01:14Z
    API Version:  karpenter.k8s.aws/v1beta1
    Fields Type:  FieldsV1
    fieldsV1:
      f:status:
        .:
        f:amis:
        f:instanceProfile:
        f:securityGroups:
        f:subnets:
    Manager:         karpenter
    Operation:       Update
    Subresource:     status
    Time:            2024-04-18T06:15:27Z
  Resource Version:  570114648
  UID:               64ff56f1-1f4d-41c7-a879-c89ce49b6b76
Spec:
  Ami Family:  AL2
  Block Device Mappings:
    Device Name:  /dev/xvda
    Ebs:
      Encrypted:    true
      Volume Size:  50Gi
      Volume Type:  gp3
    Device Name:    /dev/xvdb
    Ebs:
      Encrypted:    true
      Volume Size:  10Gi
      Volume Type:  gp3
  Metadata Options:
    Http Endpoint:                enabled
    httpProtocolIPv6:             disabled
    Http Put Response Hop Limit:  2
    Http Tokens:                  required
  Role:                           XXXXXXXXXX
  Security Group Selector Terms:
    Tags:
      XXXXXXX:  XXXXXXX
  Subnet Selector Terms:
    Tags:
      XXXXXXX:  XXXXXXX
      XXXXXXX:  XXXXXXX
  Tags:
    XXXXXXX:  XXXXXXX
Status:
  Amis:
    Id:    ami-01af8560b504eb3db
    Name:  amazon-eks-arm64-node-1.28-v20240415
    Requirements:
      Key:       kubernetes.io/arch
      Operator:  In
      Values:
        arm64
      Key:       karpenter.k8s.aws/instance-gpu-count
      Operator:  DoesNotExist
      Key:       karpenter.k8s.aws/instance-accelerator-count
      Operator:  DoesNotExist
    Id:          ami-0f6bdc3ce0ee191e9
    Name:        amazon-eks-gpu-node-1.28-v20240415
    Requirements:
      Key:       kubernetes.io/arch
      Operator:  In
      Values:
        amd64
      Key:       karpenter.k8s.aws/instance-gpu-count
      Operator:  Exists
    Id:          ami-0f6bdc3ce0ee191e9
    Name:        amazon-eks-gpu-node-1.28-v20240415
    Requirements:
      Key:       kubernetes.io/arch
      Operator:  In
      Values:
        amd64
      Key:       karpenter.k8s.aws/instance-accelerator-count
      Operator:  Exists
    Id:          ami-01520c51b1b0e680b
    Name:        amazon-eks-node-1.28-v20240415
    Requirements:
      Key:       kubernetes.io/arch
      Operator:  In
      Values:
        amd64
      Key:           karpenter.k8s.aws/instance-gpu-count
      Operator:      DoesNotExist
      Key:           karpenter.k8s.aws/instance-accelerator-count
      Operator:      DoesNotExist
  Instance Profile:  XXXXXXXXXX
  Security Groups:
    Id:    XXXXXXXX
    Name:  XXXXXXXX
  Subnets:
    Id:    XXXXXXXX
    Zone:  us-east-1f
    Id:    XXXXXXXX
    Zone:  us-east-1d
    Id:    XXXXXXXX
    Zone:  us-east-1b
    Id:    XXXXXXXX
    Zone:  us-east-1c
Events:    <none>
```

node pool
```
Name:         arm64-specific-al2
Namespace:    
Labels:       <none>
Annotations:  karpenter.sh/nodepool-hash: 11885454340938391933
API Version:  karpenter.sh/v1beta1
Kind:         NodePool
Metadata:
  Creation Timestamp:  2024-03-13T11:01:13Z
  Generation:          1
  Managed Fields:
    API Version:  karpenter.sh/v1beta1
    Fields Type:  FieldsV1
    fieldsV1:
      f:spec:
        f:disruption:
          f:consolidationPolicy:
          f:expireAfter:
        f:limits:
          f:cpu:
          f:memory:
        f:template:
          f:spec:
            f:nodeClassRef:
              f:apiVersion:
              f:kind:
              f:name:
            f:requirements:
        f:weight:
    Operation:    Apply
    Time:         2024-03-13T11:01:13Z
    API Version:  karpenter.sh/v1beta1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .:
          f:karpenter.sh/nodepool-hash:
    Manager:      karpenter
    Operation:    Update
    Time:         2024-03-13T11:01:13Z
    API Version:  karpenter.sh/v1beta1
    Fields Type:  FieldsV1
    fieldsV1:
      f:status:
        .:
        f:resources:
          .:
          f:cpu:
          f:ephemeral-storage:
          f:memory:
          f:pods:
    Manager:         karpenter
    Operation:       Update
    Subresource:     status
    Time:            2024-04-18T06:16:17Z
  Resource Version:  570115420
  UID:               570b6186-f65f-4895-8b4d-2cb7845e7924
Spec:
  Disruption:
    Budgets:
      Nodes:               10%
    Consolidation Policy:  WhenUnderutilized
    Expire After:          720h
  Limits:
    Cpu:     10000
    Memory:  1000000Gi
  Template:
    Spec:
      Node Class Ref:
        API Version:  karpenter.k8s.aws/v1beta1
        Kind:         EC2NodeClass
        Name:         arm64-specific-al2
      Requirements:
        Key:       karpenter.k8s.aws/instance-size
        Operator:  NotIn
        Values:
          metal
        Key:       kubernetes.io/arch
        Operator:  In
        Values:
          amd64
          arm64
        Key:       topology.kubernetes.io/zone
        Operator:  In
        Values:
          us-east-1c
          us-east-1f
          us-east-1b
          us-east-1d
        Key:       type
        Operator:  NotIn
        Values:
          private
        Key:       type
        Operator:  In
        Values:
          public
        Key:       karpenter.sh/capacity-type
        Operator:  In
        Values:
          on-demand
          spot
        Key:       karpenter.k8s.aws/instance-cpu
        Operator:  Gt
        Values:
          4
  Weight:  50
Status:
  Resources:
    Cpu:                  2544
    Ephemeral - Storage:  2987260812Ki
    Memory:               7254630612Ki
    Pods:                 20028
Events:                   <none>

```

DaemonSet is being scheduled on each karpenter node, this is affinity: 
```
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: karpenter.sh/registered
                operator: In
                values:
                - "true"
```

this is the affinity for the main workload
```
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: karpenter.sh/capacity-type
                operator: In
                values:
                - spot
                - on-demand
              - key: kubernetes.io/arch
                operator: In
                values:
                - arm64
              - key: type
                operator: In
                values:
                - public
              - key: type
                operator: NotIn
                values:
                - private
```

**Comment by jonathan-innis** [comment]
Do you have Karpenter controller logs that you can share from these launches as well? These should give us some detail on how much Karpenter is calculating for the requests that the node needs and how much available space that Karpenter thinks that the node will have.

**Comment by jonathan-innis** [comment]
Also, looking at the DaemonSets, there is an open issue in the kubernetes-sigs/karpenter repo around specifying DaemonSets with `karpenter.sh/registered` or `karpenter.sh/initialized` in their affinity: https://github.com/kubernetes-sigs/karpenter/issues/919.

Basically, Karpenter doesn't realize that this label is going to be present on the node when it is going through scheduling, so that causes it to think that the DaemonSet will never schedule to nodes provisioned by that NodePool. When the node actually spins-up, that label obviously gets added so the pods do schedule, but this is going to create the continual spin behavior that you are seeing. 

You should be able to fix this issue by specifying `karpenter.sh/nodepool` instead of `karpenter.sh/registered` in the affinity.

**Comment by jonathan-innis** [comment]
I haven't seen any response on this one, but I think this should cover the problem that you are hitting. Feel free to add additional comments on this if you don't think that this should have been closed. Closing for now...
