### ISSUE TITLE
Getting started steps do not result in a working cluster

### ISSUE THREAD

**Issue by casey-robertson-paypal** [aws/karpenter-provider-aws#6019]
### Description

**Observed Behavior**:

Followed the steps here: https://karpenter.sh/docs/getting-started/getting-started-with-karpenter/

The `eksctl` command in step 3 fails.  The `aws-node` daemonset is not working - failing health checks and never starts:

```
 Warning  Unhealthy  14m                   kubelet            Readiness probe failed: {"level":"info","ts":"2024-04-10T22:30:12.786Z","caller":"/root/sdk/go1.20.8/src/runt │
│ ime/proc.go:250","msg":"timeout: failed to connect service \":50051\" within 5s"}                                                                                            │
│   Normal   Killing    13m                   kubelet            Container aws-node failed liveness probe, will be restarted                                                   │
│   Warning  Unhealthy  5m18s (x94 over 14m)  kubelet            (combined from similar events): Readiness probe failed: {"level":"info","ts":"2024-04-10T22:39:02.777Z","call │
│ er":"/root/sdk/go1.20.8/src/runtime/proc.go:250","msg":"timeout: failed to connect service \":50051\" within 5s"}                                                            │
│   Warning  BackOff    16s (x17 over 4m48s)  kubelet            Back-off restarting failed container aws-node in pod aws-node-smbf4_kube-system(5a0933c0-939f-43e7-8e8c-c6175 │
│ 7f96e85)
```

**Expected Behavior**:

Cluster creation completes successfully.  I have not modified any of the inputs or the config - copying verbatim from the getting started steps.  

**Reproduction Steps** (Please include YAML):

Use the steps in the Getting Started doc

**Versions**:
- Chart Version:
- Kubernetes Version (`kubectl version`): Tried 1.29 and 1.28 as inputs

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by jigisha620** [comment]
Are you setting up your cluster with managed nodeGroups or fargate? Can you validate the initial setup that was done using cloudformation? Are all the roles and policies properly configured?

**Comment by jonathan-innis** [comment]
Looping back around to this one. @casey-robertson-paypal I don't see the same failures that you are seeing. Are you able to consistently repro this issue? If so, can you check the IAM permissions like @jigisha620 called out?
