### ISSUE TITLE
Add the possibility to use "do-not-disrupt" on namespace level

### ISSUE THREAD

**Issue by dschunack** [aws/karpenter-provider-aws#6028]
### Description

**What problem are you trying to solve?**
We have hunderts of Jenkins Masters and Clients running in dedicated namespaces and it's hard to add the "do-not-disrupt" annotation on all the PODs for Master, Clients and Schedules Jobs.
The possibility to set it on namespace level would help a lot for tools they have only a single POD like Jenkins.

**How important is this feature to you?**
It's important for us to reduce the overhead of manage the annotation for all the Deployments, STS, Jobs and PODs.
With this feature would it be very simple.

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by Bourne-ID-Work** [comment]
To keep consistency, I would recommend this being do-not-disrupt opposed to do-not-disturb.

**Comment by dschunack** [comment]
Typo, now is it correct 😄

**Comment by jonathan-innis** [comment]
> The possibility to set it on namespace level would help a lot for tools they have only a single POD like Jenkins

Agree this might be useful. Can you open this issue on the [`kubernetes-sigs/karpenter`](https://github.com/kubernetes-sigs/karpenter/issues) repo? This is generally applicable to the Karpenter framework rather than AWS-specific.

**Comment by dschunack** [comment]
Done

**Comment by jonathan-innis** [comment]
Thanks, closing this in favor of https://github.com/kubernetes-sigs/karpenter/issues/1189 then
