### ISSUE TITLE
Is Karpenter Controller support running on AL2023 ARM64?

### ISSUE THREAD

**Issue by guitarrapc** [aws/karpenter-provider-aws#6032]
### Description

**Observed Behavior**:

When running Karpenter 0.35.4 on an AL2023 ARM64 EC2 instance, I received several error messages as follows:

* no nodepools found
* skipping, unable to resolve instance types, describing subnets [{"Name":"tag:karpenter.sh/discovery","Values":["CLUSTER_NAME"]}], RequestCanceled: request context canceled caused by: context canceled
* listing nodepools, Timeout: failed waiting for *v1beta1.NodePool Informer to sync
* etreiving on-demand pricing data, RequestCanceled: request context canceled caused by: context canceled; RequestCanceled: request context canceled caused by: context canceled; retrieving spot pricing data, RequestCanceled: request context canceled caused by: context canceled
* listing cloudprovider machines, listing instances, describing ec2 instances, RequestCanceled: request context canceled caused by: context canceled
* listing instances, describing ec2 instances, RequestCanceled: request context canceled caused by: context canceled
* error received after stop sequence was engaged

**Expected Behavior**:

No error messages happen.

**Reproduction Steps** (Please include YAML):

Create EKS cluster with AL2023 ARM64 NodeGroup, and install karpenter as Getting Started notes:

ref: https://karpenter.sh/docs/getting-started/getting-started-with-karpenter/

1. Create EKS Cluster 1.29
2. Create Managed NodeGroup with AL2023 ARM64 `AL2023_ARM_64_STANDARD`.
3. Deploy Karpenter with helm 0.35.4

```
export KARPENTER_VERSION=0.35.4
helm upgrade --install karpenter oci://public.ecr.aws/karpenter/karpenter --version "${KARPENTER_VERSION}" --namespace "karpenter" --create-namespace \
  --set "settings.clusterName=${CLUSTER_NAME}" \
  --set "settings.interruptionQueue=${CLUSTER_NAME}"
  --set "serviceAccount.annotations."eks\.amazonaws\.com/role-arn"=arn:aws:iam::123456789012:role/KarpenterControllerRoleName"
  --wait
```

4. Deploy NodePool with EC2NodeClass. You will find errors.

**Versions**:
- Chart Version: 0.35.4
- Kubernetes Version (`kubectl version`): 1.29.0

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by jigisha620** [comment]
Have you tried to reproduce this issue with some other `amiFamily` other than AL2023? Do you see similar errors?

**Comment by guitarrapc** [comment]
I've tried `AL2023 AMD64` and there are no issue with this `amifamily`.

**Comment by jonathan-innis** [comment]
This looks like an issue with controller startup if you are seeing context canceled as soon as you are installing the controller. I'm going to set this as a question for the time being since this just looks like a liveness/readiness probe issue.

**Comment by guitarrapc** [comment]
Is there any workaround for an issue? None of Karpenter settings are changed since AMD64 node, but just changed to ARM64 node. If an liveness/readiness probe issue, then what should I do?

**Comment by jonathan-innis** [comment]
I tried this myself and didn't see any errors on the ARM variant. Is it possible there is some networking issue with one of the nodes that was launched in the NodeGroup that's not allowing it to connect to the apiserver correctly? Have you tried refreshing the node? Does this occur regardless of the node that Karpenter is running on?

**Comment by guitarrapc** [comment]
@jonathan-innis Thank you for clarify at your side. I've retry with fresh EKS Cluster w/0.36.0 and confirm Karpenter Controller && nodepool working without issue.

```
$ kubectl get po -n karpenter
NAME                        READY   STATUS    RESTARTS   AGE
karpenter-54dc57c5b-ngjxw   1/1     Running   0          25s
karpenter-54dc57c5b-wtdvf   1/1     Running   0          25s

$ k get po -n default -w
NAME                      READY   STATUS    RESTARTS   AGE
inflate-b5f4c8685-4jqjz   0/1     Pending   0          4s
inflate-b5f4c8685-qmmvn   0/1     Pending   0          4s
inflate-b5f4c8685-4jqjz   0/1     Pending   0          36s
inflate-b5f4c8685-qmmvn   0/1     Pending   0          36s
inflate-b5f4c8685-4jqjz   0/1     ContainerCreating   0          36s
inflate-b5f4c8685-qmmvn   0/1     ContainerCreating   0          36s
inflate-b5f4c8685-4jqjz   1/1     Running             0          40s
inflate-b5f4c8685-qmmvn   1/1     Running             0          40s

$ kubectl get no -l kubernetes.io/arch=arm64
NAME                                              STATUS   ROLES    AGE     VERSION
ip-10-1-0-10.ap-northeast-1.compute.internal      Ready    <none>   7m55s   v1.29.0-eks-5e0fdde # arm64 nodegroup
ip-10-1-0-94.ap-northeast-1.compute.internal      Ready    <none>   102m    v1.29.0-eks-5e0fdde # arm64 nodegroup
ip-10-100-93-60.ap-northeast-1.compute.internal   Ready    <none>   3m18s   v1.29.0-eks-5e0fdde # arm64 nodepool
```

Thank you again.
