### ISSUE TITLE
Reconciler error: getting drift, calculating ami drift, getting amis, describing images, InvalidParameterValue: The NextToken is invalid

### ISSUE THREAD

**Issue by rtomadpg** [aws/karpenter-provider-aws#6061]
### Description

**Observed Behavior**:

Hi team, we are running Karpenter 0.35.4 on multiple EKS 1.27 clusters and notice unusual errors. Here is a (slightly redacted) sample:

```json
{
  "level": "ERROR",
  "time": "2024-04-18T18:54:02.649Z",
  "logger": "controller",
  "message": "Reconciler error",
  "commit": "17dd42b",
  "controller": "nodeclaim.disruption",
  "controllerGroup": "karpenter.sh",
  "controllerKind": "NodeClaim",
  "NodeClaim": {
    "name": "foo-tsfms"
  },
  "namespace": "",
  "name": "foo-tsfms",
  "reconcileID": "9f7...126",
  "error": "getting drift, calculating ami drift, getting amis, describing images, InvalidParameterValue: The NextToken is invalid.\n\tstatus code: 400, request id: 4ca...8d3"
}
```

The frequency is very low (I've captured 4 on 2 clusters in 48h) and so far we have not observed any functional impact.

Also, I can't remember seeing them running 0.33.x. 

My main reason for registering a bug is to add visibility and let others know it's a known issue.

**Expected Behavior**:

No errors.

**Reproduction Steps** (Please include YAML):

Unknown, sorry.

But here is the referenced nodeclaim spec (redacted):

```yaml
apiVersion: karpenter.sh/v1beta1
kind: NodeClaim
metadata:
  annotations:
    karpenter.k8s.aws/ec2nodeclass-hash: "827...091"
    karpenter.k8s.aws/ec2nodeclass-hash-version: v1
    karpenter.k8s.aws/tagged: "true"
    karpenter.sh/nodepool-hash: "6813...305"
    karpenter.sh/nodepool-hash-version: v1
    meta.helm.sh/release-name: karpenter-config
    meta.helm.sh/release-namespace: karpenter
  creationTimestamp: "2024-04-18T12:47:49Z"
  finalizers:
  - karpenter.sh/termination
  generateName: foo-
  generation: 1
  labels:
    karpenter.k8s.aws/instance-category: c
    karpenter.k8s.aws/instance-cpu: "16"
    karpenter.k8s.aws/instance-encryption-in-transit-supported: "true"
    karpenter.k8s.aws/instance-family: c6a
    karpenter.k8s.aws/instance-generation: "6"
    karpenter.k8s.aws/instance-hypervisor: nitro
    karpenter.k8s.aws/instance-memory: "32768"
    karpenter.k8s.aws/instance-network-bandwidth: "6250"
    karpenter.k8s.aws/instance-size: 4xlarge
    karpenter.sh/capacity-type: on-demand
    karpenter.sh/nodepool: foo
    kubernetes.io/arch: amd64
    kubernetes.io/os: linux
    node.kubernetes.io/instance-type: c6a.4xlarge
    topology.kubernetes.io/region: eu-west-1
    topology.kubernetes.io/zone: eu-west-1c
  name: foo-tsfms
  ownerReferences:
  - apiVersion: karpenter.sh/v1beta1
    blockOwnerDeletion: true
    kind: NodePool
    name: foo
    uid: 918...d9e
  resourceVersion: "406...753"
  uid: 304...301
spec:
  nodeClassRef:
    apiVersion: karpenter.k8s.aws/v1beta1
    kind: EC2NodeClass
    name: foo
  requirements:
  - key: karpenter.sh/nodepool
    operator: In
    values:
    - foo
  - key: karpenter.k8s.aws/instance-hypervisor
    operator: In
    values:
    - nitro
  - key: kubernetes.io/arch
    operator: In
    values:
    - amd64
  - key: karpenter.k8s.aws/instance-generation
    operator: Gt
    values:
    - "5"
  - key: karpenter.sh/capacity-type
    operator: In
    values:
    - on-demand
  - key: kubernetes.io/os
    operator: In
    values:
    - linux
  - key: karpenter.k8s.aws/instance-cpu
    operator: In
    values:
    - "16"
    - "32"
  - key: karpenter.k8s.aws/instance-family
    operator: NotIn
    values:
    - m7i-flex
  - key: node.kubernetes.io/instance-type
    operator: In
    values:
    - c6a.4xlarge
    - c6a.8xlarge
    - c6i.4xlarge
    - c6i.8xlarge
    - c6id.4xlarge
    - c6id.8xlarge
    - c6in.4xlarge
    - c6in.8xlarge
    - c7a.4xlarge
    - c7a.8xlarge
    - c7i.4xlarge
    - c7i.8xlarge
    - m6a.4xlarge
    - m6a.8xlarge
    - m6i.4xlarge
    - m6i.8xlarge
    - m6id.4xlarge
    - m6id.8xlarge
    - m6idn.4xlarge
    - m6idn.8xlarge
    - m6in.4xlarge
    - m6in.8xlarge
    - m7a.4xlarge
    - m7a.8xlarge
    - m7i.4xlarge
    - m7i.8xlarge
  - key: karpenter.k8s.aws/instance-category
    operator: In
    values:
    - c
    - m
  resources:
    requests:
      cpu: 7880m
      memory: 20725Mi
      pods: "8"
  taints:
  - effect: NoSchedule
    key: dedicated
    value: foo
status:
  allocatable:
    cpu: 15890m
    ephemeral-storage: 44Gi
    memory: 27381Mi
    pods: "234"
    vpc.amazonaws.com/pod-eni: "54"
  capacity:
    cpu: "16"
    ephemeral-storage: 50Gi
    memory: 30310Mi
    pods: "234"
    vpc.amazonaws.com/pod-eni: "54"
  conditions:
  - lastTransitionTime: "2024-04-18T12:48:41Z"
    status: "True"
    type: Initialized
  - lastTransitionTime: "2024-04-18T12:47:52Z"
    status: "True"
    type: Launched
  - lastTransitionTime: "2024-04-18T12:48:41Z"
    status: "True"
    type: Ready
  - lastTransitionTime: "2024-04-18T12:48:24Z"
    status: "True"
    type: Registered
  imageID: ami-0dc9bb80fa2a1bb72
  nodeName: ip-AA-BB-CC-DD.eu-west-1.compute.internal
  providerID: aws:///eu-earth-1a/i-00c...f84
```

**Versions**:
- Karpenter Version:  0.35.4
- Chart Version: 0.35.4
- Kubernetes Version (`kubectl version`): v1.27.11-eks-b9c9ed7

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by jonathan-innis** [comment]
Can you share the EC2NodeClass that you are using here that's generating this error?

**Comment by jonathan-innis** [comment]
Also, the requestID for the request would be helpful here as well. We are using the `DescribeImagesPagesWithContext` function here which should handle auto-iteration through the pages -- if there's not an issue with the request itself (which we should be able to see once we have a request id) then this may be a specific bug with the aws-sdk-go package.

**Comment by rtomadpg** [comment]
Hi @jonathan-innis - thanks for having a look at this. Please find the EC2NodeClass (slighty redacted) below.

Regarding the request IDs: I am requesting an internal team to do a cloudwatch search. I will share once found.


```yaml
apiVersion: karpenter.k8s.aws/v1beta1
kind: EC2NodeClass
metadata:
  annotations:
    karpenter.k8s.aws/ec2nodeclass-hash: "827...091"
    karpenter.k8s.aws/ec2nodeclass-hash-version: v1
    meta.helm.sh/release-name: karpenter-config
    meta.helm.sh/release-namespace: karpenter
  creationTimestamp: "2024-04-10T08:20:47Z"
  finalizers:
  - karpenter.k8s.aws/termination
  generation: 2
  labels:
    app.kubernetes.io/managed-by: Helm
  name: foo
  resourceVersion: "408555514"
  uid: 8da...93a
spec:
  amiFamily: AL2
  amiSelectorTerms:
  - name: amazon-eks-node-1.27-v20240329
  - name: amazon-eks-node-1.27-v20240409
  blockDeviceMappings:
  - deviceName: /dev/xvda
    ebs:
      encrypted: true
      volumeSize: 50Gi
      volumeType: gp3
  detailedMonitoring: true
  metadataOptions:
    httpEndpoint: enabled
    httpProtocolIPv6: disabled
    httpPutResponseHopLimit: 2
    httpTokens: required
  role: apps-b-karpenter-node
  securityGroupSelectorTerms:
  - tags:
      karpenter.sh/discovery/app...b: '*'
  subnetSelectorTerms:
  - tags:
      karpenter.sh/discovery/app...b: '*'
  tags:
    ...
status:
  amis:
  - id: ami-0dc9bb80fa2a1bb72
    name: amazon-eks-node-1.27-v20240409
    requirements:
    - key: kubernetes.io/arch
      operator: In
      values:
      - amd64
  instanceProfile: app...779
  securityGroups:
  - id: sg-06d...b91
    name: app...004
  - id: sg-0ab...736
    name: app...002
  - id: sg-0ee...933
    name: eks...ess
  subnets:
  - id: subnet-016...ff7
    zone: eu-west-1a
  - id: subnet-02c...26b
    zone: eu-west-1b
  - id: subnet-0d1...366
    zone: eu-west-1c
```

**Comment by rtomadpg** [comment]
Here is a (redacted) event by RequestID. Full available via PM.

What I can deduce: Karpenter is executing a DescribeImages API call for a specific EKS AMI by name, including a NextToken, which seems to be invalid. Caching maybe?

> "1.09","{type=AssumedRole, principalid=AROA47N...X6X:1713391171618183260, arn=arn:aws:sts::892...759:assumed-role/app...ter/1713391171618183260, accountid=892...759, invokedby=null, accesskeyid=ASIA47N...MN4, username=null, sessioncontext={attributes={mfaauthenticated=false, creationdate=2024-04-17T21:59:31Z}, sessionissuer={type=Role, principalid=AROA47N...X6X, arn=arn:aws:iam::892...759:role/apps...ter, accountid=892...759, username=app...ter}}}","2024-04-17T22:46:29Z","ec2.amazonaws.com","DescribeImages","eu-west-1","34.x.x.x","aws-sdk-go/1.50.25 (go1.21.8; linux; amd64) karpenter.sh-0.35.4","Client.InvalidParameterValue","The NextToken is invalid.","{""nextToken"":""eyJ...SJ9"",""maxResults"":500,""executableBySet"":{},""imagesSet"":{},""ownersSet"":{""items"":[{""owner"":""self""},{""owner"":""amazon""}]},""filterSet"":{""items"":[{""name"":""name"",""valueSet"":{""items"":[{""value"":""amazon-eks-node-1.27-v20240329""}]}}]}}","null",,"548...01d","bbd...949",,"AwsApiCall",,"true","892...759",,,,"892...759","eu-west-1","2024","04","17"

**Comment by rtomadpg** [comment]
Maybe relevant, but in Cloudtrail we often see `Client.RequestLimitExceeded` errors for `ec2:DescribeImages` (requests by Karpenter. I am not able to correlate these errors to the `Client.InvalidParameterValue`, but maybe it's the indirect result. 

Note Karpenter also gets same error on these EC2 API calls too:
> AssignPrivateIpAddresses
AttachNetworkInterface
CreateNetworkInterface
CreateTags
ModifyNetworkInterfaceAttribute
RunInstances

I am assuming the AWS SDK used does catch these errors and retries (with backoff?).

Regardless we've created a support case to get the EC2 API limit increased.

**Comment by jonathan-innis** [comment]
> What I can deduce: Karpenter is executing a DescribeImages API call for a specific EKS AMI by name, including a NextToken, which seems to be invalid. Caching maybe

It's hard to tell what is going on with this issue without having the _exact_ requestID that is being used here so we can look back at logs and understand why the NextToken didn't match-up with what the DescribeImages API expected.

**Comment by rtomadpg** [comment]
Let's close this issue, since I have not seen it since.
