### ISSUE TITLE
allow more than a single cluster to get tagged Key=karpenter.sh/discovery

### ISSUE THREAD

**Issue by ns-rkusumoto** [aws/karpenter-provider-aws#6120]
### Description

**What problem are you trying to solve?**

Allow more than a single cluster to get tagged Key=karpenter.sh/discovery so subnets can share/coexist with other EKS clusters.

**How important is this feature to you?**

Nice to have when I'm attempting to stand up 2 (or more) EKS clusters sharing subnets.

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by engedaam** [comment]
Why can't you tag the subnets from other cluster currently with the `karpenter.sh/discovery`? Also, what the use case you are trying to achieve here?

**Comment by ns-rkusumoto** [comment]
I'm doing a blue/green cluster migration on the same subnets.  I believe the current tagging only wants a single cluster name in that key.  Either I use different subnets for multiple clusters or setup with cluster autoscaler first then migrate them to karpenter later when the old cluster is turned down.

**Comment by engedaam** [comment]
Karpenter does not need you to add the specific tag `karpenter.sh/discovery`. You can tag your subnets with any tags and pass those tags into the subnetSelectorTerms. Karpenter will discover those subnets based on tags that in the selector. Does this not meet your use case? Apologies for my question, just trying to better understand your use-case.

**Comment by ns-rkusumoto** [comment]
yes.  thanks!

**Comment by ns-rkusumoto** [comment]
just makes getting karpenter as IaC difficult if I have to pick different keys when adding it to various clusters.  I'll live
