### ISSUE TITLE
question: about instance selection

### ISSUE THREAD

**Issue by jwcesign** [aws/karpenter-provider-aws#6171]
Karpenter version: 0.36.0

I have a cluster, and use spot instances.
After Karpenter installed, it create `t3a.medium` spot instances, with 2u 4g. But I have a question:

The difference spot price between t3a.medium and t4g.medium:
![img_v3_02an_e1eb93bf-881e-4ce7-9611-77b0f41658eg](https://github.com/aws/karpenter-provider-aws/assets/19745536/25757bc5-2375-484c-8916-3e56e4d3afb4)
![img_v3_02an_83adc4e1-7346-43a2-827f-8cad292b921g](https://github.com/aws/karpenter-provider-aws/assets/19745536/07509c80-6fe1-4321-92c6-b74f76cb45da)

the interrupt ratio  between t3a.medium and t4g.medium:
![image](https://github.com/aws/karpenter-provider-aws/assets/19745536/7e3bf665-f37b-4406-859d-fb590c0acca3)
![image](https://github.com/aws/karpenter-provider-aws/assets/19745536/2fad9539-a63d-4797-a338-659536349811)

And t4g.medium is also 2u/4g, but it's cheaper and available, why not select it?

**Comment by jmdeal** [comment]
The `g` in `t4g` is for graviton, all of which are arm instance types. Right now you have an architecture requirement for `amd64` on your nodepool, filtering out all arm instance types. I expect if you remove that requirement you would see `t4g` instance types selected (or some other cheaper arm instance).
