### ISSUE TITLE
Question: customize and install karpenter to private eks cluster with no internet connectivity. Kubectl and helm running on instance with no internet connectivity

### ISSUE THREAD

**Issue by sri171208** [aws/karpenter-provider-aws#6199]
### Description

I have requirement to have private EKS cluster setup and add Karpenter to private EKS cluster with no internet connectivity.

I spin up a cloud9 instance in different VPC with no public IP, VPC and subnets are connected to internet where cloudp9 is spinned up (or) instance is running. I just cut a AMI to install kubectl and helm and ran below command to install karpenter from cloud9 instance to get karpenter.yaml 
KARPENTER_VERSION=0.36.1

helm template karpenter oci://public.ecr.aws/karpenter/karpenter --version ${KARPENTER_VERSION} --namespace karpenter \
    --set settings.aws.defaultInstanceProfile=KarpenterNodeInstanceProfile-${CLUSTER_NAME} \
    --set settings.aws.clusterName=${CLUSTER_NAME} \
    --set serviceAccount.annotations."eks\.amazonaws\.com/role-arn"="arn:${AWS_PARTITION}:iam::${AWS_ACCOUNT_ID}:role/KarpenterControllerRole-${CLUSTER_NAME}" \
    --set controller.resources.requests.cpu=1 \
    --set controller.resources.requests.memory=1Gi \
    --set controller.resources.limits.cpu=1 \
    --set controller.resources.limits.memory=1Gi > karpenter.yaml

Also downloaded and uploaded docker image for public ecr repo to private ecr register

docker pull public.ecr.aws/karpenter/controller:${KARPENTER_VERSION}

docker tag image_id account_number.dkr.ecr.us-east-1.amaonaws.com/karpenter/controller:0.36.1

aws ecr get-login-password

docker push  account_number.dkr.ecr.us-east-1.amaonaws.com/karpenter/controller:0.36.1

updated karpneter/emplaest/deployment.yaml to use local ecr repository

image: account_number.dkr.ecr.us-east-1.amaonaws.com/karpenter/controller:0.36.1

**Note:** on deployment machine which is in same subnets as my private eks cluster, spin up new vm and  executing below command.

kubectl apply -f karpenter.yaml

pods are comming up but failing with status CrashLoopBackOff 
i tailed logs seeing below message
panic:validating options, missing field, cluster-name

**Comment by jmdeal** [comment]
It looks like some of the helm values you're setting are outdated. `settings.aws.defaultInstanceProfile` was dropped at v0.33.0 and `settings.aws.clusterName` was replaced by `settings.clusterName` at the same version. Both of these changes were made as part of the [v1beta1 migration](https://karpenter.sh/v0.32/upgrading/v1beta1-migration/). If you update the cluster name flag does that fix your issue?

**Comment by sri171208** [comment]
@jmdeal I missed the cluster endpoint config and adjusted liveness probe setting on controller deployment worked for me. Thank you

**Comment by Apurv11** [comment]
@sri171208 i have run into a similar issue. pods are in crashloopbackoff with the below error
`exec /ko-app/controller: exec format error`

I am also using this to generate the manifests and then running them. 
what changes have you don to the liveness probes?

**Comment by jmdeal** [comment]
Do you mind opening a separate issue? The Karpenter controller image is multi-architecture, but it looks like you're runnining into an architecture mismatch issues (i.e. arm image on amd64 instance).

**Comment by Apurv11** [comment]
thanks, this is solved. I was assuming that linux/x86 was the default architecture platform image. solved this by using --platform option while pulling the image
