### ISSUE TITLE
Currently i am in EKS- 1.28 version and trying to upgrade my cluster to 1.29 with the karpenter supported version 0.34. I am facing issue in karpenter upgrade from 0.32.0 to 0.34 , please do let me know 0.33 karpenter version is supported for 1.28 EKS cluster 

### ISSUE THREAD

**Issue by AnithaRaaj** [aws/karpenter-provider-aws#6245]
### Description

**Observed Behavior**:

**Expected Behavior**:

**Reproduction Steps** (Please include YAML):

**Versions**:
- Chart Version:
- Kubernetes Version (`kubectl version`):

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by jmdeal** [comment]
Any version of Karpenter >= v0.31.0 is compatible with 1.28. You can find the version compatibility matrix [here](https://karpenter.sh/docs/upgrading/compatibility/). v0.34.0 is required for full 1.29 compatibility since it introduces support for native sidecar containers.

**Comment by AnithaRaaj** [comment]
I am trying to upgrade my cluster to 1.29. however, when i try to upgrade my karpenter to 0.34, i am receiving the error  whereas POD going to restart state and shows message as Permission issue to list & watch the resource "ConfigMap" As  i am aware in this 0.34 version configmap is removed.  Please help me to fix this issue.

**Comment by VMaharshi** [comment]
> Any version of Karpenter >= v0.31.0 is compatible with 1.28. You can find the version compatibility matrix [here](https://karpenter.sh/docs/upgrading/compatibility/). v0.34.0 is required for full 1.29 compatibility since it introduces support for native sidecar containers.

Karpenter now adds a default podSecurityContext that configures the fsgroup: 65536 of volumes in the pod. If you are using sidecar containers, you should review if this configuration is compatible for them. You can disable this default podSecurityContext through helm by performing --set podSecurityContext=null when installing/upgrading the chart.
