### ISSUE TITLE
karpenter_pods_startup_time_seconds goes nuts when node reboots

### ISSUE THREAD

**Issue by raonitimo** [aws/karpenter-provider-aws#6247]
### Description

**Observed Behavior**:
An EC2 instance was rebooted by AWS and Karpenter reported a pod (cilium-agent) startup time to be extremely high (multiple days).

**Expected Behavior**:
Karpenter to not report metrics on pods that were previously ready? Actually, not quite sure what would be the best outcome.

**Reproduction Steps** (Please include YAML):
Create a node, add pods to it, reboot the node - pods previously ready==true flip to ready==false then back to ready==true.

**Versions**:
- Chart Version: 
- Kubernetes Version (`kubectl version`): 1.27

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by engedaam** [comment]
Can you add a little more detail here. Here are a few questions:
- Why was the EC2 instance rebooted?
- Was the pod re-created?
- Why are you expecting Karpenter to stop reporting metrics for pods with extremely high startup time?
- Are you setting up cilium-agent using the recommended method? https://karpenter.sh/docs/concepts/nodepools/#cilium-startup-taint

**Comment by raonitimo** [comment]
Hi @engedaam, thanks for looking into this issue.

> Can you add a little more detail here. Here are a few questions:

Yes, sure.

> * Why was the EC2 instance rebooted?

AWS claims the instance was rebooted due to an underlying hardware problem.

> * Was the pod re-created?

I don't think so, no. The node came back up with this same pod that became ready again.

> * Why are you expecting Karpenter to stop reporting metrics for pods with extremely high startup time?

I'm fine with Karpenter reporting metrics for pods with extremely high startup time. The issue here is the pod didn't actually take that long to startup. It "started up" twice. And the second time the pod became "ready", karpenter reported the time difference to the first time the pod was started - which was several hours ago.

> * Are you setting up cilium-agent using the recommended method? [karpenter.sh/docs/concepts/nodepools](https://karpenter.sh/docs/concepts/nodepools/#cilium-startup-taint)

Yes.

**Comment by raonitimo** [comment]
@jmdeal @engedaam do you need more info?
