### ISSUE TITLE
Karpenter is not able to spin up the node with instance type r7i.4xlarge

### ISSUE THREAD

**Issue by nikita-ceq** [aws/karpenter-provider-aws#6266]
### Description

Hello Team

We have provisioned an eks cluster with nodegroup r7i.4xlarge and using karpenter for autoscaling 
But when a load increases karpenter is not able to spin up the nodes but it is able to spin the nodes with other instance type like M series, C series T series

Please find attached Nodepool.yaml
apiVersion: karpenter.sh/v1beta1
kind: NodePool
metadata:
  name: default
spec:
  template:
    spec:
      requirements:
        - key: node.kubernetes.io/instance-type
          operator: In
          values: ["r7i.4xlarge"]
        # - key: karpenter.k8s.aws/instance-category
        #   operator: In
        #   values: ["c"]
        # - key: karpenter.k8s.aws/instance-generation
        #   operator: In
        #   values: ["7i"]
        # - key: karpenter.k8s.aws/instance-size
        #   operator: In
        #   values: ["4xlarge"]
        - key: karpenter.sh/capacity-type
          operator: In
          values: ["on-demand"]
      nodeClassRef:
        name: default

Looking forward to hear back from you soon
Thanks

**Comment by jmdeal** [comment]
What Karpenter version are you running? Just ran a quick test and was able to launch `r7i.4xlarge` instances in us-west-2 on Karpenter 0.36.2. Do you have any logs you can share?
