### ISSUE TITLE
Seems the oci images for helm charts are not published anymore

### ISSUE THREAD

**Issue by marcofranssen** [aws/karpenter-provider-aws#6281]
### Description

**Observed Behavior**:

In the chart documentation it show v0.36.0 is released. In the tags I notice even more recent releases. However on the OCI registry those releases are not available.

```shell
$ crane ls public.ecr.aws/karpenter/karpenter | grep 'v0\.37'
$ crane ls public.ecr.aws/karpenter/karpenter | grep 'v0\.36'
$ crane ls public.ecr.aws/karpenter/karpenter | grep 'v0\.35'
$ crane ls public.ecr.aws/karpenter/karpenter | grep 'v0\.34'
v0.34.1
v0.34.5
v0.34.2
v0.34.3
v0.34.0
v0.34.6
```

**Expected Behavior**:

The Helm charts are available for all the released tags.

**Comment by rknightion** [comment]
The tags dropped the v a little while ago (look at https://gallery.ecr.aws/karpenter/karpenter and head to tags). Pulling `public.ecr.aws/karpenter/karpenter:0.37.0 ` should work
