### ISSUE TITLE
NodeClaim Failing

### ISSUE THREAD

**Issue by rajeshj-prismforce** [aws/karpenter-provider-aws#6284]
### Description

**Observed Behavior**:
Noticed nodeClaim constantly fails with below error 
{"level":"ERROR","time":"2024-05-29T14:10:55.991Z","logger":"controller","message":"Reconciler error","commit":"490ef94","controller":"nodeclaim.lifecycle","controllerGroup":"karpenter.sh","controllerKind":"NodeClaim","NodeClaim":{"name":"default-pljc5"},"namespace":"","name":"default-pljc5","reconcileID":"8682f03a-e24c-46c4-b0bb-f637d36af35e","error":"launching nodeclaim, resolving ec2nodeclass, object is awaiting reconciliation"}
**Expected Behavior**:
Nodes should get provisioned after it observes pods are in pending state.
**Reproduction Steps** (Please include YAML):
resource "kubernetes_manifest" "karpenter_node_class" {
  depends_on = [
    helm_release.karpenter
  ]
  count     = var.create_karpenter_node_group ? 1 : 0
  manifest = yamldecode(<<-YAML
apiVersion: karpenter.k8s.aws/v1beta1
kind: EC2NodeClass
metadata:
  name: default
spec:
  amiFamily: AL2
  role: "${aws_iam_role.worker_node[count.index].name}"
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: "${var.cluster_name}"
  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: "${var.cluster_name}"
  tags:
    karpenter.sh/discovery: "${var.cluster_name}"
    BusinessUnit: "Shared"
    Environment: "PFPT"
  YAML
  )
}
resource "kubernetes_manifest" "karpenter_node_pool" {
  count     = var.create_karpenter_node_group ? 1 : 0
  manifest = yamldecode(<<-YAML
apiVersion: karpenter.sh/v1beta1
kind: NodePool
metadata:
  name: default
spec:
  template:
    spec:
      requirements:
        - key: kubernetes.io/arch
          operator: In
          values: ["x86_64", "amd64"]
        - key: kubernetes.io/os
          operator: In
          values: ["linux"]
        - key: karpenter.sh/capacity-type
          operator: In
          values: ["spot", "on-demand"]
        - key: karpenter.k8s.aws/instance-category
          operator: In
          values: ["c", "m", "r"]
        - key: karpenter.k8s.aws/instance-generation
          operator: Gt
          values: ["2"]
      nodeClassRef:
        apiVersion: karpenter.k8s.aws/v1beta1
        kind: EC2NodeClass
        name: default
  limits:
    cpu: 1000
  disruption:
    consolidationPolicy: WhenUnderutilized
    expireAfter: 720h # 30 * 24h = 720h
  YAML
  )
**Versions**:
- Chart Version:  karpenter-0.37.0
- Kubernetes Version (`kubectl version`): 1.29 - EKS

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by dhohengassner** [comment]
@rajeshj-prismforce running into the same issue - also needed to rollback.

Created an issue in main Karpenter project: https://github.com/kubernetes-sigs/karpenter/issues/1288

But likely the issue fits better to the aws provider 👍

**Comment by jonathan-innis** [comment]
When you updated the helm chart to the latest version, did you also update the CRD? This version contains a change that adds status conditions to the EC2NodeClass. If that change isn't present, Karpenter could fail to provision.

**Comment by jmdeal** [comment]
Yep, that should be the issue. If you update your CRDs this should fix the issue. Upgrading the Karpenter helm chart won't upgrade the CRDs ([ref](https://helm.sh/docs/chart_best_practices/custom_resource_definitions/#some-caveats-and-explanations)). This is our doc section on [CRD upgrades](https://karpenter.sh/docs/upgrading/upgrade-guide/#crd-upgrades). 

We're adding an explicit note to the upgrade guide (#6288), and I'll go ahead and add a note to the GitHub release notes. as well.

**Comment by rajeshj-prismforce** [comment]
@vukomir , Thanks i have downgraded to 3.6.2 and this issue disappeared.

**Comment by wdonne** [comment]
The Terraform `helm_release` is not pleased with having the CRDs in both the `karpenter` and the `karpenter-crd` charts. When you install the latter, it complains about the fact that the CRDs already exist and are under another release name, which is `karpenter`.
I think it is clearer when the CRDs are either not in the `kapenter` chart or that the documentation says it should be installed with the `--skip-crds` option. Automations that make a distinction between the first run and subsequent runs are not so easy.

**Comment by sinkr** [comment]
I agree with @wdonne.  This scenario creates unnecessary confusion and more importantly dysfunction within the cluster.

**Comment by morfien101** [comment]
For anyone stuck with the terraform to do this, here is what I do and it seems to be working pretty well.

```hcl
# Check this for update notes first:
# https://karpenter.sh/docs/upgrading/upgrade-guide/#crd-upgrades
resource "helm_release" "karpenter-crd" {
  namespace           = "karpenter"
  create_namespace    = true
  name                = "karpenter-crd"
  repository          = "oci://public.ecr.aws/karpenter"
  chart               = "karpenter-crd"
  version             = var.karpenter.chart_version
  wait                = true
  values = []
}

resource "helm_release" "karpenter" {
  depends_on = [ helm_release.karpenter-crd ]
  namespace           = "karpenter"
  create_namespace    = true
  name                = "karpenter"
  repository          = "oci://public.ecr.aws/karpenter"
  chart               = "karpenter"
  version             = var.karpenter.chart_version
  wait                = true
  
  # The crds are controlled by the karpenter-crd chart above.
  skip_crds = true

  values = [...]
}
```

If you already have the CRDs installed you'll need to pass control over to the crds helm chart by updating/adding some annotations and labels.

In my case for the above it looks like this:

```yaml
metadata:
  annotations:
    meta.helm.sh/release-name: karpenter-crd
    meta.helm.sh/release-namespace: karpenter
  labels:
    app.kubernetes.io/managed-by: Helm
```

You need to do these CRDs: [ ec2nodeclasses.karpenter.k8s.aws, nodeclaims.karpenter.sh, nodepools.karpenter.sh]

**Comment by Shirueopseo** [comment]
Then from 0.37v, installing karpenter with its helm release in Terraform, now we need to add the karpenter_crds helm_release too?
Or a patch for those CRDS can be performed to just mantain a single helm_release for karpenter?
It is planned to include the CRDS in the karpenter hlm chart in any way to make it easier to mantain from now on?
