### ISSUE TITLE
karpenter provisioner failing to schedule pods on eks cluster k8s version 1.30

### ISSUE THREAD

**Issue by sakulka** [aws/karpenter-provider-aws#6286]
### Description

we are trying to test out karpenter provisioner, however, we are seeing that pods are not getting scheduled, below are the karpenter provisioner and deployment manifest files
===================
apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  annotations:
  generation: 1
  labels:
    argocd.argoproj.io/instance: aws-karpenter-provisioner
  name: rancher-provisioner
  resourceVersion: "6835393"
  uid: 502fcad4-4647-4077-9786-ccb1282009c2
spec:
  ****labels:
    application: rancher****
  limits:
    resources:
      cpu: 1000
  providerRef:
    name: rancher-provisioner
  requirements:
  - key: node.kubernetes.io/instance-type
    operator: In
  - key: karpenter.sh/capacity-type
    operator: In
    values:
    - on-demand
  **taints:
  - effect: NoSchedule
    key: application
    value: rancher**
  ttlSecondsAfterEmpty: 30
  ==========================
  deployment manifest file
  ====================
  apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  generation: 7
  labels:
    name: overlaytest
  name: rancher-test
  namespace: default
  resourceVersion: "6853218"
  uid: f2911b95-9ce6-489f-947b-13c1caee882b
spec:
  progressDeadlineSeconds: 600
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      name: overlaytest
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        name: overlaytest
    spec:
      containers:
      - command:
        - sh
        - -c
        - tail -f /dev/null
        image: rancherlabs/swiss-army-knife
        imagePullPolicy: Always
        name: overlaytest
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      **nodeSelector:
        application: rancher**
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      **tolerations:
      - effect: NoSchedule
        key: application
        operator: Equal
        value: rancher**
status:
  availableReplicas: 3
  conditions:
  - lastTransitionTime: "2024-05-29T15:09:16Z"
    lastUpdateTime: "2024-05-29T15:09:16Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2024-05-29T15:42:02Z"
    lastUpdateTime: "2024-05-29T15:42:02Z"
    message: ReplicaSet "rancher-test-98559869c" has timed out progressing.
    reason: ProgressDeadlineExceeded
    status: "False"
    type: Progressing
  observedGeneration: 7
  readyReplicas: 3
  replicas: 4
  unavailableReplicas: 1
  updatedReplicas: 1

**Comment by sakulka** [comment]
i'm using the same label and the taints in the deployment manifests, but i still see the below error in karpenter logs
===============
{"level":"ERROR","time":"2024-05-29T16:01:08.723Z","logger":"controller.provisioner","message":"Could not schedule pod, incompatible with nodepool \"default\", daemonset overhead={\"cpu\":\"736m\",\"memory\":\"1067557632\",\"pods\":\"8\"}, incompatible requirements, label \"application\" does not have known values","commit":"6b868db","pod":"default/rancher-test-98559869c-5vdw8"}
{"level":"ERROR"

**Comment by sakulka** [comment]
failing to understand why is the karpenter failing to spin up a node when the labels and nodeselctors match and using the same tolerations in deployment file

**Comment by jmdeal** [comment]
The log you provided has a commit indicating that it's from Karpenter v0.36.0 and has a different NodePool name than the Provisioner you provided. Also a Provisioner wouldn't be compatible with v0.36.0, dual support for the alpha and beta APIs was dropped at v0.33.0. Do you have a NodePool in your cluster that you would expect this pod to schedule to other than "default", which Karpenter considers incompatible?

**Comment by sakulka** [comment]
sorry, i didnt get you completely since i'm new to karpenter, i just have a single nodepool which is the default one
 kubectl get nodepool
NAME      NODECLASS
default   default

**Comment by sakulka** [comment]
is there any difference between nodepool and provisioners? my understanding may be incorrect, i deployed karpenter as an addon, and using helm i will have to deploy multiple provisioners,

**Comment by sakulka** [comment]
{{- range .Values.provisioners }}
---
apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: {{ .name }}
spec:
  labels:
  {{- range $key, $value := .labels }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
  requirements:
    - key: "node.kubernetes.io/instance-type"
      operator: In
      values: 
      {{- range .instanceTypes }}
      - {{ . }}
      {{- end }}
    - key: "karpenter.sh/capacity-type"
      operator: In
      values:
      {{- range .capacityType }}
      - {{ . }}
      {{- end }}
  limits:
    resources:
      cpu: {{ .limit }}
  {{- if .taints }}
  taints:
    - effect: NoSchedule
      key: {{ .taints.key | quote }}
      value: {{ .taints.value | quote }}
  {{- end }}
  providerRef:
    name: {{ .providerReference }}
  ttlSecondsAfterEmpty: 30
{{- end }}


this is the provisioner templabe file i'm using

**Comment by sakulka** [comment]
i would like to have the pods scheduled on the nodes which are having the same config i pass through the provisioners and not the default nodepool

**Comment by sakulka** [comment]
@jmdeal , correct me if my understanding is wrong, for karpenter 0.36.x, we have karpenter node pools instead of karpenter provisioners? from the github repo i see nodepool repo instead of a provisioner repohttps://github.com/aws/karpenter-provider-aws/tree/v0.36.1/charts/karpenter/crds

**Comment by jmdeal** [comment]
Provisioners replaced NodePools in Karpenter v0.32.0, and support for Provisioners was completely removed in v0.33.0. You'll need to replace your provisioners with equivalent nodepools for them to work with v0.36.x. You can find more information in the [v1beta1 migration guide](https://karpenter.sh/v0.32/upgrading/v1beta1-migration/#provisioner---nodepool).
