### ISSUE TITLE
Continuation of issue#: 6024

### ISSUE THREAD

**Issue by sandeepkp1175** [aws/karpenter-provider-aws#6292]
@jigisha620 @jonathan-innis 

We are seeing the below error while trying to run the Karpenter in Openshift cluster. Could you please advise?
Also please help in re-opening the GitHub issue.

`{"level":"ERROR","time":"2024-05-28T20:49:19.963Z","logger":"controller.disruption","message":"listing instance types for default, resolving node class, EC2NodeClass.karpenter.k8s.aws \"default\" not found","commit":"17dd42b"}
{"level":"ERROR","time":"2024-05-28T20:49:25.665Z","logger":"controller.provisioner","message":"skipping, unable to resolve instance types, resolving node class, EC2NodeClass.karpenter.k8s.aws \"default\" not found","commit":"17dd42b","nodepool":"default"}
{"level":"INFO","time":"2024-05-28T20:49:25.812Z","logger":"controller.provisioner","message":"found provisionable pod(s)","commit":"17dd42b","pods":"podname/model-d4dnm","duration":"162.449739ms"}
{"level":"ERROR","time":"2024-05-28T20:49:25.812Z","logger":"controller.provisioner","message":"Could not schedule pod, all available instance types exceed limits for nodepool: \"default\"","commit":"17dd42b","pod":"podname/model-d4dnm"}
{"level":"ERROR","time":"2024-05-28T20:49:27.384Z","logger":"controller.provisioner","message":"skipping, unable to resolve instance types, resolving node class, EC2NodeClass.karpenter.k8s.aws \"default\" not found","commit":"17dd42b","nodepool":"default"}
`

_Originally posted by @sandeepkp1175 in https://github.com/aws/karpenter-provider-aws/issues/6024#issuecomment-2137665024_

**Comment by engedaam** [comment]
We can re-open the original issue.
