### ISSUE TITLE
Run Karpenter on Fargate

### ISSUE THREAD

**Issue by rajeshj-prismforce** [aws/karpenter-provider-aws#6295]
### Description

**Observed Behavior**:
I would like to Karpenter for provisiong instance while CAS is also in place. My idea to install Karpenter on Fargate and remaining application pods via Karpenter. Currently fargate profile is created and pods got created but fails with below error
```
anic: failed to get region from metadata server: EC2MetadataRequestError: failed to get EC2 instance identity document
caused by: RequestError: send request failed
caused by: Get "http://169.254.169.254/latest/dynamic/instance-identity/document": context deadline exceeded (Client.Timeout exceeded while awaiting headers)

goroutine 1 [running]:
github.com/samber/lo.must({0x281d2e0, 0xc0007b7e00}, {0xc000a1fbb0, 0x1, 0x1})
	github.com/samber/lo@v1.39.0/errors.go:51 +0x1bb
github.com/samber/lo.Must[...](...)
	github.com/samber/lo@v1.39.0/errors.go:65
github.com/aws/karpenter-provider-aws/pkg/operator.NewOperator({0x32e8a58, 0xc000494780}, 0xc00079e840)
	github.com/aws/karpenter-provider-aws/pkg/operator/operator.go:111 +0x314
main.main()
	github.com/aws/karpenter-provider-aws/cmd/controller/main.go:33 +0x2a
```
My Helm chart terraform resource is as below
`resource "helm_release" "karpenter" {
  depends_on = [
    kubernetes_namespace.karpenter
  ]
  count         = var.create_karpenter_node_group ? 1 : 0
  namespace     = "karpenter"
  name          = "karpenter"
  chart         = "karpenter"
  repository    = "oci://public.ecr.aws/karpenter"
  version       = "0.36.2"
  repository_username = data.aws_ecrpublic_authorization_token.token.user_name
  repository_password = data.aws_ecrpublic_authorization_token.token.password

  create_namespace = false
   set {
    name  = "settings.clusterName"
    value = var.cluster_name
  }
  set {
    name = "settings.aws.defaultRegion"
    value = data.aws_region.current.name
  }
  set {
    name  = "serviceAccount.annotaitons.eks.amazonaws.com/role-arn"
    value = aws_iam_role.worker_node[count.index].arn
  }
  set {
    name  = "controller.resources.requests.cpu"
    value = "1"
  }
  set {
    name  = "controller.resources.requests.memory"
    value = "1Gi"
  }
  set {
    name  = "controller.resources.limits.cpu"
    value = "1"
  }
  set {
    name  = "controller.resources.limits.memory"
    value = "1Gi"
  }
}
`
**Expected Behavior**:
Karpenter pods should run and let other application deployed via Karpenter
**Reproduction Steps** (Please include YAML):
1. I have the IAM role is having OIDC supplied in its trust policy along with EKS and EC2 services.
**Versions**:
- Chart Version: 0.36.2
- Kubernetes Version (`kubectl version`): 1.29 - EKS

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by engedaam** [comment]
Have you set up the IRSA correctly? Can you share the karpenter service account and role that was created?

**Comment by rajeshj-prismforce** [comment]
Here is my Trust relationship policy and role policy i have prepared as per documentation. 
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "EC2TrustPolicy",
            "Effect": "Allow",
            "Principal": {
                "Service": "ec2.amazonaws.com"
            },
            "Action": "sts:AssumeRole"
        },
        {
            "Sid": "EKSTrustPolicy",
            "Effect": "Allow",
            "Principal": {
                "Federated": "arn:aws:iam::XXXXXXXX:oidc-provider/oidc.eks.ap-south-1.amazonaws.com/id/68A285079347D6D54D71D60E6F6F4A93"
            },
            "Action": "sts:AssumeRoleWithWebIdentity",
            "Condition": {
                "StringEquals": {
                    "oidc.eks.ap-south-1.amazonaws.com/id/68A285079347D6D54D71D60E6F6F4A93:aud": "sts.amazonaws.com",
                    "oidc.eks.ap-south-1.amazonaws.com/id/68A285079347D6D54D71D60E6F6F4A93:sub": "system:serviceaccount:karpenter:karpenter"
                }
            }
        },
        {
            "Effect": "Allow",
            "Principal": {
                "Service": "eks.amazonaws.com"
            },
            "Action": "sts:AssumeRole"
        }
    ]
}
```

**Comment by engedaam** [comment]
Can you also share the corresponding serviceAccount object that is in cluster?
