### ISSUE TITLE
v1beta1 Migration a node tag need to be added to provisioner nodes to allow termination

### ISSUE THREAD

**Issue by nalshamaajc** [aws/karpenter-provider-aws#6302]
### Description

**How can the docs be improved?**
There needs to be a step to add the tag required to meet the AllowScopedDeletion's condition on old nodes.
* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**More details**

this is how the condition looks

```

  statement {
    sid    = "AllowScopedDeletion"
    effect = "Allow"

    resources = [
      "arn:${var.addon_context.aws_partition_id}:ec2:${var.addon_context.aws_region_name}:*:instance/*",
      "arn:${var.addon_context.aws_partition_id}:ec2:${var.addon_context.aws_region_name}:*:launch-template/*",
    ]

    actions = [
      "ec2:TerminateInstances",
      "ec2:DeleteLaunchTemplate",
    ]

    condition { # <------------------------------------------ This
      test     = "StringEquals"
      variable = "aws:ResourceTag/kubernetes.io/cluster/${var.addon_context.eks_cluster_id}"
      values   = ["owned"]
    }

    condition { # <------------------------------------------ This
      test     = "StringLike"
      variable = "aws:ResourceTag/karpenter.sh/nodepool"
      values   = ["*"]
    }
  }
```

**Error**

```
User: arn:aws:sts::xxxx:assumed-role/ROLE/xxxxxxxxxxx is not authorized to perform: ec2:TerminateInstances on resource: arn:aws:ec2:xx-xx-xx:xxxxxxxxxxxx:instance/i-xxxxxxxxxxx because no identity-based policy allows the ec2:TerminateInstances action. 
```

**Comment by engedaam** [comment]
@nalshamaajc did you remove the v1alpha1 policy from you Karpenter Controller Role during the transition?

**Comment by nalshamaajc** [comment]
Though I didn't quite get what you're pointing at, during the upgrade I noticed that the chart modified the k8s roles if that's what you're talking about.

**Comment by engedaam** [comment]
On the migration guide, on step (4) we add the v1beta1 policy to the Karpenter controller Role. That being said we don't remove the old v1alpha1 policy until all nodes have moved to be running under the v1beta1 APIs. Removing the v1alpha1 policy is done on step (17). Having both policy on the Karpenter controller role is what allows Karpenter to terminate the old nodes.  I'm just trying to validate that both the v1beta1 and v1alpha1 policy are attached to the Karpenter controller Role when you are trying to move your workloads to v1beta1 APIs?

**Comment by nalshamaajc** [comment]
> Having both policy on the Karpenter controller role is what allows Karpenter to terminate the old nodes.

I manage Karpenter as a chart therefore I use the equivalent of these changes in the helm chart and Terraform. I see that the problem was that the v1alpa1 policy was removed before the termination of nodes occurred. Feel free to close this issue if that's what you meant.
