### ISSUE TITLE
Not clear where the helm stable versions are

### ISSUE THREAD

**Issue by Harguer** [aws/karpenter-provider-aws#6348]
### Description

I'm so of confused. The official documentation says the latest stable version of karpenter helm version is `v0.37.0` and i can see `v0.36.2` is valid from the official documentation , but when i go to https://gallery.ecr.aws/karpenter?page=1 , the latest i can see is `v0.34.6`.
So where is the right place to look at those images? Maybe I'm looking at the wrong repo?
```

  name                = "karpenter"
  repository          = "oci://public.ecr.aws/karpenter"
```
Getting this error because of it:
```
╷
│ Error: public.ecr.aws/karpenter/karpenter:v0.36.2: not found
│
│   with helm_release.karpenter[0],
│   on karpenter.tf line 234, in resource "helm_release" "karpenter":
│  234: resource "helm_release" "karpenter" {
```
Latest from official documentation:
<img width="397" alt="image" src="https://github.com/aws/karpenter-provider-aws/assets/42277217/00fdbb37-9d6a-46fa-9ff3-78c8dbb07287">
<img width="397" alt="image" src="https://github.com/aws/karpenter-provider-aws/assets/42277217/18dbb6a1-4d28-4103-a9bc-8b1501f107de">

VS 
Latest karpenter helm repo https://gallery.ecr.aws/karpenter/karpenter:
<img width="1098" alt="image" src="https://github.com/aws/karpenter-provider-aws/assets/42277217/edf6a60b-2687-4147-9bcc-6a285ffe87ab">

I would appreciate, you could point to the right repo and update the docs to use that. Thanks in advance.

**Comment by jmdeal** [comment]
The `v` prefix was dropped from the chart release tag starting at `0.35.0` ([ref](https://github.com/aws/karpenter-provider-aws/issues/4248)). This was done to comply with semver and improve compatibility with tools that rely on that compliance (e.g. helm semver ranges). This change only affected the tags in the OCI repo, not anywhere else. This is reflected in the current version of the [Karpenter Getting Started Guide](https://karpenter.sh/docs/getting-started/getting-started-with-karpenter/#2-set-environment-variables).

**Comment by Harguer** [comment]
Thanks @jmdeal  for your quick reply and for clarifying it.
So the concept of`stable` versions also went away, and I can use whatever is new and it should be ok, right?
Thanks again for the quick help.

**Comment by jmdeal** [comment]
I'm not sure what you mean by stable versions, could you clarify?

**Comment by Harguer** [comment]
Hi @jmdeal  , I apologies I was referring to stable `releases` not `versions`, it is about this -> https://karpenter.sh/docs/upgrading/compatibility/
in the paragraph:

**Stable Releases**
_Stable releases are the most reliable releases that are released with weekly cadence. Stable releases are our only recommended versions for production environments. Sometimes we skip a stable release because we find instability or problems that need to be fixed before having a stable release. Stable releases are tagged with a semantic version prefixed by a v. For example v0.13.0_


Thanks again!

**Comment by jmdeal** [comment]
I see, got it. That's outdated wording, I'll cut an update. As of last September, all new releases published to the public ECR are stable. We used to publish our snapshot releases to the public ECR as well, those would be tagged with their git hash.

**Comment by Harguer** [comment]
Awesome, thank you @jmdeal  !
