### ISSUE TITLE
[Doc Enhancement] Is there any documentation that identifies the vendor of Karpenter?

### ISSUE THREAD

**Issue by francis-jjk** [aws/karpenter-provider-aws#6356]
Hey folks,

I hope this message finds you well. We have developed a product based on Karpenter, but with many enhancements, including intelligent EC2 selection, fault-tolerant scheduling across multiple AZs, configure Spot percentage for each workload， easy onboarding, and more.

I am wondering if there is any documentation that identifies the vendor of Karpenter, in case some customers require good support/service and SLA guarantees.

Our official website: https://www.cloudpilot.ai

Thank you for your time and assistance.

**Comment by jmdeal** [comment]
What do you mean by "the vendor of Karpenter"? The core library has been donated to kubernetes ([kubernetes-sigs/karpetner](https://github.com/kubernetes-sigs/karpenter)) and the AWS provider (this repo) is vended by AWS.
