### ISSUE TITLE
Could not login to OCI registry "public.ecr.aws": login attempt to https://public.ecr.aws/v2/ failed with status: 403 Forbidden

### ISSUE THREAD

**Issue by RobinFrcd** [aws/karpenter-provider-aws#6357]
### Description

Hi,
I've been managing Karpenter with the helm chart + terraform for a while now, but I've had login issues since yesterday.

`Error: could not login to OCI registry "public.ecr.aws": login attempt to https://public.ecr.aws/v2/ failed with status: 403 Forbidden`

The setup is really simple:
```
provider "aws"{
  alias = "use1"
  region = "us-east-1"
}

data "aws_ecrpublic_authorization_token" "token" {
    # https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/ecrpublic_authorization_token
    provider = aws.use1
}

resource "helm_release" "karpenter" {
  namespace           = "kube-system"

  name                = "karpenter"
  repository          = "oci://public.ecr.aws/karpenter"
  repository_username = data.aws_ecrpublic_authorization_token.token.user_name
  repository_password = data.aws_ecrpublic_authorization_token.token.password
  chart               = "karpenter"
  # https://github.com/aws/karpenter-provider-aws/releases
  version             = "0.37.0"
  wait                = false
}
```

I have already tried to do `docker logout public.ecr.aws` or `helm registry logout public.ecr.aws`.

Is there any other source to pull the chart from ? This ecr repo is a bit annoying. I see I'm not the only one having this issue (https://github.com/aws/karpenter-provider-aws/issues/3441#issuecomment-2106370162).

Thanks !

**Comment by jmdeal** [comment]
I'm going to guess you can't provide an authorization token to ECR public, could you try removing these lines?

```
data "aws_ecrpublic_authorization_token" "token" {
    # https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/ecrpublic_authorization_token
    provider = aws.use1
}
```

The public ECR is currently the only official release source for the helm chart.

**Comment by RobinFrcd** [comment]
Thanks for your answer, took it from the official examples, seems there's an issue there then ! https://github.com/terraform-aws-modules/terraform-aws-eks/blob/323fb759d718ed1f295c7278ef89a2e2f060d4a1/examples/karpenter/main.tf#L147

Thanks again !

**Comment by DRBeauchamp** [comment]
Why is this closed? I am hitting the same issue. What is the solution?

**Comment by RobinFrcd** [comment]
Remove `repository_username` and `repository_password` for public repositories.

**Comment by semusings** [comment]
Just tested today by installing Karpenter. As mentioned by @RobinFrcd, it works fine after removing repository_username and repository_password for public repositories.

Additionally, we can safely remove data "aws_ecrpublic_authorization_token" if we don't use private ECR repositories.

**Comment by Harshithraj24** [comment]
docker logout public.ecr.aws

This works

Reference : https://gallery.ecr.aws/karpenter/karpenter

**Comment by DingGGu** [comment]
Logout via `helm` cli works fine.

```
$ helm registry logout public.ecr.aws
```

Check below commands for works well.
```
$ helm fetch oci://public.ecr.aws/karpenter/karpenter-crd

**Comment by ifunky** [comment]
I've just hit this today after it's been working for some time:

│ Error: could not login to OCI registry "public.ecr.aws": error storing credentials - err: exit status 1, out: `The certificate was revoked.`
│ 
│   with module.eks_cluster.helm_release.karpenter[0],
│   on modules/eks-cluster/karpenter.tf line 31, in resource "helm_release" "karpenter":
│   31: resource "helm_release" "karpenter" {

I tried the above by removing the public login creds but that doesn't work either, tried the helm logout as well but no luck.

helm fetch oci://public.ecr.aws/karpenter/karpenter-crd
Error: GET "https://public.ecr.aws/v2/karpenter/karpenter/tags/list": unable to retrieve credentials

Any suggestions please?
Thanks

**Comment by allamand** [comment]
@ifunky did you follow this response : https://github.com/aws/karpenter-provider-aws/issues/6357#issuecomment-2214255926 ?

**Comment by felipebraga** [comment]
The best solution I found.

Install the [Amazon ECR Docker Credential Helper](https://github.com/awslabs/amazon-ecr-credential-helper)

`docker logout <registry>`

`helm registry logout <registry>`

Change both in `config.json`

- `C:\Users\<username>\.docker\config.json`
- `C:\Users\<username>\AppData\Roaming\helm\registry\config.json`

```
{
	"credHelpers": {
		"public.ecr.aws": "ecr-login",
		"<aws_account_id>.dkr.ecr.<region>.amazonaws.com": "ecr-login"
	}
}
```

After, there is no need to use `docker login` or `docker logout.`

**Comment by shazib-summar** [comment]
@DingGGu @RobinFrcd can you pls explain why logging out of `public.ecr.aws` works in this case?

**Comment by allamand** [comment]
Because it is public registry that can work without credentials. But if there are outdated credentials present then it does not work

**Comment by julian3xl** [comment]
> Thanks for your answer, took it from the official examples, seems there's an issue there then ! https://github.com/terraform-aws-modules/terraform-aws-eks/blob/323fb759d718ed1f295c7278ef89a2e2f060d4a1/examples/karpenter/main.tf#L147
> 
> Thanks again !

that repository is not official, just to clarify.-

**Comment by Boris-Jancic** [comment]
> Remove `repository_username` and `repository_password` for public repositories.

Thanks! This works.
