### ISSUE TITLE
One Subnet and Multiple EKS Cluster

### ISSUE THREAD

**Issue by aishwary05** [aws/karpenter-provider-aws#6377]
Hi Team,

I am working on a project where I have only one subnet and multiple EKS clusters.
And in the subnet, I'm updating the below tag. 

` aws ec2 create-tags \
--tags "Key=karpenter.sh/discovery,Value=${CLUSTER_NAME}" \
--resources $SUBNETS`
        
And whatever ${CLUSTER_NAME} is present in the tag, Karpenter will also work fine.
So how can my Karpenter work for every cluster without changing tags every time.? 
    
Please get back to me for more information

**Comment by aishwary05** [comment]
Hello Team Can someone please advise me on this?

**Comment by binnythomas-corsearch** [comment]
Can some one please update @lamdor @javier

**Comment by binnythomas-corsearch** [comment]
just use different tags.

**Comment by aishwary05** [comment]
> just use different tags.

Hi @binnythomas-corsearch,
Thanks for the reply. But in tags, `Key=karpenter.sh/discovery` should be unique.
and we cannot duplicate this.

Example: Below Example will not work
aws ec2 create-tags \ --tags "Key=karpenter.sh/discovery,Value=${CLUSTER_NAME-1}" \ --resources $SUBNETS
aws ec2 create-tags \ --tags "Key=karpenter.sh/discovery,Value=${CLUSTER_NAME-2}" \ --resources $SUBNETS

**Comment by siddharthdeshmukh** [comment]
We had similar setup and we updated the subnet tags to 
`Key=karpener.sh/private-subnet,Value='true'` and updated the `subnetSelectorTerms` to use this tag.
