### ISSUE TITLE
Karpenter evicts pods having do-not-disrupt annotation

### ISSUE THREAD

**Issue by tinhhn** [aws/karpenter-provider-aws#6407]
### Description

**Observed Behavior**:
Karpenter evicts pods which have karpenter/do-not-disrupt “true” annotation
Verified via kube-apiserver-audit log: pods are evicted by Karpenter.
Did not see any log related to the evicted pod in the Karpenter log (the leader one), log level is DEBUG.

**Expected Behavior**:
Karpenter should not evict pods having do-not-disrupt annotation

**Reproduction Steps** (Please include YAML):
Not always, just usually, so I can not provide steps here. Sorry that I type from phone and can not provide logs due to company policy. Is there any case that would happen? Thanks in advance!

**Versions**:
- Chart Version: 0.36.0
- Kubernetes Version (`kubectl version`): 1.28

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by zaldnoay** [comment]
There is a conditional race bug in 0.36.0, update to the new version and try again?

**Comment by tinhhn** [comment]
Yes thanks. Just scouted out that earlier. Let me upgrade and check.

**Comment by Balraj06** [comment]
@tinhhn Did upgrading to latest version solved the issue?

**Comment by tinhhn** [comment]
Solved by upgrading to 0.37.0

**Comment by Balraj06** [comment]
@tinhhn is this the same issue as karpenter race condition with kube scheduler?
