### ISSUE TITLE
Upgrading from v0.32.5 to v0.33.2, nodeclaim giving issue 

### ISSUE THREAD

**Issue by iampritamagrawal** [aws/karpenter-provider-aws#6433]
### Description

**Observed Behavior**:

**Expected Behavior**:

**Reproduction Steps** (Please include YAML):

**Versions**:
- Chart Version:
- Kubernetes Version (`kubectl version`):

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by sftim** [comment]
/retitle Advice on issue encountered during upgrade from v0.32.5 to v0.33.2
/remove-kind bug
/triage needs-information

**Comment by jonathan-innis** [comment]
There's not enough information in this issue to properly triage it other than noting that there was an issue during upgrade. Closing this since there's not enough information. Feel free to open another issue if you believe there's still a problem here.
