### ISSUE TITLE
Upgrading from v0.32.5 to v0.33.2, nodeclaim giving issue {"level":"ERROR","time":"2024-07-01T07:48:17.958Z","logger":"controller.provisioner","message":"creating node claim, Internal error occurred: failed calling webhook \"validation.webhook.karpenter.sh\": failed to call webhook: Post \"https://karpenter.kube-system.svc:8443/validate/karpenter.sh?timeout=10s\": no service port 8443 found for service \"karpenter\"","commit":"3a61217"}

### ISSUE THREAD

**Issue by iampritamagrawal** [aws/karpenter-provider-aws#6434]
### Description

**Observed Behavior**: 
After upgrade from v0.32.5 to v0.33.2, 
seeing couple of issues:
1 ) failed calling webhook \"validation.webhook.karpenter.sh\": failed to call webhook: Post \"https://karpenter.kube-system.svc:8443/validate/karpenter.sh?timeout=10s\": no service port 8443 found for service \"karpenter\"","commit":"3a61217" ( webhook is disabled)

2) when webhook is enabled: giving cert issue. 

3) I am able to see the configmap forbidden issue as well.   ( I have deployed karpenter in kube-system since 2 years.) 

{"level":"ERROR","time":"2024-07-01T07:49:24.953Z","logger":"controller","message":"k8s.io/client-go@v0.28.3/tools/cache/reflector.go:229: Failed to watch *v1.ConfigMap: failed to list *v1.ConfigMap: configmaps is forbidden: User \"system:serviceaccount:kube-system:karpenter\" cannot list resource \"configmaps\" in API group \"\" in the namespace \"kube-system\"\n","commit":"3a61217"}

4) In some case i am see its using v1apha1. 
{"level":"ERROR","time":"2024-07-01T08:25:13.992Z","logger":"controller","message":"k8s.io/client-go@v0.28.3/tools/cache/reflector.go:229: Failed to watch *v1alpha5.Provisioner: failed to list *v1alpha5.Provisioner: provisioners.karpenter.sh is forbidden: User \"system:serviceaccount:kube-system:karpenter\" cannot list resource \"provisioners\" in API group \"karpenter.sh\" at the cluster scope\n","commit":"3a61217"}

**Expected Behavior**:

**Reproduction Steps** (Please include YAML):

**Versions**: 0.33.5
- Chart Version: 1.28
- Kubernetes Version (`kubectl version`):

**Comment by sftim** [comment]
/retitle Advice on issue encountered during upgrade from v0.32.5 to v0.33.2

To make this into a bug report, please add detail about how to reproduce the bug @iampritamagrawal

**Comment by iampritamagrawal** [comment]
This issue is fixed. 

1) The digest (sha256) was wrong in each of the git repos for karpenter-provider-aws ( specific branch) : 
Example: 
https://github.com/aws/karpenter-provider-aws/tree/release-v0.33.x.  branch digest is wrong.  ( should take only main branch, seems or use -1 version digest it works)
Also, all the specific branches created have a problem. 

2) I also have to completely delete validating webhook from the cluster.
kubectl delete validatingwebhookconfigurations validation.webhook.karpenter.sh

3) After disabling logging and deleting validatingwebhookconfigurations mentioned above, i don't see any issue related to forbidden on configmaps again.
