### ISSUE TITLE
Support cpuManagerPolicy for kubelet configuration in NodePool

### ISSUE THREAD

**Issue by tuan-phan** [aws/karpenter-provider-aws#6435]
### Description

**What problem are you trying to solve?**
We need to use the cpuManagerPolicy: static instead of None
Currently we only support this list: https://karpenter.sh/docs/concepts/nodepools/#spectemplatespeckubelet

**How important is this feature to you?**
Will make more choice for applications to use dedicated CPU

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by jonathan-innis** [comment]
We're currently tightly constraining down the set of kubeletConfiguration options that we offer in the NodePool. The reason for this is primarily that we (as a cloudprovider) don't want to have to handle the userData orchestration (and testing) for every kubeletconfiguration option that we add to the codebase.

If you need to add additional config to to your userData, you can add it using the [technique documented in the upstream docs](https://karpenter.sh/docs/concepts/nodeclasses/#merged-userdata-mime)

**Comment by tuan-phan** [comment]
Thank @jonathan-innis
