### ISSUE TITLE
`c7i-flex` instances are not correctly labeled with bandwidth

### ISSUE THREAD

**Issue by craigandrews** [aws/karpenter-provider-aws#6446]
### Description

**Observed Behavior**:

AWS EC2 `flex` instances (e.g. `c7i-flex`) do not get a `instance-network-bandwidth` labels, but other instance types do. The equivalent instance types (e.g. `c7i`) that do not have flex are properly labeled.

The code in [bandwidth_gen.go](https://github.com/ellistarn/karpenter-provider-aws/blob/main/hack/code/bandwidth_gen/main.go#L83) expects the bandwidth to always be the 5th column in the documentation, but for flex instances it is the 6th column due to the new "Baseline performance" feature.

It appears that `flex` instances are very new. [Documentation example](https://aws.amazon.com/ec2/instance-types/c7i/) here.

**Expected Behavior**:

All instances with explicit bandwidth values should have a `instance-network-bandwidth` label.

**Reproduction Steps** (Please include YAML):

- Allow the use of `c7i-flex` instance types
- Check the labels of an instance of that type, and there will be no `instance-network-bandwidth` label

**Versions**:
- Chart Version: N/A
- Kubernetes Version (`kubectl version`): v1.28.9-eks-036c24b

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by matheuss** [comment]
(I work with @craigandrews) Actually, we just noticed this is fixed on `main`: https://github.com/aws/karpenter-provider-aws/pull/6099 fixed it.

**Comment by jigisha620** [comment]
Closing this issue since the fix has already been added in #6099
