### ISSUE TITLE
amd series node infinite regenerative status

### ISSUE THREAD

**Issue by jhyoonzi** [aws/karpenter-provider-aws#6449]
### Description

**Observed Behavior**:
Added t3.large, t3a.large to the karpenter node.

t3.large is normally poded up by job.batch and normal for nodes.

When the pod is raised by job.batch at t3a.large, the pod briefly enters the Running state and ends, and the Node enters the Schedule disabled state and repeats it indefinitely.

**Expected Behavior**:

**Reproduction Steps** (Please include YAML):
```makefile
apiVersion: karpenter.sh/v1beta1
kind: NodePool
metadata:
  name: karpenter-spot-test
spec:
  template:
    metadata:
      labels:
        role: ops
        provision: karpenter
    spec:
      nodeClassRef:
        name: karpenter-spot-test
        apiVersion: karpenter.sh/v1beta1
        kind: EC2NodeClass

      requirements:
        - key: node.kubernetes.io/instance-type
          operator: In
          values: [
              "t3.large",
              "t3a.large",
              "t4g.large",
              "m5.large",
              "m5a.large",
            ] 
        - key: karpenter.sh/capacity-type
          operator: In
          values: ["on-demand", "spot"]
        - key: "karpenter.k8s.aws/instance-generation"
          operator: "Gt"
          values: ["2"]
        - key: kubernetes.io/arch
          operator: In
          values: ["amd64"]
        - key: kubernetes.io/os
          operator: In
          values: ["linux"]
  limits:
    cpu: "30000"
    memory: 90000Gi

---
apiVersion: karpenter.k8s.aws/v1beta1
kind: EC2NodeClass
metadata:
  name: karpenter-spot-test
spec:
  amiFamily: AL2
  role: KarpenterNodeRole
  blockDeviceMappings:
    - deviceName: /dev/xvda
      ebs:
        deleteOnTermination: true
        volumeSize: 50Gi
        volumeType: gp3
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: karpenter-spot-test
  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: karpenter-spot-test
  tags:
    Name: karpenter.sh/karpenter-spot-test
    karpenter.sh/discovery: karpenter-spot-test
    alpha.eksctl.io/nodegroup-name: karpenter-spot-test
``` 

**Versions**:
- Chart Version: v0.37
- Kubernetes Version (`kubectl version`): v1.30

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by jigisha620** [comment]
I tried to reproduce this on my end and I ddi not run into any issues. What kind of pod are you trying to run? Does it have any resource requirements that can't be satisfied by `t3a.large` ? Can you share karpenter controller logs from when this happened? Can you also share what the created nodeClaim looks like?

**Comment by jhyoonzi** [comment]
Check the problem is normal to use the OpenCV to use OpenCV to use OpenCV to use OpenCV to use OpenCV.
However, in t3A.lge is normally operated and t3a.There was a problem because there was a problem.

The issue has been resolved because it was resolved.
Thank you.
