### ISSUE TITLE
available memory on nodes is less when the node is created from karpenter

### ISSUE THREAD

**Issue by ba1ajinaidu** [aws/karpenter-provider-aws#6453]
### Description

**Observed Behavior**:

I recently ran into a issue where a nodeclaim couldn't be created for a pod even though the pod requested for less memory(110GiB) than what the instance provides(c6gd.16xlarge - 128 GiB), but reducing the pod request to 105GiB worked. Looking more into settings of karpenter I found karpenter reserved some overhead(--vm-memory-overhead-percent) for better bin packing the instance. The default value for this is 0.075 but even after accounting for this reserved overhead I expected the node to have more than 110GiB. But from [this doc](https://karpenter.sh/v0.37/reference/instance-types/#c6gd16xlarge) I found it's very close to 110GiB. Can I get some help to understand how exactly this number is calculated?

**Expected Behavior**:
This is the capacity and allocatable resources of c6gd.16xlarge instance
![image](https://github.com/aws/karpenter-provider-aws/assets/72434180/0912f30f-c0c5-4251-9f9e-96b746fec2b3)

If I reduce the 7.5% of memory over head;
from node capacity, the memory should be - `1,17,022 MiB`
from node allocatable, the memory should be - `1,09,196 MiB`

neither of them match with the number in the doc `1,12,720 MiB`

**Reproduction Steps** (Please include YAML):

**Versions**:
- Chart Version:
`karpenter-0.36.2`

- Kubernetes Version (`kubectl version`):
`v1.29.4-eks-036c24b`

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by jigisha620** [comment]
You don't have to subtract vm memory overhead percentage from the allocatable memory. Allocatable memory seen on the nodeClaim already accounts for it. Did you get values for capacity and allocatable memory from describing the nodeClaim?

**Comment by ba1ajinaidu** [comment]
the values of capacity and allocatable are from the node and nodeclaim, why are the values different on node and nodeclaim? how are the values calculated for nodeclaim?

**Comment by jigisha620** [comment]
The value seen on the nodeClaim is an estimate that we make so that we don't end up launching smaller instance types that can't fit the pod requirement. This is calculated by subtracting kube reserved, system reserved and eviction threshold. The value seen on the node however is the actual reported memory. We want to ensure that Karpenter will underestimate the amount of memory available on an instance rather than overestimate.

**Comment by ba1ajinaidu** [comment]
How is the memory estimated, is it a fixed number/percentage that is subtracted from what the instanceType promises? I want to pin my pods to a certain instance type, so requesting for more memory(than what karpenter provides) causes it to not schedule

**Comment by jigisha620** [comment]
This is how the calculation is done. 
```
spec:
  capacity:
    memory: describeInstanceType - VM memory overhead
  allocatable:
    memory: describeInstanceType - VM memory overhead - kubeReserved - systemReserved - eviction
```
Further calculation for kubeReserved, systemReserved and evictionThreshold is done [here](https://github.com/aws/karpenter-provider-aws/blob/main/pkg/providers/instancetype/types.go#L61-L65).
