### ISSUE TITLE
conflict in policy between two docs

### ISSUE THREAD

**Issue by ben-dov** [aws/karpenter-provider-aws#6457]
### Description

**How can the docs be improved?**

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

# Issue
Seems that these two docs mention creating a policy for karpenter, but they are different permissions.:
* https://karpenter.sh/v0.32/upgrading/v1beta1-migration/
* https://karpenter.sh/v0.32/getting-started/migrating-from-cas/

The issue seems to repeat in 0.37 as well:
* https://karpenter.sh/v0.37/reference/cloudformation/
* https://karpenter.sh/v0.37/getting-started/migrating-from-cas/

What are the correct permissions we are meant to use?

**Comment by jigisha620** [comment]
I may have misunderstood what you are trying to point here, so I would want to confirm what policy are you exactly looking at? Also these docs make two different assumptions; v1beta1 migration assumes that you already have  Karpenter controller on cluster and want to upgrade that cluster to v0.32.x. Whereas the migration guide assumes you don't have Karpenter and are rather migrating from cluster autoscaler to Karpenter.

**Comment by ben-dov** [comment]
hey @jigisha620 I might have just been confused, because I see in https://karpenter.sh/v0.32/getting-started/getting-started-with-karpenter/ that the guide **is** using the role from cloudformation. (which I assume is the correct role/policy)

**Comment by jigisha620** [comment]
If you are looking at KarpenterNodeRole, then both have same policies. 
https://karpenter.sh/v0.37/getting-started/migrating-from-cas/#create-iam-roles
https://karpenter.sh/v0.37/reference/cloudformation/#karpenternoderole

**Comment by ben-dov** [comment]
THX for the reply,
to be clear, my question was about the karpenter controller role

**Comment by ben-dov** [comment]
@jigisha620 the ticket is no longer relevant, seems I was just confused between the guides.
I am closing
