### ISSUE TITLE
What's karpenter EC2 selection policy if the workloads overcommit heavily (limits/request>3) ？

### ISSUE THREAD

**Issue by francis-jjk** [aws/karpenter-provider-aws#6461]
### Description

**Observed Behavior**:
Let's say I have a Java workload which need much more memory than CPU. I set：

- CPU request = 0.5 core, CPU Limit = 2 core，CPU utilization = 1 Cores
- Memory request = 5 Gib, Memory limit = 16 GiB，Memory utilization = 12GB

In my case I choose m5.2xlarge(8C32G) as the candidate，but karpenter recommend us migrate to t3.small（2C2G）. Karptener seems only consider CPU Request to select EC2 instance. Which probably has following issues：

- OOM happens if the Pod been scheduled to t3.small

R5.xlarge(4C 32G) seems to be a better option

**Expected Behavior**:

**Reproduction Steps** (Please include YAML):

**Versions**:
- Chart Version:
- Kubernetes Version (`kubectl version`):

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by jmdeal** [comment]
Karpenter should consider all resource requests when selecting instances, not just CPU. Note that it only respects requests and not limits (same as kube-scheduler), but it should have still selected an instance with at least 5Gb of memory. Can you share your pod spec, created nodeclaim spec, and Karpenter logs?
