### ISSUE TITLE
Change to image tagging stratgey 

### ISSUE THREAD

**Issue by crablab** [aws/karpenter-provider-aws#6496]
### Description

It appears there's been a change to the image tagging prefix between v0.36.0 and 0.37.0. 

ie. public.ecr.aws/karpenter/karpenter:0.37.0 vs public.ecr.aws/karpenter/karpenter:v0.36.0

I couldn't see this noted anywhere in the [release notes](https://github.com/aws/karpenter-provider-aws/releases/tag/v0.37.0) for 0.37.0 which makes me wonder if it's unintentional? 

If it's not, I think it'd be worth calling this out in the release notes & in the upgrade guide. It's a small thing but it is a 'breaking change' to some pipelines.

**Comment by mikestef9** [comment]
See https://karpenter.sh/preview/upgrading/upgrade-guide/#upgrading-to-0350

**Comment by jmdeal** [comment]
As @mikestef9 commented, this change was made at 0.35, not 0.37. This change was documented in the upgrade guide and in the release notes. I'm not sure how you would have been able to pull `v0.36.0` from our ECR gallery, I've verified that no such tag exists.
