### ISSUE TITLE
Node Metrics included nodes not managed by Karpenter

### ISSUE THREAD

**Issue by hitsub2** [aws/karpenter-provider-aws#6552]
### Description

**Observed Behavior**:

Node metrics show the nodes that are not created by Karpenter.

**Expected Behavior**:

**Reproduction Steps** (Please include YAML):

**Versions**:
- Chart Version:
- Kubernetes Version (`kubectl version`):

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by engedaam** [comment]
Which metrics specifically are you seeing nodes that are not managed by Karpetner?

**Comment by hitsub2** [comment]
The following metrics,

karpenter_nodes_total_pod_requests 
karpenter_nodes_total_pod_limits
karpenter_nodes_total_daemon_requests
karpenter_nodes_total_daemon_limits
karpenter_nodes_system_overhead
karpenter_nodes_allocatable

Examples of samples

```shell

karpenter_nodes_total_pod_requests{app_kubernetes_io_instance="karpenter", app_kubernetes_io_managed_by="Helm", app_kubernetes_io_name="karpenter", app_kubernetes_io_version="0.36.0", arch="amd64", helm_sh_chart="karpenter-0.36.0", instance="100.64.81.229:8000", instance_type="m5.xlarge", job="kubernetes-service-endpoints", kubernetes_namespace="karpenter", node_name="ip-100-64-245-1.us-west-2.compute.internal", os="linux", region="us-west-2", resource_type="cpu", service="karpenter", zone="us-west-2b"} | 1.06
karpenter_nodes_total_pod_requests{app_kubernetes_io_instance="karpenter", app_kubernetes_io_managed_by="Helm", app_kubernetes_io_name="karpenter", app_kubernetes_io_version="0.36.0", arch="amd64", helm_sh_chart="karpenter-0.36.0", instance="100.64.81.229:8000", instance_type="m5.xlarge", job="kubernetes-service-endpoints", kubernetes_namespace="karpenter", node_name="ip-100-64-245-1.us-west-2.compute.internal", os="linux", region="us-west-2", resource_type="memory", service="karpenter", zone="us-west-2b"} | 1935671296
karpenter_nodes_total_pod_requests{app_kubernetes_io_instance="karpenter", app_kubernetes_io_managed_by="Helm", app_kubernetes_io_name="karpenter", app_kubernetes_io_version="0.36.0", arch="amd64", helm_sh_chart="karpenter-0.36.0", instance="100.64.81.229:8000", instance_type="m5.xlarge", job="kubernetes-service-endpoints", kubernetes_namespace="karpenter", node_name="ip-100-64-245-1.us-west-2.compute.internal", os="linux", region="us-west-2", resource_type="pods", service="karpenter", zone="us-west-2b"} | 5

```

**Comment by engedaam** [comment]
What version of Karpenter are you using?

**Comment by engedaam** [comment]
This currenlty expected behavior. You should be able to filter out non Karpenter ownd nodes by using nodepool label
