### ISSUE TITLE
Distribute workloads across multiple Availability Zones to mitigate the risk of single-zone failure.

### ISSUE THREAD

**Issue by rr-krupesh-savaliya** [aws/karpenter-provider-aws#6553]
### Description

**What problem are you trying to solve?**

We need to spread nodes across different zones to prevent single-zone failures. A similar feature is available in ASG called "AZRebalance".

**How important is this feature to you?**

This feature is crucial not just for us but other as well. We are using Karpenter in production and require this functionality to ensure high availability and prevent single points of failure. If our production workloads are running in a single Availability Zone, it becomes very critical.

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by eladmotola** [comment]
Hey, did you check that up?
https://karpenter.sh/preview/concepts/scheduling/#topology-spread

**Comment by engedaam** [comment]
@eladmotola Are you using topology spread on your workloads? If so, Karpetner will try to provision nodes to respect the topology spread, however Karpetner will not try to rebalance and delete nodes to conform to topology spread

**Comment by eladmotola** [comment]
@engedaam yes i do. i read his demand as "hey, i need a way to spread my workload between 2 or more azs, how can I achieve it?".  and not as "I know how to spread my workload between multiple azs, can karpenter recover from az failure?"
so i believed this is the answer he want but we cannot be sure since he didn't comment yed
