### ISSUE TITLE
Expose real time cluster cost metric

### ISSUE THREAD

**Issue by jan-ludvik** [aws/karpenter-provider-aws#6566]
### Description

**What problem are you trying to solve?**
eks-node-viewer (which I really like, thanks!) shows real time cluster cost metric. It would be really great if karpenter could expose the same.
Here in the cluster summary on the right:
```
44 nodes (902794m/1056270m) 85.5% cpu ██████████████████████████████████░░░░░░ $25.082/hour | $18,310.152/month 
2,072 pods (44 pending 2,028 running 2,035 bound)
```

I am aware of `karpenter_cloudprovider_instance_type_offering_price_estimate` metric but I don't know how calculate cluster cost from that in Datadog.
**How important is this feature to you?**
It is not critical but it would help with optimising cluster costs and catching anomalies.

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by engedaam** [comment]
@jan-ludvik I think this issue could be added here https://github.com/kubernetes-sigs/karpenter/issues/1051. Closing as a duplicate.
