### ISSUE TITLE
Karpenter not able to schedule GPU instance 

### ISSUE THREAD

**Issue by surlalwani** [aws/karpenter-provider-aws#6574]
### Description

**Observed Behavior**:
Karpenter is unable to schedule a GPU node for the deployment. The following error is observed:
incompatible with nodepool "gpu-nodepool", daemonset overhead={"cpu":"185m","memory":"240Mi","pods":"7"}, no instance type satisfied resources {"cpu":"185m","memory":"240Mi","nvidia.com/gpu":"1","pods":"8"} and requirements app In [gpu-test], karpenter.sh/capacity-type In [on-demand spot], karpenter.sh/nodepool In [gpu-nodepool], node.kubernetes.io/instance-type In [g4dn.xlarge g5.xlarge] (no instance type met all requirements);

**Expected Behavior**:
Karpenter should provision a GPU node (either g5.xlarge or g4dn.xlarge) and schedule the deployment on it.

**Reproduction Steps** (Please include YAML):
Apply following nodepool

apiVersion: karpenter.sh/v1beta1
kind: NodePool
metadata:
  name: gpu-nodepool
spec:
  template:
    metadata:
      labels:
        app: gpu-test
    spec:
      nodeClassRef:
        name: gpu-nodepool
      requirements:
        - key: karpenter.sh/capacity-type
          operator: In
          values: ["spot","on-demand"]
        - key: "node.kubernetes.io/instance-type"
          operator: In
          values: ["g5.xlarge","g4dn.xlarge"]
  disruption:
    consolidationPolicy: WhenUnderutilized
    expireAfter: 24h
    
    Apply the following EC2NodeClass:
    
    apiVersion: karpenter.k8s.aws/v1beta1
kind: EC2NodeClass
metadata:
  name: gpu-nodepool
spec:
  amiFamily: AL2
  blockDeviceMappings:
  - deviceName: /dev/xvda
    ebs:
      encrypted: true
      volumeSize: 200Gi
      volumeType: gp3
  role: "KarpenterNodeRole-production-python"
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: production-python
  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: production-python
        
   Apply the following Deployment:
 apiVersion: apps/v1
kind: Deployment
metadata:
  name: gpu-test-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gpu-test
  template:
    metadata:
      labels:
        app: gpu-test
    spec:
      containers:
      - command:
        - nvidia-smi
        image: nvidia/cuda:11.0-base
        name: gpu-test-container
        resources:
          limits:
            nvidia.com/gpu: "1"
          requests:
            nvidia.com/gpu: "1"
      nodeSelector:
        app: gpu-test

**Versions**:
Karpenter Version: 0.33
Kubernetes Version: 1.28
- Chart Version:
- Kubernetes Version (`kubectl version`):

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by engedaam** [comment]
I think the issue is coming from your nodeSelector https://karpenter.sh/docs/concepts/scheduling/#node-selectors. Since `app: gpu-test` is a custom label, you need to make sure that the karpenter provisioned will have that label https://karpenter.sh/docs/concepts/scheduling/#user-defined-labels
