### ISSUE TITLE
Unexpected termination of pods with PVC

### ISSUE THREAD

**Issue by improved-broccoli** [aws/karpenter-provider-aws#6581]
### Description

**Observed Behavior**:

Given a node pool using spot and on-demand
1. ~10 Spot node claims are created for pods with a PVC
2. PVCs are being provisioned / node claims are in progress
3. Some pods are scheduled on nodes but some node claim fails
4. Finally some pods are scheduled on different nodes
5. New node claim are created for on-demand
6. On-demand node claims succeed
7. Pods are scheduled on on-demand nodes
8. PVCs cannot be used because pods are not the owner
9. Pods are killed

Here is a typical log showing the issue:
```
0s                      Warning   FailedScheduling         Pod/runner-b9ndp-runner-zh7dx                                   0/18 nodes are available: waiting for ephemeral volume controller to create the persistentvolumeclaim "runner-b9ndp-runner-zh7dx-work". preemption: 0/18 nodes are available: 18 Preemption is not helpful for scheduling.
1s                      Normal    WaitForPodScheduled      PersistentVolumeClaim/runner-b9ndp-runner-zh7dx-work            waiting for pod runner-b9ndp-runner-zh7dx to be scheduled
0s                      Normal    Nominated                Pod/runner-b9ndp-runner-zh7dx                                   Pod should schedule on: nodeclaim/actions-runners-ppjvv, node/ip-10-127-200-230.ec2.internal
0s                      Normal    ExternalProvisioning     PersistentVolumeClaim/runner-b9ndp-runner-zh7dx-work            Waiting for a volume to be created either by the external provisioner 'ebs.csi.aws.com' or manually by the system administrator. If volume creation is delayed, please verify that the provisioner is running and correctly registered.
0s                      Normal    Provisioning             PersistentVolumeClaim/runner-b9ndp-runner-zh7dx-work            External provisioner is provisioning volume for claim "github/runner-b9ndp-runner-zh7dx-work"
0s                      Normal    ProvisioningSucceeded    PersistentVolumeClaim/runner-b9ndp-runner-zh7dx-work            Successfully provisioned volume pvc-59f104ed-a185-42d6-8d99-cb8014b42bfe
0s                      Normal    Scheduled                Pod/runner-b9ndp-runner-zh7dx                                   Successfully assigned github/runner-b9ndp-runner-zh7dx to ip-10-127-205-153.ec2.internal
0s                      Normal    SuccessfulAttachVolume   Pod/runner-b9ndp-runner-zh7dx                                   AttachVolume.Attach succeeded for volume "pvc-59f104ed-a185-42d6-8d99-cb8014b42bfe"
0s                      Normal    Pulled                   Pod/runner-b9ndp-runner-zh7dx                                   Container image "00000000000.dkr.ecr.us-east-1.amazonaws.com/ghcr/actions/actions-runner:2.317.0" already present on machine
0s                      Normal    Created                  Pod/runner-b9ndp-runner-zh7dx                                   Created container runner
0s                      Normal    Started                  Pod/runner-b9ndp-runner-zh7dx                                   Started container runner
0s                      Normal    Evicted                  Pod/runner-b9ndp-runner-zh7dx                                   Evicted pod
0s                      Normal    Killing                  Pod/runner-b9ndp-runner-zh7dx                                   Stopping container runner
0s                      Warning   FailedBinding            Pod/runner-b9ndp-runner-zh7dx                                   ephemeral volume work: PVC github/runner-b9ndp-runner-zh7dx-work was not created for pod github/runner-b9ndp-runner-zh7dx (pod is not owner)
```

The pod should have scheduled on node `ip-10-127-200-230.ec2.internal` but finally was scheduled on `ip-10-127-205-153.ec2.internal`. The EBS volume have been prepared in the meantime but for the first node I guess.

For now, the only workaround is to not use Spot but only on-demand

**Expected Behavior**:

Given a node pool using spot and on-demand
1. A Spot node claim created for a pod with a PVC
2. The PVC is being provisioned / The node claim is in progress on Spot
3. Node claim fail, create a new node claim for on-demand
4. On-demand node claim succeed
5. The pod is scheduled on that node
6. The volume can be used because the owner has been updated after the failed node claim

**Reproduction Steps** (Please include YAML):

**Versions**:
- Chart Version: 0.37.0
- Kubernetes Version (`kubectl version`): EKS 1.30

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by engedaam** [comment]
Closing in favor of https://github.com/kubernetes-sigs/karpenter/issues/944. Duplicate issue
