### ISSUE TITLE
Karpenter does not support labels such as karpenter.k8s.aws/instance-cpu in preferredDuringSchedulingIgnoredDuringExecution

### ISSUE THREAD

**Issue by ujjawal-khare-27** [aws/karpenter-provider-aws#6587]
### Description

**What problem are you trying to solve?**
We are scheduling stateful pods in our application which might run from 30 min to 90 days or more. When karpenter schedules pods it fits the pod in existing large machines which is having some temporary workloads but when these workloads goes away large instance type still is taken by  long running pod (We use do-not-disrupt annotation due to stateful application). These leads to high cost.

**How important is this feature to you?**
It leads to around increased cost for us in order of thousand dollars per day.

I am interested in working on this issue.

**Comment by engedaam** [comment]
I think here is a related issue. https://github.com/kubernetes-sigs/karpenter/issues/666. Closing as a duplicate
