### ISSUE TITLE
vmMemoryOverheadPercent name is misleading 

### ISSUE THREAD

**Issue by bnetzi** [aws/karpenter-provider-aws#6612]
### Description

**How can the docs be improved?**

The name vmMemoryOverhead**Percent** indicated the overhead calculated is in percent, bet it is actually a factor so the default 
0.0725 is **actually 7.25%** which is very significant

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by njtran** [comment]
Feel free to cut a docs PR to fix this as you see fit!
