### ISSUE TITLE
Display Nodepool Validation Result in Nodepool Events

### ISSUE THREAD

**Issue by YouhuaLi** [aws/karpenter-provider-aws#6618]
### Description

**What problem are you trying to solve?**
I created a nodepool but it didn't work. I checked Karpenter pod logs and see:
`{"level":"ERROR","time":"2024-07-31T18:56:27.370Z","logger":"controller","message":"nodepool failed validation","commit":"490ef94","controller":"provisioner","NodePool":{"name":"xxxx"},"error":"invalid key name \"app.kubernetes.io/managed-by\": spec.template.metadata.labels\nlabel app.kubernetes.io/managed-by is restricted; ....., or a custom label that does not use a restricted domain: [k8s.io karpenter.k8s.aws karpenter.sh kubernetes.io]"}`

It would be nice that the validation result can be seen when I describe the nodepool:

```
 kubectl describe nodepool xxxx
....
          spot
          on-demand
      Taints:
        Effect:  NoSchedule
        Key:     xxx
        Value:   xxxx
  Weight:        5
Events:
   <display the validation result here.>
```

**How important is this feature to you?**

This feature will help find nodepool issues earlier. CRD `ec2nodeclass` has this feature already.

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by njtran** [comment]
Seems fairly easy to do this. Would you be interested in cutting a fix?

**Comment by YouhuaLi** [comment]
ok, I can try that.

**Comment by YouhuaLi** [comment]
saw this is already done in version 1.0+. so closing the issue
