### ISSUE TITLE
Getting started section is inaccurate

### ISSUE THREAD

**Issue by willredington** [aws/karpenter-provider-aws#6619]
### Description

https://karpenter.sh/docs/getting-started/getting-started-with-karpenter/

Karpenter supports only 1.29 of kubernetes in the docs its specifying 1.30

These values return not found in both us-east-1 and us-east-2:

```
export ARM_AMI_ID="$(aws ssm get-parameter --name /aws/service/eks/optimized-ami/${K8S_VERSION}/amazon-linux-2-arm64/recommended/image_id --query Parameter.Value --output text)"
export AMD_AMI_ID="$(aws ssm get-parameter --name /aws/service/eks/optimized-ami/${K8S_VERSION}/amazon-linux-2/recommended/image_id --query Parameter.Value --output text)"
export GPU_AMI_ID="$(aws ssm get-parameter --name /aws/service/eks/optimized-ami/${K8S_VERSION}/amazon-linux-2-gpu/recommended/image_id --query Parameter.Value --output text)"
```

**Comment by njtran** [comment]
We support 1.30. These all work for me for 1.30. Here's an example of one of the commands I used

```
aws ssm get-parameter --name /aws/service/eks/optimized-ami/1.30/amazon-linux-2-gpu/recommended/image_id --query Parameter.Value --output text --region us-east-2
```

**Comment by willredington** [comment]
I am seeing ParameterNotFound for all of them in us-east-2 both on the CLI and in the console

**Comment by aaroniscode** [comment]
@willredington I can confirm running the command @njtran shared above and it's working for me. I've used Karpenter with EKS 1.30.

Can you try running the command in AWS CloudShell to rule out any issue with your AWS CLI command?  If it's working there, that might help you root cause why it's not working in the other environment.

**Comment by willredington** [comment]
Got it working thanks
