### ISSUE TITLE
Tolerations added to helm values not being added to the actual deployment

### ISSUE THREAD

**Issue by cw-sanikachavan** [aws/karpenter-provider-aws#6633]
### Description

**Observed Behavior**:
![image](https://github.com/user-attachments/assets/91f3db28-c02d-47ec-a83e-55c9db995363)

**Expected Behavior**:
![image](https://github.com/user-attachments/assets/57ed2218-11ba-4c82-8018-e4dcd56738c6)

**Reproduction Steps** (Please include YAML):

**Versions**:
- Chart Version: 0.37
- Kubernetes Version (`kubectl version`): 1.29

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by njtran** [comment]
What's your helm install command so I can reproduce? I just changed the values in my values.yaml and saw the tolerations apply.

**Comment by cw-sanikachavan** [comment]
@njtran 
```
helm --kubeconfig=/home/consul/.kube/eks-dev.yml upgrade --install --namespace kube-system karpenter oci://public.ecr.aws/karpenter/karpenter --version 0.37.0 --set settings.clusterName=k8s-dev --set "serviceAccount.annotations.eks\.amazonaws\.com/role-arn=arn:aws:iam::408531640850:role/KarpenterControllerRole-k8s-dev"
```

**Comment by cw-sanikachavan** [comment]
Can anyone help here?
