### ISSUE TITLE
Karpenter disrespecting Pod Disruption Budget while downscaling of pod

### ISSUE THREAD

**Issue by coniferrkishor0874** [aws/karpenter-provider-aws#6646]
### Description

**Observed Behavior**:
When sudden load are input on deployment, pod got scaled up to 10 pods on new nodes and existing nodes but during downscaling of pods it comes down to desired number of pods i.e 2, it was noticed pods were stable for few hours, when load comes up again, it was first bring down to 0 pod and then suddenly scaled to 7-10 pods.  I have pdb configured with min 1 number of pod. 

When provisioner got expired after ttl, it forcefully replace the node with disrespecting pdb for application. Application facing downtime of ~2 min until new nodes spins up. I have seen this event occurrence are not too frequent but looking for option what others things can be done from pdb side or karpenter provisioner setting.

**Expected Behavior**: It should respect pdb while downscaling of pods. I have ttl period of 7 days in provisioners. 

Looking for help how karpenter setting tuning will respect the pdb kind or any alternative solution for this also appreciated?
Thanks

**Versions**:
- Karpenter Version: 0.30
- EKS Kubernetes Version: 1.29

**Comment by njtran** [comment]
Hey @coniferrkishor0874, I'm not sure I'm understanding your reproduction steps. Are you saying you have ttlSecondsUntilExpired enabled on your Provisioner, and after the node expires, draining doesn't respect pod disruption budgets? can you share your logs? If you have a minAvailable of 1, you should eventually see it fully drain to another node, but it should never bypass the PDB.

**Comment by duyvinh229148** [comment]
I have similar issue, PDB set to minAvailable 1, but when checking 'Events', I see that karpenter evict all node that contains that service's pod, leaving down time. None of my nodeclaim is close to expire time of 168h that I set.
