### ISSUE TITLE
add option to karpenter helm chart to set custom annotations on the custom resource definitions

### ISSUE THREAD

**Issue by martijnvdp** [aws/karpenter-provider-aws#6649]
### Description
add an option to make it possible to set annotations on the custom resource definitions, so we can set in our use case the helm keep tag to ensure these never get deleted by an accidential uninstall of the karpenter-crd chart
```
  annotations:
    helm.sh/resource-policy: keep
```

**What problem are you trying to solve?**
we would like to be able to set cutom annotations to the crds, in our case a the specific helm keep tag to ensure the crds are preserved by an accidental uninstall of the chart and that would prevent node interuptions

**Comment by njtran** [comment]
Does it make sense to just support helm-customized annotations on your helm install command, rather than codifying this one specific integration with helm?

**Comment by martijnvdp** [comment]
yes sure that will also do, can change it
