### ISSUE TITLE
Allow metadata in tags is set to Enabled by default in the EC2LaunchTemplates on the eu-north-1 region, causing Karpenter to not provision the nodes

### ISSUE THREAD

**Issue by atelal** [aws/karpenter-provider-aws#6669]
### Description

Hello,

**Observed Behavior**:
While creating a Nodeclaim, the READY status is set to False, and the following message appears:
``` text
    Message:               creating instance, with fleet error(s), InvalidParameterValue: 'kubernetes.io/cluster/ex-karpenter' is not a valid tag key. Tag keys must match pattern ([0-9a-zA-Z\\-_+=,.@:]{1,255}), and must not be a reserved name ('.', '..', '_index')
```

Upon checking the EC2LaunchTemplate, I found out the following:
![image](https://github.com/user-attachments/assets/ca9e308e-906b-46cc-915b-e06792c22707)
As you can see, the `Allow tags in metadata` is set to `-`, which means it's enabled.

I tried to create an EC2LaunchTemplate by hand, and by default, it is set to enabled.
What is strange is that the AWS [documentation](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_LaunchTemplateInstanceMetadataOptionsRequest.html) specifies that the InstanceMetadataTags are set to disabled by default.

In the [launchtemplate.go](https://github.com/aws/karpenter-provider-aws/blob/0d86d4792795e1482284785626f6dd41ad1fa063/pkg/providers/launchtemplate/launchtemplate.go#L248) file, it is assuming the default (which should be disabled, or not included in launch template). Wouldn't it be safer to set it to disabled anyway?

I have tried it on the eu-north-1 region. Upon checking on the multiple other regions, I see that the `Allow tags in metadata` is set to `Don't include in Launch Template`.

**Expected Behavior**:
The expected behavior should disable the tags in metadata to be safe.

**Reproduction Steps** (Please include YAML):
- Setup EKS with Karpenter via terraform, as shown in [this example](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/v20.22.0/examples/karpenter/main.tf)
- Scale the replicas of the inflate deployment:
``` bash
kubectl scale deployments/inflate --replicas=1
```
- check the nodeclaims (a new one appears)
``` bash
kubectl get nodeclaim
```
- Wait 45 seconds for the READY status to be False.
- Check the content:
``` bash
kubectl describe nodeclaim ${NODECLAIM}
```
Error message:
``` text
    Message:               creating instance, with fleet error(s), InvalidParameterValue: 'kubernetes.io/cluster/ex-karpenter' is not a valid tag key. Tag keys must match pattern ([0-9a-zA-Z\\-_+=,.@:]{1,255}), and must not be a reserved name ('.', '..', '_index')
```

**Versions**:
- Chart Version: 0.37.0
- Kubernetes Version (`kubectl version`): 1.29

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by atelal** [comment]
Hello again,
Seems like I have found the source of the issue.
On the AWS account, in EC2, for this particular region, the setting `Access to tags in metadata` was set to Enabled by default.

![image](https://github.com/user-attachments/assets/4c57ab1c-ef0c-476c-97d1-c1d7ed555333)

I have set it back to `No preference` (the default).

Should Karpenter override these kinds of settings? If not I totally understand.

Thanks.

**Comment by njtran** [comment]
It seems like Karpenter should just use the default, assuming that a user who wants the different default would modify their tags to be compliant with the syntax. Is there any case for having access to tags in metadata?

**Comment by atelal** [comment]
Hello,

If I use the following Terraform snippet:
``` terraform
resource "aws_ec2_instance_metadata_defaults" "eu-north-1" {
  http_endpoint               = "enabled"
  http_tokens                 = "required"
  http_put_response_hop_limit = 1
  instance_metadata_tags      = "enabled"
}
```

Then Karpenter will not be able to launch new EC2 instances, due to the tags passed to the EC2 instance, because they are containing `/`.

To fix this, I had to change it to:

``` terraform
resource "aws_ec2_instance_metadata_defaults" "eu-north-1" {
  http_endpoint               = "enabled"
  http_tokens                 = "required"
  http_put_response_hop_limit = 1
  instance_metadata_tags      = "disabled"
}
```

This is the ec2 instance metadata default settings that can be applied to the whole region on which I apply it.
Karpenter is forcing people to use the `instance_metadata_tags      = "disabled"` on the whole region (I think I have seen a similar [issue](https://github.com/aws/karpenter-provider-aws/issues/3650) btw).

So, to me, I see to solutions:
- Change the code to set it to enabled
- Add a note in the documentation that warns people that it is required to have  the `instance_metadata_tags      = "disabled"` before installing Karpenter.

I don't think Karpenter should assume settings that may be made on a region (unless it's written somewhere).

I would be glad to help regarding the documentation.

Thanks.

**Comment by atelal** [comment]
Hello,
I can still edit the docs if needed.
Thanks.

**Comment by atelal** [comment]
Hello,
I can still edit the docs if needed.
Thanks.

**Comment by scotthesterberg** [comment]
The drop of being able to support providing a launch template has broken things for us as well. Our AWS region does not allow configuring LaunchTemplate metadataOptions. Previously you could provide `metdadataOptions: {}` under spec in AWSNodeTemplates which fixed this issue. This is no longer possible so Karpenter is completely broken.  All AWS Regions either need to be fully supported (tall order) or restoration of additional customization needs to be added to `EC2NodeClass`. I recommend those who can to pressure their AWS support reps and hopefully we can get through to the karpenter project owners.

**Comment by atelal** [comment]
Hello,
I can still edit the docs if needed.
Thanks.

**Comment by atelal** [comment]
Hello,
I can still edit the docs if needed.
Thanks.
