### ISSUE TITLE
Filebeat to send karpenter controller logs(runing on bottlerocket OS) to elastic search

### ISSUE THREAD

**Issue by dhanutalari** [aws/karpenter-provider-aws#6693]
### Description

Hi 
iam running karpenter controller in bottlerocket os , I am trying to forward the karpenter controller logs to graylog elastic search using filebeat.
if i use volume mount with host path getting below error.
Error: failed to generate container "4580c2878f037c731ae6df75dfd2fea0ca917ee252d913379d05546553fdea53" spec: failed to apply OCI options: failed to mkdir "/.bottlerocket/rootfs/var/log/pods/": mkdir /.bottlerocket: read-only file system

if i use "shareProcessNamespace: true" , iam getting Permission denied

/proc/7/root/proc/34/task/40/ns': Permission denied

Please share suggestion implement fileabeat to send karpenter controller logs to elastic search.

**Comment by njtran** [comment]
you can't do `mkdir` in bottlerocket, as the log shares. This is a bottlerocket specific issue, please cut an issue with in https://github.com/bottlerocket-os/bottlerocket as this isn't an issue with Karpenter
