### ISSUE TITLE
Grafana Dashboard needs updated for newer APIs

### ISSUE THREAD

**Issue by jukie** [aws/karpenter-provider-aws#6696]
### Description

**Observed Behavior**:
Dashboard still uses older metrics and types (e.g. provisioner vs nodepool)

**Expected Behavior**:
Dashboard to be compatible with latest version

**Reproduction Steps** (Please include YAML):

**Versions**:
- Chart Version:
- Kubernetes Version (`kubectl version`):

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by jukie** [comment]
Looks like the json source has been updated in the repo but the dashboard needs updated in grafana.com

https://github.com/aws/karpenter-provider-aws/blob/d678b0d7907118b141b31767e6c72aaa90becd90/designs/metrics.md?plain=1#L186

**Comment by njtran** [comment]
I've reached out to the person who made the dashboard to see if they can update the dashboard.

**Comment by njtran** [comment]
Updating further, we don't have plans to maintain and upkeep this dashboard. Thoughts on if we should delete it or just keep it around knowing it's stale?

**Comment by njtran** [comment]
I'm going to take the opinion that this is something we don't need to maintain, but will keep up to not break anyone who's still relying on it. Feel free to cut an issue if you feel strongly the contrary
