### ISSUE TITLE
post-install-hook uses image version of kubectl that does not have arm64 support

### ISSUE THREAD

**Issue by kayneb** [aws/karpenter-provider-aws#6751]
### Description

**Observed Behavior**:
Image pull errors on post install hook

**Expected Behavior**:
No image pull errors on post install hook

**Reproduction Steps** (Please include YAML):
Install Karpenter v0.35.6 on arm64 nodes
On an arm64 machine, run `docker pull public.ecr.aws/bitnami/kubectl:1.30`

**Versions**:
- Chart Version: 0.35.6
- Kubernetes Version (`kubectl version`): 1.28.11

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by njtran** [comment]
Thanks for the message, you can configure the image in your helm values. https://github.com/aws/karpenter-provider-aws/pull/6754 adds a note to include this.
