### ISSUE TITLE
[Karpenter] Not able to run postInstallHook

### ISSUE THREAD

**Issue by raghavanrrs** [aws/karpenter-provider-aws#6761]
### Description

**Observed Behavior**:

Failed to pull image "public.ecr.aws/bitnami/kubectl:1.30@sha256:13a2ad1bd37ce42ee2a6f1ab0d30595f42eb7fe4a90d6ec848550524104a1ed6": rpc error: code = NotFound desc = failed to pull and unpack image "public.ecr.aws/bitnami/kubectl@sha256:13a2ad1bd37ce42ee2a6f1ab0d30595f42eb7fe4a90d6ec848550524104a1ed6": no match for platform in manifest: not found
**Expected Behavior**:

postInstallHook should be able to download the image digest mentioned and run the scripts.

**Reproduction Steps** (Please include YAML):

Upgrade to version 1.0.0
Running on EKS Bottlerocket **ARM64** node AMI version: 1.20.5-a3e8bda1

**Versions**:
- Chart Version: 1.0.0
- Kubernetes Version (`kubectl version`): 1.28

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by engedaam** [comment]
This is currently mentioned as part of the v1 migration guide upgrade https://karpenter.sh/docs/upgrading/v1-migration/

**Comment by syed-faraz** [comment]
> I swapped out to the dockerhub sourced bitnami kubectl image which does have arm64 builds:
> 
> _values.yaml_
> 
> ```yaml
> postInstallHook:
>   image:
>     repository: bitnami/kubectl
>     tag: "1.30"
>     digest: sha256:13210e634b6368173205e8559d7c9216cce13795f28f93c39b1bb8784cac8074
> ```
> 
> The actual fix should be multiplatform builds on ECR.

Unfortunately version v1 also still has this issue. Your solution worked, thanks.
