### ISSUE TITLE
NodeClasses

### ISSUE THREAD

**Issue by raghavanrrs** [aws/karpenter-provider-aws#6762]
Update the content to support latest version required key:

from:
nodeClassRef:
        apiVersion: karpenter.k8s.aws/v1
        kind: EC2NodeClass
        name: default

to:
nodeClassRef:
        group: karpenter.k8s.aws/v1
        kind: EC2NodeClass
        name: default

**Comment by engedaam** [comment]
Can you provide what version of karpenter you are seeing this on? Also can you provide more information to what you are expecting?

**Comment by raghavanrrs** [comment]
Kindly ignore, can see the updated content.
