### ISSUE TITLE
Allow for gracefulTerminationPeriod for node expiration / expireAfter

### ISSUE THREAD

**Issue by ecerulm** [aws/karpenter-provider-aws#6764]
### Description

**What problem are you trying to solve?**

I have a workload (airflow worker tasks)  consisting only of relatively short-lived pods (10minutes to 6 hours) assigned to a given `NodePool` with with `consolidationPolicy: WhenEmpty`. New pods are created at an unpredictable rate.

Karpenter is able to scale up (spinning new EKS nodes) fine.  But when the rate of new pods decreases nodes are not shutdown because new pods arrive and they are scheduled to any of the existing nodes in the `NodePool`, so they never achieve the "empty" condition. 

In order to force certain amount of scale down, I though of using **`expireAfter`**  but it has the drawback of killing / evicting the pods which I don't want. 

I would like to have  a **configurable graceful termination period** after `expireAfter` where the node is **cordoned** (marking it as unavailable for the scheduler )  , thus no new pods will be started on that node. Then the pod in that node will have enough time to finish in their own before the node is actually shuts down. If the node becomes empty during the graceful termination period it can be shut down right away.

My proposal would be to have 

```
spec:
  disruption:
    consolidationPolicy: WhenEmpty
    expireAfter: 24h
    gracefulTerminationPeriod: 8h
```

**How important is this feature to you?**

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by ecerulm** [comment]
I can submit a PR if the proposal is accepted.

**Comment by jmdeal** [comment]
Have you taken a look at [terminationGracePeriod](https://karpenter.sh/docs/concepts/nodepools/#spectemplatespecterminationgraceperiod)? It sounds like this should meet your use-case exactly.

**Comment by ecerulm** [comment]
No, I didn't know about NodePool `spec.template.spec.terminationGracePeriod`, I guess this is a new addition to Karpenter 1.0.0 released yesterday (2024-08-14) because I could find it when I looked in the [0.37 documentation for NodePool](https://karpenter.sh/v0.37/concepts/nodepools/#specdisruption). 

I agree that this cover exactly  what I want so I'm closing this
