### ISSUE TITLE
Allow podlabel in post-install-hook job

### ISSUE THREAD

**Issue by joshiparth1000** [aws/karpenter-provider-aws#6772]
### Description

**What problem are you trying to solve?**
We currently run karpenter on fargate nodes. the helm install of karpenter does not complete on v1.0.0 since the post-install-hook does not get scheduled since there are no nodes available. if podlabel parameter is also added to the job then this pod will also get scheduled on fargate nodes

**How important is this feature to you?**
Very critical because without this the deployment doesnt succeed.

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by engedaam** [comment]
@joshiparth1000 What podlabel are you needing to apply? I was able to install v1.0 with Fargate as the capacity

**Comment by joshiparth1000** [comment]
> @joshiparth1000 What podlabel are you needing to apply? I was able to install v1.0 with Fargate as the capacity

The karpenter controller does come up on fargate but the post-install-hook job does not have pod labels in its spec so it waits for a node to come up. This causes the deployment to fail since the job does not succeed.

**Comment by engedaam** [comment]
> so it waits for a node to come up

I'm a little confused here. Are seeing the post-install-hook run get on existing capacity on the cluster when it should have wait for the Fargate node? If so, what are the logs you are seeing? can you share those?

**Comment by joshiparth1000** [comment]
> > so it waits for a node to come up
> 
> I'm a little confused here. Are seeing the post-install-hook run get on existing capacity on the cluster when it should have wait for the Fargate node? If so, what are the logs you are seeing? can you share those?

So, let say you are building a brand new cluster from scratch. First thing you want is karpenter so that nodes can be scheduled for other workloads. Using the podlabels in the karpenter helm chart i am able to get the controller scheduled on fargate. This same podlabel is not available on the post-install-hook so it waits for a node to be available and is in pending state. Keep in mind i have not yet defined ec2nodeclass or nodepool since that is a subsequent activity after installing karpenter. If the same podlabel was assigned to the post-install-hook as the controller then it will also be scheduled on fargate and the helm deployment. Since thats not done the helm install fails and the job is in pending state.

**Comment by engedaam** [comment]
The post install hook main purpose is to adjust the [conversion block](https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definition-versioning/#service-reference) of the Karpenter CRDs to align it to the conversion webhook configuration set on Karpenter controller. As a workaround, you can disable the the post install hook by include `--no-hooks` flag as part of the helm upgrade, and utilize the `karpenter-crd` helm chart as a mechanism to configure the webhook configuration on the CRDs.

**Comment by dom-raven** [comment]
We're currently experiencing this issue as well while using Terraform, we're using [helm_release](https://registry.terraform.io/providers/hashicorp/helm/latest/docs/resources/release).  `disable_webhooks = true` seems to temporarily resolve the problem while we await a fix.

**Comment by engedaam** [comment]
The post install hooks have now been removed and released https://github.com/aws/karpenter-provider-aws/releases/tag/v1.0.1
