### ISSUE TITLE
The v1.0.0 chart installs v1beta1 CRDs

### ISSUE THREAD

**Issue by diranged** [aws/karpenter-provider-aws#6778]
### Description

**Observed Behavior**:
The [v1.0.0](https://github.com/aws/karpenter-provider-aws/tree/v1.0.0/charts/karpenter/crds) helm chart is pointing to the `v1beta1` CRDs - causing Karpenter to fail to start up upon installation. The `kubernetes-crd` chart could be used ... except that Helm will not overwrite existing resources once they've previously been installed, making it impossible to upgrade.

<img width="946" alt="image" src="https://github.com/user-attachments/assets/1d6f1eec-77cd-461d-8caf-fc3857333070">

**Expected Behavior**:
The v1.0.0 chart should be installing the V1 CRDs.

**Comment by diranged** [comment]
Ok.. interesting. I take it back - the comment on the far right tricked me. The reason I ever looked in the first place though is that when we install Karpenter (via AWS CDK via the `HelmChart` resource type), and we upgrade from `0.37.0` -> `1.0.0`, the application itself gets updated ... but the CRDs stay the same (v1beta1). That causes the Karpenter pods to come up like this:

<img width="1650" alt="image" src="https://github.com/user-attachments/assets/1927aa41-c28c-46e6-8583-66175bc03b29">

If you force an upgrade using `kubectl apply -f https://raw.githubusercontent.com/aws/karpenter-provider-aws/v1.0.0/pkg/apis/crds/karpenter.sh_nodeclaims.yaml https://raw.githubusercontent.com/aws/karpenter-provider-aws/v1.0.0/pkg/apis/crds/karpenter.sh_nodepools.yaml https://raw.githubusercontent.com/aws/karpenter-provider-aws/v1.0.0/pkg/apis/crds/karpenter.k8s.aws_ec2nodeclasses.yaml` .. you run into a new problem because those CRDs have a hard-coded namespace for the karpenter service (`kube-system`) and that fails like this:

```
{"level":"INFO","time":"2024-08-16T00:59:28.895Z","logger":"controller","caller":"cache/reflector.go:353","message":"k8s.io/client-go@v0.30.3/tools/cache/reflector.go:232: failed to list *v1.NodeClaim: conversion webhook for karpenter.sh/v1beta1, Kind=NodeClaim failed: Post \"https://karpenter.kube-system.svc:8443/?timeout=30s\": service \"karpenter\" not found","commit":"5bdf9c3"}
{"level":"ERROR","time":"2024-08-16T00:59:28.895Z","logger":"controller","caller":"cache/reflector.go:299","message":"k8s.io/client-go@v0.30.3/tools/cache/reflector.go:232: Failed to watch *v1.NodeClaim: failed to list *v1.NodeClaim: conversion webhook for karpenter.sh/v1beta1, Kind=NodeClaim failed: Post \"https://karpenter.kube-system.svc:8443/?timeout=30s\": service \"karpenter\" not found","commit":"5bdf9c3"}
```

So ... I guess the thing is.. the upgrade process to 1.0.0 is pretty rough. When you have dozens or hundreds of clusters, it can't be a manual process.

**Comment by jigisha620** [comment]
Hi @diranged ,
Can you not upgrade your CRDs using this which allows you to specify namespace in which Karpenter is installed?
```
helm upgrade --install karpenter-crd oci://public.ecr.aws/karpenter/karpenter-crd --version "${KARPENTER_VERSION}" --namespace "${KARPENTER_NAMESPACE}" --create-namespace \
    --set webhook.enabled=true \
    --set webhook.serviceName=karpenter \
    --set webhook.serviceNamespace="${KARPENTER_NAMESPACE}" \
    --set webhook.port=8443
```

**Comment by diranged** [comment]
> Hi @diranged , Can you not upgrade your CRDs using this which allows you to specify namespace in which Karpenter is installed?
> 
> ```
> helm upgrade --install karpenter-crd oci://public.ecr.aws/karpenter/karpenter-crd --version "${KARPENTER_VERSION}" --namespace "${KARPENTER_NAMESPACE}" --create-namespace \
>     --set webhook.enabled=true \
>     --set webhook.serviceName=karpenter \
>     --set webhook.serviceNamespace="${KARPENTER_NAMESPACE}" \
>     --set webhook.port=8443
> ```

So the original CRDs were installed as a byproduct of the main `karpenter` helm chart installation... so we actually have to do a `helm install` instead of a `helm upgrade`. The problem is the `helm install` fights with the existing CRD resources! Also, I can't seem to get past this error:

```
% helm template foo oci://public.ecr.aws/karpenter/karpenter-crd
Error: GET "https://public.ecr.aws/v2/karpenter/karpenter-crd/tags/list": unexpected status code 403: denied: Your authorization token has expired. Reauthenticate and try again.
% helm registry logout public.ecr.aws
Error: not logged in
% helm template foo oci://public.ecr.aws/karpenter/karpenter-crd
Error: GET "https://public.ecr.aws/v2/karpenter/karpenter-crd/tags/list": unexpected status code 403: denied: Your authorization token has expired. Reauthenticate and try again.
```

**Comment by stevehipwell** [comment]
@diranged Helm doesn't modify CRDs by design, so you need to manage them externally to the main chart.

FYI I can run `helm template foo oci://public.ecr.aws/karpenter/karpenter-crd` and it works correctly (although I'd suggest using the `--version` flag). What version of Helm are you using?

**Comment by diranged** [comment]
```
% helm version
version.BuildInfo{Version:"v3.15.4", GitCommit:"fa9efb07d9d8debbb4306d72af76a383895aa8c4", GitTreeState:"clean", GoVersion:"go1.22.6"}
```

I've also tried wiping out my `$HOME/.config` directory to make sure no helm bits are laying around...

**Comment by diranged** [comment]
I don't really understand how this is supposed to work:
```
% helm template foo oci://public.ecr.aws/karpenter/karpenter-crd --debug 
install.go:222: [debug] Original chart version: ""
Error: GET "https://public.ecr.aws/v2/karpenter/karpenter-crd/tags/list": unexpected status code 403: denied: Your authorization token has expired. Reauthenticate and try again.
helm.go:84: [debug] GET "https://public.ecr.aws/v2/karpenter/karpenter-crd/tags/list": unexpected status code 403: denied: Your authorization token has expired. Reauthenticate and try again.
% curl https://public.ecr.aws/v2/karpenter/karpenter-crd/tags/list
{"errors":[{"code":"DENIED","message":"Not Authorized"}]}
```

**Comment by stevehipwell** [comment]
@diranged I suspect it might be related to the login/logout for ECR public, so it might be worth checking Docker ETC to see if there is something stuck there?

**Comment by diranged** [comment]
Ok ... I figured out how to log in. I don't know why this is what _I_ have to do, when the karpenter docs specifically tell me to log out .. but i'll leave this here for the next person:

```
aws ecr-public get-authorization-token --region us-east-1 --output=text --query 'authorizationData.authorizationToken' | base64 -d  | awk -F':' '{print $2}' | helm registry login public.ecr.aws --password-stdin --username AWS --debug
Login Succeeded
```

**Comment by diranged** [comment]
Ok... and I figured out how to make Helm accept the existing CRDs. Now this kind of sucks because if you have dozens or hundreds of clusters, you have to figure out how to run this everywhere, and we don't typically allow humans to do these actions. But here it is for posterity. This will allow you to run `helm template ...` (or use CDK's `HelmChart`) to take over existing CRDs and put them into a Helm chart:

```bash
    kubectl --context $CLUSTER annotate crd $CRD app.kubernetes.io/managed-by=Helm
    kubectl --context $CLUSTER annotate crd $CRD meta.helm.sh/release-name=karpenter-crd
    kubectl --context $CLUSTER annotate crd $CRD meta.helm.sh/release-namespace=karpenter-system
    kubectl --context $CLUSTER label crd $CRD app.kubernetes.io/managed-by=Helm
```

```
% helm install karpenter-crd oci://public.ecr.aws/karpenter/karpenter-crd --set webhook.serviceNamespace=karpenter-system 
Pulled: public.ecr.aws/karpenter/karpenter-crd:1.0.0
Digest: sha256:f252259ec545db990ff821d6e718e489fe0834c26847d5c6c5730c173e14f167
NAME: karpenter-crd
LAST DEPLOYED: Fri Aug 16 05:34:32 2024
NAMESPACE: karpenter-system
STATUS: deployed
REVISION: 1
TEST SUITE: None
```

**Comment by diranged** [comment]
Ok .. so I think we can close this. The issue is invalid. The one note I will give here is that by forcing the _generated CRDs_ at https://github.com/aws/karpenter-provider-aws/blob/v1.0.0/pkg/apis/crds/karpenter.k8s.aws_ec2nodeclasses.yaml#L1336-L1346 to have a hard-coded webhook in it, you make it relatively difficult for people to just use `kubectl apply <crd>`... I would recommend that the generated CRD _do not_ have the conversion webhook, and only the `karpenter-crd` chart templates should have that.

Ref: https://github.com/aws/karpenter-provider-aws/blob/v1.0.0/pkg/apis/crds/karpenter.k8s.aws_ec2nodeclasses.yaml#L1336-L1346

**Comment by diranged** [comment]
(we have both a legacy and modern way of managing cluster startup... and our modern model uses CDK and the `HelmChart` resource.. but the legacy model relies exclusively on `kubectl`)
