### ISSUE TITLE
Add Bottlerocket support for kubeletConfiguration.cpuCFSQuota

### ISSUE THREAD

**Issue by ecerulm** [aws/karpenter-provider-aws#6782]
### Description

**What problem are you trying to solve?**

Bottlerocket AMI now support CPU quota enforcement `settings.kubernetes.cpu-fs-quota-enforced` (see https://github.com/bottlerocket-os/bottlerocket/pull/2930) . We should pass these additinal properties from the `kubeletConfiguration` into the TOML. 

**How important is this feature to you?**

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by jigisha620** [comment]
Hi @ecerulm,
This is already being supported [kubeletConfiguration.cpuCFSQuota](https://github.com/aws/karpenter-provider-aws/blob/v1.0.0/pkg/providers/amifamily/bootstrap/bottlerocketsettings.go#L75).

**Comment by jigisha620** [comment]
@ecerulm , thanks for pointing this out. I will go ahead and update the documentation since the change to support this field was merged - https://github.com/aws/karpenter-provider-aws/pull/4260
