### ISSUE TITLE
Post install hook should be optional

### ISSUE THREAD

**Issue by stevehipwell** [aws/karpenter-provider-aws#6784]
### Description

**What problem are you trying to solve?**
My CRDs as they are managed externally so I don't want or need the post install hook running. I'd like to be able to disable them vai the Helm chart values.

**How important is this feature to you?**
This is important as due to #6775 I need to manually provide a smaller image that works on ARM64 even though I don't want or need the functionality.

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by engedaam** [comment]
You should be able to include the `--no-hooks` flag as part of the helm chart, and disable the post install hook all together, no?

**Comment by danielloader** [comment]
https://github.com/argoproj/argo-cd/issues/4331 might not work so well with Argo CD as one aspect to this problem.

**Comment by stevehipwell** [comment]
@engedaam I could use `--no-hooks`, but I shouldn't need to use a separate concept to do this and there is always the risk that this setting (this is IaC usage) isn't removed and impacts another future hook which is required.

**Comment by danielloader** [comment]
I'd be able to skip this via `argocd.argoproj.io/hook: Skip` as an annotation on the job, but since the annotation is universal and applied to all resources which isn't the desired outcome either.

**Comment by stevehipwell** [comment]
I see the hook has been removed, but we need a release ASAP as the whole hook implementation is flawed.

When adding in a helper like a Helm hook much more attention to detail needs to be taken and it needs to be much more configurable. The current implementation is effectively tightly coupled to a non-standard and bloated `kubectl` image with no way of disabling the hook template or substituting in a "good" `kubectl` image such as `registry.k8s.io/kubectl`.

**Comment by Vinaum8** [comment]
@stevehipwell Has the hook been removed? Do you know which version it will come out in?

**Comment by stevehipwell** [comment]
@Vinaum8 it was removed on `main` but AFAIK the change hasn't been released.

**Comment by engedaam** [comment]
We have just released the change with removing the post install hook https://github.com/aws/karpenter-provider-aws/releases/tag/v1.0.1
