### ISSUE TITLE
Wrong url for getting-started-with-karpenter/cloudformation.yaml for v.1.0.0

### ISSUE THREAD

**Issue by ybezsonov** [aws/karpenter-provider-aws#6790]
### Description

**How can the docs be improved?**
Documentation https://karpenter.sh/v1.0/getting-started/getting-started-with-karpenter/ has wrong url to download cloudformation.yaml

Current version has 
https://raw.githubusercontent.com/aws/karpenter-provider-aws/v1.0.0/website/content/en/v1.0/getting-started/getting-started-with-karpenter/cloudformation.yaml

Should it be replaced with the url below, like in https://karpenter.sh/v1.0/upgrading/v1-migration/ ?
https://raw.githubusercontent.com/aws/karpenter-provider-aws/v"${KARPENTER_VERSION}"/website/content/en/preview/getting-started/getting-started-with-karpenter/cloudformation.yaml

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by jonathan-innis** [comment]
Yep, this looks wrong. Should be pretty easy to make a fix. I'll throw one up.
