### ISSUE TITLE
Only generation 5 for R instance families ?

### ISSUE THREAD

**Issue by ckhelifi** [aws/karpenter-provider-aws#6807]
### Description

**Observed Behavior**:

Karpenter does ask for only generation 5 for R instance families.

**Expected Behavior**:

I expected to see almost only generation 7 instances as they are the newest .

**Reproduction Steps** (Please include YAML):

```
apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  annotations:
    karpenter.sh/provisioner-hash: "6924582558972346519"
    meta.helm.sh/release-name: karpenter-provisioners
    meta.helm.sh/release-namespace: kube-system
  creationTimestamp: "2024-01-31T18:53:26Z"
  generation: 4
  labels:
    app.kubernetes.io/managed-by: Helm
  name: paiement-private-amd64-r-spot-blue
  resourceVersion: "3471024904"
  uid: 020b602c-416b-437c-9ee7-a75c2504a7f4
spec:
  consolidation:
    enabled: true
  labels:
    mmb.fr/arch: amd64
    mmb.fr/capacity-type: spot
    mmb.fr/color: blue
    mmb.fr/domain: paiement
    mmb.fr/instance-category: r
    mmb.fr/network: private
  providerRef:
    name: paiement-private-amd64-r-spot-blue
  requirements:
  - key: karpenter.k8s.aws/instance-category
    operator: In
    values:
    - r
  - key: karpenter.k8s.aws/instance-size
    operator: In
    values:
    - large
    - xlarge
    - 2xlarge
    - 4xlarge
    - 8xlarge
  - key: kubernetes.io/os
    operator: In
    values:
    - linux
  - key: kubernetes.io/arch
    operator: In
    values:
    - amd64
  - key: karpenter.sh/capacity-type
    operator: In
    values:
    - spot
  taints:
  - effect: NoSchedule
    key: mmb.fr/domain
    value: paiement
  - effect: NoSchedule
    key: mmb.fr/instance-category
    value: r
  weight: 80
```

**Versions**:
- Version: v0.31.3

**Comment by jmdeal** [comment]
Instance generation is not a factor when Karpenter is comparing instance types. When using `on-demand` instances Karpenter will launch the cheapest instance available that is compatible with your pending workload. It looks like you're using spot instances, which are provisioned using `CreateFleet`'s [price-capacity-optimized allocation strategy](https://aws.amazon.com/blogs/compute/introducing-price-capacity-optimized-allocation-strategy-for-ec2-spot-instances/). This strategy balances price and availability of the spot instance (to help minimize interruptions). 

If you want to prioritize newer generation instances, you could create multiple weighted NodePools, with the higher weight NodePool only selecting newer instances.

**Comment by ckhelifi** [comment]
Hi,

Thanks for your answer and informations !

You can close this.

Appreciate,

**Comment by hirenko-v** [comment]
@jmdeal is your comment is still relevant? 
we use list of instance types In Nodepool:
```
              - key: node.kubernetes.io/instance-type
                operator: In
                values:
                - m6a.2xlarge
                - m5.2xlarge
                - m7a.2xlarge
        ```
                
     and Karpenter always picks m7a.2xlarge which is the mist expensive

**Comment by jmdeal** [comment]
Are you using spot or on-demand? Do you have any other requirements on your NodePool or workloads that are further restricting the available instance types? 

If you are using spot, this could certainly still apply if the availability of the `m7a` instance type is better than the other options.

**Comment by hirenko-v** [comment]
@jmdeal 
It is on-demand with no other requirements, just instance-type
