### ISSUE TITLE
How to upgrade AMI to latest version in a controlled manner?

### ISSUE THREAD

**Issue by artem-nefedov** [aws/karpenter-provider-aws#6862]
### Description

**How can the docs be improved?**

I was going for the following setup:

1. Specify `amiSelectorTerms: [{"alias": "al2023@latest"}]` in EC2NodeClass
2. Specify `expireAfter: 720h` in NodePool with the hope of nodes being recycled every 30 days to restart with latest AMI version

However, later I realised this will not work as I expected, because description for "alias" field states that new AMI will cause drift, in which case, specifying `expireAfter` for the sake of update is pointless, since the nodes will be recycled immediately after new AMI becomes available. The existing docs are not clear about this scenario.

My question is how to actually implement the desired scenario, and is it even possible. Updating related docs would make sense too, as I could only find out about drift after looking at CRD spec.

Even more, the description of `expireAfter` field suggests that it should be used for this case:

>   expireAfter   <string>
    ExpireAfter is the duration the controller will wait
    before terminating a node, measured from when the node is created. This
    is useful to implement features like **eventually consistent node upgrade**,
    memory leak protection, and disruption testing.

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by jmdeal** [comment]
That's a good callout on the `expireAfter` docs, I'm going to guess that wording was from a pre-drift. This is no longer a recommended way to cycle nodes for AMI upgrades, this should be orchestrated by Drift. `amiSelectorTerms` is specified under [Special Cases on Drift](https://karpenter.sh/docs/concepts/disruption/#special-cases-on-drift) in the disruption docs; values in `amiSelectorTerms` are dynamically resolved and if a new AMI is resolved for a term the node will be drifted. This applies to alias in the same way it applies to other terms (e.g. tags).

**Comment by calvinbui** [comment]
With v1, drift can't be disabled. 

We tag new AMIs for Karpenter to use, let existing nodes naturally consolidate/refresh/expire and bring up new nodes with the newer AMI.

It was a gradual rollout and we felt safer than replacing all nodes at once. 

@jmdeal is there a way to keep the above/previous workflow?

**Comment by jmdeal** [comment]
Since you found a solution I'm going to close this issue, feel free to reopen if needed.
