### ISSUE TITLE
Nodepool `.status.resources.pods` doesn't seem to be accurate

### ISSUE THREAD

**Issue by williwlwilliwll** [aws/karpenter-provider-aws#6878]
### Description

The number of pods reported by my 3 nodepools is way off the number of pods I can see with kubectl. Why would this be? 

**Observed Behavior**:
```
kubectl --all-namespaces=true get pods | wc -l
     246
```

```
kubectl get nodepools --output=custom-columns=STATUS:.status
STATUS
map[resources:map[cpu:40 ephemeral-storage:229830436Ki memory:113316656Ki pods:238]]
map[resources:map[cpu:6 ephemeral-storage:62681028Ki memory:5859792Ki pods:24]]
map[resources:map[cpu:22 ephemeral-storage:167149408Ki memory:60206512Ki pods:183]]
```

**Expected Behavior**:
I would expect the number of pods returned by both of the above commands to be roughly the same 

**Reproduction Steps** (Please include YAML):

**Versions**:
- Chart Version:
0.37.1
- Kubernetes Version (`kubectl version`):
1.30.2

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by williwlwilliwll** [comment]
Could the numbers that I am seeing in the Nodepools' `.status.resources` be cumulative? The total pods/CPU/memory that the nodepool has ever provisioned?

**Comment by engedaam** [comment]
Yes, the `.status.resources` is the total capacity currently provisioned within that nodepool. In the case of your three nodepools, the `.status.resources.pods` represent the total amount of pods that could be scheduled on the provisioned  nodeclaims.
