### ISSUE TITLE
CRD configuration leads to v1 resources being served by default on v0.37.2

### ISSUE THREAD

**Issue by msaah-benchling** [aws/karpenter-provider-aws#6897]
### Description

**Observed Behavior**:
While running 0.37.2, I expect to be able to use `kubectl edit nodepool foo`. However, this returns:
```
#·nodepools.karpenter.sh·"foo"·was·not·valid:$
#·*·spec.template.spec.nodeClassRef.group:·Required·value$
#·*·spec.template.spec.nodeClassRef.kind:·Required·value$
#·*·spec.disruption.consolidationPolicy:·Unsupported·value:·"WhenUnderutilized":·supported·values:·"WhenEmpty",·"WhenEmptyOrUnderutilized"$
#·*·spec.disruption.consolidateAfter:·Required·value$
#·*·<nil>:·Invalid·value:·"null":·some·validation·rules·were·not·checked·because·the·object·was·invalid;·correct·the·existing·errors·to·complete·validation$
```

`kubectl edit nodepools.v1beta1.karpenter.sh foo` works as expected.

I believe this is ultimately because `v1` is being served by default:
```
kubectl get nodepool foo -oyaml | grep apiVersion
apiVersion: karpenter.sh/v1
```

~this could potentially be mitigated by enabling the [conversion webhook](https://github.com/aws/karpenter-provider-aws/blob/v0.37.2/charts/karpenter-crd/templates/karpenter.sh_nodepools.yaml#L1022-L1034), which is [disabled by default](https://github.com/aws/karpenter-provider-aws/blob/v0.37.2/charts/karpenter-crd/values.yaml#L3).~ this did not work.

**Expected Behavior**:

`kubectl edit` works without specifying the fully qualified version. more broadly, v1beta1 should be served by default since it's still to my knowledge it's still the officially used version for 0.37.2.

**Reproduction Steps** (Please include YAML):
install karpenter crds from helm chart 0.37.2 with default values

**Versions**:
- Chart Version: 0.37.2
- Kubernetes Version (`kubectl version`): kubectl 1.28.2

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by dblackdblack** [comment]
Simple repro case:
```
$ kubectl --kubeconfig kubeconfig.yaml --context my-cluster-context annotate nodepool.v1beta1.karpenter.sh/graviton foo=bar

The NodePool "graviton" is invalid: 
* spec.template.spec.nodeClassRef.group: Required value
* spec.template.spec.nodeClassRef.kind: Required value
* spec.disruption.consolidationPolicy: Unsupported value: "WhenUnderutilized": supported values: "WhenEmpty", "WhenEmptyOrUnderutilized"
* spec.disruption.consolidateAfter: Required value
* <nil>: Invalid value: "null": some validation rules were not checked because the object was invalid; correct the existing errors to complete validation
```

**Comment by engedaam** [comment]
Unfortunately, this is how Kubernetes default versioning works https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definition-versioning/#version-priority. If there are more then one version supported by CRDs `kubectl` will need users specify the version to be served if it's not the latest. for example `kubectl get nodepool.v1beta1.karpenter.sh`

**Comment by msaah-benchling** [comment]
@engedaam understood thanks. perhaps it could be noted in the docs (maybe in the upgrade guides) for any versions pre-1.0 versions that enable both v1 and v1beta.
