### ISSUE TITLE
Error while downgrading Karpenter

### ISSUE THREAD

**Issue by vipul0805** [aws/karpenter-provider-aws#6910]
Version
Karpenter Version: v0.37.0

Kubernetes Version: v1.3

Expected Behavior
Get CR's after applying the CRD.

Actual Behavior
Not able to get CR's after applying the v1beta1 CRD's. I was rolling back karpenter from v1.0.0 -> 0.37.0 and removed all the components in my cluster and did a fresh installation.

I am seeing this error while getting the nodeclaims and ec2nodeclasses

```Error from server: request to convert CR from an invalid group/version: karpenter.k8s.aws/v1```
Can anyone please help me identify what's wrong here.

**Comment by engedaam** [comment]
Did you remove the Karpenter CRDs as well?

**Comment by vipul0805** [comment]
I found the root cause for this. The nodeclaims and ec2nodeclasses were lying around in the cluster even after deleting the CRDs.

closing this issue. Thanks
