### ISSUE TITLE
Karpenter deleting drifted nodes with reason SecurityGroupDrift even though there is no change in the security group

### ISSUE THREAD

**Issue by vipul0805** [aws/karpenter-provider-aws#6913]
### Description

**Observed Behavior**:
Karpenter deleting nodes with reason securityGroupDrift even though there is no change In the security group.

Karpenter Logs:
```
{"level":"DEBUG","time":"2024-09-02T10:22:25.036Z","logger":"controller","caller":"disruption/controller.go:91","message":"marking drifted","commit":"62a726c","controller":"nodeclaim.disruption","controllerGroup":"karpenter.sh","controllerKind":"NodeClaim","NodeClaim":{"name":"al2-9x6cm"},"namespace":"","name":"al2-9x6cm","reconcileID":"ef9fbbda-8a18-4ebc-8378-e1455235597a","reason":"SecurityGroupDrift"}
```
**Expected Behavior**:
There should be no deletion of nodes with reason securityGroupDrift
**Reproduction Steps** (Please include YAML):
```
apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  annotations:
    karpenter.sh/nodepool-hash: "18440777320956233133"
    karpenter.sh/nodepool-hash-version: v3
    meta.helm.sh/release-name: nodepool
    meta.helm.sh/release-namespace: karpenter
  creationTimestamp: "2024-09-02T10:06:11Z"
  generation: 1
  labels:
    app: raw
    app.kubernetes.io/managed-by: Helm
    chart: raw-0.2.3
    heritage: Helm
    release: nodepool
  name: al2
  resourceVersion: "867401464"
  uid: 714495e7-f180-4841-b8ee-e358cc40256b
spec:
  disruption:
    budgets:
    - nodes: 10%
    consolidateAfter: Never
    consolidationPolicy: WhenEmpty
  limits:
    cpu: "120"
    memory: 320Gi
  template:
    metadata:
      labels:
        errors.ea.com/linux-distro: al2
    spec:
      expireAfter: 720h
      nodeClassRef:
        group: karpenter.k8s.aws
        kind: EC2NodeClass
        name: al2
      requirements:
      - key: topology.kubernetes.io/zone
        operator: In
        values:
        - us-east-1a
        - us-east-1b
      - key: node.kubernetes.io/instance-type
        operator: In
        values:
        - c5.large
        - c5.xlarge
        - c5.2xlarge
        - c6i.large
        - c6i.xlarge
        - c6i.2xlarge
        - m5.large
        - m5.xlarge
        - m5.2xlarge
        - m6i.large
        - m6i.large
        - m6i.2xlarge
        - r5.large
        - r5.xlarge
        - r6i.large
        - r6i.xlarge
        - t3.small
        - t3.medium
        - t3.large
        - t3.xlarge
        - t3.2xlarge
      - key: kubernetes.io/arch
        operator: In
        values:
        - amd64
      - key: kubernetes.io/os
        operator: In
        values:
        - linux
      - key: karpenter.sh/capacity-type
        operator: In
        values:
        - on-demand
```

```
apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  annotations:
    karpenter.k8s.aws/ec2nodeclass-hash: "2204428126396386490"
    karpenter.k8s.aws/ec2nodeclass-hash-version: v3
    meta.helm.sh/release-name: nodepool
    meta.helm.sh/release-namespace: karpenter
  creationTimestamp: "2024-09-02T10:06:11Z"
  finalizers:
  - karpenter.k8s.aws/termination
  generation: 1
  labels:
    app: raw
    app.kubernetes.io/managed-by: Helm
    chart: raw-0.2.3
    heritage: Helm
    release: nodepool
  name: al2
  resourceVersion: "867406141"
  uid: 78db21aa-dded-40a8-aa1a-02770631c7c6
spec:
  amiFamily: AL2
  amiSelectorTerms:
  - alias: al2@latest
  metadataOptions:
    httpEndpoint: enabled
    httpProtocolIPv6: disabled
    httpPutResponseHopLimit: 1
    httpTokens: required
  role: KarpenterNodeRole-XXX
  securityGroupSelectorTerms:
  - tags:
      karpenter.sh/discovery: XXX
  subnetSelectorTerms:
  - tags:
      karpenter.sh/discovery: XXX
```
**Versions**:
- Chart Version: 1.0.1
- Kubernetes Version (`kubectl version`):
```
Client Version: v1.23.15
Server Version: v1.30.2-eks-db838b0
```

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by engedaam** [comment]
Are there any process inside of the account that would be tagging/untagging security group(SG)? Keep in mind SG drift is considered a [special case of drift](https://karpenter.sh/docs/concepts/disruption/#special-cases-on-drift). If SGs inside of the AWS account are being tagged or untagged that karpenter discovers, that can causel nodes to be drifted.

**Comment by vipul0805** [comment]
I don't think that there are any processes inside the account or EKS cluster that might be modifying the tags. Karpenter is still deleting the nodes even when I disable `Drift` from budgets.

**Comment by engedaam** [comment]
Since you have not defined any budget that relates to drift, all drifted nodes will be disrupted. Budgets only block based on what is defined or else it defaults to allow disruption: https://karpenter.sh/docs/concepts/disruption/#reasons. To block drift you will need to an additional budget as such:

```
budgets:
  - nodes: "10%"
    reasons: 
      - "Empty"
      - "Underutilized"
  - nodes: "0"
    reasons: 
      - "Drifted"
```

Are you able to see the security groups that are discovered in the status of the EC2NodeClass? If the  SGs are updated then karpenter is discovering new SGs in the account.

**Comment by vipul0805** [comment]
Yes, I can see that it is discovering the correct SG in the EC2NodeClass.
``` conditions:
  - lastTransitionTime: "2024-09-02T10:06:11Z"
    message: ""
    reason: AMIsReady
    status: "True"
    type: AMIsReady
  - lastTransitionTime: "2024-09-02T10:06:11Z"
    message: ""
    reason: InstanceProfileReady
    status: "True"
    type: InstanceProfileReady
  - lastTransitionTime: "2024-09-02T10:06:11Z"
    message: ""
    reason: Ready
    status: "True"
    type: Ready
  - lastTransitionTime: "2024-09-02T10:06:11Z"
    message: ""
    reason: SecurityGroupsReady
    status: "True"
    type: SecurityGroupsReady
  - lastTransitionTime: "2024-09-02T10:06:11Z"
    message: ""
    reason: SubnetsReady
    status: "True"
    type: SubnetsReady
  instanceProfile: XXX
  securityGroups:
  - id: sg-XXX
    name: YYY
  subnets:
  - id: subnet-XXX
    zone: us-east-1b
    zoneID: use1-az2
  - id: subnet-XXX
    zone: us-east-1a
    zoneID: use1-az1
```

**Comment by vipul0805** [comment]
I noticed that some Security Groups are managed by our organization and are automatically added to nodes. My question is, will Karpenter detect these security groups, even if they aren't tagged for discovery, and subsequently mark the node as drifted?

**Comment by engedaam** [comment]
Yeah, if there is another process in the account adding security groups to a node or tagging a security group. Karpenter will detect those changes and consider the node drifted if the EC2NodeClass and instance security groups are not the same https://github.com/aws/karpenter-provider-aws/blob/c83c154504ca0e0b172ca3c8ac0c923ad9c1996c/pkg/cloudprovider/drift.go#L110

**Comment by scany1211** [comment]
We had the same issue, but we already disable the drift, still encountered the Securitygroupdrift. How to disable the drift completely?
```

spec:
  disruption:
    budgets:
    - nodes: 100%
      reasons:
      - Empty
    - nodes: "0"
      reasons:
      - Drifted
      - Underutilized
    consolidateAfter: 900s
    consolidationPolicy: WhenEmpty

```
