### ISSUE TITLE
Metrics "karpenter_nodepools_limit" are missing for v1

### ISSUE THREAD

**Issue by justinas-wix** [aws/karpenter-provider-aws#6914]
### Description

**Observed Behavior**: After upgrading Karpenter to v1 renamed metrics "karpenter_nodepools_limit" are not exposed.

**Expected Behavior**: "karpenter_nodepools_limit" metrics is there together with other metrics

**Reproduction Steps** (Please include YAML): Install fresh v1 on upgrade from older version. (for previous version metric was called "karpenter_nodepool_limit")
check /metrics endpoint to see the list of metrics.

- So far discovered that only this one is missing others etc: "karpenter_nodepools_usage" are there. 
- Does not exist by old name neither. 

**Versions**:
- Chart Version: 1.0.1
- Kubernetes Version (`kubectl version`): v1.28.12-eks-2f46c53 

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by justinas-wix** [comment]
We have multiple clusters where before v1 we had metric present "karpenter_nodepool_limit" for all of them. After upgrade metric "karpenter_nodepools_limit" is gone. Has something changed? Limits here shows on how many cpu's node pools have currently in total as I understand. So if I have "karpenter_nodepools_usage" > 0 then limits should also be > 0. And in no mater the situation this metric should still be present.

**Comment by engedaam** [comment]
[karpenter_nodepool_limit](https://karpenter.sh/docs/reference/metrics/#karpenter_nodepools_limit) only represents the total amount of resources on a nodepool when limits are defined on the nodepool https://karpenter.sh/docs/concepts/nodepools/#speclimits. So, if limits are not defined it is possible for `karpenter_nodepools_usage` > 0 and `karpenter_nodepool_limit` not to be present. Do you have any limits on your nodes? What version of Karpenter were you running before?

**Comment by justinas-wix** [comment]
previously it was 0.37.0 - not sure if these metrics were present when upgraded to 0.37.2 before moving to 1.0.1. 
I have checked some of the node pool configurations and it seems we do not have any limits defined for them. 
Any chance previously limits had some default values? 
OK so I'm searching for something what should not be here in the first place. My bad. We can close then.

**Comment by engedaam** [comment]
Makes sense. We have not had any default limes for v1beta1. I'm not sure why you would have seen any values for that metric
