### ISSUE TITLE
Modify kubelet configurations rather than user_data

### ISSUE THREAD

**Issue by arijitamin** [aws/karpenter-provider-aws#6915]
Hi Team,

I’m looking to adjust the containerLogMaxSize parameter to "300Mi" for the Karpenter nodes in our Kubernetes setup. While I understand that modifying kubelet-config.json via the user_data.sh script is one approach, I’m curious if there are alternative methods to achieve this configuration.

Could anyone suggest other ways to modify the kubelet-config.json or to set the containerLogMaxSize parameter for the Karpenter nodes?

Your guidance and suggestions would be greatly appreciated.

**Comment by engedaam** [comment]
Currenlty, userData is the supported method for adjusting `containerLogMaxSize`. Another option could be creating your own AMI with the adjusted `containerLogMaxSize`

**Comment by arijitamin** [comment]
Ok, Thanks.
