### ISSUE TITLE
unable to customise the post install job 

### ISSUE THREAD

**Issue by nathan9120** [aws/karpenter-provider-aws#6916]
### Description

**Observed Behavior**:
In my k8s environment i have a number restrictions applied for security and compliance reasons i am unable to do the following, when deploying via the helm chart:

Our gatekeeper policies trigger the following:

```
Container post-install-job is attempting to run without a required securityContext/runAsNonRoot or securityContext/runAsUser != 0

Privilege escalation container is not allowed: post-install-job

container <post-install-job> is not dropping all required capabilities. Container must drop all of ["ALL"]

All pods, services and jobs must have ....  project labels.
```

**Expected Behavior**:

Expect i can set the security context for the job, explictly deny allowPrivilegeEscalation and drop all capabilites  also allowing labels to be set on the pod spawned from the job.

Looking at the job it doesn't look like it needs any special permissions, so perhaps this could be defined as default ?

**Reproduction Steps** (Please include YAML):

There is no YAML that allows me to configure any of the above.

**Versions**: 
- Chart Version: 1.0.0
- Kubernetes Version (`kubectl version`): 1.28.11

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by engedaam** [comment]
The post install job was dropped as part of [v1.0.1](https://github.com/aws/karpenter-provider-aws/releases/tag/v1.0.1)
