### ISSUE TITLE
consecutive drift behaviors

### ISSUE THREAD

**Issue by InsomniaCoder** [aws/karpenter-provider-aws#6923]
### Description

**How can the docs be improved?**

Hi Team,

I have a question regarding Karpenter's behavior. 

Let's say that we are upgrading EKS version from 1.28 to 1.29, it will cause a drift to the AMI. However, we are having a very strict disruption budget and it's going slowly.  In the meantime, we want to double jump the upgrade directly to 1.30.

What is the behaviour of Karpenter in this scenario?

Will it refresh the drift totally and start over, or it will wait until the first drift to complete before starting again?

Thank you

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by engedaam** [comment]
If you are using AMI discovery, Karpenter will drift all the nodes as soon as it sees a new version of kubernetes. So, if a node is marked as drifted and replacement node will have the latest AMI that Karpenter has discovered at the time of the launch. In your case, the nodes that are at to 1.28 AMI will be drifted to AMIs at 1.30, and nodes that have already been drifted to 1.29 will be marked as drifted and replaced with AMIs at 1.30

**Comment by InsomniaCoder** [comment]
thanks for the clarification!
