### ISSUE TITLE
Unexpected Node Replacement Behavior After Snapshot Update

### ISSUE THREAD

**Issue by rohith1312** [aws/karpenter-provider-aws#6933]
### Description

**Observed Behavior**:
I have configured a Karpenter NodePool with a specific EC2NodeClass that uses a snapshot for disk provisioning. When I update the snapshot in the NodePool configuration, the following unexpected behavior occurs:

a. Older Pods Termination: Existing pods on the old nodes are being terminated.
b. New Pods Scheduling: New pods are being scheduled on the new nodes created with the updated snapshot.
**Expected Behavior**:
a. Node Availability: The old nodes should remain available and continue running existing pods until those pods are terminated.
b. Pod Scheduling: New pods should be scheduled on new nodes created with the updated snapshot.
c. Node Termination: Only after all existing pods on the old node are terminated should the old node be terminated.
**Reproduction Steps** (Please include YAML):
a. Setup: Configure a NodePool and EC2NodeClass with a specific snapshot for disk provisioning.
b. Deploy Pods: Deploy some pods to the cluster.
c. Update Snapshot: Change the snapshot ID in the EC2NodeClass configuration.
d. Apply Changes: Apply the updated NodePool and EC2NodeClass configuration.
e. Observe Behavior: Check the scheduling and termination behavior of the pods and nodes.

configuration file:

$ cat snapshot-bottle.yaml

# This example NodePool will provision instances
# running Bottlerocket OS
---
apiVersion: karpenter.sh/v1beta1
kind: NodePool
metadata:
  name: default
  annotations:
    kubernetes.io/description: "General purpose NodePool for generic workloads"
spec:
  template:
    metadata:
      labels:
        worker: bottlerocket-karpenter
    spec:
      requirements:
        - key: kubernetes.io/arch
          operator: In
          values: ["amd64"]
        - key: kubernetes.io/os
          operator: In
          values: ["linux"]
        - key: karpenter.sh/capacity-type
          operator: In
          values: ["on-demand"]
        - key: node.kubernetes.io/instance-type
          operator: In
          values: ["i3.8xlarge", "i3.4xlarge"]
        - key: karpenter.k8s.aws/instance-generation
          operator: Gt
          values: ["2"]
      nodeClassRef:
        apiVersion: karpenter.k8s.aws/v1beta1
        kind: EC2NodeClass
        name: bottlerocket
      taints:
        - key: nodeType
          value: bottlerocket-karpenter
          effect: NoSchedule
  disruption:
    consolidationPolicy: WhenEmpty
    consolidateAfter: 20m
    expireAfter: 720h
---
apiVersion: karpenter.k8s.aws/v1beta1
kind: EC2NodeClass
metadata:
  name: bottlerocket
  annotations:
    kubernetes.io/description: "EC2NodeClass for running Bottlerocket nodes"
spec:
  amiFamily: Bottlerocket
  role: "KarpenterNodeRole-cbb-dev" # replace with your cluster name
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: "cbb-dev" # replace with your cluster name
  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: "cbb-dev" # replace with your cluster name
  blockDeviceMappings:
    - deviceName: /dev/xvda
      ebs:
        volumeType: gp3
        volumeSize: 10Gi
        deleteOnTermination: true
    # Bottlerocket data volume
    - deviceName: /dev/xvdb
      ebs:
        volumeType: gp3
        volumeSize: 500Gi # replace with your required disk size
        snapshotID: snap-0a85dc8*******631
        deleteOnTermination: true
  userData: |
    [settings.kernel.sysctl]
    "user.max_user_namespaces" = "16384"
    [settings.host-containers.admin]
    enabled = true

Observations:
a. After updating the snapshot, existing pods on old nodes are terminated, and new pods are scheduled on newly created nodes.
b. The old nodes are not retained until all existing pods are terminated.

Additional Notes:

a. Please advise if additional configurations or settings are needed to ensure the old nodes are retained until all existing pods are terminated.
b. Any insights or suggestions to resolve this issue are appreciated.

**Comment by engedaam** [comment]
This is expected behavior. When the block device mapping felid is updated, nodes provisioned with that EC2NodeClass are replaced. It sounds like you need to control when nodes are replaced. Disruption controllers offers that level of configurability: https://karpenter.sh/docs/concepts/disruption/#controls. You can also use the `do-not-disrupt` annotation on specific pods you don't want terminated until the pods are finished https://karpenter.sh/docs/concepts/disruption/#pod-level-controls

**Comment by rohith1312** [comment]
Thanks for the response. I was able to achieve this, but I am also looking for additional behavior:

Pod Scheduling: New pods should be scheduled on the new nodes created with the updated snapshot.
The old pods should continue running on the existing (old) node until they are terminated(this is working after making above changes to the pod-level-controls)
.
