### ISSUE TITLE
Removal of settings.assumeRoleARN in v1

### ISSUE THREAD

**Issue by InsomniaCoder** [aws/karpenter-provider-aws#6960]
### Description

**Observed Behavior**:

Hi Team,

I would like to report that after migrating to Karpenter v1. I noticed that the existing setting which is 

settings.assumeRoleARN is gone from the chart: https://github.com/aws/karpenter-provider-aws/pull/6755/files#diff-cf1db5e9953df52fe2559dec879f544faee698be2138a3fab3c2a9e7387f4687L15-L16

I don't see this mentioned in the upgrade guide to v1. 

Do you have any pointer to where this can be set instead?

with my limitation, I cannot use Pod Identity and IRSA just yet and this is breaking my permission after the upgrade.

Hope you can enlighten me on this 

**Expected Behavior**:

- Assuming Karpenter permission using assumrRoleARN still works after upgrading 

**Reproduction Steps** (Please include YAML):

- Use the same chart value as in 0.37.0

**Versions**:
- Chart Version:
- v1.0.1
- Kubernetes Version (`kubectl version`): 1.28

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by jonathan-innis** [comment]
> I don't see this mentioned in the upgrade guide to v1.

This is mentioned in the [Environment Variable Changes](https://karpenter.sh/docs/upgrading/v1-migration/#:~:text=to%20reflect%20this.-,Environment%20Variable%20Changes,-%3A) section of the v1 upgrade guide.

> I cannot use Pod Identity and IRSA just yet and this is breaking my permission after the upgrade

What did you need the assumeRoleARN for?

**Comment by InsomniaCoder** [comment]
> > I don't see this mentioned in the upgrade guide to v1.
> 
> This is mentioned in the [Environment Variable Changes](https://karpenter.sh/docs/upgrading/v1-migration/#:~:text=to%20reflect%20this.-,Environment%20Variable%20Changes,-%3A) section of the v1 upgrade guide.
> 
> > I cannot use Pod Identity and IRSA just yet and this is breaking my permission after the upgrade
> 
> What did you need the assumeRoleARN for?

thanks for the reference, I missed it indeed.

We are using a tool called kiam but we were relying on this setting before. now, we switch to annotate directly at the pod level. thanks!

btw, I have a non-related quesition, if you could help.

for the kubelet configuration that's now moved to ec2nodeclass in v1. we have a different kubelet setting at the moment, do they get still applied/converted from the v1beta1 nodepool during the webhook conversion?
