### ISSUE TITLE
 no matches for kind "NodeClaim" in version "karpenter.sh/v1"

### ISSUE THREAD

**Issue by ashutosh-delta** [aws/karpenter-provider-aws#6973]
### Description

I am encountering an issue while installing Karpenter version "1.0.2" using Helm. The installation fails with the following error:
panic: failed to setup nodeclaim provider id indexer: no matches for kind "NodeClaim" in version "karpenter.sh/v1"

command used to install karpenter controller : 
helm upgrade --install karpenter oci://public.ecr.aws/karpenter/karpenter --version "1.0.2" --namespace "karpenter" \
  --set "settings.clusterName=xxxxxxxx" \
  --set "settings.interruptionQueue=xxxxxxxx" \
  --set controller.resources.requests.cpu=1 \
  --set controller.resources.requests.memory=1Gi \
  --set controller.resources.limits.cpu=1 \
  --set controller.resources.limits.memory=1Gi \
  --wait

Logs of pod: 
panic: failed to setup nodeclaim provider id indexer: no matches for kind "NodeClaim" in version "karpenter.sh/v1"

goroutine 1 [running]:
github.com/samber/lo.must({0x27de9c0, 0xc000b711c0}, {0xc000a1f9f0, 0x1, 0x1})
        github.com/samber/lo@v1.46.0/errors.go:51 +0x1bb
github.com/samber/lo.Must0(...)
        github.com/samber/lo@v1.46.0/errors.go:72
sigs.k8s.io/karpenter/pkg/operator.NewOperator()
        sigs.k8s.io/karpenter@v1.0.1/pkg/operator/operator.go:201 +0x162e
main.main()
        github.com/aws/karpenter-provider-aws/cmd/controller/main.go:32 +0x25

Kubernetes Version: 1.28
Karpenter Version: 1.0.2
Helm Version: v3.11.2
Cloud Provider:  AWS EKS

**Comment by dcherniv** [comment]
Try to install into `kube-system` namespace. `--namespace "kube-system"`

**Comment by ashutosh-delta** [comment]
@dcherniv 
Error: rendered manifests contain a resource that already exists. Unable to continue with install: ClusterRole "karpenter-admin" in namespace "" exists and cannot be imported into the current release: invalid ownership metadata; annotation validation error: key "meta.helm.sh/release-namespace" must equal "kube-system": current value is "karpenter"

**Comment by dcherniv** [comment]
> @dcherniv
> 
> helm upgrade --install karpenter oci://public.ecr.aws/karpenter/karpenter --version "1.0.2" --namespace "kube-system" --set "settings.clusterName=xxxxxx" --set "settings.interruptionQueue=xxxxx" --set controller.resources.requests.cpu=1 --set controller.resources.requests.memory=1Gi --set controller.resources.limits.cpu=1 --set controller.resources.limits.memory=1Gi --wait
> 
> Error: rendered manifests contain a resource that already exists. Unable to continue with install: ClusterRole "karpenter-admin" in namespace "" exists and cannot be imported into the current release: invalid ownership metadata; annotation validation error: key "meta.helm.sh/release-namespace" must equal "kube-system": current value is "karpenter"

You have to clean out old release first which seems to have not been fully installed

**Comment by jonathan-innis** [comment]
Yeah, this just sounds like the CRDs didn't get updated when you performed the upgrade. Consider following https://karpenter.sh/docs/upgrading/upgrade-guide/#crd-upgrades or using `kubectl` statements to just override CRDs that Karpenter vends outright.

**Comment by ashutosh-delta** [comment]
why it is important to install karpenter in kube-system ns ?

**Comment by jonathan-innis** [comment]
> why it is important to install karpenter in kube-system ns

A few reasons: One is that this is the logical location for critical system components. Given how critical Karpenter is for scaling application workloads on your cluster, `kube-system` belongs here. The other reason is the FlowSchemas and PriorityLevelConfigurations that are given out of the box by default for the `kube-system` namespace components. There's more detail [here](https://karpenter.sh/docs/getting-started/getting-started-with-karpenter/#preventing-apiserver-request-throttling), but, effectively, this allows Karpenter requests to the apiserver not to get throttled by misbehaving application pods that may be sending too many requests to the apiserver.

**Comment by ashutosh-delta** [comment]
I have tried setting up karpenter with 1.0.2 version on kube-system ns , deployed nodepool & nodeclass. ec2 machine are getting spinned up with every matching label , but nodes are not getting registered to the cluster , getting below error : 

```
Sep 16 07:17:11 ip-xxxxx.ap-northeast-1.compute.internal kubelet[3184]: E0916 07:17:11.418865    3184 kubelet_node_status.go:96] "Unable to register node with API server" err="nodes is forbidden: User \"system:node:ip-xxxxx.ap-northeast-1.compute.internal\" cannot create resource \"nodes\" in API group \"\" at the cluster scope" node="ip-xxxxx.ap-northeast-1.compute.internal"
Sep 16 07:17:12 ip-xxxxx.ap-northeast-1.compute.internal kubelet[3184]: I0916 07:17:12.171340    3184 csi_plugin.go:880] Failed to contact API serverwhen waiting for CSINode publishing: csinodes.storage.k8s.io "ip-xxxxxx.ap-northeast-1.compute.internal" is forbidden: User "system:node:ip-xxxxxx.ap-northeast-1.compute.internal" cannot get resource "csinodes" in API group "storage.k8s.io" at the cluster scope
```

I have already configured in aws-auth cm : 

- rolearn: arn:aws:iam::xxxxxx:role/KarpenterNodeRole-xxxxx
   username: system:node:{{EC2PrivateDNSName}}

**Comment by jonathan-innis** [comment]
> I have already configured in aws-auth cm

Have you assigned the correct `groups` to that entry? There's a few groups that need to be assigned or else the Node isn't going to get the relevant permission.

**Comment by ashutosh-delta** [comment]
I have assigned group system:nodes , you can see below : 

```
mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::xxxxxxx:role/AmazonEKSNodeRole
      username: system:node:{{EC2PrivateDNSName}}
    - rolearn: arn:aws:iam::xxxxxxxx:role/KarpenterNodeRole-xxxxxxxx
      username: system:node:{{EC2PrivateDNSName}}
```

The node group that I am manually create in eks , gets registered to the cluster But whenever the karpenter spin up a new nodes it gets failed to register to the cluster 

@jonathan-innis
