### ISSUE TITLE
`use-max-pods` is disabled by default on AL2 and wrong `max-pods` is set on the node

### ISSUE THREAD

**Issue by nadavbuc** [aws/karpenter-provider-aws#6979]
### Description

**Observed Behavior**:
According to the [documentation](https://karpenter.sh/docs/concepts/nodeclasses/#al2) - use-max-pods is disabled by default
**Expected Behavior**:
We need a way to allow it to be set to true - otherwise it sets the limit too high and we see failures in scheduling
**Reproduction Steps** (Please include YAML):
Launch a lot of small pods on a single node - without specifying `maxpods`
**Versions**:
- Chart Version: 1.0.2
- Kubernetes Version (`kubectl version`): `Server Version: version.Info{Major:"1", Minor:"28+", GitVersion:"v1.28.12-eks-2f46c53", GitCommit:"6e67a6b95e77f4e41e2d9cacb6992bef7357cec7", GitTreeState:"clean", BuildDate:"2024-07-25T04:23:15Z", GoVersion:"go1.22.5", Compiler:"gc", Platform:"linux/amd64"}`

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by jonathan-innis** [comment]
This looks related to #6890. There's a number of users that are reporting inconsistencies in the maxPods values that Karpenter is using post-v1.

**Comment by jonathan-innis** [comment]
Posted an update [here](https://github.com/aws/karpenter-provider-aws/issues/6890#issuecomment-2353440735). You should be able to follow that link to install a snapshot and test if you are still hitting the issue anymore.

**Comment by jonathan-innis** [comment]
#7020 merged! So I think we are good to close this out now. We should have a patch that includes this soon!
