### ISSUE TITLE
budgets should have expired reason

### ISSUE THREAD

**Issue by bhavasarpritesh** [aws/karpenter-provider-aws#6980]
### Description

**What problem are you trying to solve?**
I would like the ability to apply a budget on nodes that are marked as "Expired" so that they are not recycled during the day. Currently, Karpenter supports three node conditions for budgeting: Underutilized, Empty, and Drifted. Adding "Expired" as a node condition would allow better control over node recycling and avoid interruptions during peak hours.
**How important is this feature to you?**
Nodes that expire should not be recycled during the day, as this can cause unnecessary disruptions and workload redistribution. By applying a budget only to expired nodes, this would enable more efficient handling of node lifecycle and reduce operational overhead during daytime operations.

**Comment by bhavasarpritesh** [comment]
1. Is there an alternative method or workaround to achieve control over expired node recycling, so that it can be handled at a more convenient time (e.g., not during peak hours)?
2. Are there any plans or discussions for future releases that might include "Expired" as a node condition for budgeting?

**Comment by pkit** [comment]
@njtran I think this design is totally unusable in practice.
Imagine 3 nodes start in time `t`. They will be expired at `t+720h` ALL OF THEM.
I.e. total cluster unavailability.
It's not theoretical, easily checkable, it happens.
Now what?

**Comment by wufengzlw** [comment]
same request here:
https://github.com/aws/karpenter-provider-aws/issues/7797

**Comment by songponlekpetch** [comment]
Is there any workaround to handle node expiration?
Ideally, I would love to renew nodes with a new patch update, but I want to avoid a pod eviction storm during peak times, as it could cause small service downtime.

It would be great if there is any workaround.
For now, I have stopped using the expiration feature because I think it's not ready for production use yet.

**Comment by cloudlady911** [comment]
@pkit The trick here would be to only create the original nodes after hours.  If you have your disruptions scheduled for after hours then there will not be any nodes that expire during the day.
