### ISSUE TITLE
SpotToSpotConsolidation is trying to spin up a node which is then not available

### ISSUE THREAD

**Issue by woehrl01** [aws/karpenter-provider-aws#6984]
### Description

**Observed Behavior**:

Having `SpotToSpotConsolidation: true`. We see that it suggests that a smaller spot instance is available, it then starts to consolidate the node, but the smaller spot instance type is not available, failing to create the node. It then creates a bigger instances type again, resulting in a loop.
![Bildschirmfoto 2024-09-04 um 09 29 19](https://github.com/user-attachments/assets/d6420d9f-2bdc-40bf-bdb9-a7a1493e6e73)

![Bildschirmfoto 2024-09-12 um 08 05 42](https://github.com/user-attachments/assets/04f98535-6212-41b8-899c-d7dad5c03d33)

![Bildschirmfoto 2024-09-12 um 08 18 02](https://github.com/user-attachments/assets/a8043234-3894-46ca-9ca6-b896fdf62766)

**Expected Behavior**:

Should only consolidate if the instances sizes are actually available.

**Reproduction Steps** (Please include YAML):

**Versions**:
- Chart Version: 1.0.0
- Kubernetes Version (`kubectl version`): 1.30

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by jonathan-innis** [comment]
> but the smaller spot instance type is not available, failing to create the node

Can you share the logs from this operation? We definitely shouldn't be deleting the old node before the replacement successfully comes up. Are you seeing the old node getting torn down when you are seeing the bigger instance type get launched or are you seeing us launch double capacity for the same pods?

**Comment by woehrl01** [comment]
Please see here some related logs

![Bildschirmfoto 2024-09-17 um 16 12 26](https://github.com/user-attachments/assets/3899b21a-5b07-4409-baa6-834d3f1593c7)

I noticed that it didn't schedule any pods on the node which should be torn down, as it was marked for deletion, effectively preventing any scheduling of new pods.
