### ISSUE TITLE
Unhandled Content-Type warning in EC2NodeClass UserData with AL2023 AMI

### ISSUE THREAD

**Issue by amin-o** [aws/karpenter-provider-aws#6989]
### Description

**Observed Behavior**:

When using the following EC2NodeClass with custom userData, the system log shows a warning regarding an unhandled unknown content-type (application/node.eks.aws) in the user data.

```
[    8.950282] cloud-init[2183]: 2024-09-12 12:57:56,263 - __init__.py[WARNING]: Unhandled unknown content-type (application/node.eks.aws) userdata: 'b'# Karpenter Generated No'...'
[    8.953015] cloud-init[2183]: 2024-09-12 12:57:56,263 - __init__.py[WARNING]: Unhandled unknown content-type (application/node.eks.aws) userdata: 'b'---'...'
```

Despite this warning, inside the node, the configuration is applied correctly with the following:

``/etc/kubernetes/kubelet/config.json.d/00-nodeadm.conf:``

```
{
  "apiVersion": "kubelet.config.k8s.io/v1beta1",
  "clusterDNS": [
      "172.20.0.10"
  ],
  "cpuCFSQuota": false,
  "kind": "KubeletConfiguration",
  "maxPods": 29,
  "registerWithTaints": [
      {
          "effect": "NoSchedule",
          "key": "general"
      }
  ]
}
```

**Expected Behavior**:

The custom userData should be processed without warnings, ensuring proper handling of all content types.

**Reproduction Steps** (Please include YAML):

1. Use the following EC2NodeClass specification:
```
apiVersion: karpenter.k8s.aws/v1beta1
kind: EC2NodeClass
metadata:
  name: default
spec:
  amiFamily: AL2023
  role: {{ .Values.karpenter.settings.nodeRole }}
  securityGroupSelectorTerms:
  - tags:
      karpenter.sh/discovery: {{ .Values.karpenter.settings.clusterName }}
  subnetSelectorTerms:
  - tags:
      karpenter.sh/discovery: {{ .Values.karpenter.settings.clusterName }}
  tags:
    karpenter.sh/discovery: {{ .Values.karpenter.settings.clusterName }}
    owner: {{ .Values.karpenter.settings.clusterName }}
  userData: |
    MIME-Version: 1.0
    Content-Type: multipart/mixed; boundary="BOUNDARY"

    --BOUNDARY
    Content-Type: application/node.eks.aws

    ---
    apiVersion: node.eks.aws/v1alpha1
    kind: NodeConfig
    spec:
      kubelet:
        config:
          cpuCFSQuota: false

    --BOUNDARY
    Content-Type: text/x-shellscript; charset="us-ascii"

    #!/bin/bash

    set -eoux pipefail
    modprobe tls

    cat <<EOF >> /etc/sysctl.conf

    # tcp keepalive
    net.ipv4.tcp_keepalive_time = 300
    net.ipv4.tcp_keepalive_probes = 5
    net.ipv4.tcp_keepalive_intvl = 15

    net.ipv4.tcp_slow_start_after_idle=0

    # bbr tcp congestion control algorithm
    net.core.default_qdisc=fq
    net.ipv4.tcp_congestion_control=bbr

    EOF

    sysctl -p /etc/sysctl.conf

    --BOUNDARY--
```

2. Observe the system log to see the warnings.

**Versions**:
- Chart Version: 0.37.3
- Kubernetes Version (`kubectl version`): 
```
Client Version: v1.29.0
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.30.3-eks-2f46c53
```

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by jmdeal** [comment]
I was able to replicate with the latest AL2023 AMI, no errors from nodeadm, but the same warning in the cloud-init log:

**nodeadm:**
```bash
$ sudo journalctl -u nodeadm-config
...
Sep 12 15:04:18 localhost nodeadm[1968]: {"level":"info","ts":1726153458.010883,"caller":"init/init.go:57","msg":"Loading configuration..","configSource":"imds://user-data"}
Sep 12 15:04:18 localhost nodeadm[1968]: {"level":"info","ts":1726153458.0367737,"caller":"init/init.go:66","msg":"Loaded configuration","config":{"metadata":{"creationTimestamp":null},"spec":{"cluster":{"name":"k8s-130-release","apiServerEndpoint":"REDACTED","certificateAuthority":"REDACTED", ...}
Sep 12 15:04:18 localhost nodeadm[1968]: {"level":"info","ts":1726153458.0369208,"caller":"init/init.go:68","msg":"Enriching configuration.."}
...
```

**cloud-init:**
```bash
$ sudo cat /var/log/cloud-init.log | grep 'eks'
2024-09-12 15:04:22,242 - __init__.py[DEBUG]: {'Content-Type': 'application/node.eks.aws', 'Content-Disposition': 'attachment; filename="part-001"'}
2024-09-12 15:04:22,250 - __init__.py[WARNING]: Unhandled unknown content-type (application/node.eks.aws) userdata: 'b'# Karpenter Generated No'...'
```

Given `application/node.eks.aws` is the expected content type for AL2023 UserData ([ref](https://awslabs.github.io/amazon-eks-ami/nodeadm/#configuration)), and nodeadm is properly processing it, I don't think there's anything actionable for us in Karpenter. I'd recommend opening an issue against [awslabs/amazon-eks-ami](https://github.com/awslabs/amazon-eks-ami) directly to address the warning in the cloud-init logs.

**Comment by amin-o** [comment]
Thank you for the prompt response, @jmdeal.

I'll open an issue on the [awslabs/amazon-eks-ami ](https://github.com/awslabs/amazon-eks-ami) repository.

**Comment by amin-o** [comment]
This behavior is intentional. Closing the issue.
