### ISSUE TITLE
Regarding Karpenter controller IAM role for Redhat Openshift

### ISSUE THREAD

**Issue by sandeepkp1175** [aws/karpenter-provider-aws#7003]
### Description

**How can the docs be improved?**

We have a question regarding the below documentation. We are trying to enable Karpenter for Openshift. The service account token used within Openshift are stored in Hashicorp vault, and it doesn't use IRSA with OIDC endpoint. How do we implement that? Do you have the steps on how can this be done?

`Now we need to create an IAM role that the Karpenter controller will use to provision new instances. The controller will be using [IAM Roles for Service Accounts (IRSA)](https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts.html) which requires an OIDC endpoint.
If you have another option for using IAM credentials with workloads (e.g. [kube2iam](https://github.com/jtblin/kube2iam)) your steps will be different.`

**Comment by dcherniv** [comment]
as long as you token (and other information) allows karpenter to assume the IAM role you should be good to go. Karpenter uses standard AWS authentication library.
AS for the way to provide these credentials to the pod. One way to do this would be vault csi driver https://developer.hashicorp.com/vault/docs/platform/k8s/csi
