### ISSUE TITLE
Allow for user PDB configuration so new fields can be added

### ISSUE THREAD

**Issue by peterabarr** [aws/karpenter-provider-aws#7025]
### Description

**What problem are you trying to solve?**
I would like the PDB used by the Karpenter Helm Chart to be configurable, so that new fields can be used if desired such as [unhealthyPodEvictionPolicy](https://kubernetes.io/blog/2023/01/06/unhealthy-pod-eviction-policy-for-pdbs/).

**How important is this feature to you?**
This feature would be nice to have but it is not urgent for our workflow.

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by njtran** [comment]
This sounds reasonable to me. Are you open to cutting a PR?

**Comment by peterabarr** [comment]
@njtran Yeah I've opened and tested #7037

**Comment by aydosman** [comment]
Any update on this MR @njtran @peterabarr

**Comment by peterabarr** [comment]
@aydosman waiting for @njtran to review it.
