### ISSUE TITLE
Clarity in documentation for drifted nodes and blocking updates during a specific time

### ISSUE THREAD

**Issue by sagargulabani** [aws/karpenter-provider-aws#7036]
### Description

**How can the docs be improved?**

https://karpenter.sh/docs/concepts/disruption/#nodepool-disruption-budgets

```
Budgets will consider nodes that are actively being deleted for any reason, and will only block Karpenter from disrupting nodes voluntarily through drift, emptiness, and consolidation. Note that NodePool Disruption Budgets do not prevent Karpenter from cleaning up expired or drifted nodes.

```
The question over here is that does nodepool disruption budget prevent drifted nodes from being removed or not ?

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by josh-ferrell** [comment]
In my testing any nodepool disruption budget with a node count of "0" and either Drifted in the reasons list or no reasons provided will prevent nodeclaim replacement because of drift. However, these disruption budgets do not stop nodeclaim termination because of expiration.
