### ISSUE TITLE
Can you pass dynamic or variable values to EC2NodeClass' role or instance profile attributes?

### ISSUE THREAD

**Issue by mnazir23** [aws/karpenter-provider-aws#7175]
### Description

Hi,

This is something that I would like some clarification on as I haven't been able to find anything in the documentation.

Can you pass a value from a variable to the `spec.role` or `spec.instanceprofile` attributes in EC2NodeClass file?

From what I can see from the examples, we can use the `${CLUSTER_NAME}` env variable because it is global but other than that I haven't seen a variable value being passed to these attributes.

Does it need to be hardcoded for each EC2NodeClass file that we have?

Please confirm.

Thank you.

Link: https://karpenter.sh/docs/concepts/nodeclasses/#specrole

**Comment by engedaam** [comment]
You can pass in a variable for spec.role or spec.instanceprofile https://karpenter.sh/docs/getting-started/getting-started-with-karpenter/#5-create-nodepool

**Comment by mnazir23** [comment]
Hi @engedaam 

Yes, you can pass pre-defined Karpenter variables to a role or an instance profile but not a custom variable value.
