### ISSUE TITLE
Disabling webhooks v0.33.10

### ISSUE THREAD

**Issue by mwetika** [aws/karpenter-provider-aws#7182]
### Description

**Observed Behavior**:
We are in the process of upgrading karpenter from 0.32.10 to 0.33.10 on our EKS 1.29 cluster.
When running a `helm diff upgrade` on the helm chart we saw that the `disable_webhook` was going to be set as false.

```
                value: "8001"
+             - name: DISABLE_WEBHOOK
+               value: "false"
              - name: LOG_LEVEL
-               value: "debug"
+               value: "info"
```

**Expected Behavior**:
From reading the docs [here](https://karpenter.sh/v1.0/upgrading/upgrade-guide/#upgrading-to-0330), it implies that EKS versions greater than 1.25 should have the `disable_webhook` set to true by default and no action should be required.

We can see these two PR's one which sets the [helm chart default to enable webhooks and permissions ](https://github.com/aws/karpenter-provider-aws/pull/6904/files)
and the other which sets the [`disable_webhook` as `false`](https://github.com/kubernetes-sigs/karpenter/pull/1620/files)

**Reproduction Steps** (Please include YAML):

**Versions**:
- Chart Version: 0.33.10
- Kubernetes Version (`kubectl version`): 1.29

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by engedaam** [comment]
This an issue with our documentation. We had recently updated the default webhook as part of v0.33.8. The documentation should be updated here https://github.com/aws/karpenter-provider-aws/pull/7220.
>Starting with 0.33.8 Karpenter has enabled conversion webhooks by default to improve the v1 migration experience. If working with a cluster with a network policy that blocks Ingress, ports 8000, 8001, 8081, 8443 will need to be allowlisted

CC: https://karpenter.sh/v1.0/upgrading/upgrade-guide/#upgrading-to-0330
