### ISSUE TITLE
Karpenter does not work with Fargate for Karpenter/core modules

### ISSUE THREAD

**Issue by billnbell3** [aws/karpenter-provider-aws#7187]
### Description

1.0.6 version

There does not appear to be a walkthrough around setting up Karpenter pods in Fargate. Managed nodes seems to be the only easy way to get this to work. I can use taints on the MNG to make sure only Karpenter runs on these nodes, but it would be cleaner to run Karpenter itself on Fargate, and then have Karpenter manage the nodes it creates.

I get DNS issues when trying to get Fargate to work. Fargate takes 5 minutes to come up and has timeouts as well.

Documentation on a working walkthrough would be awesome. 

We would love to run the actual Karpenter on Fargate (2 nodes).

Also if anyone was able to run all cluster_addons in Fargate that also would be helpful!

**Comment by billnbell3** [comment]
Anything?

**Comment by engedaam** [comment]
We have a toggle to setup karpenter with Fargate https://karpenter.sh/docs/getting-started/getting-started-with-karpenter/#3-create-a-cluster

**Comment by billnbell3** [comment]
Well we are using terraform and it does not seem at all simple to do.

**Comment by engedaam** [comment]
Have you looked at the notes for installing Karpenter? https://karpenter.sh/docs/getting-started/getting-started-with-karpenter/#4-install-karpenter

**Comment by billnbell3** [comment]
Of course. I have looked into it for long hours and tried to do it several times. I cannot get Fargate to work on all the other core pods. Karpenter will run and manage normally using node groups. I am trying to script this with terraform, and it is not easy to do, because the documentation for the setup will need to be reverse engineered. What is it doing when it runs in fargate mode? 

1. What is needed to run core pods in Fargate and the rest in Karpenter?
2. It appears a service account is needed. What perms does this account need, and why do I need one?
3. Has anyone set this up and actually had it work in 1.0.6 using Fargate from scratch ?
4. DId you have to revert to eksctl ?

**Comment by qspors** [comment]
I have working solution 
k8s 1.31
karpenter 1-1.0.6 under fargate on karpeter namespace + coredns + csi
everything deployed thru TF with terraform-aws-modules/eks/aws v "19.18" + aws-ia/eks-blueprints-addons/aws "1.11"

Only one issue with karpenter leader election when pretty big loads, but I think need to manage overhead resources for karp for fix it
