### ISSUE TITLE
Node claim lifetime configuration 

### ISSUE THREAD

**Issue by dmity-st** [aws/karpenter-provider-aws#7212]
### Description

**What problem are you trying to solve?**

Based on the documentation Node Claim exists for 15 minutes. If this fails to succeed within 15 minutes, Karpenter will remove the NodeClaim from the cluster and delete the underlying instance, creating another NodeClaim.

The problem is that we use custom userData startup script which completion  can take more then 15 minutes.  As a result Karpneter kill the valid node which runs userdata script and start a loop with adding a new node. 

The perfect solution could be is a possibility to configure a custom NodeClaim TTL more than 15m.

**Comment by engedaam** [comment]
Closing as a duplicate https://github.com/kubernetes-sigs/karpenter/issues/357
