### ISSUE TITLE
Limit on maximum number of nodes that can be provisioned for a karpenter enabled cluster

### ISSUE THREAD

**Issue by liafizan** [aws/karpenter-provider-aws#7217]
### Description

**What problem are you trying to solve?**
We are migrating from ASG based nodepools to karpenter driven nodepools. One feature that we would want to map from ASG world is to have a limit on number of nodes that can be provisioned for a cluster by karpenter. 

I have gone through FAQs and [limits](https://karpenter.sh/docs/concepts/nodepools/#speclimits) but do not see anything defined for this. 

In karpenter world, node-count limit on node pool does not add much value since a nodepool can have different instance types underneath it. Hence, request to have a cluster-wide limit. 

This should probably go to karpenter-core

**How important is this feature to you?**
It is an important feature as we would like to control our expenditure for AWS for our non production environments & limit clusters beyond CPU/Memory for a nodepool. We would like to have an overall limit for the cluster to have greater control on our costs

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by engedaam** [comment]
This feature is best held in kubernetes-sigs/karpenter. Closing this out as duplicate
