### ISSUE TITLE
Development Guide

### ISSUE THREAD

**Issue by Pokom** [aws/karpenter-provider-aws#7224]
There is a section in the [developer guide](https://karpenter.sh/docs/contributing/development-guide/#build-and-deploy):

> If you are only interested in building the Karpenter images and not deploying the updated release > to your cluster immediately with Helm, you can run make image # build and push the karpenter images

However there does not appear to be a `make image` command anymore. I believe the intent is for `make build` to replace this, but not quite sure. 

---

Looks like this is an issue on what the source of truth is. I'm trying to make a change in https://github.com/kubernetes-sigs/karpenter, but the documentation is for this repo. I'll leave this open in the meantime as it can be quite confusing for a new developer trying to get onboarded to know which one to follow.

**Comment by engedaam** [comment]
The development guide is for the AWS provider. The most up-to-date version for development guide for the upstream project would be https://github.com/kubernetes-sigs/karpenter/tree/main/kwok

**Comment by njtran** [comment]
We talked about this in the kubernetes slack too. @Pokom I'll close this since you were planning on cutting a PR
