### ISSUE TITLE
INTERRUPTION_QUEUE setting is missing

### ISSUE THREAD

**Issue by melodyyangaws** [aws/karpenter-provider-aws#7249]
### Description

Please add the spot interruption queue setting when [generating a full Karpenter deployment yaml from Helm chart](https://karpenter.sh/docs/getting-started/migrating-from-cas/#deploy-karpenter). Otherwise, the graceful shutdown won't work, after migrated from Cluster Autoscaler to Karpenter. 

Suggestions:
1. in the Getting Started -> Migrating from Cluster Autoscaler documentation, modify the section "Create IAM roles" by adding the CloudFormation, which will create KarpenterNodeRole + KarpenterControllerPolicy + SQS rules (the current doc has missed)
2. Add the "settings.interruptionQueue" line to `karpenter.yaml`.
```sh
helm template karpenter oci://public.ecr.aws/karpenter/karpenter --version "${KARPENTER_VERSION}" --namespace "${KARPENTER_NAMESPACE}" \
    --set "settings.clusterName=${CLUSTER_NAME}" \
    --set "settings.interruptionQueue=${CLUSTER_NAME}" \
    --set "serviceAccount.annotations.eks\.amazonaws\.com/role-arn=arn:${AWS_PARTITION}:iam::${AWS_ACCOUNT_ID}:role/KarpenterControllerRole-${CLUSTER_NAME}" \
    --set controller.resources.requests.cpu=1 \
    --set controller.resources.requests.memory=1Gi \
    --set controller.resources.limits.cpu=1 \
    --set controller.resources.limits.memory=1Gi > karpenter.yaml
```

**Comment by mozammil89** [comment]
https://github.com/aws/karpenter-provider-aws/pull/7343
