### ISSUE TITLE
Add new condition to NodePool that tells whether any nodeclaims are drifted from the desired state

### ISSUE THREAD

**Issue by reegnz** [aws/karpenter-provider-aws#7293]
### Description

**What problem are you trying to solve?**

I'm trying to integrate karpenter nodepools into [argocd health checks](https://argo-cd.readthedocs.io/en/latest/operator-manual/health/#custom-health-checks).
This would help argocd determine when a deployment of an ec2nodeclass or nodepool configuration change has been reconciled.

I think I could resolve this by writing a custom controller that adds an extra condition called `Drifted` to each NodePool resource, but I'd much rather have this solved natively by karpenter.

Proposal:

* Introduce a new `condition` called `Drifted` with a value of `False` if the hashes of the NodeClaims managed by the NodePool do not match the hash of the NodePool and/or the Ec2NodeClass. The value should be `True` if any of the NodeClaims has a drifted hash of the NodePool or Ec2NodeClass.

**How important is this feature to you?**

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by njtran** [comment]
What seems even more valuable here is a status that says the number/percent of nodes that are drifted for a nodepool, right? Then you can easily check if == 0, then no drift.

**Comment by njtran** [comment]
Can you close and re-open this in github.com/kubernetes-sigs/karpenter?

**Comment by reegnz** [comment]
Sure, let me reopen it under the other repo.
