### ISSUE TITLE
EKS upgrade to 1.29 with Karpenter 0.31.x

### ISSUE THREAD

**Issue by peterreji** [aws/karpenter-provider-aws#7353]
### Description

I am running on EKS 1.28 with Karpenter 0.31.5. I wanted to upgrade my EKS cluster to 1.29, but as per the compatibility matrix - https://karpenter.sh/docs/upgrading/compatibility/ - it says that for EKS 1.29 you need karpenter >= 0.34. How mandatory is this? What happens if I upgrade the cluster to 1.29 without upgrading Karpenter first? Will my karpenter nodes be recreated with the EKS upgrade? Or will it no longer create new nodes?

**Comment by jmdeal** [comment]
Certain features on EKS 1.29 will not be supported (e.g. native sidecar containers), and the Karpenter team does not guarantee compatibility with versions outside those in the compatibility matrix. It may continue to work on 1.29, but we strongly recommend upgrading to an officially supported version.

**Comment by masoodamunchen** [comment]
Hi I have similar situation that the compatibility matrix says for 1.30l we need karpenter version greater than equal to 0.37 but in our case v0.36 actually works with 1.30! Now we are upgrading EKS cluster to 1.31 and the matrix tells us >= 1.0.5 is required , what are the things that might not work with 0.36 and cluster 1.31?
