### ISSUE TITLE
Karpenter version is 1.0.8, but helm still uses 0.37.0?

### ISSUE THREAD

**Issue by timetofaceit** [aws/karpenter-provider-aws#7372]
### Description

Hi! 👋 

Just want to ask is this a bug or forgotten update that Karpenter version and helm chart image versions are different?

Link - https://github.com/aws/karpenter-provider-aws/blob/v1.0.8/charts/karpenter/values.yaml#L104

**Comment by rschalo** [comment]
Hi @timetofaceit - looks like this is changed in main: https://github.com/aws/karpenter-provider-aws/blob/main/charts/karpenter/values.yaml#L107. That said, feel free to open a PR for `release-v1.0.x`: https://github.com/aws/karpenter-provider-aws/blob/release-v1.0.x/charts/karpenter/values.yaml#L104

**Comment by kpjani** [comment]
Submitted PR to update the version: https://github.com/aws/karpenter-provider-aws/pull/7403
