### ISSUE TITLE
Set a max node count within NodePool config

### ISSUE THREAD

**Issue by nabeelpaytrix** [aws/karpenter-provider-aws#7458]
### Description

**What problem are you trying to solve?**

I would like to be able to set a maximum number of nodes provisioned within a NodePool.
Right now Karpenter is creating 15+ `xlarge` nodes in my cluster instead of fewer `2x` or `4x` large instances.
I have Datadog agent installed in my cluster and Datadog charges for the amount of nodes which are sending data into Datadog, so more nodes incurs a very high bill, even if the volume of data is the same.

**How important is this feature to you?**

Considering this is causing a large spike in our Datadog bill, we really need to keep a control on how many nodes are created by Karpenter.
The way I imagine this works is that:

* Set a node limit of 10 for a NodePool
* If 10 nodes are currently running and none of them can fit a new pod, then a new larger node is created which can host all the existing pods, and the new pod
* So we temporarily have 11 nodes, but it goes back down to 10
* When performing Rolling Deployments of several services at once, this can cause several large nodes to be created, but from the docs it looks like Karpenter will eventually "right-size" these nodes.

**Comment by jonathan-innis** [comment]
This seems related to https://github.com/kubernetes-sigs/karpenter/issues/732. Closing it as a duplicate. Agreed it's an interesting feature to explore but this also applies across providers in the upstream project. If you have thoughts around how we could achieve this, please open an RFC as a PR against `kuberenetes-sigs/karpenter`
