### ISSUE TITLE
EKS cluster upgrade to 1.31 - compatibility question

### ISSUE THREAD

**Issue by masoodamunchen** [aws/karpenter-provider-aws#7485]
Hello,

According to the compatibility matrix the kubernetes cluster version 1.31 is only compatible with karpenter >= 1.0.5 but in our case we have seen 0.36 works fine with 1.30 but as per the matrix it shouldn’t! So what are the feature of karpenter 0.36 that might not work with cluster version 1.31?  

There was a similar issue raised for 1.29 by another user but that is marked as closed so I am opening a new one for 1.31.

Thanks!

**Comment by engedaam** [comment]
There may not be any specific issue that will block any older version of Karpenter from working a newer version of k8s, however the team does not support making older version Karpenter work on a newer version of EKS clusters. The compatibility matrix just outline which Kubernetes versions are fully supported at each karpenter version

**Comment by masoodamunchen** [comment]
@engedaam Thanks for the clarification! Really appreciate it.
