### ISSUE TITLE
Cilium EKS Overlay - Karpenter Nodes Not registering

### ISSUE THREAD

**Issue by sujeetkp** [aws/karpenter-provider-aws#7487]
### Description

**Observed Behavior**:
I have configured Cilium on EKS in Overlay mode. Kubesystem Node group is up and running. When I create a Node with Karpenter, I see Karpenter creating an EC2 instance, but that EC2 instance never gets registered with the EKS Cluster nor the Cilium agent gets scheduled on those nodes. 
**Expected Behavior**:
Cilium agent should run on Karpenter Nodes and Karpenter Nodes should get registered to EKS Cluster.
**Reproduction Steps** (Please include YAML):

**Versions**:
- Chart Version: 1.0.2
- Kubernetes Version (`kubectl version`):
1.29
* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by irwin-rex** [comment]
me too

**Comment by sujeetkp** [comment]
Fixed it - There was no issue with CIlium or Karpenter. I had recently added a new CIDR to the VPC and the same was missing in the EKS VPC Endpoint SG Inbound Rules.
