### ISSUE TITLE
Nodeclaim in Unknown statys

### ISSUE THREAD

**Issue by nitinjain999** [aws/karpenter-provider-aws#7493]
### Description

**Observed Behavior**:
kubectl get nodeclaims.karpenter.sh                                                                                                                                                                                               
NAME                        TYPE              CAPACITY    ZONE          NODE   READY     AGE
atg-worker-ondemand-284k9   m7i-flex.large    on-demand   eu-north-1b          Unknown   7s
atg-worker-ondemand-5nv97   m7i-flex.xlarge   on-demand   eu-north-1a          Unknown   47s
atg-worker-ondemand-c92dk   m7i-flex.xlarge   on-demand   eu-north-1a          Unknown   17s
atg-worker-ondemand-ffkrh   m7i-flex.large    on-demand   eu-north-1b          Unknown   37s
atg-worker-ondemand-plrc5   m7i-flex.large    on-demand   eu-north-1b          Unknown   17s
atg-worker-ondemand-w52rl   m7i-flex.xlarge   on-demand   eu-north-1a          Unknown   7s
atg-worker-ondemand-zb6hl   m7i-flex.xlarge   on-demand   eu-north-1b          Unknown   27s

,"name":"atg-worker-ondemand-gqf79","reconcileID":"b8d4056c-b379-4faa-be40-134c980554c4","provider-id":"aws:///eu-north-1b/i-0d39d13a6941da7c1","instance-type":"m7i-flex.large","zone":"eu-north-1b","capacity-type":"on-demand","allocatable":{"cpu":"1930m","ephemeral-storage":"17Gi","memory":"6903Mi","pods":"29","vpc.amazonaws.com/pod-eni":"3"}}
{"level":"INFO","time":"2024-12-06T16:58:04.778Z","logger":"controller","caller":"lifecycle/launch.go:61","message":"launched nodeclaim","commit":"0a85efb","controller":"nodeclaim.lifecycle","controllerGroup":"karpenter.sh","controllerKind":"NodeClaim","NodeClaim":{"name":"atg-worker-ondemand-xh48r"},"namespace":"","name":"atg-worker-ondemand-xh48r","reconcileID":"93e8432f-0e38-4c18-b559-3b51e43b6885","provider-id":"aws:///eu-north-1a/i-00dd095c70b42d17a","instance-type":"m7i-flex.xlarge","zone":"eu-north-1a","capacity-type":"on-demand","allocatable":{"cpu":"3920m","ephemeral-storage":"17Gi","memory":"14162Mi","pods":"58","vpc.amazonaws.com/pod-eni":"8"}}
{"level":"INFO","time":"2024-12-06T16:58:04.806Z","logger":"controller","caller":"lifecycle/controller.go:118","message":"deleted nodeclaim","commit":"0a85efb","controller":"nodeclaim.lifecycle","controllerGroup":"karpenter.sh","controllerKind":"NodeClaim","NodeClaim":{"name":"atg-worker-ondemand-ffkrh"},"namespace":"","name":"atg-worker-ondemand-ffkrh","reconcileID":"3a94c22e-6495-4ecf-a363-a75cd26ac6b7","Node":{"name":""},"provider-id":"aws:///eu-north-1b/i-0e47e19bc28af415b"}
{"level":"INFO","time":"2024-12-06T16:58:07.817Z","logger":"controller","caller":"lifecycle/controller.go:118","message":"deleted nodeclaim","commit":"0a85efb","controller":"nodeclaim.lifecycle","controllerGroup":"karpenter.sh","controllerKind":"NodeClaim","NodeClaim":{"name":"atg-worker-ondemand-t56nl"},"namespace":"","name":"atg-worker-ondemand-t56nl","reconcileID":"3f6fa579-49e4-426f-a46d-263b7663cab7","Node":{"name":""},"provider-id":"aws:///eu-north-1b/i-01269d053bbe3976c"}
{"level":"INFO","time":"2024-12-06T16:58:11.466Z","logger":"controller","caller":"interruption/controller.go:212","message":"initiating delete from interruption message","commit":"0a85efb","controller":"interruption","namespace":"","name":"","reconcileID":"5308e924-bb38-4df8-aa44-932b73e2b85e","queue":"Karpenter-atg-eun1-devtest-dataplatform-eks","messageKind":"instance_terminated","NodeClaim":{"name":"atg-worker-ondemand-gqf79"},"action":"CordonAndDrain"}
{"level":"INFO","time":"2024-12-06T16:58:11.477Z","logger":"controller","caller":"interruption/controller.go:212","message":"initiating delete from interruption message","commit":"0a85efb","controller":"interruption","namespace":"","name":"","reconcileID":"5308e924-bb38-4df8-aa44-932b73e2b85e","queue":"Karpenter-atg-eun1-devtest-dataplatform-eks","messageKind":"instance_terminated","NodeClaim":{"name":"atg-worker-ondemand-xh48r"},"action":"CordonAndDrain"}
{"level":"DEBUG","time":"2024-12-06T16:58:13.146Z","logger":"controller","caller":"scheduling/scheduler.go:241","message":"1 out of 5 instance types were excluded because they would breach limits","commit":"0a85efb","controller":"provisioner","namespace":"","name":"","reconcileID":"1a3e9d38-ded1-4e6d-b7ef-73ac8f603d55","NodePool":{"name":"atg-worker-ondemand"}}
{"level":"DEBUG","time":"2024-12-06T16:58:13.147Z","logger":"controller","caller":"scheduling/scheduler.go:241","message":"3 out of 5 instance types were excluded because they would breach limits","commit":"0a85efb","controller":"provisioner","namespace":"","name":"","reconcileID":"1a3e9d38-ded1-4e6d-b7ef-73ac8f603d55","NodePool":{"name":"atg-worker-ondemand"}}
{"level":"INFO","time":"2024-12-06T16:58:13.147Z","logger":"controller","caller":"provisioning/provisioner.go:129","message":"found provisionable pod(s)","commit":"0a85efb","controller":"provisioner","namespace":"","name":"","reconcileID":"1a3e9d38-ded1-4e6d-b7ef-73ac8f603d55","Pods":"default/inflate-66d97b798d-dqlrp, default/inflate-66d97b798d-wz9gr, default/inflate-66d97b798d-kk6mp","duration":"13.754641ms"}
{"level":"INFO","time":"2024-12-06T16:58:13.147Z","logger":"controller","caller":"provisioning/provisioner.go:352","message":"computed new nodeclaim(s) to fit pod(s)","commit":"0a85efb","controller":"provisioner","namespace":"","name":"","reconcileID":"1a3e9d38-ded1-4e6d-b7ef-73ac8f603d55","nodeclaims":2,"pods":3}
{"level":"INFO","time":"2024-12-06T16:58:13.163Z","logger":"controller","caller":"provisioning/provisioner.go:150","message":"created nodeclaim","commit":"0a85efb","controller":"provisioner","namespace":"","name":"","reconcileID":"1a3e9d38-ded1-4e6d-b7ef-73ac8f603d55","NodePool":{"name":"atg-worker-ondemand"},"NodeClaim":{"name":"atg-worker-ondemand-9l96l"},"requests":{"cpu":"1680m","memory":"976Mi","pods":"10"},"instance-types":"m7i-flex.large, m7i-flex.xlarge"}
{"level":"INFO","time":"2024-12-06T16:58:13.164Z","logger":"controller","caller":"provisioning/provisioner.go:150","message":"created nodeclaim","commit":"0a85efb","controller":"provisioner","namespace":"","name":"","reconcileID":"1a3e9d38-ded1-4e6d-b7ef-73ac8f603d55","NodePool":{"name":"atg-worker-ondemand"},"NodeClaim":{"name":"atg-worker-ondemand-phbx2"},"requests":{"cpu":"2680m","memory":"976Mi","pods":"11"},"instance-types":"m7i-flex.2xlarge, m7i-flex.4xlarge, m7i-flex.xlarge"}
{"level":"INFO","time":"2024-12-06T16:58:14.766Z","logger":"controller","caller":"lifecycle/launch.go:61","message":"launched nodeclaim","commit":"0a85efb","controller":"nodeclaim.lifecycle","controllerGroup":"karpenter.sh","controllerKind":"NodeClaim","NodeClaim":{"name":"atg-worker-ondemand-phbx2"},"namespace":"","name":"atg-worker-ondemand-phbx2","reconcileID":"ac306cbd-b5be-407e-a4b6-f6029262232d","provider-id":"aws:///eu-north-1a/i-088b6699710a8532d","instance-type":"m7i-flex.xlarge","zone":"eu-north-1a","capacity-type":"on-demand","allocatable":{"cpu":"3920m","ephemeral-storage":"17Gi","memory":"14162Mi","pods":"58","vpc.amazonaws.com/pod-eni":"8"}}
{"level":"INFO","time":"2024-12-06T16:58:14.811Z","logger":"controller","caller":"lifecycle/launch.go:61","message":"launched nodeclaim","commit":"0a85efb","controller":"nodeclaim.lifecycle","controllerGroup":"karpenter.sh","controllerKind":"NodeClaim","NodeClaim":{"name":"atg-worker-ondemand-9l96l"},"namespace":"","name":"atg-worker-ondemand-9l96l","reconcileID":"f97c13f9-2f07-4a2e-9c2b-1519c915759b","provider-id":"aws:///eu-north-1b/i-02dfd8c396b34560c","instance-type":"m7i-flex.large","zone":"eu-north-1b","capacity-type":"on-demand","allocatable":{"cpu":"1930m","ephemeral-storage":"17Gi","memory":"6903Mi","pods":"29","vpc.amazonaws.com/pod-eni":"3"}}
{"level":"INFO","time":"2024-12-06T16:58:17.931Z","logger":"controller","caller":"lifecycle/controller.go:118","message":"deleted nodeclaim","commit":"0a85efb","controller":"nodeclaim.lifecycle","controllerGroup":"karpenter.sh","controllerKind":"NodeClaim","NodeClaim":{"name":"atg-worker-ondemand-vrjp6"},"namespace":"","name":"atg-worker-ondemand-vrjp6","reconcileID":"6715a781-93d7-4a8a-8cf5-0dbada71ff69","Node":{"name":""},"provider-id":"aws:///eu-north-1a/i-06c0f53949f8ebdb5"}
{"level":"INFO","time":"2024-12-06T16:58:21.544Z","logger":"controller","caller":"interruption/controller.go:212","message":"initiating delete from interruption message","commit":"0a85efb","controller":"interruption","namespace":"","name":"","reconcileID":"315216d1-638c-4816-90d1-b87e43c45e6a","queue":"Karpenter-atg-eun1-devtest-dataplatform-eks","messageKind":"instance_terminated","NodeClaim":{"name":"atg-worker-ondemand-9l96l"},"action":"CordonAndDrain"}
{"level":"INFO","time":"2024-12-06T16:58:21.709Z","logger":"controller","caller":"interruption/controller.go:212","message":"initiating delete from interruption message","commit":"0a85efb","controller":"interruption","namespace":"","name":"","reconcileID":"2327a509-d0b1-4924-b60b-bd7fc2613ff1","queue":"Karpenter-atg-eun1-devtest-dataplatform-eks","messageKind":"instance_terminated","NodeClaim":{"name":"atg-worker-ondemand-phbx2"},"action":"CordonAndDrain"}
{"level":"DEBUG","time":"2024-12-06T16:58:23.147Z","logger":"controller","caller":"scheduling/scheduler.go:241","message":"1 out of 5 instance types were excluded because they would breach limits","commit":"0a85efb","controller":"provisioner","namespace":"","name":"","reconcileID":"0565980b-f956-4d72-833f-8a229263692e","NodePool":{"name":"atg-worker-ondemand"}}
{"level":"DEBUG","time":"2024-12-06T16:58:23.148Z","logger":"controller","caller":"scheduling/scheduler.go:241","message":"3 out of 5 instance types were excluded because they would breach limits","commit":"0a85efb","controller":"provisioner","namespace":"","name":"","reconcileID":"0565980b-f956-4d72-833f-8a229263692e","NodePool":{"name":"atg-worker-ondemand"}}
{"level":"INFO","time":"2024-12-06T16:58:23.148Z","logger":"controller","caller":"provisioning/provisioner.go:129","message":"found provisionable pod(s)","commit":"0a85efb","controller":"provisioner","namespace":"","name":"","reconcileID":"0565980b-f956-4d72-833f-8a229263692e","Pods":"default/inflate-66d97b798d-dqlrp, default/inflate-66d97b798d-wz9gr, default/inflate-66d97b798d-kk6mp","duration":"14.25587ms"}
{"level":"INFO","time":"2024-12-06T16:58:23.148Z","logger":"controller","caller":"provisioning/provisioner.go:352","message":"computed new nodeclaim(s) to fit pod(s)","commit":"0a85efb","controller":"provisioner","namespace":"","name":"","reconcileID":"0565980b-f956-4d72-833f-8a229263692e","nodeclaims":2,"pods":3}
{"level":"INFO","time":"2024-12-06T16:58:23.186Z","logger":"controller","caller":"provisioning/provisioner.go:150","message":"created nodeclaim","commit":"0a85efb","controller":"provisioner","namespace":"","name":"","reconcileID":"0565980b-f956-4d72-833f-8a229263692e","NodePool":{"name":"atg-worker-ondemand"},"NodeClaim":{"name":"atg-worker-ondemand-m8v7v"},"requests":{"cpu":"1680m","memory":"976Mi","pods":"10"},"instance-types":"m7i-flex.large, m7i-flex.xlarge"}
{"level":"INFO","time":"2024-12-06T16:58:23.188Z","logger":"controller","caller":"provisioning/provisioner.go:150","message":"created nodeclaim","commit":"0a85efb","controller":"provisioner","namespace":"","name":"","reconcileID":"0565980b-f956-4d72-833f-8a229263692e","NodePool":{"name":"atg-worker-ondemand"},"NodeClaim":{"name":"atg-worker-ondemand-qjcbt"},"requests":{"cpu":"2680m","memory":"976Mi","pods":"11"},"instance-types":"m7i-flex.2xlarge, m7i-flex.4xlarge, m7i-flex.xlarge"}
{"level":"INFO","time":"2024-12-06T16:58:23.419Z","logger":"controller","caller":"lifecycle/controller.go:118","message":"deleted nodeclaim","commit":"0a85efb","controller":"nodeclaim.lifecycle","controllerGroup":"karpenter.sh","controllerKind":"NodeClaim","NodeClaim":{"name":"atg-worker-ondemand-8tkhg"},"namespace":"","name":"atg-worker-ondemand-8tkhg","reconcileID":"6fcaf546-34f4-4f91-8230-7ef9b6e3c455","Node":{"name":""},"provider-id":"aws:///eu-north-1a/i-069a7bc6bff0174c8"}
{"level":"INFO","time":"2024-12-06T16:58:24.727Z","logger":"controller","caller":"lifecycle/launch.go:61","message":"launched nodeclaim","commit":"0a85efb","controller":"nodeclaim.lifecycle","controllerGroup":"karpenter.sh","controllerKind":"NodeClaim","NodeClaim":{"name":"atg-worker-ondemand-qjcbt"},"namespace":"","name":"atg-worker-ondemand-qjcbt","reconcileID":"63e4ebfd-0bbd-411f-9bd7-6d7396010e25","provider-id":"aws:///eu-north-1a/i-02ca3c197f026d313","instance-type":"m7i-flex.xlarge","zone":"eu-north-1a","capacity-type":"on-demand","allocatable":{"cpu":"3920m","ephemeral-storage":"17Gi","memory":"14162Mi","pods":"58","vpc.amazonaws.com/pod-eni":"8"}}
{"level":"INFO","time":"2024-12-06T16:58:24.810Z","logger":"controller","caller":"lifecycle/launch.go:61","message":"launched nodeclaim","commit":"0a85efb","controller":"nodeclaim.lifecycle","controllerGroup":"karpenter.sh","controllerKind":"NodeClaim","NodeClaim":{"name":"atg-worker-ondemand-m8v7v"},"namespace":"","name":"atg-worker-ondemand-m8v7v","reconcileID":"66604b1e-8eca-49e4-bd02-8614a9e9cfe1","provider-id":"aws:///eu-north-1b/i-02808d1916bd51e54","instance-type":"m7i-flex.large","zone":"eu-north-1b","capacity-type":"on-demand","allocatable":{"cpu":"1930m","ephemeral-storage":"17Gi","memory":"6903Mi","pods":"29","vpc.amazonaws.com/pod-eni":"3"}}
{"level":"INFO","time":"2024-12-06T16:58:27.696Z","logger":"controller","caller":"lifecycle/controller.go:118","message":"deleted nodeclaim","commit":"0a85efb","controller":"nodeclaim.lifecycle","controllerGroup":"karpenter.sh","controllerKind":"NodeClaim","NodeClaim":{"name":"atg-worker-ondemand-xh48r"},"namespace
**Expected Behavior**:

**Reproduction Steps** (Please include YAML):

**Versions**:
- Chart Version:
- 1.10.0
- Kubernetes Version (`kubectl version`):
- EKS 1.31
- 
* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by engedaam** [comment]
Closing as a duplicate https://github.com/aws/karpenter-provider-aws/issues/7494
