### ISSUE TITLE
Existing  nodeclaims `READY` status becomes `Unknown`

### ISSUE THREAD

**Issue by celik-sr** [aws/karpenter-provider-aws#7494]
### Description

**Observed Behavior**:

When upgrading from `1.0.2` to `1.1.0`, the existing nodeclaims READY status becomes Unknown and new nodeclaims created after the upgrade are `READY: True` . The nodeclaims in the Unknown state are registered to the cluster, and I don't see any errors in the debug logs.

Status of existing nodeclaim:

```
Status:
  Allocatable:
    Cpu:                        3920m
    Ephemeral - Storage:        89Gi
    Memory:                     29471Mi
    Pods:                       350
    vpc.amazonaws.com/pod-eni:  18
  Capacity:
    Cpu:                        4
    Ephemeral - Storage:        100Gi
    Memory:                     30310Mi
    Pods:                       350
    vpc.amazonaws.com/pod-eni:  18
  Conditions:
    Last Transition Time:  2024-12-06T01:24:44Z
    Message:
    Reason:                Launched
    Status:                True
    Type:                  Launched
    Last Transition Time:  2024-12-06T01:25:28Z
    Message:
    Reason:                Registered
    Status:                True
    Type:                  Registered
    Last Transition Time:  2024-12-06T01:25:59Z
    Message:
    Reason:                Initialized
    Status:                True
    Type:                  Initialized
    Last Transition Time:  2024-12-06T01:34:44Z
    Message:
    Reason:                ConsistentStateFound
    Status:                True
    Type:                  ConsistentStateFound
    Last Transition Time:  2024-12-06T20:55:32Z
    Message:               NodePoolDrifted
    Observed Generation:   1
    Reason:                NodePoolDrifted
    Status:                True
    Type:                  Drifted
    Last Transition Time:  2024-12-06T21:17:10Z
    Message:
    Observed Generation:   1
    Reason:                Consolidatable
    Status:                True
    Type:                  Consolidatable
    Last Transition Time:  2024-12-06T19:17:06Z
    Message:               Initialized=True, Registered=True, Launched=True
    Observed Generation:   1
    Reason:                ReconcilingDependents
    Status:                Unknown
    Type:                  Ready
  Image ID:                ami-02ebe9cc28f2e32f8
  Last Pod Event Time:     2024-12-06T21:07:10Z
```

Additionally, when a nodeclaim in an Unknown status is deleted, it briefly (before being terminated) updates its Status  to Ready. Example below:

```
❯ k get nodeclaims
NAME            TYPE         CAPACITY   ZONE         NODE        READY     AGE
default-fkr66   r5dn.large   spot       us-east-1c   REDACTED    Unknown   20h
default-r7nn9   c7a.medium   spot       us-east-1a   REDACTED    Unknown   20h
default-z5zff   r5b.xlarge   spot       us-east-1c   REDACTED    Unknown   20h
``` 

After the delete,  the status changes to `Ready: True` before deleting the disrupted node

```
❯ k get nodeclaims
NAME            TYPE         CAPACITY   ZONE         NODE        READY     AGE
default-fkr66   r5dn.large   spot       us-east-1c   REDACTED    True      20h
default-r7nn9   c7a.medium   spot       us-east-1a   REDACTED  Unknown   20h
default-x25jw   m7a.medium   spot       us-east-1a   REDACTED   Unknown   73s
default-z5zff   r5b.xlarge   spot       us-east-1c   REDACTED   Unknown   20h
```

And finally, once the old claims are deleted:
```
❯ k get nodeclaims
NAME            TYPE         CAPACITY   ZONE         NODE        READY     AGE
default-r7nn9   c7a.medium   spot       us-east-1a   REDACTED    Unknown   20h
default-x25jw   m7a.medium   spot       us-east-1a   REDACTED   True      2m28s
default-z5zff   r5b.xlarge   spot       us-east-1c   REDACTED   Unknown   20h
```

Tracing the nodeclaim `default-fkr66` you can see the behavior above. The nodeclaims appear to be functional, as karpenter can disrupt them, and they are registered to the cluster so pods can be scheduled to their underlying nodes.  

**Expected Behavior**:

Existing nodeclaims after the upgrade remain in `READY: True` status. 

This was also discussed in [slack](https://kubernetes.slack.com/archives/C02SFFZSA2K/p1733515347003009)

**Reproduction Steps** (Please include YAML):

**Versions**:
- Chart Version: `1.1.0` 
- Kubernetes Version (`kubectl version`):  v1.30

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by jonathan-innis** [comment]
This should have been resolved with https://github.com/kubernetes-sigs/karpenter/pull/1869 and we are planning to release this with a v1.1.1 patch
