### ISSUE TITLE
Missing KarpenterNodeInstanceProfile

### ISSUE THREAD

**Issue by FromOopsToOps** [aws/karpenter-provider-aws#7503]
### Description

**Observed Behavior**:
Current cloudformation.yaml from the Getting Started Documentation is missing KarpenterNodeInstanceProfile.
Running that cloudformation.yaml and then proceeding with the document, when we try to bring up a node, we get an error like this:

│ {"level":"ERROR","time":"2024-12-09T14:48:32.537Z","logger":"controller","message":"Reconciler error","commit":"0a85efb","controller":"nodeclaim.lifecycle","controllerGroup":"karpenter ││ .sh","controllerKind":"NodeClaim","NodeClaim":{"name":"general-apps-nodepool-vpmpg"},"namespace":"","name":"general-apps-nodepool-vpmpg","reconcileID":"82ae0ec6-d802-457c-9fee-049d2f19 ││ e4aa","error":"launching nodeclaim, creating instance, InvalidParameterValue: Value (KarpenterNodeInstanceProfile-experimental-us-east-2-1) for parameter iamInstanceProfile.name is inv ││ alid. Invalid IAM Instance Profile name"} 

**Expected Behavior**:

Create a node normally.

**Reproduction Steps** (Please include YAML):
Just follow the Getting Started guide. After adding the missing resource node creation happens.
**Versions**:
- Chart Version: 1.1.0
- Kubernetes Version (`kubectl version`): 1.31

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by engedaam** [comment]
Are you passing in an instance profile to your EC2NodeClass? If so, you will need to create the instance profile yourself. We recommended that you pass in a role, so that Karpenter will auto create the instance profile for you https://karpenter.sh/docs/concepts/nodeclasses/#specrole. Are you able to pass in the node role that was created with the cloud formation stack?
