### ISSUE TITLE
Unable to register node with API server at Karpenter v1.1

### ISSUE THREAD

**Issue by FabioRodrigues3** [aws/karpenter-provider-aws#7508]
Hi,

I installed Karpenter v1.1 and followed all the configurations according to the https://karpenter.sh/v1.1/getting-started/, but Karpenter cannot register new nodes to the cluster. Accessing directly the instance created by Karpenter and running the command "journalctl -D /.bottlerocket/rootfs/var/log/journal -u kubelet.service" I have the following log:

Dec 10 12:37:42 ip-111-22-333-444.ec2.internal kubelet[2239]: I1210 12:37:42.998722    2239 kubelet_node_status.go:73] "Attempting to register node" node="ip-111-22-333-444.ec2.internal"
Dec 10 12:37:43 ip-111-22-333-444.ec2.internal kubelet[2239]: E1210 12:37:43.000051    2239 kubelet_node_status.go:96] "Unable to register node with API server" err="nodes \"ip-111-22-333-444.ec2.internal\" is forbidden: node \"i-0ed67a34f87240f5c\" is not allowed to modify node \"ip-111-22-333-444.ec2.internal\"" node="ip-111-22-333-444.ec2.internal"
Dec 10 12:37:49 ip-111-22-333-444.ec2.internal kubelet[2239]: E1210 12:37:49.990470    2239 controller.go:145] "Failed to ensure lease exists, will retry" err="leases.coordination.k8s.io \"ip-111-22-333-444.ec2.internal\" is forbidden: User \"system:node:i-0ed67a34f87240f5c\" cannot get resource \"leases\" in API group \"coordination.k8s.io\" in the namespace \"kube-node-lease\": can only access node lease with the same name as the requesting node" interval="7s"

My aws-auth has the following permission:

    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::12345678910:role/KarpenterNodeRole-my-cluster-name
      username: system:node:{{EC2PrivateDNSName}}

Previously I was using Karpenter v1.0.7 and it worked normally. To install v1.1 I uninstalled everything and started from scratch.
Has anyone had a similar problem, can you help?

I'm using only this nodepool at the moment.
[default_nodepool.txt](https://github.com/user-attachments/files/18080540/default_nodepool.txt)

**Comment by engedaam** [comment]
Have you followed these troubleshooting steps? https://karpenter.sh/docs/troubleshooting/#node-notready

**Comment by FabioRodrigues3** [comment]
Hi, thanks for the reply!

Yes, I followed the troubleshooting step by step but everything seems to be ok, I reviewed the permissions, the security group and subnets are also tagged karpenter.sh/discovery, the logs from my aws-node pods are all OK. Cluster roles were also created automatically during Karpenter installation via Helm.

**Comment by FabioRodrigues3** [comment]
Hello, 

I managed to solve the problem by recreating the two Karpenter roles. After that, it returned to operating as desired.

**Comment by FabioRodrigues3** [comment]
Hello,

I managed to solve the problem by recreating the two Karpenter roles. After that, it returned to operating as desired.
